import {test,expect,type Page} from '@playwright/test';
import {mockSource} from './fixtures';
import {newCharacter,type Character,type Entry} from '../../src/core/model';
import {exportOwlbear} from '../../src/core/export';
import {evaluate} from '../../src/core/engine';
const entry=(kind:Entry['kind'],name:string,raw:Entry['raw']={}):Entry=>({id:`activity-test:${name}`,kind,name,english:name,source:'XPHB',edition:'2024',packId:'test',revision:'1',entries:['原创展示正文：一个可用于测试的词条。'],raw});
function character(){const c=newCharacter();c.name='展示验收';c.abilities.int=16;c.selections=[entry('spell','验收戏法',{level:0}),entry('spell','已备法术',{level:1}),entry('spell','未备法术',{level:1}),entry('feature','验收特性'),entry('item','验收物品',{weight:2,value:100})].map(e=>({id:e.id,entry:e,level:1,quantity:1,equipped:false}));c.spellSettings={mode:'prepared',modeOverride:true,ability:'int',capacity:3,attackBonus:0,dcBonus:0,prepared:['activity-test:已备法术'],slots:{}};return c;}
async function load(page:Page,c:Character){await mockSource(page);await page.goto('/');await expect(page.getByRole('button',{name:'更新资料',exact:true})).toBeEnabled();await page.getByRole('button',{name:'导入 / 导出',exact:true}).click();await page.getByTestId('character-file').setInputFiles({name:'test.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(c))});await page.getByRole('button',{name:'关闭弹窗'}).click();}
test('cantrips remain on the main sheet; manual spell adjustments are independent and edit-only',async({page})=>{
 await load(page,character());await expect(page.locator('.overview-spells')).toContainText('验收戏法');await expect(page.locator('.overview-spells')).toContainText('已备法术');await expect(page.locator('.overview-spells')).not.toContainText('未备法术');await page.screenshot({path:'test-results/activity185-overview.png'});
 await page.getByRole('tab',{name:'法术',exact:true}).click();await expect(page.locator('.header-法术 .stat-adjustment')).toHaveCount(0);await expect(page.locator('.header-法术 .page-value').first()).toHaveText('+5');
 await page.getByRole('switch',{name:'编辑模式'}).click();await expect(page.getByRole('spinbutton',{name:'法术攻击调整值',exact:true})).toHaveValue('0');await page.getByRole('spinbutton',{name:'法术攻击调整值',exact:true}).fill('2');await page.getByRole('spinbutton',{name:'法术攻击调整值',exact:true}).press('Enter');await expect(page.locator('.header-法术 .page-value').first()).toHaveText('+7');await page.getByRole('spinbutton',{name:'法术DC调整值',exact:true}).fill('1');await page.getByRole('spinbutton',{name:'法术DC调整值',exact:true}).press('Enter');await expect(page.locator('.header-法术 .page-value').nth(1)).toHaveText('14');await page.screenshot({path:'test-results/activity185-spell-edit.png'});
 await page.getByRole('switch',{name:'编辑模式'}).click();await expect(page.locator('.header-法术 .stat-adjustment')).toHaveCount(0);await expect(page.locator('.header-法术 .page-value').first()).toHaveText('+7');await page.screenshot({path:'test-results/activity185-spell-normal.png'});
});
test('bubble, spell and item menus share only the selected entry; received notifications navigate Wiki',async({page:host})=>{
 const c=character(),protocol='full-suite-workbench/v1',session='activity185';await host.route('**/activity-host185',r=>r.fulfill({contentType:'text/html',body:'<!doctype html><title>Activity test host</title>'}));await host.goto('/activity-host185');
 await host.evaluate(({protocol,session})=>{(window as any).requests=[];window.addEventListener('message',e=>{const m=e.data;if(m?.protocol!==protocol||m.session!==session)return;const send=(v:any)=>(e.source as Window).postMessage({protocol,session,hostStarted:185,...v},location.origin);if(m.type==='hello'||m.type==='ping')send({type:m.type==='hello'?'ready':'pong'});if(m.type==='showEntry'){(window as any).requests.push(m);send({type:'ack',requestId:m.requestId,ok:true});}});},{protocol,session});
 const waiting=host.context().waitForEvent('page');await host.evaluate(session=>{(window as any).viewer=window.open('/#suite='+session+'&bridge='+encodeURIComponent(location.origin),'activity185');},session);const page=await waiting;await mockSource(page);await expect(page.locator('.app-shell')).toBeVisible();
 const send=async(type:string,payload:any={})=>host.evaluate(({type,payload,protocol,session})=>(window as any).viewer.postMessage({protocol,session,hostStarted:185,type,...payload},location.origin),{type,payload,protocol,session});
 const state={key:'room:card:one',itemId:'token-one',cardId:'one',kind:'character',name:c.name,role:'GM',write:true,resources:[],conditions:[],locked:false,stats:{health:1,'max health':1,'armor class':10}};
 await send('ready');await send('catalog',{sequence:1,role:'GM',cards:[{...state,id:'one',inScene:true}],monsters:[],enabled:{},visibility:{wiki:true,monsters:true},inventory:{publicId:'public:test',access:'gm',containers:{'card:one':{id:'card:one',name:c.name,kind:'card',revision:1,items:[{id:'stock-one',name:'验收物品',kind:'item',quantity:1,revision:1,slot:0,entry:c.selections[4].entry}],columns:4,capacity:24,write:true}}}});await send('selection',{sequence:2,state,document:{...exportOwlbear(c,evaluate(c)),dnd_card_web:c,_suiteRevision:1}});await send('navigate');
 const share=async(locator:ReturnType<Page['locator']>,name:string,count:number)=>{await locator.click({button:'right'});await expect(page.locator('[data-testid="tooltip-backdrop"]')).toHaveCount(0);await page.getByRole('menuitem',{name:'向全员展示',exact:true}).click();await expect.poll(()=>host.evaluate(()=>(window as any).requests.length)).toBe(count);expect(await host.evaluate(()=>(window as any).requests.at(-1).entry.name)).toBe(name);};
 await share(page.locator('.feature-caption').filter({hasText:'验收特性'}),'验收特性',1);
 await page.getByRole('tab',{name:'法术',exact:true}).click();await share(page.locator('.spell-stock-tile').filter({hasText:'已备法术'}),'已备法术',2);await page.screenshot({path:'test-results/activity185-spells.png'});
 await page.getByRole('tab',{name:'背包',exact:true}).click();await share(page.locator('[data-stock-id="stock-one"]'),'验收物品',3);
 const requests=await host.evaluate(()=>(window as any).requests);for(const req of requests){expect(req.key).toBeUndefined();expect(req.itemId).toBeUndefined();expect(req.entry).not.toHaveProperty('selections');}
 await send('showWiki',{entry:c.selections[1].entry});await expect(page.locator('.entry-detail .detail-title')).toContainText('已备法术');await expect(page.locator('.entry-detail')).toContainText('原创展示正文');
 await page.setViewportSize({width:480,height:720});await send('selection',{sequence:3,state:{...state,key:'room:monster:test',itemId:'test-monster',cardId:'',kind:'monster',name:'显示验收怪物',slug:'test'},document:{name:'显示验收怪物',source:'TEST',size:['M'],type:'humanoid',ac:[12],hp:{average:12},speed:{walk:30},str:10,dex:12,con:12,int:10,wis:10,cha:10,trait:[{name:'原创测试特性',entries:['用于检查怪物卡的可读字号。']}]}});await send('navigate');await expect(page.locator('.workbench-monster h1')).toContainText('显示验收怪物');await expect(page.locator('.sheet-viewport')).toHaveClass(/sheet-reflow/);await page.screenshot({path:'test-results/activity185-monster-reading.png'});await page.setViewportSize({width:1280,height:720});await expect(page.locator('.sheet-viewport')).not.toHaveClass(/sheet-reflow/);await page.setViewportSize({width:1920,height:1280});await expect(page.locator('.sheet-viewport')).not.toHaveClass(/sheet-reflow/);

});
