import {test,expect,type Page} from '@playwright/test';
import {readFileSync,mkdirSync} from 'node:fs';
import {mockSource} from './fixtures';
const out='F:/CodexWork/2026-09-20/w-xu/adaptive180';
mkdirSync(out,{recursive:true});
const baseline=JSON.parse(readFileSync(new URL('./adaptive180.baseline.json',import.meta.url),'utf8'));
test.setTimeout(90000);
const runtimeErrors=new WeakMap<Page,string[]>();
test.beforeEach(async({page})=>{const errors:string[]=[];runtimeErrors.set(page,errors);page.on('pageerror',e=>errors.push(e.message));});
test.afterEach(async({page})=>{expect(runtimeErrors.get(page)).toEqual([]);});
async function openHuman(page:Page){await mockSource(page);await page.goto('/');await page.getByRole('button',{name:'导入 / 导出',exact:true}).click();await page.getByTestId('character-file').setInputFiles({name:'adaptive180.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(baseline.character))});await page.getByRole('button',{name:'关闭弹窗'}).click();await expect(page.locator('.paper')).toBeVisible();await page.waitForTimeout(1100);}
async function openMonster(page:Page){
 await page.route('**/adaptive180-harness',route=>route.fulfill({contentType:'text/html',body:`<!doctype html><html><head><meta charset="utf-8">${['style','workspace','workbench','overview','library','cardAtmosphere','libraryRefine','characterPages','suiteTheme','responsive176','responsive177'].map(name=>`<link rel="stylesheet" href="/src/ui/${name}.css">`).join('')}<style>body{overflow:hidden}#test-root{height:100vh}#test-wiki{height:32px}#test-wiki button{height:30px}</style></head><body><div id="test-root"></div><script type="module">import RefreshRuntime from '/@react-refresh';RefreshRuntime.injectIntoGlobalHook(window);window.$RefreshReg$=()=>{};window.$RefreshSig$=()=>type=>type;window.__vite_plugin_react_preamble_installed__=true;</script><script type="module" src="/tests/e2e/adaptiveMonster180.harness.jsx"></script></body></html>`}));
 await page.goto('/adaptive180-harness#suite=adaptive180&bridge='+encodeURIComponent('http://127.0.0.1:5179'));await expect(page.locator('.workbench-monster')).toBeVisible();
}
const effects=['prone','restrained','grappled','charmed','deafened','blinded','poisoned','concentration','exhaustion'];
async function setEffects(page:Page,ids=effects,settle=true){await page.evaluate(ids=>(window as any).setMonsterConditions(ids),ids);if(settle)await page.waitForTimeout(1100);}
async function isotropic(page:Page,symbols=true){
 const transforms=await page.locator('[data-adaptive-symbol]').evaluateAll(nodes=>nodes.map(e=>{const m=(e as SVGGraphicsElement).getScreenCTM()!;return {x:Math.hypot(m.a,m.b),y:Math.hypot(m.c,m.d)};}));if(symbols)expect(transforms.length).toBeGreaterThan(0);for(const m of transforms)expect(m.x/m.y).toBeCloseTo(1,3);
 const bounds=await page.locator('[data-adaptive-atmosphere],.adaptive-frame-art').evaluateAll(nodes=>nodes.map(e=>{const svg=e.tagName.toLowerCase()==='svg'?e:e.querySelector('svg'),m=(svg as SVGGraphicsElement|null)?.getScreenCTM();return {w:e.clientWidth,h:e.clientHeight,view:svg?.getAttribute('viewBox')?.split(/\s+/).map(Number),sx:m?Math.hypot(m.a,m.b):0,sy:m?Math.hypot(m.c,m.d):0,events:getComputedStyle(e).pointerEvents};}));for(const b of bounds){if(!b.w||!b.h)continue;expect(b.view).toBeDefined();expect(b.view![2]).toBe(b.w);expect(b.view![3]).toBe(b.h);expect(b.sx/b.sy).toBeCloseTo(1,3);expect(b.events).toBe('none');}
}
test('wide human keeps the original A4 geometry and original status layers',async({page})=>{
 await page.setViewportSize({width:1512,height:982});await openHuman(page);await expect(page.locator('.paper')).not.toHaveClass(/adaptive-card/);
 const geometry=await page.locator('.paper').evaluate(p=>{const r=p.getBoundingClientRect(),scale=r.width/p.clientWidth;return {width:p.clientWidth,height:p.clientHeight,cells:[...p.querySelectorAll('.sheet-cell')].map(e=>{const b=e.getBoundingClientRect();return {x:(b.x-r.x)/scale,y:(b.y-r.y)/scale,w:b.width/scale,h:b.height/scale};}),effects:[...p.querySelectorAll('[data-card-effect]')].map(e=>({tag:e.tagName,effect:e.getAttribute('data-card-effect'),parent:(e.parentElement as any).className?.baseVal||e.parentElement!.className})),layers:[...p.querySelectorAll('.card-art-background,.card-art-edge')].map(e=>({tag:e.tagName,class:e.getAttribute('class'),viewBox:e.getAttribute('viewBox')}))};});
 expect(geometry.width).toBe(baseline.geometry.width);expect(geometry.height).toBe(baseline.geometry.height);expect(geometry.cells).toHaveLength(baseline.geometry.cells.length);geometry.cells.forEach((cell,i)=>{for(const key of ['x','y','w','h'] as const)expect(Math.abs(cell[key]-baseline.geometry.cells[i][key])).toBeLessThan(.4);});expect(geometry.effects).toEqual(baseline.geometry.effects);expect(geometry.layers).toEqual(baseline.geometry.layers);await page.screenshot({path:out+'/human-a4-after.png'});
 for(const tab of ['特性','背景','法术','背包']){await page.getByRole('tab',{name:tab,exact:true}).click();await expect(page.locator('[data-adaptive-atmosphere]')).toHaveCount(0);await expect(page.locator('.paper .card-art-layer')).toHaveCount(2);expect(await page.locator('.paper').evaluate(e=>({width:e.clientWidth,height:e.clientHeight}))).toEqual({width:geometry.width,height:geometry.height});}
 await page.getByRole('tab',{name:'主要',exact:true}).click();await page.setViewportSize({width:390,height:900});await expect(page.locator('.paper')).toHaveClass(/adaptive-card-host/);await expect(page.locator('.paper .card-art-layer')).toHaveCount(0);await page.setViewportSize({width:1512,height:982});await expect(page.locator('.paper')).not.toHaveClass(/adaptive-card-host/);await expect(page.locator('.paper .card-art-layer')).toHaveCount(2);await expect(page.locator('[data-adaptive-frame]')).toHaveCount(0);const restored=await page.locator('.paper').evaluate(p=>{const r=p.getBoundingClientRect(),s=r.width/p.clientWidth;return [...p.querySelectorAll('.sheet-cell')].map(e=>{const b=e.getBoundingClientRect();return {x:(b.x-r.x)/s,y:(b.y-r.y)/s,w:b.width/s,h:b.height/s};});});expect(restored).toHaveLength(geometry.cells.length);restored.forEach((cell,i)=>{for(const key of ['x','y','w','h'] as const)expect(Math.abs(cell[key]-geometry.cells[i][key])).toBeLessThan(.4);});
});
test('narrow human uses its own proportional atmosphere and keeps readable controls',async({page})=>{
 await page.setViewportSize({width:390,height:900});await openHuman(page);await expect(page.locator('.paper')).toHaveClass(/adaptive-card/);await expect(page.locator('.paper .card-art-layer')).toHaveCount(0);await expect(page.locator('[data-adaptive-atmosphere]')).toBeVisible();await expect(page.locator('.ability-skill').first()).toHaveCSS('font-size','12px');
 await page.getByRole('switch',{name:'编辑模式',exact:true}).click();await expect(page.locator('.paper')).toHaveClass(/adaptive-editing/);await page.getByRole('switch',{name:'编辑模式',exact:true}).click();await expect(page.locator('.paper')).not.toHaveClass(/adaptive-editing/);await page.waitForTimeout(1100);await page.screenshot({path:out+'/human-narrow-after.png'});
 for(const tab of ['特性','背景','法术','背包']){await page.getByRole('tab',{name:tab,exact:true}).click();await expect(page.locator('.paper')).toHaveClass(/adaptive-card/);await expect(page.locator('.paper .card-art-layer')).toHaveCount(0);await page.waitForTimeout(150);await isotropic(page,false);}
});
test('monster effects are proportional on wide and narrow layouts and remain behind controls',async({page})=>{
 await page.setViewportSize({width:900,height:960});await openMonster(page);await setEffects(page);await expect(page.locator('.paper')).toHaveClass(/adaptive-card/);await expect(page.locator('.paper .card-art-layer')).toHaveCount(0);for(const id of effects){await expect(page.locator('.paper')).toHaveClass(new RegExp('adaptive-condition-'+id));if(id!=='prone')expect(await page.locator(`[data-adaptive-effect="${id}"][data-phase="present"]`).count()).toBeGreaterThan(0);}await isotropic(page);await page.getByRole('button',{name:'石桥守卫',exact:true}).click();await expect.poll(()=>page.evaluate(()=>(window as any).requests.some((m:any)=>m.type==='assignName'))).toBe(true);await page.screenshot({path:out+'/monster-wide-main.png'});
 await page.getByRole('tab',{name:'背包',exact:true}).click();await expect(page.locator('[data-stock-id="rope"]')).toBeVisible();await page.waitForTimeout(1100);await isotropic(page);await page.locator('[data-stock-id="rope"]').click({button:'right'});await expect(page.getByRole('menu')).toBeVisible();await page.keyboard.press('Escape');await page.screenshot({path:out+'/monster-wide-backpack.png'});
 await page.setViewportSize({width:360,height:900});await page.getByRole('tab',{name:'主要',exact:true}).click();await isotropic(page);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(360);await page.getByRole('switch',{name:'怪物编辑模式'}).click();await expect(page.locator('.paper')).toHaveClass(/adaptive-editing/);await page.locator('.monster-editor').getByLabel('名称',{exact:true}).fill('更名后的守卫');await page.locator('.monster-editor').getByRole('button',{name:'保存资料',exact:true}).click();await expect(page.getByRole('switch',{name:'怪物编辑模式'})).toHaveAttribute('aria-checked','false');await expect(page.getByRole('button',{name:'更名后的守卫',exact:true})).toBeVisible();await page.waitForTimeout(1100);await isotropic(page);await page.screenshot({path:out+'/monster-narrow-main.png'});
 await page.getByRole('tab',{name:'背包',exact:true}).click();await expect(page.locator('[data-stock-id="rope"]')).toBeVisible();await page.waitForTimeout(1100);await isotropic(page);await page.screenshot({path:out+'/monster-narrow-backpack.png'});
 await setEffects(page,[],false);await expect(page.locator('[data-adaptive-effect="restrained"][data-phase="leaving"]')).toHaveCount(1);await expect(page.locator('[data-adaptive-effect="restrained"]')).toHaveCount(0);await expect(page.locator('.paper')).not.toHaveClass(/adaptive-condition-prone/);
});
test('monster incapacitation moves only internal frames and editing restores usable layout',async({page})=>{
 await page.setViewportSize({width:780,height:960});await openMonster(page);const before=await page.locator('.paper').boundingBox();await setEffects(page,['petrified','frightened']);await expect(page.locator('.paper')).toHaveClass(/adaptive-condition-incapacitated/);await expect.poll(()=>page.locator('[data-adaptive-fallen="true"]').count()).toBeGreaterThan(0).catch(async error=>{console.log('GRAVITY DIAGNOSTIC',JSON.stringify(await page.locator('.paper').evaluate(p=>({class:p.className,rect:p.getBoundingClientRect().toJSON(),cells:[...p.querySelectorAll('[data-adaptive-physical]')].map(e=>({class:e.className,rect:e.getBoundingClientRect().toJSON(),style:e.getAttribute('style')}))}))));throw error;});const after=await page.locator('.paper').boundingBox();expect(after!.x).toBeCloseTo(before!.x,1);expect(after!.width).toBeCloseTo(before!.width,1);
 await expect.poll(()=>page.locator('[data-adaptive-fallen="true"]').evaluateAll(nodes=>nodes.some(e=>Math.abs(parseFloat(getComputedStyle(e).translate.split(' ')[1])||0)>2))).toBe(true);
 await page.getByRole('switch',{name:'怪物编辑模式'}).click();await expect(page.locator('.monster-editor').getByLabel('名称',{exact:true})).toBeVisible();await expect(page.locator('.paper')).toHaveClass(/adaptive-editing/);await expect.poll(()=>page.locator('[data-adaptive-fallen="true"]').count()).toBe(0);await page.getByRole('switch',{name:'怪物编辑模式'}).click();await expect.poll(()=>page.locator('[data-adaptive-fallen="true"]').count()).toBeGreaterThan(0);await page.getByRole('tab',{name:'背包',exact:true}).click();await expect(page.locator('[data-stock-id="rope"]')).toBeVisible();await expect.poll(()=>page.locator('[data-adaptive-fallen="true"]').count()).toBeGreaterThan(0);await page.waitForTimeout(2800);await page.screenshot({path:out+'/monster-gravity-backpack.png'});
});
