import {test,expect,type Page} from '@playwright/test';
import {mockSource,suppressAnnouncement} from './fixtures';
import {RULE_PACK_EXAMPLE} from '../../src/platform/rulePackExample';

async function ready(page:Page){await mockSource(page);await suppressAnnouncement(page);await page.goto('/card/?intro=0');await expect(page.locator('.paper')).toBeVisible();await expect(page.getByRole('button',{name:'更新资料',exact:true})).toBeEnabled();}
test('character book sorting and manual order survive reopening and page reload',async({page})=>{
 await ready(page);await page.getByRole('button',{name:/^角色簿/}).click();const book=page.getByRole('dialog',{name:'角色簿'});await book.getByText('批量创建角色',{exact:true}).click();await book.getByLabel('批量角色名').fill('Zeta\nAlpha');await book.getByRole('button',{name:'创建这些角色'}).click();await expect(book.locator('.character-title').filter({hasText:'Zeta'})).toBeVisible();await book.getByLabel('角色排序',{exact:true}).selectOption('name');const names=await book.locator('.character-title strong').allTextContents();expect(names.indexOf('Alpha')).toBeLessThan(names.indexOf('Zeta'));
 await book.getByLabel('角色排序',{exact:true}).selectOption('manual');await book.getByRole('button',{name:'上移Alpha',exact:true}).click();const ordered=await book.locator('.character-title strong').allTextContents();expect(ordered.indexOf('Alpha')).toBeLessThan(ordered.indexOf('Zeta'));await page.getByRole('button',{name:'关闭弹窗',exact:true}).click();await page.reload();await page.getByRole('button',{name:/^角色簿/}).click();expect(await book.locator('.character-title strong').allTextContents()).toEqual(ordered);await page.screenshot({path:test.info().outputPath('character-book260.png')});
});
test('extension file drops validate before mutation and remain in both custom and item categories after reload',async({page})=>{
 await ready(page);await page.getByRole('button',{name:'规则与扩展',exact:true}).click();const dialog=page.getByRole('dialog',{name:'规则与扩展'}),drop=dialog.locator('.json-file-drop');
 const invalid=await page.evaluateHandle(()=>{const dt=new DataTransfer();dt.items.add(new File(['{"schemaVersion":'],'bad.json',{type:'application/json'}));return dt;});await drop.dispatchEvent('drop',{dataTransfer:invalid});await invalid.dispose();await expect(dialog.getByRole('alert')).toBeVisible();await expect(dialog.locator('.pack-row')).toHaveCount(0);
 const valid=await page.evaluateHandle(pack=>{const dt=new DataTransfer();dt.items.add(new File([JSON.stringify(pack)],'extension.json',{type:'application/json'}));return dt;},RULE_PACK_EXAMPLE);await drop.dispatchEvent('drop',{dataTransfer:valid});await valid.dispose();await expect(dialog.locator('.pack-row')).toContainText('我的扩展');await page.getByRole('button',{name:'关闭弹窗',exact:true}).click();
 const tabs=page.getByRole('navigation',{name:'资料分类'});await tabs.getByRole('button',{name:'自定义',exact:true}).click();const spear=page.locator('.catalog-row').filter({hasText:'练习矛'});await expect(spear).toBeVisible();await spear.click();await expect(page.locator('.entry-detail')).toContainText('1d6');await tabs.getByRole('button',{name:'装备',exact:true}).click();await expect(spear).toBeVisible();
 await page.locator('.custom-visibility').click();await expect(spear).toHaveCount(0);await page.locator('.custom-visibility').click();await expect(spear).toBeVisible();await page.reload();await expect(spear).toBeVisible();await page.screenshot({path:test.info().outputPath('imported-extension.png')});
});
test('long monster drafts scroll to their bottom and open a bounded editor next to the clicked content',async({page})=>{
 await ready(page);await page.getByRole('navigation',{name:'资料分类'}).getByRole('button',{name:'自定义',exact:true}).click();await page.getByRole('button',{name:'JSON 输入',exact:true}).click();
 const raw={name:'长文守卫',ENG_name:'Long Guardian',source:'CUSTOM',size:['M'],type:'construct',alignment:['N'],ac:[{ac:16,from:['测试护甲'],unknownAc:'keep'}],hp:{average:55,formula:'10d8+10',unknownHp:'keep'},speed:{walk:30},str:18,dex:10,con:12,int:8,wis:10,cha:8,cr:'2',trait:Array.from({length:35},(_,i)=>({name:`特质 ${i}`,entries:['用于验证长文滚动的自定义说明。'.repeat(15)]})),action:[{name:'底部岩拳',entries:['命中造成 {@damage 2d6+4} 钝击伤害。']}],unknown:{keep:true}};
 await page.getByLabel('完整自定义条目 JSON',{exact:true}).fill(JSON.stringify({name:raw.name,english:raw.ENG_name,type:'monster',edition:'both',entries:[],raw}));await page.getByRole('button',{name:'格式输入',exact:true}).click();const action=page.locator('.custom-document').getByRole('button',{name:'修改动作',exact:true});await action.scrollIntoViewIfNeeded();await expect(action).toBeInViewport();const box=(await action.boundingBox())!;await action.click({position:{x:20,y:Math.min(20,box.height/2)}});
 const popup=page.getByRole('region',{name:'编辑动作',exact:true});await expect(popup).toBeVisible();const pb=(await popup.boundingBox())!;expect(pb.x).toBeGreaterThanOrEqual(10);expect(pb.y).toBeGreaterThanOrEqual(10);expect(pb.y+pb.height).toBeLessThanOrEqual(962);expect(Math.abs(pb.x-(box.x+20))).toBeLessThan(490);await page.getByLabel('子条目名称',{exact:true}).fill('修改后的底部岩拳');await page.getByRole('button',{name:'完成修改',exact:true}).click();await page.getByRole('button',{name:'保存条目',exact:true}).click();await expect(page.locator('.entry-detail')).toContainText('修改后的底部岩拳');await page.screenshot({path:test.info().outputPath('long-monster-bottom.png')});
 await page.reload();await expect(page.locator('.entry-detail')).toContainText('修改后的底部岩拳');await page.getByRole('button',{name:'编辑此条目',exact:true}).click();await page.getByRole('button',{name:'JSON 输入',exact:true}).click();const saved=JSON.parse(await page.getByLabel('完整自定义条目 JSON',{exact:true}).inputValue());expect(saved.raw.unknown).toEqual({keep:true});expect(saved.raw.ac[0].unknownAc).toBe('keep');expect(saved.raw.hp.unknownHp).toBe('keep');
});
