import {test,expect,type Page} from '@playwright/test';
import {createHash} from 'node:crypto';
import {newCharacter,type Entry} from '../../src/core/model';
import {newAutomationState} from '../../src/core/automation/state';
import {exportCharacter} from '../../src/core/export';
import {mockSource,suppressAnnouncement} from './fixtures';
import {installCardAutomation,browserFixtureEnvelope} from './automationFixtures';
const armor:Entry={id:'ir-test:armor',name:'原创重甲',english:'Authored Heavy Armor',kind:'item',packId:'fixture',source:'XPHB',edition:'2024',revision:'test',entries:['原创浏览器验收资料。'],raw:{type:'HA',ac:16}};
function card(legacy=false){const c=newCharacter();c.name=legacy?'协议二验收':'IR 数据验收';c.abilities.dex=16;c.selections=[{id:'armor',entry:structuredClone(armor),quantity:1,level:1,equipped:true}];c.runtime.resources.spent={name:'保留次数',current:1,max:3};c.automation=legacy?{protocol:2,enabled:true,rulesVersion:'equipment.1',defaultsVersion:1}:newAutomationState();return c;}
async function workspace(page:Page){return page.evaluate(async()=>{const request=indexedDB.open('dnd-card-standalone'),db=await new Promise<IDBDatabase>((resolve,reject)=>{request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});try{return await new Promise<any>((resolve,reject)=>{const req=db.transaction('documents').objectStore('documents').get('workspace');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}finally{db.close();}});}
async function openSettings(page:Page){await page.getByRole('button',{name:'自动化设置',exact:true}).click();}
async function start(page:Page,c=card()){
 await mockSource(page);await suppressAnnouncement(page);const fixture=await installCardAutomation(page,c,[],false);await page.goto('/');await openSettings(page);await expect(page.getByTestId('automation-data-status')).toContainText(/已读取|已缓存/);await page.keyboard.press('Escape');
 await page.getByRole('button',{name:'导入 / 导出',exact:true}).click();await page.getByTestId('character-file').setInputFiles({name:'authored.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(exportCharacter(c)))});await expect(page.locator('.character-tabs').getByRole('tab',{name:c.name+'（导入）',exact:true})).toHaveAttribute('aria-selected','true');await page.getByRole('dialog',{name:'导入与导出',exact:true}).getByRole('button',{name:'关闭弹窗',exact:true}).click();await expect(page.locator('.save-status')).toContainText('已保存到本机');return fixture;
}
test('protocol 2 import and reload preserve the original; explicit IR upgrade creates a separate copy',async({page})=>{
 await start(page,card(true));const before=await workspace(page),original=before.characters.find((c:any)=>c.id===before.activeId);expect(original.automation.protocol).toBe(2);await openSettings(page);await expect(page.getByRole('alert').filter({hasText:'旧版或尚未支持'})).toBeVisible();await expect(page.getByRole('checkbox',{name:'启用自动计算',exact:true})).toHaveCount(0);await expect(page.getByTestId('automation-ac')).toHaveText('13');await page.keyboard.press('Escape');await page.reload();await openSettings(page);expect((await workspace(page)).characters.find((c:any)=>c.id===original.id)).toEqual(original);
 await page.getByRole('button',{name:'复制并升级到 IR 自动化',exact:true}).click();await expect(page.locator('.character-tabs').getByRole('tab',{name:original.name+'（IR 副本）',exact:true})).toHaveAttribute('aria-selected','true');await expect(page.locator('.save-status')).toContainText('已保存到本机');await openSettings(page);await expect(page.getByTestId('automation-ac')).toHaveText('16');const after=await workspace(page),copy=after.characters.find((c:any)=>c.id===after.activeId);expect(copy.id).not.toBe(original.id);expect(copy.automation.protocol).toBe(3);expect(copy.runtime.resources.spent).toEqual(original.runtime.resources.spent);expect(after.characters.find((c:any)=>c.id===original.id)).toEqual(original);
});
test('hash-locked cached rules survive a dataset network failure and retain consumed resources',async({page})=>{
 const fixture=await start(page);await openSettings(page);await expect(page.getByTestId('automation-ac')).toHaveText('16');await page.keyboard.press('Escape');const before=await workspace(page);await page.unroute(fixture.source.url);await page.route(fixture.source.url,route=>route.abort('internetdisconnected'));await page.reload();await openSettings(page);await expect(page.getByTestId('automation-data-status')).toContainText('已缓存，可离线使用');await expect(page.getByTestId('automation-ac')).toHaveText('16');expect((await workspace(page)).characters.find((c:any)=>c.id===before.activeId).runtime.resources.spent).toEqual({name:'保留次数',current:1,max:3});
});
test('invalid refreshed rules disable execution visibly and retain the stored card and resource debt',async({page})=>{
 const fixture=await start(page);const before=await workspace(page);await openSettings(page);await page.locator('.automation-panel').getByText('自动化资料源',{exact:true}).click();await page.getByRole('textbox',{name:'自动化资料版本',exact:true}).fill(fixture.source.kiweeVersion);await page.getByRole('textbox',{name:'自动化资料哈希',exact:true}).fill(fixture.source.sha256);const badUrl='https://example.org/corrupt.json';await page.route(badUrl,route=>route.fulfill({json:{}}));await page.getByRole('textbox',{name:'自动化资料地址',exact:true}).fill(badUrl);await page.getByRole('button',{name:'读取资料源',exact:true}).click();await expect(page.getByTestId('automation-data-status')).toContainText('不可用');await expect(page.getByTestId('automation-selected-coverage')).toContainText('待注释 1');await expect(page.getByTestId('automation-ac')).toHaveText('13');expect((await workspace(page)).characters).toEqual(before.characters);
});
test('a valid file hash cannot bypass canonical identity validation on local IR import',async({page})=>{
 const c=card(),fixture=await start(page,c),before=await workspace(page),forged=browserFixtureEnvelope(c.selections.map(row=>row.entry));forged.records[0].identity.key='forged';const body=JSON.stringify(forged),sha=createHash('sha256').update(body).digest('hex');expect(sha).not.toBe(fixture.source.sha256);await openSettings(page);await page.locator('.automation-panel').getByText('自动化资料源',{exact:true}).click();await page.getByRole('textbox',{name:'自动化资料版本',exact:true}).fill(fixture.source.kiweeVersion);await page.getByRole('textbox',{name:'自动化资料哈希',exact:true}).fill(sha);await page.getByLabel('导入自动化资料',{exact:true}).setInputFiles({name:'forged.json',mimeType:'application/json',buffer:Buffer.from(body)});await expect(page.getByTestId('automation-data-status')).toContainText('不可用');expect((await workspace(page)).characters).toEqual(before.characters);
});
