import {test,expect,type Page} from '@playwright/test';
import {mockSource} from './fixtures';
import {newCharacter} from '../../src/core/model';
const output='F:/CodexWork/2026-09-20/w-xu/tests177';
async function harness(page:Page,body:string,suffix=''){
 page.on('pageerror',error=>console.log('HARNESS ERROR',error.message));
 await page.route('**/cards177-harness',route=>route.fulfill({contentType:'text/html',body:`<!doctype html><html><head><meta charset="utf-8">${['style','workspace','workbench','overview','library','cardAtmosphere','libraryRefine','characterPages','suiteTheme','responsive176','responsive177'].map(name=>`<link rel="stylesheet" href="/src/ui/${name}.css">`).join('')}</head><body><div id="test-root"></div><script type="module">import RefreshRuntime from "/@react-refresh";RefreshRuntime.injectIntoGlobalHook(window);window.$RefreshReg$=()=>{};window.$RefreshSig$=()=>type=>type;window.__vite_plugin_react_preamble_installed__=true;</script><script type="module">import React from '/node_modules/.vite/deps/react.js';import ReactDOM from '/node_modules/.vite/deps/react-dom_client.js';const {createRoot}=ReactDOM;${body}</script></body></html>`}));await page.goto('/cards177-harness'+suffix);
}
test('narrow character and all detail pages are readable; wide sheet remains A4',async({page})=>{
 await mockSource(page);await page.setViewportSize({width:300,height:920});await page.goto('/');await expect(page.locator('.sheet-reflow .paper')).toBeVisible();const shape=await page.locator('.paper').boundingBox();expect(shape!.width).toBeGreaterThan(260);expect(shape!.height).toBeGreaterThan(1100);await expect(page.locator('.ability-skill').first()).toHaveCSS('font-size','12px');await page.screenshot({path:`${output}/character177-top.png`});await page.locator('.ability-str').scrollIntoViewIfNeeded();await page.screenshot({path:`${output}/character177-abilities.png`});
 for(const tab of ['特性','背景','法术','背包']){await page.getByRole('tab',{name:tab,exact:true}).click();await expect(page.locator('.sheet-details')).toBeVisible();const bounds=await page.locator('.paper').evaluate(el=>({width:el.clientWidth,scrollWidth:el.scrollWidth,scale:new DOMMatrix(getComputedStyle(el).transform).a}));expect(bounds.scrollWidth).toBeLessThanOrEqual(bounds.width+2);expect(bounds.scale).toBe(1);if(tab==='背景')await expect(page.locator('.biography-field').first()).toHaveCSS('font-size','13px');if(tab==='背包')await expect(page.locator('.stock-item').first()).toHaveCSS('height','46px');await page.screenshot({path:`${output}/character177-${tab}.png`});}
 await page.setViewportSize({width:1800,height:1080});await page.getByRole('tab',{name:'主要',exact:true}).click();await expect(page.locator('.sheet-reflow')).toHaveCount(0);const wide=await page.locator('.paper').boundingBox();expect(wide!.height/wide!.width).toBeCloseTo(297/210,2);
});
test('monster text and ability rolls remain legible in 254 px pane',async({page})=>{
 await page.setViewportSize({width:254,height:920});await harness(page,`import {WorkbenchMonster} from '/src/ui/Workbench.tsx';const target={key:'monster:test',itemId:'test',id:'test',kind:'monster',name:'测试怪物',slug:'test',write:true,role:'GM',stats:{health:20,'max health':20,'temporary health':0,'armor class':13}};createRoot(document.getElementById('test-root')).render(React.createElement('section',{className:'sheet-pane mobile-active',style:{height:'100dvh'}},React.createElement(WorkbenchMonster,{target,raw:{name:'测试怪物',source:'CUSTOM',size:['M'],type:'beast',str:12,dex:13,con:12,int:4,wis:12,cha:4,action:[{name:'啮咬',entries:['以利齿攻击目标。'.repeat(80)]}]},online:true,onLink:()=>{}})));`);
 await expect(page.locator('.monster-document')).toHaveCSS('font-size','13px');const viewport=await page.locator('.sheet-viewport').evaluate(el=>({height:el.clientHeight,scroll:el.scrollHeight}));expect(viewport.scroll).toBeGreaterThan(viewport.height);const paper=await page.locator('.paper').evaluate(el=>({w:el.clientWidth,sw:el.scrollWidth}));expect(paper.sw).toBeLessThanOrEqual(paper.w+2);await page.screenshot({path:`${output}/monster177.png`});
});
test('resources commit once on Enter or blur without a confirmation button',async({page})=>{
 await harness(page,`import {ResourceRow} from '/src/ui/ResourceRow.tsx';window.commits=[];let r={name:'法术点',type:'number',current:3,max:9};const root=createRoot(document.getElementById('test-root'));function render(){root.render(React.createElement('div',null,React.createElement(ResourceRow,{resource:r,enabled:true,gm:true,change:async n=>{window.commits.push(n);r={...r,current:n};render();}}),React.createElement('button',null,'外部区域')));}render();`);
 await page.locator('.resource-numeric').click();await page.getByRole('textbox',{name:'法术点剩余'}).fill('5');await page.keyboard.press('Enter');await expect(page.locator('.resource-numeric')).toContainText('5');expect(await page.evaluate(()=>(window as any).commits)).toEqual([5]);await expect(page.getByRole('button',{name:'结束资源输入'})).toHaveCount(0);await page.locator('.resource-numeric').click();await page.getByRole('textbox',{name:'法术点剩余'}).fill('7');await page.getByRole('button',{name:'外部区域'}).click();await expect(page.locator('.resource-numeric')).toContainText('7');expect(await page.evaluate(()=>(window as any).commits)).toEqual([5,7]);await page.locator('.resource-numeric').click();await page.getByRole('button',{name:'外部区域'}).click();await expect(page.locator('.resource-numeric')).toBeVisible();expect(await page.evaluate(()=>(window as any).commits)).toEqual([5,7]);
});
test('warehouse lock is isolated from collapse and unlocked player can edit quantity',async({page})=>{
 await harness(page,`import {StockBoard} from '/src/ui/StockBoard.tsx';import {previewInventory} from '/src/core/inventory.ts';window.ops=[];let gm=true,container={id:'public:test',name:'公共仓库',kind:'public',write:false,locked:false,revision:1,columns:4,items:[{id:'a',kind:'item',name:'绳索',quantity:2,slot:0,revision:1}]};const root=createRoot(document.getElementById('test-root'));function render(){root.render(React.createElement('div',null,React.createElement('button',{onClick:()=>{gm=!gm;render();}},'切换身份'),React.createElement(StockBoard,{container,gm,operation:async op=>{window.ops.push(op);container=previewInventory({revision:1,containers:{[container.id]:container}},op).containers[container.id];render();}})));}render();`);
 await page.getByRole('button',{name:'上锁公共仓库',exact:true}).click();await expect(page.locator('.stock-collection')).toBeVisible();await expect(page.getByRole('button',{name:'解锁公共仓库',exact:true})).toHaveAttribute('aria-pressed','true');await page.getByRole('button',{name:'切换身份'}).click();await expect(page.getByRole('button',{name:'绳索数量'})).toBeDisabled();await page.getByRole('button',{name:'切换身份'}).click();await page.getByRole('button',{name:'解锁公共仓库',exact:true}).click();await page.getByRole('button',{name:'切换身份'}).click();await expect(page.getByRole('button',{name:'绳索数量'})).toBeEnabled();await page.getByRole('button',{name:'绳索数量'}).click();await page.getByRole('textbox',{name:'绳索数量'}).fill('4');await page.keyboard.press('Enter');await expect(page.getByRole('button',{name:'绳索数量'})).toHaveText('x4');
});
test('portrait deletion confirms and persists without removing independent illustration',async({page})=>{
 await mockSource(page);await page.goto('/');await expect(page.getByRole('button',{name:'更新资料',exact:true})).toBeEnabled();const c=newCharacter(),data=await page.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=100;canvas.height=100;const ctx=canvas.getContext('2d')!;ctx.fillStyle='tomato';ctx.fillRect(0,0,100,100);return canvas.toDataURL();});c.portrait={data,x:0,y:0,zoom:1};c.illustration={data,x:0,y:0,zoom:1};await page.getByRole('button',{name:'导入 / 导出',exact:true}).click();await page.getByTestId('character-file').setInputFiles({name:'portrait.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(c))});await page.getByRole('button',{name:'关闭弹窗'}).click();await page.getByRole('switch',{name:'编辑模式'}).click();await page.locator('.portrait-view').hover();await page.getByRole('button',{name:'删除头像',exact:true}).click();await page.getByRole('button',{name:'取消',exact:true}).click();await expect(page.getByAltText('角色头像')).toBeVisible();await page.locator('.portrait-view').hover();await page.getByRole('button',{name:'删除头像',exact:true}).click();await page.getByRole('alertdialog').getByRole('button',{name:'删除',exact:true}).click();await expect(page.getByAltText('角色头像')).toHaveCount(0);await page.getByRole('tab',{name:'背景',exact:true}).click();await expect(page.getByAltText('角色立绘')).toBeVisible();await page.reload();await page.getByRole('tab',{name:'主要',exact:true}).click();await expect(page.getByAltText('角色头像')).toHaveCount(0);
});
test('character strip scrolls on a separate row without selecting during drag; reconnection never shifts rows',async({page})=>{
 await page.setViewportSize({width:300,height:800});await harness(page,`import {WorkbenchBar} from '/src/ui/Workbench.tsx';window.changes=[];const root=createRoot(document.getElementById('test-root'));window.setBar=online=>root.render(React.createElement(WorkbenchBar,{online,page:'console',message:online?'':'正在重新连接枭熊…',target:{name:'角色甲'},change:p=>window.changes.push(p),save:()=>{}}));window.setBar(true);`, '#suite=strip177&bridge='+encodeURIComponent('http://127.0.0.1:5179'));
 await page.evaluate(()=>{const send=(type:string,rest:any={})=>window.dispatchEvent(new MessageEvent('message',{source:window,origin:location.origin,data:{protocol:'full-suite-workbench/v1',session:'strip177',type,...rest}}));send('ready');send('catalog',{role:'GM',sequence:1,enabled:{},cards:Array.from({length:12},(_,i)=>({id:String(i),itemId:'card:'+i,name:'测试冒险者'+i,write:true,inScene:true,locked:false,resources:[],stats:{}})),monsters:[]});});
 await expect(page.locator('.workbench-cards>button')).toHaveCount(12);await expect(page.locator('.workbench-cards small')).toHaveCount(0);const before=await page.locator('.workbench-cards').boundingBox(),modes=await page.locator('.workbench-modes').boundingBox();expect(before!.y).toBeGreaterThanOrEqual(modes!.y+modes!.height);await page.locator('.workbench-cards').hover();await page.mouse.wheel(0,180);await expect.poll(()=>page.locator('.workbench-cards').evaluate(el=>el.scrollLeft)).toBeGreaterThan(100);const current=await page.locator('.workbench-cards').evaluate(el=>el.scrollLeft);await page.mouse.move(240,before!.y+12);await page.mouse.down();await page.mouse.move(70,before!.y+12,{steps:8});await page.mouse.up();expect(await page.locator('.workbench-cards').evaluate(el=>el.scrollLeft)).toBeGreaterThan(current);expect(await page.evaluate(()=>(window as any).changes)).toEqual([]);await page.evaluate(()=>(window as any).setBar(false));const after=await page.locator('.workbench-cards').boundingBox();expect(after!.y).toBe(before!.y);expect(after!.height).toBe(before!.height);
});
test('warehouse transfer lands as a compact tile rather than covering the recipient',async({page})=>{
 await harness(page,`import {StockBoard} from '/src/ui/StockBoard.tsx';const container={id:'public:test',name:'公共仓库',kind:'public',write:true,revision:1,columns:4,items:[{id:'a',kind:'item',name:'绳索',quantity:2,slot:0,revision:1}]};window.ops=[];createRoot(document.getElementById('test-root')).render(React.createElement('div',{style:{width:400}},React.createElement(StockBoard,{container,gm:true,operation:async op=>window.ops.push(op)}),React.createElement('article',{'data-inventory-recipient':'card:target',style:{height:240,width:380,background:'#ddd'}},'接收角色')));`);
 const source=await page.locator('[data-stock-id="a"]').boundingBox(),target=await page.locator('[data-inventory-recipient]').boundingBox();await page.mouse.move(source!.x+15,source!.y+15);await page.mouse.down();await page.mouse.move(target!.x+80,target!.y+40,{steps:8});await page.mouse.up();const landing=await page.locator('.pointer-ghost').evaluate(el=>el.getAnimations().flatMap(a=>(a.effect as KeyframeEffect).getKeyframes()).map(f=>({width:f.width,height:f.height})));expect(landing.some(f=>Number.parseFloat(String(f.width))>source!.width+1)).toBe(false);expect(landing.some(f=>Number.parseFloat(String(f.height))>source!.height+1)).toBe(false);await expect.poll(()=>page.evaluate(()=>(window as any).ops.length)).toBe(1);expect(await page.evaluate(()=>(window as any).ops[0].to)).toBe('card:target');
});

test('narrow PNG export uses full A4 pixels and restores readable layout afterwards',async({page})=>{
 await mockSource(page);await page.setViewportSize({width:300,height:920});await page.goto('/');await expect(page.locator('.sheet-reflow .paper')).toBeVisible();
 const before=await page.locator('.paper').evaluate(el=>({width:el.clientWidth,height:el.clientHeight}));
 const result=await page.evaluate(async()=>{const paper=document.querySelector<HTMLElement>('.paper')!,viewport=paper.closest('.sheet-viewport')!;let exportedAtA4=false;const observer=new MutationObserver(()=>{if(paper.classList.contains('sheet-export')&&!viewport.classList.contains('sheet-reflow')&&paper.clientWidth>=678&&paper.clientHeight>=959)exportedAtA4=true;});observer.observe(paper,{attributes:true});const source='/src/platform/sheetImage.ts';const {captureSheet}=await import(source);const blob=await captureSheet();observer.disconnect();const image=await createImageBitmap(blob);const result={width:image.width,height:image.height,size:blob.size,exportedAtA4};image.close();return result;});
 expect(result.width).toBe(2480);expect(result.height).toBe(3508);expect(result.size).toBeGreaterThan(10000);expect(result.exportedAtA4).toBe(true);await expect(page.locator('.sheet-reflow .paper')).toBeVisible();expect(await page.locator('.paper').evaluate(el=>({width:el.clientWidth,height:el.clientHeight}))).toEqual(before);
});

test('uncertain resource and stat values stay visible until terminal receipts or matching authority',async({page})=>{
 await harness(page,`import {ResourceRow} from '/src/ui/ResourceRow.tsx';import {StatInput} from '/src/ui/StatInput.tsx';let current=3,hp=10;window.uncertain=true;const root=createRoot(document.getElementById('test-root'));const fail=id=>Promise.reject(Object.assign(Error('await receipt'),{uncertain:window.uncertain,requestId:id,statField:'health'}));window.updateValues=(r,s)=>{current=r;hp=s;render();};function render(){root.render(React.createElement('div',null,React.createElement(ResourceRow,{resource:{id:'fuel',name:'能量',type:'number',current,max:12},enabled:true,gm:true,change:()=>fail('resource-ui')}),React.createElement(StatInput,{value:hp,label:'生命',commit:()=>fail('stats-ui')}),React.createElement('button',null,'其他区域')));}render();`);
 await page.locator('.resource-numeric').click();await page.getByRole('textbox',{name:'能量剩余'}).fill('7');await page.keyboard.press('Enter');await expect(page.locator('.resource-numeric')).toContainText('7');await page.getByRole('textbox',{name:'生命',exact:true}).fill('20');await page.keyboard.press('Enter');await expect(page.getByRole('textbox',{name:'生命',exact:true})).toHaveValue('20');
 await page.evaluate(()=>(window as any).updateValues(2,9));await expect(page.locator('.resource-numeric')).toContainText('7');await expect(page.getByRole('textbox',{name:'生命',exact:true})).toHaveValue('20');await page.evaluate(()=>window.dispatchEvent(new CustomEvent('workbench-operation-result',{detail:{requestId:'resource-ui',ok:false,uncertain:true}})));await expect(page.locator('.resource-numeric')).toContainText('7');
 await page.evaluate(()=>{(window as any).updateValues(6,17);window.dispatchEvent(new CustomEvent('workbench-operation-result',{detail:{requestId:'resource-ui',ok:true,result:{snapshot:{state:{resources:[{id:'fuel',current:6}]}}}}}));window.dispatchEvent(new CustomEvent('workbench-operation-result',{detail:{requestId:'stats-ui',ok:true,result:{snapshot:{state:{stats:{health:17}}}}}}));});await expect(page.locator('.resource-numeric')).toContainText('6');await expect(page.getByRole('textbox',{name:'生命',exact:true})).toHaveValue('17');
 await page.evaluate(()=>(window as any).uncertain=false);await page.locator('.resource-numeric').click();await page.getByRole('textbox',{name:'能量剩余'}).fill('11');await page.keyboard.press('Enter');await expect(page.locator('.resource-numeric')).toContainText('6');await page.getByRole('textbox',{name:'生命',exact:true}).fill('2');await page.keyboard.press('Enter');await expect(page.getByRole('textbox',{name:'生命',exact:true})).toHaveValue('17');
});
test('overview ResourceCard preserves its uncertain overlay and clears it on the late terminal ACK',async({page})=>{
 await harness(page,`import {DMConsole} from '/src/ui/WorkbenchConsole.tsx';createRoot(document.getElementById('test-root')).render(React.createElement(DMConsole,{navigate:()=>{}}));window.requests=[];window.addEventListener('message',event=>{if(event.source===window&&event.data.type==='resource'){window.requests.push(event.data);window.dispatchEvent(new MessageEvent('message',{source:window,origin:location.origin,data:{protocol:'full-suite-workbench/v1',session:'resource177',type:'ack',requestId:event.data.requestId,ok:false,uncertain:true,message:'await receipt'}}));}});`, '#suite=resource177&bridge='+encodeURIComponent('http://127.0.0.1:5179'));
 await page.evaluate(()=>{const send=(type:string,rest:any={})=>window.dispatchEvent(new MessageEvent('message',{source:window,origin:location.origin,data:{protocol:'full-suite-workbench/v1',session:'resource177',type,...rest}}));(window as any).emit=send;send('ready');(window as any).card={id:'hero',itemId:'card:hero',kind:'character',name:'英雄',locked:false,write:true,inScene:true,resources:[{id:'fuel',name:'能量',type:'number',current:3,max:12}],stats:{health:10,'max health':20,'temporary health':0,'armor class':12}};send('catalog',{sequence:1,role:'GM',enabled:{inventory:false},cards:[(window as any).card],monsters:[]});});
 await page.locator('.resource-numeric').click();await page.getByRole('textbox',{name:'英雄能量剩余'}).fill('7');await page.keyboard.press('Enter');await expect.poll(()=>page.evaluate(()=>(window as any).requests.length)).toBe(1);await expect(page.locator('.resource-numeric')).toContainText('7');
 await page.evaluate(()=>{const card=(window as any).card;card.resources[0].current=2;(window as any).emit('catalog',{sequence:2,role:'GM',enabled:{inventory:false},cards:[card],monsters:[]});});await expect(page.locator('.resource-numeric')).toContainText('7');
 await page.evaluate(()=>{const card=(window as any).card;card.resources[0].current=7;(window as any).emit('ack',{requestId:(window as any).requests[0].requestId,ok:true,result:{sequence:3,snapshot:{sequence:3,state:{...card,cardId:card.id,key:'room:card:hero',role:'GM',kind:'character',pinned:false,slug:''}}}});});await expect(page.locator('.resource-numeric')).toContainText('7');
 await page.evaluate(()=>{const card=(window as any).card;card.resources[0].current=8;(window as any).emit('catalog',{sequence:4,role:'GM',enabled:{inventory:false},cards:[card],monsters:[]});});await expect(page.locator('.resource-numeric')).toContainText('8');
});

test('uncertain widgets reconcile only a genuine authority match and keep the original sent target',async({page})=>{
 await harness(page,`import {ResourceRow} from '/src/ui/ResourceRow.tsx';import {StatInput} from '/src/ui/StatInput.tsx';let current=3,confirmed=3,hp=10,optimistic=1,calls=0;window.reconciled=[];window.addEventListener('workbench-operation-reconciled',e=>window.reconciled.push(e.detail.requestId));const root=createRoot(document.getElementById('test-root'));const fail=(id,blocked=false)=>Promise.reject(Object.assign(Error('await receipt'),{uncertain:true,requestId:id,queueBlocked:blocked}));window.values=(r,c,h,o)=>{current=r;confirmed=c;hp=h;optimistic=o;render();};function render(){root.render(React.createElement('div',null,React.createElement(ResourceRow,{resource:{id:'fuel',name:'能量',type:'number',current,max:12},confirmedCurrent:confirmed,enabled:true,gm:true,change:()=>fail('raw-resource',++calls>1)}),React.createElement(StatInput,{value:hp,label:'生命',commit:()=>fail('raw-stat')}),React.createElement(StatInput,{value:optimistic,label:'仅乐观值',authority:false,commit:()=>fail('overlay-stat')})));}render();`);
 await page.locator('.resource-numeric').click();await page.getByRole('textbox',{name:'能量剩余'}).fill('7');await page.keyboard.press('Enter');await expect(page.locator('.resource-numeric')).toContainText('7');
 await page.evaluate(()=>(window as any).values(7,3,10,1));expect(await page.evaluate(()=>(window as any).reconciled)).toEqual([]);
 await page.locator('.resource-numeric').click();await page.getByRole('textbox',{name:'能量剩余'}).fill('9');await page.keyboard.press('Enter');await expect(page.locator('.resource-numeric')).toContainText('9');
 await page.getByRole('textbox',{name:'生命',exact:true}).fill('15');await page.keyboard.press('Enter');await page.getByRole('textbox',{name:'仅乐观值',exact:true}).fill('4');await page.keyboard.press('Enter');
 await page.evaluate(()=>(window as any).values(9,7,15,4));await expect.poll(()=>page.evaluate(()=>(window as any).reconciled)).toEqual(['raw-resource','raw-stat']);await expect(page.locator('.resource-numeric')).toContainText('7');await expect(page.getByRole('textbox',{name:'生命',exact:true})).toHaveValue('15');
 await page.evaluate(()=>window.dispatchEvent(new CustomEvent('workbench-operation-reconciled',{detail:{requestId:'overlay-stat'}})));await page.evaluate(()=>(window as any).values(7,7,16,6));await expect(page.getByRole('textbox',{name:'仅乐观值',exact:true})).toHaveValue('6');
});

test('overview matching catalog releases the unknown queue without replaying its blocked edit',async({page})=>{
 await harness(page,`import {DMConsole} from '/src/ui/WorkbenchConsole.tsx';createRoot(document.getElementById('test-root')).render(React.createElement(DMConsole,{navigate:()=>{}}));window.requests=[];window.reconciled=[];window.addEventListener('workbench-operation-reconciled',e=>window.reconciled.push(e.detail.requestId));window.addEventListener('message',event=>{if(event.source===window&&event.data.type==='resource'){window.requests.push(event.data);window.dispatchEvent(new MessageEvent('message',{source:window,origin:location.origin,data:{protocol:'full-suite-workbench/v1',session:'resource177',type:'ack',requestId:event.data.requestId,ok:false,uncertain:true,message:'await receipt'}}));}});`, '#suite=resource177&bridge='+encodeURIComponent('http://127.0.0.1:5179'));
 await page.evaluate(()=>{const send=(type:string,rest:any={})=>window.dispatchEvent(new MessageEvent('message',{source:window,origin:location.origin,data:{protocol:'full-suite-workbench/v1',session:'resource177',type,...rest}}));(window as any).emit=send;send('ready');(window as any).card={id:'hero',itemId:'card:hero',kind:'character',name:'英雄',locked:false,write:true,inScene:true,resources:[{id:'fuel',name:'能量',type:'number',current:3,max:12}],stats:{health:10,'max health':20,'temporary health':0,'armor class':12}};send('catalog',{sequence:1,role:'GM',enabled:{inventory:false},cards:[(window as any).card],monsters:[]});});
 for(const value of ['7','9']){await page.locator('.resource-numeric').click();await page.getByRole('textbox',{name:'英雄能量剩余'}).fill(value);await page.keyboard.press('Enter');await expect(page.locator('.resource-numeric')).toContainText(value);}
 expect(await page.evaluate(()=>(window as any).requests.length)).toBe(1);expect(await page.evaluate(()=>(window as any).reconciled)).toEqual([]);
 await page.evaluate(()=>{const card=(window as any).card;card.resources[0].current=7;(window as any).emit('catalog',{sequence:2,role:'GM',enabled:{inventory:false},cards:[card],monsters:[]});});await expect(page.locator('.resource-numeric')).toContainText('7');await expect.poll(()=>page.evaluate(()=>(window as any).reconciled.length)).toBeGreaterThan(0);expect(await page.evaluate(()=>(window as any).requests.length)).toBe(1);
 await page.locator('.resource-numeric').click();await page.getByRole('textbox',{name:'英雄能量剩余'}).fill('8');await page.keyboard.press('Enter');await expect.poll(()=>page.evaluate(()=>(window as any).requests.length)).toBe(2);expect(await page.evaluate(()=>(window as any).requests.map((r:any)=>r.resource?.current??r.payload?.resource?.current))).toEqual([7,8]);
});
