import {test,expect,type Page} from '@playwright/test';
import {mockSource,fillFromDetail} from './fixtures';
import {newCharacter,type Character,type Entry} from '../../src/core/model';
const tabs=(page:Page)=>page.getByRole('navigation',{name:'资料分类'});
test.beforeEach(async({page})=>{await mockSource(page);});
async function importCard(page:Page,c:Character){await page.goto('/');await expect(page.getByRole('button',{name:'更新资料',exact:true})).toBeEnabled();await page.getByRole('button',{name:'导入 / 导出',exact:true}).click();await page.getByTestId('character-file').setInputFiles({name:'test.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(c))});await page.getByRole('button',{name:'关闭弹窗'}).click();}
const e=(kind:Entry['kind'],name:string,raw:Entry['raw']={}):Entry=>({id:`test:${name}`,kind,name,english:name,source:'XPHB',edition:'2024',packId:'test',revision:'1',raw,entries:['用于页面验收的自制内容。']});
function add(c:Character,entry:Entry){c.selections.push({id:entry.id,entry,quantity:1,level:1,equipped:false});}
test('nested choice references expand and committing a card preview preserves its scroll offset',async({page})=>{
 await page.route('**/data/class/class-test.json',r=>r.fulfill({json:{class:[{name:'测试法师',source:'XPHB',classFeatures:['前言|测试法师|XPHB|1','圣职|测试法师|XPHB|1']}],classFeature:[{name:'前言',className:'测试法师',classSource:'XPHB',source:'XPHB',level:1,entries:Array.from({length:40},()=> '长正文用于确认预览滚动位置。')},{name:'圣职',className:'测试法师',classSource:'XPHB',source:'XPHB',level:1,entries:[{type:'entries',entries:[{type:'options',entries:[{type:'refClassFeature',classFeature:'保护者|测试法师|XPHB|1'}]}]}]},{name:'保护者',className:'测试法师',classSource:'XPHB',source:'XPHB',level:1,entries:['这里是选项的完整正文，默认展开。']}]}}));
 await page.goto('/');await expect(page.getByRole('button',{name:'更新资料',exact:true})).toBeEnabled();await page.locator('.catalog-row').click();await expect(page.locator('.document-prose')).toContainText('这里是选项的完整正文');await fillFromDetail(page);const chip=page.locator('.class-features .feature-caption').filter({hasText:'圣职'});await chip.hover();await expect.poll(()=>page.locator('.entry-detail').evaluate(e=>e.scrollTop)).toBeGreaterThan(100);const before=await page.locator('.entry-detail').evaluate(e=>e.scrollTop);await chip.click();await page.mouse.move(30,30);await expect.poll(async()=>Math.abs(await page.locator('.entry-detail').evaluate(e=>e.scrollTop)-before)).toBeLessThan(3);
});
test('subclass drops require their owner and replace only that owner’s subclass',async({page})=>{
 const c=newCharacter();add(c,e('class','法师'));add(c,e('class','战士'));add(c,e('subclass','旧学派',{className:'法师',classSource:'XPHB'}));c.selections.at(-1)!.parentId='test:法师';add(c,e('subclass','战士子职',{className:'战士',classSource:'XPHB'}));c.selections.at(-1)!.parentId='test:战士';
 await page.route('**/data/class/class-test.json',r=>r.fulfill({json:{class:[{name:'法师',source:'XPHB'},{name:'游侠',source:'XPHB'}],subclass:[{name:'新学派',source:'XPHB',className:'法师',classSource:'XPHB'},{name:'游侠子职',source:'XPHB',className:'游侠',classSource:'XPHB'}]}}));await importCard(page,c);await page.locator('.catalog-row').filter({hasText:'法师'}).click();await page.locator('.class-subclasses button').filter({hasText:'新学派'}).dragTo(page.locator('.identity-class'));await expect(page.locator('.identity-class')).toContainText('新学派');await expect(page.locator('.identity-class')).not.toContainText('旧学派');await expect(page.locator('.identity-class')).toContainText('战士子职');await page.locator('.catalog-row').filter({hasText:'游侠'}).click();await page.locator('.class-subclasses button').dragTo(page.locator('.identity-class'));await expect(page.locator('.identity-class')).not.toContainText('游侠子职');
});
test('background choices, feats, biographies and prepared spells persist in separate page sections',async({page})=>{
 await page.route('**/data/backgrounds.json',r=>r.fulfill({json:{background:[{name:'抄书员',source:'XPHB',ability:[{choose:{weighted:{from:['int','wis','cha'],weights:[2,1]}}}],feats:[{'旅行笔记|xphb':true}],skillProficiencies:[{history:true}],startingEquipment:[{A:[{special:'墨水',quantity:2},{value:800}],B:[{value:5000}]}]}]}}));
 const c=newCharacter();add(c,e('spell','光箭',{level:1}));add(c,e('spell','护盾',{level:1}));await importCard(page,c);await tabs(page).getByRole('button',{name:'背景',exact:true}).click();await page.locator('.catalog-row').click();await fillFromDetail(page);await page.getByRole('tab',{name:'特性',exact:true}).click();await expect(page.locator('.detail-feats')).toContainText('旅行笔记');await expect(page.locator('.detail-background-features')).not.toContainText('旅行笔记');await page.getByRole('switch',{name:'编辑模式'}).click();await page.getByLabel('背景智力加值').fill('2');await page.getByRole('button',{name:'方案 A',exact:true}).click();await page.getByRole('tab',{name:'背包',exact:true}).click();await expect(page.locator('.inventory-cell')).toContainText('墨水');await expect(page.getByLabel('GP数量')).toHaveValue('8');await page.getByRole('tab',{name:'背景',exact:true}).click();await page.getByRole('textbox',{name:'背景故事',exact:true}).fill('从藏书馆开始的旅程');await expect(page.getByText('冒险笔记',{exact:true})).toHaveCount(0);await page.getByRole('tab',{name:'法术',exact:true}).click();await page.getByLabel('预备上限').fill('2');await page.getByRole('switch',{name:'编辑模式'}).click();await expect(page.locator('.prepared-cell')).toBeVisible();await page.locator('.spell-choice').filter({hasText:'护盾'}).click();await page.getByRole('button',{name:'预备空位2'}).click();await page.locator('.spell-choice').filter({hasText:'光箭'}).click();await page.getByRole('button',{name:'取消预备护盾'}).click();await expect(page.getByRole('button',{name:'取消预备光箭'})).toBeVisible();await expect(page.getByRole('button',{name:'预备空位1'})).toBeVisible();await expect(page.locator('.prepared-slot').nth(1)).toContainText('光箭');await page.reload();await expect(page.getByRole('textbox',{name:'角色姓名',exact:true})).toBeVisible();await page.getByRole('tab',{name:'法术',exact:true}).click();await expect(page.getByRole('button',{name:'取消预备光箭'})).toBeVisible();await expect(page.locator('.spell-slots-cell')).toHaveCount(0);await page.getByRole('tab',{name:'背景',exact:true}).click();await expect(page.locator('.bio-story')).toContainText('从藏书馆开始的旅程');await expect(page.getByRole('textbox',{name:'背景故事',exact:true})).toHaveCount(0);
});
test('right page index, workspace resize, compressed portrait and palette survive reload',async({page})=>{
 test.setTimeout(60000);await importCard(page,newCharacter());const paper=await page.locator('.paper').boundingBox(),index=await page.getByRole('tablist',{name:'角色卡页面'}).boundingBox();expect(index!.x).toBeGreaterThanOrEqual(paper!.x+paper!.width-1);const divider=page.getByRole('separator',{name:'调整角色卡与规则资料宽度'}),box=await divider.boundingBox();await page.mouse.move(box!.x+4,box!.y+100);await page.mouse.down();await page.mouse.move(box!.x+100,box!.y+100,{steps:8});await page.mouse.up();expect(Number(await divider.getAttribute('aria-valuenow'))).toBeGreaterThan(48);
 await page.getByRole('switch',{name:'编辑模式'}).click();await page.getByLabel('框默认色').fill('#445566');await page.locator('.portrait-view').hover();const png=await page.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=2400;canvas.height=1600;const ctx=canvas.getContext('2d')!;const grad=ctx.createLinearGradient(0,0,2400,1600);grad.addColorStop(0,'#e1c6a3');grad.addColorStop(1,'#314454');ctx.fillStyle=grad;ctx.fillRect(0,0,2400,1600);ctx.fillStyle='#dbbf9a';ctx.beginPath();ctx.arc(1200,550,270,0,Math.PI*2);ctx.fill();return canvas.toDataURL().split(',')[1];});const chooser=page.waitForEvent('filechooser');await page.getByRole('button',{name:'设置头像',exact:true}).click();await (await chooser).setFiles({name:'portrait.png',mimeType:'image/png',buffer:Buffer.from(png,'base64')});await expect(page.getByAltText('角色头像')).toBeVisible();const image=page.getByAltText('角色头像');expect((await image.getAttribute('src'))!.length).toBeLessThan(650000);const move=page.getByRole('button',{name:'移动头像，滚轮缩放'});await move.hover();await page.mouse.wheel(0,-300);await expect(image).not.toHaveCSS('transform','matrix(1, 0, 0, 1, 0, 0)');const b=await move.boundingBox();await page.mouse.move(b!.x+b!.width/2,b!.y+b!.height/2);await page.mouse.down();await page.mouse.move(b!.x+b!.width/2+18,b!.y+b!.height/2+12,{steps:4});await page.mouse.up();const transform=await image.evaluate(e=>getComputedStyle(e).transform);await page.reload();await expect(page.getByAltText('角色头像')).toHaveCSS('transform',transform);await expect(page.locator('.sheet-cell').first()).toHaveCSS('--cell-border','#445566');await expect(page.getByRole('button',{name:'设置头像'})).toHaveCount(0);
});

test('inventory quantities and attunement update weight, and PNG temporarily renders the list view',async({page})=>{
 test.setTimeout(60000);const c=newCharacter();add(c,e('item','旅行长杖',{weight:4}));await importCard(page,c);await page.getByRole('tab',{name:'背包',exact:true}).click();await page.getByLabel('旅行长杖数量').fill('3');await page.getByLabel('同调旅行长杖').check();await expect(page.locator('.inventory-toolbar')).toContainText('12 磅');await expect(page.locator('.attunement-cell')).toContainText('1 / 3');await expect(page.locator('.inventory-grid')).toBeVisible();
 await page.evaluate(()=>{(window as any).capturedList=false;new MutationObserver(()=>{const list=document.querySelector('.sheet-export .inventory-columns');if(list&&(getComputedStyle(list).display==='grid'))(window as any).capturedList=true;}).observe(document.querySelector('.paper')!,{attributes:true,attributeFilter:['class']});});await page.getByRole('button',{name:'导入 / 导出',exact:true}).click();await page.getByRole('button',{name:'生成当前页 PNG'}).click();await expect(page.getByAltText('当前角色卡 PNG 预览')).toBeVisible({timeout:30000});expect(await page.evaluate(()=>(window as any).capturedList)).toBe(true);await expect(page.locator('.paper')).not.toHaveClass(/sheet-export/);await expect(page.locator('.inventory-grid')).toHaveCount(1);
});


test('palette previews without character updates, stays round and black gaps survive; prose and empty preparations behave correctly',async({page})=>{
 const c=newCharacter();add(c,e('feature','可选择的正文'));add(c,e('spell','光箭',{level:1}));c.spellSettings={mode:'prepared',ability:'int',capacity:2,attackBonus:0,dcBonus:0,prepared:[],slots:{}};await importCard(page,c);await page.getByRole('switch',{name:'编辑模式'}).click();
 const color=page.getByLabel('框默认色'),before=(await page.locator('.paper-footer').textContent())!;const b=(await color.boundingBox())!;expect(Math.abs(b.width-b.height)).toBeLessThan(.1);
 await color.evaluate(async(input:HTMLInputElement)=>{for(let i=0;i<30;i++){input.value=`#${(0x663300+i).toString(16)}`;input.dispatchEvent(new Event('input',{bubbles:true}));await new Promise(requestAnimationFrame);}});await expect(page.locator('.paper-footer')).toHaveText(before);await expect(page.locator('.paper')).toHaveCSS('--paper-frame','#66331d');await expect(page.locator('.cell-perimeter path').first()).toHaveCSS('stroke','rgb(0, 0, 0)');await color.dispatchEvent('change');await expect(page.locator('.paper-footer')).not.toHaveText(before);await page.reload();await page.getByRole('switch',{name:'编辑模式'}).click();await expect(color).toHaveValue('#66331d');
 await page.getByRole('tab',{name:'特性',exact:true}).click();await expect(page.locator('.detail-class-features .feature-prose p').first()).toHaveCSS('cursor','text');await expect(page.locator('.detail-class-features .feature-caption').first()).toHaveCSS('cursor','grab');
 await page.getByRole('tab',{name:'法术',exact:true}).click();await expect(page.locator('.prepared-cell')).toBeVisible();await page.locator('.spell-choice').click();await expect(page.locator('.prepared-cell')).toBeVisible();await page.getByRole('button',{name:'取消预备光箭'}).click();await expect(page.locator('.prepared-cell')).toBeVisible();
});
