import {test,expect,type Page} from '@playwright/test';
import {mockSource,suppressAnnouncement} from './fixtures';
import {customField} from './customCanvasHelpers';
import {newCharacter} from '../../src/core/model';
import {exportCharacter} from '../../src/core/export';

async function start(page:Page){await mockSource(page);await suppressAnnouncement(page);await page.goto('/card/');await expect(page.getByRole('button',{name:'更新资料',exact:true})).toBeEnabled();}
async function workspace(page:Page){return page.evaluate(()=>new Promise<any>((resolve,reject)=>{const request=indexedDB.open('dnd-card-standalone',1);request.onerror=()=>reject(request.error);request.onsuccess=()=>{const db=request.result,get=db.transaction('documents').objectStore('documents').get('workspace');get.onsuccess=()=>{resolve(get.result);db.close();};};}));}

test('document areas edit complete spells and the three-state filter applies to list and search after reload',async({page})=>{
 await start(page);const mode=page.locator('.custom-visibility');await expect(mode).toHaveText('目前全部');expect((await mode.boundingBox())!.x).toBeLessThan((await page.getByRole('button',{name:'更新资料',exact:true}).boundingBox())!.x);
 await page.getByRole('navigation',{name:'资料分类'}).getByRole('button',{name:'自定义',exact:true}).click();await expect(page.locator('.custom-document')).toBeVisible();await expect(page.getByLabel('自定义条目名称',{exact:true})).toHaveCount(0);
 await(await customField(page,'自定义条目类型')).selectOption('spell');await page.getByRole('button',{name:'完成修改',exact:true}).click();await expect(page.locator('.custom-document')).toContainText('1 环');await(await customField(page,'自定义条目名称')).fill('星光护幕');await(await customField(page,'法术学派')).selectOption('V');await(await customField(page,'法术环阶')).fill('2');await(await customField(page,'材料 M')).check();await(await customField(page,'材料说明')).fill('一小片星石');await page.getByRole('button',{name:'完成修改',exact:true}).click();await expect(page.locator('.custom-document')).toContainText('材料 M：一小片星石');await page.screenshot({path:test.info().outputPath('custom-spell-desktop.png')});await page.getByRole('button',{name:'保存条目',exact:true}).click();await expect(page.locator('.catalog-row').filter({hasText:'星光护幕'})).toBeVisible();
 await page.getByRole('navigation',{name:'资料分类'}).getByRole('button',{name:'法术',exact:true}).click();await expect(page.locator('.catalog-row').filter({hasText:'星光护幕'})).toBeVisible();await expect(page.locator('.catalog-row').filter({hasText:'微光术'})).toBeVisible();
 await mode.click();await expect(mode).toHaveText('目前仅非自定义');await expect(page.locator('.catalog-row').filter({hasText:'星光护幕'})).toHaveCount(0);await page.getByRole('textbox',{name:'搜索规则资料',exact:true}).fill('星光护幕');await expect(page.getByRole('region',{name:'全局搜索结果'})).toContainText('没有匹配结果');await page.getByRole('button',{name:'清空搜索',exact:true}).click();await mode.click();await expect(mode).toHaveText('目前仅自定义');await expect(page.locator('.catalog-row').filter({hasText:'微光术'})).toHaveCount(0);await page.getByRole('textbox',{name:'搜索规则资料',exact:true}).fill('星光护幕');await expect(page.getByRole('region',{name:'全局搜索结果'})).toContainText('星光护幕');await page.getByRole('button',{name:'清空搜索',exact:true}).click();await page.reload();await expect(mode).toHaveText('目前仅自定义');await expect(page.locator('.catalog-row').filter({hasText:'星光护幕'})).toBeVisible();const saved=await workspace(page);expect(saved.customEntries[0].raw).toMatchObject({level:2,school:'V',components:{m:'一小片星石'}});
});

test('dragging onto the content area displays the copy effect and opens an unsaved independent draft',async({page})=>{
 await start(page);const original=page.locator('.catalog-row').filter({hasText:'测试法师'}).first();await original.click();const before=await workspace(page),source=await original.boundingBox(),target=await page.locator('.wiki-content-drop').boundingBox();await page.mouse.move(source!.x+30,source!.y+source!.height/2);await page.mouse.down();await page.mouse.move(source!.x+48,source!.y+source!.height/2,{steps:3});await page.mouse.move(target!.x+target!.width*.55,target!.y+target!.height*.65,{steps:12});await expect(page.getByRole('status').filter({hasText:'以该条目创建自定义副本'})).toBeVisible();await page.screenshot({path:test.info().outputPath('custom-copy-drag.png')});await page.mouse.up();await expect(page.locator('.custom-document h1')).toContainText('测试法师（自定义副本）');expect((await workspace(page)).customEntries||[]).toHaveLength(0);await page.getByRole('button',{name:'保存条目',exact:true}).click();await expect(page.locator('.save-status')).toContainText('已保存到本机');const after=await workspace(page);expect(after.customEntries[0].id).toMatch(/^custom:/);expect(after.customEntries[0].source).toBe('CUSTOM');expect(after.characters).toEqual(before.characters);await page.locator('.custom-visibility').click();await page.getByRole('navigation',{name:'资料分类'}).getByRole('button',{name:'职业',exact:true}).click();await expect(page.locator('.catalog-row').filter({hasText:'测试法师'})).toHaveCount(2);
});

test('complete monster document supports region editing, structured actions, saving and mobile reading',async({page})=>{
 await start(page);await page.getByRole('navigation',{name:'资料分类'}).getByRole('button',{name:'自定义',exact:true}).click();await(await customField(page,'自定义条目类型')).selectOption('monster');await(await customField(page,'自定义条目名称')).fill('灰岩守卫');await(await customField(page,'怪物平均 HP')).fill('35');await(await customField(page,'怪物力量属性')).fill('18');await page.getByRole('button',{name:'完成修改',exact:true}).click();await page.locator('.custom-document').getByRole('button',{name:'修改动作',exact:true}).click();await page.getByLabel('子条目名称',{exact:true}).fill('岩拳');await page.getByLabel('子条目正文',{exact:true}).fill('命中：{@damage 2d6+4} 钝击伤害。');await page.getByRole('button',{name:'完成修改',exact:true}).click();await expect(page.locator('.custom-document .monster-document')).toContainText('35');await expect(page.locator('.custom-document .monster-document')).toContainText('岩拳');await page.screenshot({path:test.info().outputPath('custom-monster-desktop.png')});await page.getByRole('button',{name:'保存条目',exact:true}).click();await expect(page.locator('.entry-detail .monster-document')).toContainText('岩拳');await page.reload();await expect(page.locator('.entry-detail .detail-heading')).toContainText('灰岩守卫');await expect(page.locator('.entry-detail .monster-document')).toContainText('岩拳');const saved=(await workspace(page)).customEntries[0];expect(saved).toMatchObject({kind:'monster',raw:{hp:{average:35},str:18,action:[{name:'岩拳',entries:['命中：{@damage 2d6+4} 钝击伤害。']}]}});await page.setViewportSize({width:390,height:844});await page.getByRole('navigation',{name:'工作区',exact:true}).getByRole('button',{name:'Wiki',exact:true}).click();await page.getByRole('button',{name:'编辑此条目',exact:true}).click();await page.screenshot({path:test.info().outputPath('custom-monster-mobile.png')});expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
});

test('JSON file area accepts actual dropped files and click selection, validating the whole batch before mutation',async({page})=>{
 await start(page);await page.getByRole('button',{name:'导入 / 导出',exact:true}).click();const drop=page.locator('.transfer-panel .json-file-drop'),initial=(await workspace(page)).characters.length,card=newCharacter();card.name='拖入的角色';const json=JSON.stringify(exportCharacter(card));
 const invalid=await page.evaluateHandle(text=>{const data=new DataTransfer();data.items.add(new File([text],'valid.json',{type:'application/json'}));data.items.add(new File(['{"schemaVersion":'],'broken.json',{type:'application/json'}));return data;},json);await drop.dispatchEvent('drop',{dataTransfer:invalid});await expect(page.locator('.transfer-panel [role=alert]')).toBeVisible();expect((await workspace(page)).characters).toHaveLength(initial);await invalid.dispose();
 const valid=await page.evaluateHandle(text=>{const data=new DataTransfer();data.items.add(new File([text],'character.json',{type:'application/json'}));return data;},json);await drop.dispatchEvent('drop',{dataTransfer:valid});await expect(page.getByRole('dialog',{name:'批量导入前核对'})).toBeVisible();expect((await workspace(page)).characters).toHaveLength(initial);await page.getByRole('button',{name:'确认导入这批角色'}).click();await expect.poll(async()=>(await workspace(page)).characters.length).toBe(initial+1);await valid.dispose();await page.getByRole('button',{name:'关闭弹窗',exact:true}).click();await page.getByRole('button',{name:'导入 / 导出',exact:true}).click();const choose=page.waitForEvent('filechooser');await drop.click();await(await choose).setFiles({name:'another.json',mimeType:'application/json',buffer:Buffer.from(json)});await page.getByRole('button',{name:'确认导入这批角色'}).click();await expect.poll(async()=>(await workspace(page)).characters.length).toBe(initial+2);
});

test('a single spell level has a complete 3 by 2 default module without changing balances',async({page})=>{
 await start(page);await page.getByRole('switch',{name:'编辑模式'}).click();await page.locator('.catalog-row').filter({hasText:'测试法师'}).first().click({button:'right'});await page.getByRole('menuitem',{name:'添加至角色卡',exact:true}).click();const module=page.locator('.paper [data-resource-id="spell-slot:1"]');await expect(module).toHaveAttribute('data-grid-w','3');await expect(module).toHaveAttribute('data-grid-h','2');await expect(module.locator('[data-resource-unit]')).toHaveCount(2);const before=(await workspace(page)).characters[0].runtime.resources['spell-slot:1'];await page.setViewportSize({width:390,height:844});await page.getByRole('navigation',{name:'工作区',exact:true}).getByRole('button',{name:'功能页',exact:true}).click();await expect(module).toBeVisible();await page.screenshot({path:test.info().outputPath('single-level-slots-mobile.png')});await page.reload();await expect(module).toHaveAttribute('data-grid-w','3');expect((await workspace(page)).characters[0].runtime.resources['spell-slot:1']).toEqual(before);
});
