import {customField,finishCustomField} from './customCanvasHelpers';
import {test,expect} from '@playwright/test';
import {mockSource,suppressAnnouncement} from './fixtures';
test('custom JSON preserves original entries through mode changes, other edits, example undo and persisted save; raw numbers stay synchronized',async({page})=>{
 await mockSource(page);await suppressAnnouncement(page);await page.goto('/');await expect(page.locator('.save-status')).toContainText('已保存到本机');await page.locator('.category-tabs').getByRole('button',{name:'自定义',exact:true}).click();
 const entries=['{"type":"entries","name":"这是普通字符串","entries":["原始文字"]}','甲\n\n乙',{type:'entries',name:'真正的对象',entries:['保留对象']},''];const data={name:'原创无损条目',type:'item',edition:'both',entries,raw:{value:100,weight:1,customNested:{keep:true}}};
 await finishCustomField(page);await page.getByRole('button',{name:'JSON 输入',exact:true}).click();const json=page.getByLabel('完整自定义条目 JSON');await json.fill(JSON.stringify(data));await finishCustomField(page);await page.getByRole('button',{name:'格式输入',exact:true}).click();await finishCustomField(page);await page.getByRole('button',{name:'JSON 输入',exact:true}).click();expect(JSON.parse(await json.inputValue()).entries).toEqual(entries);
 await finishCustomField(page);await page.getByRole('button',{name:'格式输入',exact:true}).click();await (await customField(page,'自定义条目名称')).fill('原创无损条目改名');const body=(await customField(page,'自定义条目正文'));const baseline=await body.inputValue();await body.focus();await body.press('Control+End');await body.pressSequentially('撤');await body.press('Control+z');await expect(body).toHaveValue(baseline);await finishCustomField(page);await page.getByRole('button',{name:'填充格式示例',exact:true}).click();await page.getByRole('button',{name:'撤回',exact:true}).click();await finishCustomField(page);await page.getByRole('button',{name:'JSON 输入',exact:true}).click();expect(JSON.parse(await json.inputValue()).entries).toEqual(entries);expect(JSON.parse(await json.inputValue()).name).toBe('原创无损条目改名');
 await finishCustomField(page);await page.getByRole('button',{name:'格式输入',exact:true}).click();await finishCustomField(page);await page.locator('.custom-entry-editor details').filter({hasText:'结构字段'}).locator('summary').click();const raw=page.getByLabel('自定义结构字段');const changed=JSON.parse(await raw.inputValue());changed.value=500;changed.weight=2;await raw.fill(JSON.stringify(changed));await expect((await customField(page,'物品价格（金币）'))).toHaveValue('5');await expect((await customField(page,'物品重量（磅）'))).toHaveValue('2');await finishCustomField(page);await page.getByRole('button',{name:'JSON 输入',exact:true}).click();expect(JSON.parse(await json.inputValue()).raw).toMatchObject({value:500,weight:2,customNested:{keep:true}});
 await finishCustomField(page);await page.getByRole('button',{name:'格式输入',exact:true}).click();await finishCustomField(page);await page.locator('.custom-entry-editor details').filter({hasText:'结构字段'}).locator('summary').click();await (await customField(page,'物品价格（金币）')).fill('6.5');await expect.poll(async()=>JSON.parse(await raw.inputValue()).value).toBe(650);await raw.fill('{"value":');await expect(page.getByRole('button',{name:'保存条目',exact:true})).toBeDisabled();await finishCustomField(page);await page.getByRole('button',{name:'JSON 输入',exact:true}).click();await expect(raw).toHaveValue('{"value":');await raw.fill(JSON.stringify({...changed,value:650}));await finishCustomField(page);await page.getByRole('button',{name:'保存条目',exact:true}).click();await expect(page.locator('.catalog-row').filter({hasText:'原创无损条目改名'})).toBeVisible();await expect(page.locator('.save-status')).toContainText('已保存到本机');await page.reload();await page.locator('.catalog-row').filter({hasText:'原创无损条目改名'}).click();await page.getByRole('button',{name:'编辑此条目',exact:true}).click();await finishCustomField(page);await page.getByRole('button',{name:'JSON 输入',exact:true}).click();const saved=JSON.parse(await json.inputValue());expect(saved.entries).toEqual(entries);expect(saved.raw).toMatchObject({value:650,weight:2,customNested:{keep:true}});
 await finishCustomField(page);await page.getByRole('button',{name:'格式输入',exact:true}).click();await (await customField(page,'自定义条目正文')).fill('真正修改后的第一段\n\n第二段');await finishCustomField(page);await page.getByRole('button',{name:'JSON 输入',exact:true}).click();expect(JSON.parse(await json.inputValue()).entries).toEqual(['真正修改后的第一段','第二段']);
});
