import {test,expect,type Page} from '@playwright/test';
const editor=(page:Page)=>page.getByRole('dialog',{name:'仪表盘',exact:true});
const status=(page:Page)=>editor(page).locator('.dashboard-savebar > [role=status]');
const widget=(page:Page,id='ring')=>editor(page).locator(`[data-resource-id="${id}"]`);
async function open(page:Page){await page.getByTestId('dashboard-open').click();await expect(editor(page).locator('.resource-dashboard')).toBeVisible();}
async function fixture(page:Page){await page.goto('/tests/fixtures/resource-dashboard220/index.html?scenario=appearance');await open(page);}
const read=(page:Page)=>page.locator('#fixture-data').textContent().then(value=>JSON.parse(value!));
async function scale(page:Page,value:string){const range=editor(page).getByLabel('模块内部缩放',{exact:true});await range.focus();await range.press('Home');for(let n=0;n<Math.round((Number(value)-.25)/.05);n++)await range.press('ArrowRight');await expect(range).toHaveValue(value);}
for(const width of [1280,390])test(`237 ${width}: compact artwork reclaims real footprint, frame controls roundtrip and divider has no dead gap`,async({page})=>{
 await page.setViewportSize({width,height:960});await fixture(page);const initial=await read(page),ring=widget(page),group=widget(page,'first'),original=(await ring.boundingBox())!;
 // The redesigned face carries a 1px design frame until the player overrides it; the cell itself has no padding.
 await expect(ring.locator('.resource-module-art')).toHaveCSS('border-top-width','1px');await expect(ring).toHaveCSS('padding','0px');
 const divider=editor(page).getByRole('separator');expect((await divider.boundingBox())!.width).toBeLessThanOrEqual(1.1);
 await ring.locator('.resource-widget-face').click();await scale(page,'0.25');await editor(page).getByRole('button',{name:'紧凑尺寸',exact:true}).click();
 await expect(ring).toHaveAttribute('data-grid-w','1');await expect(ring).toHaveAttribute('data-grid-h','1');const compact=(await ring.boundingBox())!;expect(compact.width).toBeLessThan(original.width*.4);expect(compact.height).toBeLessThan(original.height*.4);
 await expect(ring.locator('.resource-widget-handle')).toHaveCount(8);await expect(ring.locator('.rm-name')).toHaveText('新资源');await expect(ring.locator('.rm-readout')).toContainText('3');
 const inside=await ring.locator('.resource-module-art').evaluate(el=>{const outer=el.getBoundingClientRect();return [...el.querySelectorAll('.rm-name,.rm-readout')].every(node=>{const b=node.getBoundingClientRect();return b.left>=outer.left-.5&&b.right<=outer.right+.5&&b.top>=outer.top-.5&&b.bottom<=outer.bottom+.5;});});expect(inside).toBe(true);
 await group.locator('.resource-widget-face').click();const beforeGroup=(await group.boundingBox())!;await scale(page,'0.5');await editor(page).getByRole('button',{name:'紧凑尺寸',exact:true}).click();await expect(group).toHaveAttribute('data-grid-w','2');await expect(group).toHaveAttribute('data-grid-h','2');const compactGroup=(await group.boundingBox())!;expect(compactGroup.width).toBeLessThan(beforeGroup.width*.6);expect(compactGroup.height).toBeLessThan(beforeGroup.height*.6);await expect(group.locator('[data-subresource-id]')).toHaveCount(2);await expect(group.locator('[data-resource-unit]')).toHaveCount(6);
 await editor(page).getByLabel('模块背景色',{exact:true}).fill('#dce8f2');await editor(page).getByLabel('模块描边粗细',{exact:true}).fill('3');await editor(page).getByLabel('模块圆角',{exact:true}).fill('8');await editor(page).getByLabel('模块内边距',{exact:true}).fill('1');await editor(page).getByLabel('模块内容间距',{exact:true}).fill('2');
 await expect(group.locator('.resource-module-art')).toHaveCSS('background-color','rgb(220, 232, 242)');await expect(group.locator('.resource-module-art')).toHaveCSS('border-top-width','3px');await expect(group.locator('.resource-module-art')).toHaveCSS('border-top-left-radius','8px');await expect(group.locator('.rm-pools')).toHaveCSS('gap','2px');for(const row of await group.locator('.rm-pool').all())await expect(row).toHaveCSS('padding','1px');
 await editor(page).getByRole('button',{name:'保存布局',exact:true}).click();await expect(status(page)).toHaveText('已保存布局');const saved=await read(page);expect(saved.runtime.resources).toEqual(initial.runtime.resources);expect(saved.quickbarLayout.widgets.first).toMatchObject({w:2,h:2,contentScale:.5,background:'#dce8f2',borderWidth:3,borderRadius:8,padding:1,gap:2});
 await editor(page).getByRole('button',{name:'关闭弹窗',exact:true}).click();await page.reload();await open(page);expect((await read(page)).quickbarLayout).toEqual(saved.quickbarLayout);await expect(widget(page,'first').locator('.resource-module-art')).toHaveCSS('border-top-width','3px');await editor(page).screenshot({path:test.info().outputPath(`237-dense-frame-${width}.png`)});
});
for(const action of ['close','escape','backdrop'] as const)test(`237 ${action}: cancel leaves dirty draft intact and confirmed discard never writes`,async({page})=>{
 await fixture(page);const initial=await read(page);await widget(page).locator('.resource-widget-face').click();await editor(page).getByLabel('模块描边粗细',{exact:true}).fill('2');
 const dismiss=async()=>{if(action==='close')await editor(page).getByRole('button',{name:'关闭弹窗',exact:true}).click();else if(action==='escape')await page.keyboard.press('Escape');else await editor(page).dispatchEvent('click');};
 let prompts=0;const cancel=async(dialog:any)=>{prompts++;expect(dialog.message()).toContain('未保存');await dialog.dismiss();};page.once('dialog',cancel);await dismiss();await expect(editor(page)).toBeVisible();await expect(editor(page).locator('.resource-dashboard')).toHaveAttribute('data-dirty','true');await expect(editor(page).getByLabel('模块描边粗细',{exact:true})).toHaveValue('2');expect(await read(page)).toEqual(initial);
 page.once('dialog',async dialog=>{prompts++;await dialog.accept();});await dismiss();await expect(editor(page)).not.toBeVisible();expect(prompts).toBe(2);expect(await read(page)).toEqual(initial);await open(page);await expect(editor(page).locator('.resource-dashboard')).toHaveAttribute('data-dirty','false');
});
test('237 clean editor does not prompt; unsaved resource forms survive cancelled module switch',async({page})=>{
 await fixture(page);let prompts=0;const handler=async(dialog:any)=>{prompts++;await dialog.dismiss();};page.on('dialog',handler);
 await editor(page).getByRole('button',{name:'关闭弹窗',exact:true}).click();await expect(editor(page)).not.toBeVisible();expect(prompts).toBe(0);await open(page);
 await widget(page).locator('.resource-widget-face').click();await editor(page).getByLabel('资源名称',{exact:true}).fill('保留的草稿');await widget(page,'first').locator('.resource-widget-face').click();await expect(editor(page).getByLabel('资源名称',{exact:true})).toHaveValue('保留的草稿');expect(prompts).toBe(1);
 page.off('dialog',handler);page.once('dialog',dialog=>void dialog.accept());await widget(page,'first').locator('.resource-widget-face').click();await expect(editor(page).getByLabel('资源名称',{exact:true})).toHaveValue('子资源 1');
});
test('237 overview failure retains draft; retry awaits ACK and preserves concurrent resource spend',async({page,baseURL})=>{
 await page.goto('/tests/fixtures/overview-dashboard235/#suite=overview-dashboard235&bridge='+encodeURIComponent(new URL(baseURL!).origin));await page.getByRole('button',{name:'管理原创资源布局测试资源',exact:true}).click();await expect(editor(page).locator('.resource-dashboard')).toBeVisible();const focus=widget(page,'focus');await focus.locator('.resource-widget-face').click();await editor(page).getByLabel('模块背景色',{exact:true}).fill('#dce8f2');await editor(page).getByLabel('模块描边粗细',{exact:true}).fill('2');await expect(focus.locator('.resource-module-art')).toHaveCSS('border-top-width','2px');await editor(page).getByLabel('模块描边粗细',{exact:true}).fill('0');await expect(focus.locator('.resource-module-art')).toHaveCSS('border-top-width','0px');await scale(page,'0.25');await editor(page).getByRole('button',{name:'紧凑尺寸',exact:true}).click();
 await page.evaluate(()=>(window as any).dashboard235.fail());await editor(page).getByRole('button',{name:'保存布局',exact:true}).click();await expect(status(page)).toContainText('测试保存失败');await expect(editor(page).locator('.resource-dashboard')).toHaveAttribute('data-dirty','true');page.once('dialog',dialog=>void dialog.dismiss());await page.keyboard.press('Escape');await expect(editor(page)).toBeVisible();
 await page.evaluate(()=>(window as any).dashboard235.remote());await editor(page).getByRole('button',{name:'保存布局',exact:true}).click();await expect(status(page)).toHaveText('已保存布局');const result=await page.evaluate(()=>(window as any).dashboard235.authority());expect(result.runtime.resources.focus.current).toBe(1);expect(result.notes).toBe('远端编辑保留');expect(result.quickbarLayout.widgets.focus).toMatchObject({w:1,h:1,contentScale:.25,borderWidth:0,background:'#dce8f2'});
 await editor(page).getByRole('button',{name:'关闭弹窗',exact:true}).click();await expect(editor(page)).toHaveCount(0);const actual=page.locator('[data-resource-target="hero"] [data-resource-id="focus"] .resource-module-art');await expect(actual).toHaveCSS('background-color','rgb(220, 232, 242)');await expect(actual).toHaveCSS('border-top-width','0px');await page.screenshot({path:test.info().outputPath('237-overview-saved.png')});
});
for(const transition of ['selectOther','leaveScene','removeCard','switchScope','disableCards'] as const)test(`237 overview ${transition}: detached draft survives owner unmount and access is refreshed`,async({page,baseURL})=>{
 await page.goto('/tests/fixtures/overview-dashboard235/#suite=overview-dashboard235&bridge='+encodeURIComponent(new URL(baseURL!).origin));await page.getByRole('button',{name:'管理原创资源布局测试资源',exact:true}).click();await expect(editor(page).locator('.resource-dashboard')).toBeVisible();await widget(page,'focus').locator('.resource-widget-face').click();await editor(page).getByLabel('模块描边粗细',{exact:true}).fill('2');
 await page.evaluate(transition=>(window as any).dashboard235[transition](),transition);await expect(editor(page)).toBeVisible();await expect(editor(page).locator('.resource-dashboard')).toHaveAttribute('data-dirty','true');await expect(editor(page).getByLabel('模块描边粗细',{exact:true})).toHaveValue('2');
 if(transition!=='selectOther'){await expect(editor(page).locator('.dashboard-savebar button.primary')).toBeDisabled();if(transition==='removeCard'||transition==='switchScope'||transition==='disableCards'){await expect(editor(page).getByText('当前读取权限已失效',{exact:false})).toBeVisible();await expect(widget(page,'focus')).not.toBeVisible();await expect(editor(page).getByRole('heading')).toHaveText('资源仪表盘');}await page.evaluate(()=>(window as any).dashboard235.restoreCard());}
 await expect(editor(page).getByRole('button',{name:'保存布局',exact:true})).toBeEnabled();await editor(page).getByRole('button',{name:'保存布局',exact:true}).click();await expect(status(page)).toHaveText('已保存布局');expect((await page.evaluate(()=>(window as any).dashboard235.authority())).quickbarLayout.widgets.focus.borderWidth).toBe(2);
});
