import {test,expect,type Page} from '@playwright/test';
import {mockSource,suppressAnnouncement} from './fixtures';
import {newCharacter,type Character,type Entry} from '../../src/core/model';
import {exportCharacter} from '../../src/core/export';

function fixture(){
 const c=newCharacter();c.name='熟练与攻击原创验收';c.abilities={str:8,dex:18,con:10,int:10,wis:14,cha:8};
 const entry:Entry={id:'controls232-class',name:'原创守望者',english:'Authored Watcher',kind:'class',source:'XPHB',edition:'2024',packId:'fixture',revision:'1',entries:['原创软件验收条目。'],raw:{hd:{faces:8},proficiency:['str','wis'],startingProficiencies:{skills:[{perception:true,history:true}]}}};
 c.selections=[{id:'controls232-selection',entry,level:1,quantity:1,equipped:false}];c.expertise={stealth:true};c.proficiencies={arcana:true,'save:con':true};c.skillBonuses={perception:9,athletics:-11};c.runtime.hp=5;c.runtime.resources={focus:{name:'原创专注',current:1,max:4}};
 c.quickbarActions=[{id:'original',name:'原创月刃',attack:'+12',damage:'1d8+4'}];return c;
}
async function saved(page:Page):Promise<Character>{return page.evaluate(async()=>{
 const databases=await indexedDB.databases(),name=databases.some(x=>x.name==='dnd-card-standalone')?'dnd-card-standalone':'dnd-card-workspace';const db=await new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open(name);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});
 try{return await new Promise<Character>((resolve,reject)=>{const r=db.transaction('documents').objectStore('documents').get('workspace');r.onsuccess=()=>resolve(r.result.characters.find((c:Character)=>c.id===r.result.activeId));r.onerror=()=>reject(r.error);});}finally{db.close();}
});}
async function load(page:Page,mode:'a4'|'screen'='a4',c=fixture()){
 await mockSource(page,{displayMode:mode});await suppressAnnouncement(page);await page.goto('/');await expect(page.getByRole('button',{name:'更新资料',exact:true})).toBeEnabled();await page.getByRole('button',{name:'导入 / 导出',exact:true}).click();await page.getByTestId('character-file').setInputFiles({name:'controls232.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(exportCharacter(c)))});await expect(page.getByRole('tab',{name:/^熟练与攻击原创验收（导入）(?:\s*旧卡资料需要核对)?$/})).toHaveAttribute('aria-selected','true');await page.getByRole('button',{name:'关闭弹窗',exact:true}).click();await expect.poll(async()=>(await saved(page)).name).toBe(c.name+'（导入）');
}
async function editMode(page:Page,enabled=true){const toggle=page.getByRole('switch',{name:'编辑模式',exact:true});if(await toggle.getAttribute('aria-checked')!==String(enabled))await toggle.click();}

test('one disabled state follows skill/save rule grant and revoke while adjustments save and reload',async({page})=>{
 await load(page);await editMode(page);const paper=page.locator('.paper'),before=await saved(page);await expect(paper.locator('.ability-skill input[type=checkbox]')).toHaveCount(18);await expect(paper.locator('.ability-save input[type=checkbox]')).toHaveCount(6);await expect(paper.locator('.ability-proficiency-row input[type=checkbox]:enabled')).toHaveCount(0);
 const perception=page.getByRole('checkbox',{name:'察觉熟练状态：熟练',exact:true}),expert=page.getByRole('checkbox',{name:'隐匿熟练状态：专精',exact:true}),strengthSave=page.getByRole('checkbox',{name:'力量豁免熟练状态：熟练',exact:true});for(const control of [perception,expert,strengthSave]){await expect(control).toBeDisabled();await expect(control).toBeChecked();}await expect(perception).toHaveAccessibleDescription(/规则.*不能在此手动更改.*额外调整值仍可编辑/);await expect(expert).toHaveClass(/expert/);
 const bonus=page.getByRole('spinbutton',{name:'察觉额外调整值',exact:true});await expect(bonus).toBeEnabled();await bonus.fill('-3');await bonus.press('Tab');await expect(paper.locator('.ability-skill').filter({has:bonus}).locator('b')).toHaveText('+1');await expect.poll(async()=>(await saved(page)).skillBonuses?.perception).toBe(-3);
 await page.locator('.identity-class .identity-title').press('Delete');await expect(page.getByRole('checkbox',{name:'察觉熟练状态：无熟练',exact:true})).not.toBeChecked();await expect(page.getByRole('checkbox',{name:'力量豁免熟练状态：无熟练',exact:true})).not.toBeChecked();await expect(expert).toBeChecked();await expect(paper.locator('.ability-skill').filter({has:bonus}).locator('b')).toHaveText('-1');await page.getByRole('button',{name:'撤销',exact:true}).click();await expect(perception).toBeChecked();await expect(strengthSave).toBeChecked();await expect.poll(async()=>(await saved(page)).selections.length).toBe(before.selections.length);
 await page.reload();await expect(page.getByRole('spinbutton',{name:'察觉额外调整值',exact:true})).toHaveValue('-3');await expect(perception).toBeDisabled();const after=await saved(page);expect(after.proficiencies).toEqual(before.proficiencies);expect(after.expertise).toEqual(before.expertise);expect(after.runtime).toEqual(before.runtime);await page.screenshot({path:test.info().outputPath('disabled-derived-status-adjustment.png')});
});

for(const mode of ['a4','screen'] as const)test(`${mode} save and skill columns align in both modes at desktop and narrow zoom`,async({page})=>{
 await load(page,mode);
 for(const width of [1512,390]){await page.setViewportSize({width,height:982});for(const editing of [false,true]){await editMode(page,editing);const measurements=await page.locator('.ability-box').evaluateAll(boxes=>boxes.map(box=>{const rows=[...box.querySelectorAll<HTMLElement>('.ability-proficiency-row')];return rows.map(row=>{const cells=[...row.children].slice(0,3).map(el=>{const rect=el.getBoundingClientRect();return {x:rect.x,w:rect.width};});const value=row.children[1],label=row.children[2];const textBottom=(el:Element)=>{const range=document.createRange();range.selectNodeContents(el);return range.getBoundingClientRect().bottom;};return {cells,baseline:Math.abs(textBottom(value)-textBottom(label)),overflow:row.scrollWidth-row.clientWidth};});}));
  for(const rows of measurements){for(const row of rows){for(let i=0;i<3;i++)expect(Math.abs(row.cells[i].x-rows[0].cells[i].x)).toBeLessThan(1.1);expect(row.baseline).toBeLessThan(1.6);expect(row.overflow).toBeLessThanOrEqual(1);}}await expect(page.locator('.ability-str .ability-skill b')).toHaveText('-12');await expect(page.locator('.ability-wis .ability-skill').filter({hasText:'察觉'}).locator('b')).toHaveText('+13');expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);const longLabel=page.locator('.ability-int .ability-skill').first().locator(':scope > span:nth-child(3)');await longLabel.evaluate(el=>el.textContent='长技能名称与两位加值验收');expect(await longLabel.evaluate(el=>getComputedStyle(el).textOverflow)).toBe('ellipsis');expect(await page.locator('.ability-int').evaluate(el=>el.scrollWidth-el.clientWidth)).toBeLessThanOrEqual(1);await page.screenshot({path:test.info().outputPath(`aligned-${mode}-${width}-${editing?'edit':'read'}.png`)});await longLabel.evaluate(el=>el.textContent=el.getAttribute('title'));
 }}
});
