import {test,expect,type Page} from '@playwright/test';
import {mockSource,suppressAnnouncement} from './fixtures';
import {newCharacter,type Character,type Entry} from '../../src/core/model';
import {spellState} from '../../src/core/characterDetails';
import {exportCharacter} from '../../src/core/export';
async function ready(page:Page){
 await mockSource(page);await suppressAnnouncement(page);await page.goto('/');await expect(page.getByRole('button',{name:'更新资料',exact:true})).toBeEnabled();
 const c=newCharacter();c.name='原创冷启动验收';const entry:Entry={id:'direct232-spell',name:'原创星光',english:'Original Starlight',kind:'spell',raw:{level:1},source:'XPHB',edition:'2024',packId:'fixture',revision:'1',entries:['原创的界面验收文本。']};c.selections=[{id:'direct232-spell-selection',entry,quantity:1,level:1,equipped:false}];c.spellSettings={...spellState(c),capacityAdjustment:2};
 await page.getByRole('button',{name:'导入 / 导出',exact:true}).click();await page.getByTestId('character-file').setInputFiles({name:'direct232.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(exportCharacter(c)))});await expect(page.getByRole('tab',{name:c.name+'（导入）'})).toHaveAttribute('aria-selected','true');await page.keyboard.press('Escape');await expect(page.locator('.save-status')).toContainText('已保存到本机');
}
async function viewportSize(page:Page){return page.evaluate(()=>({w:document.documentElement.scrollWidth,h:document.documentElement.scrollHeight,x:scrollX,y:scrollY}));}
for(const backpackFirst of [false,true])test(`standalone spell menu is positioned on cold load (backpack first ${backpackFirst})`,async({page})=>{
 await ready(page);if(backpackFirst)await page.getByRole('tab',{name:'背包',exact:true}).click();await page.getByRole('tab',{name:'法术',exact:true}).click();const tile=page.locator('.spell-library-level .spell-stock-tile').first();await expect(tile).toBeVisible();const before=await viewportSize(page);await tile.click({button:'right'});
 const menu=page.getByRole('menu',{name:'法术操作'});await expect(menu).toBeVisible();expect(await menu.evaluate(el=>getComputedStyle(el).position)).toBe('absolute');expect(await page.locator('.spell-menu-shade').evaluate(el=>getComputedStyle(el).position)).toBe('fixed');const box=(await menu.boundingBox())!;expect(box.x).toBeGreaterThanOrEqual(0);expect(box.y).toBeGreaterThanOrEqual(0);expect(box.x+box.width).toBeLessThanOrEqual(1512);expect(box.y+box.height).toBeLessThanOrEqual(982);expect(await viewportSize(page)).toEqual(before);await page.screenshot({path:test.info().outputPath(`spell-menu-${backpackFirst?'warm':'cold'}.png`)});await page.keyboard.press('Escape');await expect(menu).toHaveCount(0);
});
test('cold spell dragging cancels and removes without viewport overflow or stale ghosts',async({page})=>{
 await ready(page);await page.getByRole('switch',{name:'编辑模式',exact:true}).click();await page.getByRole('tab',{name:'法术',exact:true}).click();const tile=page.locator('.spell-library-level .spell-stock-tile').first();await expect(tile).toBeVisible();const before=await viewportSize(page);
 for(const cancel of ['Escape','blur']){const b=(await tile.boundingBox())!;await page.mouse.move(b.x+20,b.y+b.height/2);await page.mouse.down();await page.mouse.move(b.x+70,b.y+b.height/2+8,{steps:4});await expect(page.locator('.pointer-ghost')).toHaveCount(1);expect(await page.locator('.pointer-ghost').evaluate(el=>getComputedStyle(el).position)).toBe('fixed');expect(await viewportSize(page)).toEqual(before);if(cancel==='Escape')await page.keyboard.press('Escape');else await page.evaluate(()=>window.dispatchEvent(new Event('blur')));await page.mouse.up();await expect(page.locator('.pointer-ghost')).toHaveCount(0);await expect(tile).toBeVisible();expect(await viewportSize(page)).toEqual(before);}
 const b=(await tile.boundingBox())!;await page.mouse.move(b.x+20,b.y+b.height/2);await page.mouse.down();await page.mouse.move(1490,400,{steps:20});await page.mouse.up();for(let i=0;i<8;i++){expect(await viewportSize(page)).toEqual(before);await page.waitForTimeout(35);}await expect(page.locator('.pointer-ghost')).toHaveCount(0);await expect(tile).toHaveCount(0);expect(await page.locator('.drag-lifted,.drag-landing-hidden').count()).toBe(0);
});
test('twelve character tabs stay single-row, keyboard reachable and active tab visible',async({page})=>{
 await ready(page);await page.evaluate(async()=>{const db=await new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open('dnd-card-standalone');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});const t=db.transaction('documents','readwrite'),s=t.objectStore('documents'),w:any=await new Promise(resolve=>{const r=s.get('workspace');r.onsuccess=()=>resolve(r.result);});const c=w.characters.find((x:any)=>x.id===w.activeId);w.characters=Array.from({length:12},(_,i)=>({...structuredClone(c),id:`tab-${i}`,name:i%2?'非常长的原创角色名字用于测试标签可达性'+i:'短名'+i}));w.activeId='tab-11';s.put(w,'workspace');await new Promise<void>((resolve,reject)=>{t.oncomplete=()=>resolve();t.onerror=()=>reject(t.error);});db.close();});await page.reload();await expect(page.locator('#root')).toHaveJSProperty('inert',false);const tabs=page.getByRole('tablist',{name:'当前角色'});await expect(tabs.getByRole('tab')).toHaveCount(12);expect(await tabs.evaluate(el=>getComputedStyle(el).display)).toBe('flex');
 for(const width of [1512,1040,390]){await page.setViewportSize({width,height:982});const selected=tabs.locator('[aria-selected=true]');await expect.poll(()=>selected.evaluate(el=>{const b=el.getBoundingClientRect(),p=el.parentElement!.getBoundingClientRect();return b.left>=p.left-1&&b.right<=p.right+1;})).toBe(true);const ys=await tabs.getByRole('tab').evaluateAll(es=>es.map(el=>Math.round(el.getBoundingClientRect().y)));expect(new Set(ys).size).toBe(1);await selected.focus();await page.keyboard.press('Home');await expect(tabs.getByRole('tab').first()).toHaveAttribute('aria-selected','true');await page.keyboard.press('End');await expect(tabs.getByRole('tab').last()).toHaveAttribute('aria-selected','true');await page.screenshot({path:test.info().outputPath(`character-tabs-${width}.png`)});expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);}
});
test('backpack has five default coins on one row and retains quantity and moves after reload',async({page})=>{
 await ready(page);await page.getByRole('switch',{name:'编辑模式',exact:true}).click();await page.getByRole('tab',{name:'背包',exact:true}).click();const coins=page.locator('.stock-currency');await expect(coins).toHaveCount(5);const ys=await coins.evaluateAll(es=>es.map(el=>Math.round(el.getBoundingClientRect().y)));expect(new Set(ys).size).toBe(1);expect(await page.locator('.stock-grid').evaluate(el=>getComputedStyle(el).gridTemplateColumns.split(' ').length)).toBe(5);await page.screenshot({path:test.info().outputPath('five-coins-wide.png')});
 await page.getByRole('button',{name:'金币数量',exact:true}).click();await page.getByRole('textbox',{name:'金币数量',exact:true}).fill('17');await page.getByRole('textbox',{name:'金币数量',exact:true}).press('Enter');await expect(page.getByRole('button',{name:'金币数量',exact:true})).toHaveText('x17');const board=page.locator('.paper .stock-board'),coin=board.locator('[data-stock-id="coin:gp"]'),target=board.locator('[data-stock-slot="9"]');await coin.dragTo(target);await expect(page.locator('.pointer-ghost')).toHaveCount(0);await expect(page.locator('[data-stock-id="coin:gp"]')).toHaveCount(1);await expect(coin).toHaveAttribute('data-stock-slot','9');await expect(page.locator('.save-status')).toContainText('已保存到本机');await page.reload();await page.getByRole('tab',{name:'背包',exact:true}).click();await expect(page.getByRole('button',{name:'金币数量',exact:true})).toHaveText('x17');await expect(coin).toHaveAttribute('data-stock-slot','9');await page.setViewportSize({width:390,height:844});await page.screenshot({path:test.info().outputPath('backpack-narrow-saved.png')});expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);
});

for(const edition of ['2014','2024'] as const)test(`class-derived ${edition} title stays visible across page and narrow layout changes`,async({page})=>{
 await ready(page);const c=newCharacter(edition);c.name=`原创${edition}职业标题`;
 const source=edition==='2014'?'PHB':'XPHB';c.selections=[{id:'title-owner',entry:{id:`title-owner-${source}`,kind:'class',name:'原创学者',english:'Authored Title Scholar',source,edition,packId:'fixture',revision:'1',raw:{hd:{faces:6}},entries:['原创卡头验收。']},level:1,quantity:1,equipped:false}];
 await page.getByRole('button',{name:'导入 / 导出',exact:true}).click();await page.getByTestId('character-file').setInputFiles({name:'title.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(exportCharacter(c)))});// Cross-edition imports deliberately stop before mutating the workspace.
 if(edition==='2014'){
  const review=page.getByRole('dialog',{name:'导入前核对',exact:true});await expect(review).toBeVisible();
  await expect(review).toContainText('导入角色使用 2014，当前规则使用 2024。导入后保留该角色自己的规则版本。');
  await expect(page.getByRole('tablist',{name:'当前角色'}).getByRole('tab')).toHaveCount(2);
  await review.getByRole('button',{name:'保留全部记录并导入',exact:true}).click();await expect(review).toHaveCount(0);
 }
 const selected=page.locator('.character-tabs [role="tab"]').filter({hasText:c.name});
 await expect(selected).toHaveAttribute('title',c.name+'（导入）');await expect(selected).toHaveAttribute('aria-selected','true');await page.keyboard.press('Escape');
 await expect(page.locator('.save-status')).toContainText('已保存到本机');
 await page.getByRole('combobox',{name:'资料版本',exact:true}).selectOption(edition==='2014'?'2024':'2014');
 for(const width of [1512,390]){await page.setViewportSize({width,height:982});for(const name of ['主要','特性','法术']){await page.getByRole('tab',{name,exact:true}).click();const title=page.locator('.paper .edition-divider>strong');await expect(title).toHaveText(`DND 五版角色卡 · ${edition}`);const visible=await title.evaluate(el=>{const a=el.getBoundingClientRect(),b=el.parentElement!.getBoundingClientRect();return a.left>=b.left-1&&a.right<=b.right+1&&a.width>0;});expect(visible).toBe(true);expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);}await page.screenshot({path:test.info().outputPath(`class-title-${edition}-${width}.png`)});}
});
