import {test,expect,type Page} from '@playwright/test';
import {writeFileSync} from 'node:fs';
import {mockSource,suppressAnnouncement} from './fixtures';
import {newCharacter,type Entry} from '../../src/core/model';
import {newAutomationState} from '../../src/core/automation/state';
async function records(page:Page){return page.evaluate(async()=>{const req=indexedDB.open('dnd-card-standalone');await new Promise<void>(resolve=>req.onsuccess=()=>resolve());const db=req.result;try{return await new Promise<any>(resolve=>{const req=db.transaction('documents').objectStore('documents').get('workspace');req.onsuccess=()=>resolve(req.result);});}finally{db.close();}});}
async function setup(page:Page,cards:number,catalog:number,mode:'a4'|'screen'){
 await mockSource(page,{displayMode:mode});await suppressAnnouncement(page);
 await page.route('**/data/spells/spells-test.json',r=>r.fulfill({json:{spell:Array.from({length:catalog},(_,i)=>({name:`原创资料法术${i}`,ENG_name:`Authored Spell ${i}`,source:'XPHB',level:i%10,entries:['原创性能夹具条目，用于测量资料规模，非公开出版物。']}))},headers:{'access-control-allow-origin':'*'}}));
 const characters=Array.from({length:cards},(_,i)=>{const c=newCharacter();c.name=i===0?'短名':`角色${i} - ${'很长的角色名称'.repeat(i%3===0?5:1)}`;c.automation=newAutomationState();c.runtime.resources.manual={name:'自定义资源',current:3,max:7};c.selections=Array.from({length:20},(_,j)=>({id:`sel-${i}-${j}`,entry:{id:`entry-${i}-${j}`,name:`原创特性${j}`,english:`Authored feature ${j}`,kind:'feature',edition:'2024',source:'XPHB',revision:'1',packId:'fixture',entries:['原创卡面性能测试，不带自动化声明。'],raw:{} } as Entry,level:1,quantity:1,equipped:false}));return c;});
 await page.addInitScript(characters=>{localStorage.setItem('dnd-card:editing','true');const r=indexedDB.open('dnd-card-standalone',1);r.onupgradeneeded=()=>{r.result.createObjectStore('documents');r.result.createObjectStore('cache');};r.onsuccess=()=>{const db=r.result,tx=db.transaction('documents','readwrite'),store=tx.objectStore('documents'),read=store.get('workspace');read.onsuccess=()=>{if(!read.result)store.put({schemaVersion:1,characters,activeId:characters[0].id,packs:[]},'workspace');};tx.oncomplete=()=>db.close();};},characters);
 await page.goto('/');await expect(page.getByRole('switch',{name:'编辑模式',exact:true})).toBeEnabled();await expect(page.getByRole('button',{name:'更新资料',exact:true})).toBeEnabled();await expect(page.locator('.save-status')).toContainText('已保存到本机');
 await page.waitForTimeout(400);
 const client=await page.context().newCDPSession(page);await client.send('Emulation.setCPUThrottlingRate',{rate:4});
 await page.evaluate(()=>{const metrics:any=(window as any).__editMetrics={events:[],longtasks:[],drag:[]};new PerformanceObserver(list=>metrics.longtasks.push(...list.getEntries().map(e=>({start:e.startTime,duration:e.duration})))).observe({type:'longtask',buffered:false});const starts=new WeakMap<Event,any>();document.addEventListener('input',e=>{if((e.target as HTMLElement)?.getAttribute('aria-label')!=='角色姓名')return;const start=performance.now(),event:any={start};metrics.events.push(event);starts.set(e,event);requestAnimationFrame(()=>requestAnimationFrame(()=>event.paint=performance.now()-start));},true);document.addEventListener('input',e=>{const event=starts.get(e);if(event)event.handler=performance.now()-event.start;});document.addEventListener('pointerup',()=>{const start=performance.now();requestAnimationFrame(()=>requestAnimationFrame(()=>metrics.drag.push(performance.now()-start)));},true);});
 return (await records(page)).characters;
}
function stats(values:number[]){const sorted=values.slice().sort((a,b)=>a-b);return {count:values.length,p50:sorted[Math.floor(sorted.length*.5)]||0,p95:sorted[Math.floor(sorted.length*.95)]||0,max:sorted.at(-1)||0};}
for(const mode of ['a4','screen'] as const)for(const [cards,catalog] of [[1,100],[12,100],[12,10000]])test(`${mode} ${cards} cards ${catalog} catalog name edits and class drop`,async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));const original=await setup(page,cards,catalog,mode);const name=page.getByRole('textbox',{name:'角色姓名',exact:true});
 const measure=async(label:string,value:string)=>{await page.evaluate(()=>{(window as any).__editMetrics.events=[];(window as any).__editMetrics.longtasks=[];});await name.fill('');await name.pressSequentially(value,{delay:20});await expect(name).toHaveValue(value);await expect(page.locator('.save-status')).toContainText('已保存到本机');await page.waitForTimeout(150);const metrics=await page.evaluate(()=>(window as any).__editMetrics);expect(metrics.events.length).toBeGreaterThanOrEqual(value.length);expect(metrics.events.every((e:any)=>Number.isFinite(e.handler)&&Number.isFinite(e.paint))).toBe(true);return {label,handler:stats(metrics.events.map((e:any)=>e.handler)),paint:stats(metrics.events.map((e:any)=>e.paint)),longtasks:stats(metrics.longtasks.map((e:any)=>e.duration))};};
 const metrics=[await measure('short-first','ShortName'),await measure('short-reedit','NameAgain'),await measure('long-name','Long character name for repeat editing and layout sizing 0123456789')];
 const row=page.locator('.catalog-row').filter({hasText:'测试法师'}).first(),target=page.locator('.identity-class');await row.scrollIntoViewIfNeeded();await page.evaluate(()=>{(window as any).__editMetrics.longtasks=[];(window as any).__editMetrics.drag=[];});await row.dragTo(target);await expect(target).toContainText('测试法师');await expect(page.locator('.save-status')).toContainText('已保存到本机');await page.waitForTimeout(150);const drag=await page.evaluate(()=>(window as any).__editMetrics);expect(drag.drag.length).toBeGreaterThan(0);const saved=await records(page),active=saved.characters.find((c:any)=>c.id===saved.activeId);expect(active.selections.some((s:any)=>s.entry.name==='初始特性')).toBe(true);expect(active.runtime.resources.manual).toEqual(original[0].runtime.resources.manual);expect(saved.characters.slice(1)).toEqual(original.slice(1));expect(errors).toEqual([]);
 const result={build:test.info().project.name,baselineSha:process.env.DND_PERF_BASELINE_SHA,mode,cards,catalog,cpuThrottle:4,metrics,drop:{paint:stats(drag.drag),longtasks:stats(drag.longtasks.map((e:any)=>e.duration))}};writeFileSync(test.info().outputPath('metrics.json'),JSON.stringify(result,null,2));console.log('PERF232 '+JSON.stringify(result));
 await page.reload();await expect(page.getByRole('textbox',{name:'角色姓名',exact:true})).toHaveValue(active.name);await expect(page.locator('.identity-class')).toContainText('测试法师');
});
