import {test,expect,type Page} from '@playwright/test';
import {mockSource,suppressAnnouncement} from './fixtures';
import {newCharacter,type Character} from '../../src/core/model';
import {exportCharacter} from '../../src/core/export';
async function start(page:Page){await mockSource(page);await suppressAnnouncement(page);await page.goto('/');await expect(page.getByRole('button',{name:'更新资料',exact:true})).toBeEnabled();}
async function workspace(page:Page){return page.evaluate(async()=>{const db=await new Promise<IDBDatabase>(ok=>{const r=indexedDB.open('dnd-card-standalone');r.onsuccess=()=>ok(r.result);});try{return await new Promise<any>(ok=>{const r=db.transaction('documents').objectStore('documents').get('workspace');r.onsuccess=()=>ok(r.result);});}finally{db.close();}});}
async function upload(page:Page,c:Character){await page.getByRole('button',{name:'导入 / 导出',exact:true}).click();await page.getByTestId('character-file').setInputFiles({name:'authored217.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(exportCharacter(c)))});await page.getByRole('button',{name:'关闭弹窗'}).click();await expect(page.locator('.save-status')).toContainText('已保存到本机');}
test('current class with custom ancestry and bubbles has no old-card warning',async({page})=>{
 await start(page);await page.getByRole('switch',{name:'编辑模式'}).click();await page.locator('.catalog-row').filter({hasText:'测试法师'}).click({button:'right'});await page.getByRole('menuitem',{name:'添加至角色卡',exact:true}).click();await expect(page.locator('.identity-class')).toContainText('测试法师');await expect.poll(async()=>{const w=await workspace(page);return w?.characters.find((c:Character)=>c.id===w.activeId)?.selections.filter((s:any)=>s.entry.kind==='class').length;}).toBe(1);
 const w=await workspace(page),c=w.characters.find((c:Character)=>c.id===w.activeId);c.id='fixture217-current';c.name='正常职业加个人内容';c.selections.push({id:'personal',level:1,quantity:1,equipped:false,entry:{id:'personal-entry',name:'原创个人能力',english:'Original Feature',kind:'feature',source:'CUSTOM',packId:'custom',revision:'1',edition:'both',entries:['原创'],raw:{_custom:true}}});await upload(page,c);await expect(page.locator('.class-compatibility-banner')).toHaveCount(0);await expect(page.getByRole('tab',{name:'正常职业加个人内容',exact:true}).locator('.class-warning-icon')).toHaveCount(0);await page.reload();await expect(page.locator('.paper')).toBeVisible();await expect(page.locator('.class-compatibility-banner')).toHaveCount(0);await page.getByRole('button',{name:'导入 / 导出',exact:true}).click();await page.getByRole('button',{name:'核对当前角色资料',exact:true}).click();await expect(page.getByRole('dialog',{name:'旧卡资料同步',exact:true})).toBeVisible();
});
test('all skill adjustments are inline, change calculations, and survive reload',async({page})=>{
 await start(page);await page.getByRole('switch',{name:'编辑模式'}).click();await expect(page.locator('.skill-extra-adjustment')).toHaveCount(18);const p=page.getByLabel('察觉额外调整值');await p.fill('3');await p.press('Tab');await expect(page.locator('.ability-skill').filter({has:p}).locator('b')).toHaveText('+3');const n=page.getByLabel('运动额外调整值');await n.fill('-2');await n.press('Tab');await expect.poll(async()=>{const w=await workspace(page);return w?.characters.find((c:Character)=>c.id===w.activeId)?.skillBonuses;}).toEqual({perception:3,athletics:-2});
 const sameRow=await p.evaluate(el=>{const b=el.getBoundingClientRect(),label=el.previousElementSibling!.getBoundingClientRect();return Math.abs(b.y+b.height/2-label.y-label.height/2)<6;});expect(sameRow).toBe(true);await page.screenshot({path:test.info().outputPath('skills-editing.png')});await page.reload();await expect(page.getByLabel('察觉额外调整值')).toHaveValue('3');await page.getByRole('switch',{name:'编辑模式'}).click();await expect(page.locator('.skill-extra-adjustment')).toHaveCount(0);await expect(page.locator('.ability-skill').filter({hasText:'察觉'}).locator('b')).toHaveText('+3');
});
test('custom examples fill every field, undo restores edits, JSON is bidirectional and context menu removes catalog only',async({page})=>{
 await start(page);await page.locator('.category-tabs').getByRole('button',{name:'自定义',exact:true}).click();await page.getByLabel('自定义条目名称',{exact:true}).fill('保留的草稿');await page.getByLabel('自定义条目类型',{exact:true}).selectOption('spell');await page.getByRole('button',{name:'填充格式示例',exact:true}).click();await expect(page.getByLabel('自定义条目名称',{exact:true})).toHaveValue('自定义条目');await expect(page.getByLabel('法术环阶',{exact:true})).toHaveValue('1');await page.getByRole('button',{name:'撤回',exact:true}).click();await expect(page.getByLabel('自定义条目名称',{exact:true})).toHaveValue('保留的草稿');await page.getByRole('button',{name:'填充格式示例',exact:true}).click();await page.getByLabel('自定义条目名称',{exact:true}).fill('原创星光');await page.getByRole('button',{name:'JSON 输入',exact:true}).click();const json=page.getByLabel('完整自定义条目 JSON');const data=JSON.parse(await json.inputValue());expect(data.name).toBe('原创星光');data.name='原创月光';data.raw.level=2;await json.fill(JSON.stringify(data));await page.getByRole('button',{name:'格式输入',exact:true}).click();await expect(page.getByLabel('自定义条目名称',{exact:true})).toHaveValue('原创月光');await expect(page.getByLabel('法术环阶',{exact:true})).toHaveValue('2');await page.getByRole('button',{name:'保存条目',exact:true}).click();await expect(page.locator('.catalog-row').filter({hasText:'原创月光'})).toBeVisible();await page.getByRole('switch',{name:'编辑模式'}).click();await page.locator('.catalog-row').filter({hasText:'原创月光'}).click({button:'right'});await page.getByRole('menuitem',{name:'添加至角色卡',exact:true}).click();await expect.poll(async()=>{const w=await workspace(page);return w.characters.find((c:Character)=>c.id===w.activeId).selections.some((s:any)=>s.entry.name==='原创月光');}).toBe(true);await page.reload();const before=await workspace(page),original=before.characters.find((c:Character)=>c.id===before.activeId);await page.locator('.catalog-row').filter({hasText:'原创月光'}).click({button:'right'});await page.getByRole('menuitem',{name:'移除自定义条目',exact:true}).click();await expect(page.locator('.catalog-row').filter({hasText:'原创月光'})).toHaveCount(0);await expect.poll(async()=>(await workspace(page))?.customEntries?.length).toBe(0);const after=await workspace(page);expect(after.characters.find((c:Character)=>c.id===original.id)).toEqual(original);await page.reload();const persisted=await workspace(page);expect(persisted.characters.find((c:Character)=>c.id===original.id).selections.some((s:any)=>s.entry.name==='原创月光')).toBe(true);
});
test('authoring guide and reference header remain accessible while scrolling',async({page})=>{
 await start(page);await page.locator('.category-tabs').getByRole('button',{name:'自定义',exact:true}).click();await page.getByLabel('自定义条目类型',{exact:true}).selectOption('spell');await page.getByRole('button',{name:'使用必看！填写帮助'}).hover();await expect(page.getByRole('tooltip')).toContainText('整体扩展包');await page.getByRole('button',{name:'查看参考格式',exact:true}).click();const dialog=page.getByRole('dialog',{name:'自定义条目参考格式'});await dialog.evaluate(el=>el.scrollTop=el.scrollHeight);const close=dialog.getByRole('button',{name:'关闭参考格式'});expect(await close.evaluate(el=>{const b=el.getBoundingClientRect();return el.contains(document.elementFromPoint(b.x+b.width/2,b.y+b.height/2));})).toBe(true);await page.screenshot({path:test.info().outputPath('reference-sticky.png')});await close.click();
});
test('announcement has inline support, native QR enlargement, continuous full-screen names and cleanup',async({page})=>{
 await start(page);await page.route('**/support/supporters.json',r=>r.fulfill({json:[{name:'原创支持者甲',amount:10},{name:'原创支持者乙',amount:20}]}));await page.getByRole('button',{name:'公告',exact:true}).click();const dialog=page.getByRole('dialog',{name:/欢迎/});await expect(page.locator('.announcement .author-support')).toContainText('1763086701psw@gmail.com');await expect(page.locator('.supporter-marquee.is-fullscreen')).toBeVisible();const qr=page.getByRole('button',{name:'放大微信赞助二维码'});await qr.hover();await expect(page.locator('.author-qr-preview:popover-open')).toBeVisible();await page.locator('.author-qr-preview:popover-open').getByRole('button',{name:'关闭二维码'}).click();await expect.poll(()=>page.locator('.supporter-flight').count(),{timeout:10000}).toBeGreaterThan(4);await page.screenshot({path:test.info().outputPath('announcement-support.png')});await page.getByRole('button',{name:'我知道了',exact:true}).click();await expect(page.locator('[data-supporter-marquee]')).toHaveCount(0);
});
