import {test,expect} from '@playwright/test';
import {readFileSync} from 'node:fs';
import {suppressAnnouncement} from './fixtures';
test('drag paints independent depth immediately and keeps cached paper nodes',async({page,request})=>{
 const fixture=JSON.parse(readFileSync('evidence/cloud-fixture.json','utf8')),headers={Origin:'http://127.0.0.1:5320','X-CSRF-Token':fixture.ownerSession.csrf,Cookie:'dnd_cloud='+fixture.ownerSession.token},ids:string[]=[];
 for(let i=0;i<5;i++){const r=await request.post('/api/cards',{headers,data:{confirmUpload:true,character:{...fixture.card.character,id:crypto.randomUUID(),name:'原创弧线过渡验收 '+i}}});expect(r.status()).toBe(201);ids.push((await r.json()).id);}
 try{
  await suppressAnnouncement(page);const reads:string[]=[];page.on('request',r=>{if(/\/api\/cards\/[A-Z]{6}$/.test(r.url())&&r.method()==='GET')reads.push(r.url());});await page.goto('/library/?q=原创弧线过渡验收');await expect(page.locator('.cloud-gallery-stage .paper')).toHaveCount(5);await expect.poll(()=>reads.length).toBe(5);
  const stage=page.locator('.cloud-gallery-stage'),active=page.locator('.cloud-gallery-item.is-active'),previous=page.locator('.cloud-gallery-item[data-offset="-1"]');const scale=(node:any)=>node.evaluate((el:HTMLElement)=>{const m=new DOMMatrix(getComputedStyle(el).transform);return Math.hypot(m.a,m.b);});const a=await scale(active),b=await scale(previous),id=await active.getAttribute('data-card-id');const papers=await page.locator('.cloud-gallery-item').evaluateAll(nodes=>{(window as any).savedGalleryPapers=Object.fromEntries(nodes.map(node=>[node.getAttribute('data-card-id'),node.querySelector('.paper')]));return nodes.length;});expect(papers).toBe(5);
  const box=(await stage.boundingBox())!;await page.mouse.move(box.x+box.width/2,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width/2+20,box.y+box.height/2,{steps:6});await expect(active).toHaveAttribute('data-card-id',id!);await expect.poll(()=>scale(active)).toBeLessThan(a-.005);await expect.poll(()=>scale(previous)).toBeGreaterThan(b+.005);expect(await stage.boundingBox()).toEqual(box);await page.mouse.up();await expect(page.getByRole('dialog',{name:'全屏角色卡'})).toHaveCount(0);
  for(let i=0;i<5;i++){await page.getByRole('button',{name:'下一张角色卡'}).click();await expect(page.locator('.cloud-gallery-item.is-active .paper')).toBeVisible();}expect(reads).toHaveLength(5);expect(await page.locator('.cloud-gallery-item').evaluateAll(nodes=>nodes.every(node=>(window as any).savedGalleryPapers[node.getAttribute('data-card-id')!]===node.querySelector('.paper')))).toBe(true);
 }finally{for(const id of ids)expect((await request.delete('/api/cards/'+id,{headers,data:{revision:1}})).ok()).toBe(true);}
});
