import {test,expect,type Page} from '@playwright/test';
import {newCharacter} from '../../src/core/model';import {exportOwlbear} from '../../src/core/export';import {evaluate} from '../../src/core/engine';import {mockSource} from './fixtures';
const protocol='full-suite-workbench/v1',session='group217';
async function send(host:Page,type:string,extra:any){await host.evaluate(({protocol,session,type,extra})=>(window as any).viewer.postMessage({protocol,session,type,hostStarted:217,...extra,...(type==='groupRollState'?{groupRevision:++(window as any).groupRevision}:{})},location.origin),{protocol,session,type,extra});}
test('group area locks DC results, separates settlement from close and restores prior card view',async({page:host},info)=>{
 await mockSource(host);await host.route('**/group-host217',route=>route.fulfill({contentType:'text/html',body:'<!doctype html><title>合成群体宿主</title>'}));await host.goto('/group-host217');
 await host.evaluate(({protocol,session})=>{const w=window as any;w.requests=[];w.groupRevision=0;window.addEventListener('message',e=>{const m=e.data;if(m?.protocol!==protocol||m.session!==session)return;w.requests.push(m);const reply=(type:string,extra:any={})=>(e.source as Window).postMessage({protocol,session,type,hostStarted:217,...extra},location.origin);if(m.type==='hello'||m.type==='ping')reply(m.type==='hello'?'ready':'pong');if(m.type==='groupRoll'){if(m.action==='adjust')w.group={...w.group,adjustment:{field:m.field,mode:m.mode,value:m.value,pending:false},targets:w.group.targets.map((t:any)=>({...t,applied:true}))};if(m.action==='roll')w.group={...w.group,phase:'resolve',kind:m.kind,targets:w.group.targets.map((t:any,i:number)=>({...t,result:i?18:7,applied:false}))};if(m.action==='visibility')w.group={...w.group,visible:m.visible};if(m.action==='settle')w.group={...w.group,phase:'settled',targets:w.group.targets.map((t:any)=>({...t,applied:true}))};if(m.action==='close')w.group=null;reply('groupRollState',{group:w.group,groupRevision:++w.groupRevision});reply('ack',{requestId:m.requestId,ok:true,result:{}});}});},{protocol,session});
 const waiting=host.context().waitForEvent('page');await host.evaluate(session=>{(window as any).viewer=window.open('/#suite='+session+'&bridge='+encodeURIComponent(location.origin),'group217');},session);const page=await waiting;await mockSource(page);await expect(page.locator('.app-shell')).toBeVisible();
 const c=newCharacter();c.name='合成群体验收卡';c.baseHp=30;c.runtime.hp=21;const state={key:'room:card:synthetic',cardId:'synthetic',itemId:'token-one',name:c.name,kind:'character',role:'GM',write:true,locked:false,pinned:false,stats:{health:21,'max health':30,'temporary health':0,'armor class':10},resources:[],conditions:[]};
 await send(host,'catalog',{sequence:1,cards:[{...state,id:'synthetic',inScene:true}],monsters:[],role:'GM',enabled:{characterCards:true},visibility:{wiki:true,monsters:true}});await send(host,'selection',{sequence:2,state,document:{...exportOwlbear(c,evaluate(c)),dnd_card_web:c}});await send(host,'navigate',{});await expect(page.locator('.paper')).toBeVisible();
 const group={id:'group-synthetic',phase:'select',kind:'save',ability:'dex',variant:'normal',visible:true,targets:['one','two'].map((id,i)=>({itemId:'token-'+id,key:'room:card:'+id,name:'合成目标 '+(i+1),hidden:false,initiative:2,ability:{dex:2},saves:{dex:4}}))};await host.evaluate(group=>(window as any).group=group,group);await send(host,'groupRollState',{group});const area=page.getByRole('region',{name:'群体区域'});await expect(area).toBeVisible();await expect(page.locator('.dm-console')).toBeVisible();for(const [field,mode,value]of [['health','heal','2'],['max health','set','40'],['armor class','damage','1']]){await area.getByLabel('群体修改字段').selectOption(field);await area.getByLabel('群体调整效果').selectOption(mode);await area.getByLabel('群体结算数值').fill(value);await area.getByRole('button',{name:'应用调整',exact:true}).click();await expect(area).toContainText('已应用数值调整');}await area.getByRole('button',{name:'同时投掷'}).click();await expect(area).toContainText('结果已就绪，可以直接结算');
 // A selection notification and explicit follow-selection navigation cannot
 // replace an active DC area. The host state machine is separately unit-tested.
 await send(host,'selection',{sequence:3,state,document:{...exportOwlbear(c,evaluate(c)),dnd_card_web:c}});await send(host,'navigate',{});await expect(area).toBeVisible();await area.getByRole('button',{name:'隐藏数字'}).click();await expect(area.getByRole('button',{name:'显示数字'})).toBeVisible();await area.getByRole('button',{name:'显示数字'}).click();await area.getByLabel('群体结算数值').fill('12');await area.getByRole('button',{name:'结算',exact:true}).click();await expect(area).toContainText('已结算；头顶结果保留至关闭');await expect(area).toBeVisible();await page.screenshot({path:info.outputPath('group-area-settled.png')});
 await area.getByRole('button',{name:'关闭',exact:true}).click();await expect(area).toHaveCount(0);await expect(page.locator('.paper')).toBeVisible();await expect(page.getByLabel('当前生命值',{exact:true})).toHaveValue('21');const actions=await host.evaluate(()=>(window as any).requests.filter((m:any)=>m.type==='groupRoll').map((m:any)=>m.action));expect(actions).toEqual(['adjust','adjust','adjust','roll','visibility','visibility','settle','close']);const edits=await host.evaluate(()=>(window as any).requests.filter((m:any)=>m.type==='groupRoll'&&m.action==='adjust').map((m:any)=>[m.field,m.mode,m.value]));expect(edits).toEqual([['health','heal',2],['max health','set',40],['armor class','damage',1]]);const settlement=await host.evaluate(()=>(window as any).requests.find((m:any)=>m.action==='settle'));expect(settlement.field).toBe('armor class');expect(settlement.dc).toBe(10);
 const heal={...group,id:'group-heal',phase:'resolve',targets:group.targets.map((t:any)=>({...t,result:12}))};await host.evaluate(group=>(window as any).group=group,heal);await send(host,'groupRollState',{group:heal});await expect(area).toBeVisible();await area.getByLabel('群体调整效果').selectOption('heal');await area.getByLabel('群体修改字段').selectOption('max health');await area.getByLabel('群体结算 DC').fill('');await area.getByLabel('群体结算数值').fill('3');await area.getByRole('button',{name:'结算',exact:true}).click();await expect(area).toContainText('已结算');const healing=await host.evaluate(()=>(window as any).requests.filter((m:any)=>m.action==='settle').at(-1));expect(healing.field).toBe('max health');expect(healing.mode).toBe('heal');expect(healing.dc).toBeUndefined();await area.getByRole('button',{name:'关闭',exact:true}).click();await expect(area).toHaveCount(0);
 const makeTargets=(count:number)=>Array.from({length:count},(_,i)=>({...group.targets[0],itemId:'budget-'+i,key:'card:budget-'+i,name:'合成预算目标 '+i}));
 const normal100={...group,id:'group-normal100',targets:makeTargets(100)};await send(host,'groupRollState',{group:normal100});await expect(area.getByRole('button',{name:'同时投掷'})).toBeEnabled();await expect(area).toContainText('普通投掷最多 100 个单位');await area.getByRole('combobox',{name:/方式/}).selectOption('adv');await expect(area.getByRole('button',{name:'同时投掷'})).toBeDisabled();await expect(area).toContainText('优势投掷最多 50 个单位');await area.getByRole('combobox',{name:/方式/}).selectOption('normal');await expect(area.getByRole('button',{name:'同时投掷'})).toBeEnabled();
 const adv50={...group,id:'group-adv50',targets:makeTargets(50),variant:'adv'};await send(host,'groupRollState',{group:adv50});await expect(area.getByRole('button',{name:'同时投掷'})).toBeEnabled();await area.getByRole('combobox',{name:/方式/}).selectOption('dis');await expect(area.getByRole('button',{name:'同时投掷'})).toBeEnabled();await expect(area).toContainText('劣势投掷最多 50 个单位');
 const adv51={...group,id:'group-adv51',targets:makeTargets(51),variant:'adv'};await send(host,'groupRollState',{group:adv51});await expect(area.getByRole('button',{name:'同时投掷'})).toBeDisabled();await expect(area).toContainText('当前选择超出数量');await area.getByRole('combobox',{name:/方式/}).selectOption('normal');await expect(area.getByRole('button',{name:'同时投掷'})).toBeEnabled();
 const limited={...group,id:'group-too-many',targets:[],selectedCount:101,error:'单批最多 100 枚实体骰，当前选择超过 100 个单位；没有省略或投掷任何目标。'};await send(host,'groupRollState',{group:limited});await expect(area.getByRole('button',{name:'同时投掷'})).toBeDisabled();await expect(area).toContainText('单批最多 100 枚实体骰');

});
