import {test,expect,type Page} from '@playwright/test';
import {ready,workspace,dragWiki} from './automationChoiceFixture';

async function saved(page:Page){return page.evaluate(()=>new Promise<any>((resolve,reject)=>{
 const request=indexedDB.open('dnd-card-automation-choices-20261001');request.onerror=()=>reject(request.error);request.onupgradeneeded=()=>{request.transaction?.abort();reject(Error('Expected saved choice-preview database'));};request.onsuccess=()=>{const db=request.result,get=db.transaction('documents').objectStore('documents').get('workspace');get.onerror=()=>{db.close();reject(get.error);};get.onsuccess=()=>{const w=get.result;db.close();resolve(w.characters.find((c:any)=>c.id===w.activeId));};};
}));}
test('reading-mode choice activates editing inside the main feature frame and keeps the other stats visible',async({page},info)=>{
 await ready(page);await page.getByRole('switch',{name:'编辑模式',exact:true}).click();await expect(page.getByRole('switch',{name:'编辑模式',exact:true})).toHaveAttribute('aria-checked','false');
 await page.locator('.class-features').getByRole('button',{name:'起始熟练项 0/2',exact:true}).click();await expect(page.getByRole('switch',{name:'编辑模式',exact:true})).toHaveAttribute('aria-checked','true');await expect(page.getByRole('tab',{name:'主要',exact:true})).toHaveAttribute('aria-selected','true');
 const inline=workspace(page,'起始熟练项');await expect(inline).toHaveClass(/choice-inline/);expect(await inline.evaluate(el=>!!el.closest('.class-features'))).toBe(true);await expect(page.locator('.ability-con')).toBeVisible();await expect(page.locator('.life-cell')).toBeVisible();
 const bounds=await inline.evaluate(el=>{const box=el.getBoundingClientRect(),host=el.closest('.class-features')!.getBoundingClientRect();return {height:box.height,hostHeight:host.height,left:box.left,hostLeft:host.left,right:box.right,hostRight:host.right};});expect(bounds.height).toBeLessThan(bounds.hostHeight);expect(bounds.left).toBeGreaterThanOrEqual(bounds.hostLeft);expect(bounds.right).toBeLessThanOrEqual(bounds.hostRight);
 await dragWiki(page,'运动',0);await expect(inline.getByRole('status').first()).toContainText('1/2');await expect(page.getByRole('tab',{name:'主要',exact:true})).toHaveAttribute('aria-selected','true');await page.screenshot({path:info.outputPath('main-inline-choice.png')});
});
test('an unfinished feature is clickable while reading without committing a Wiki navigation',async({page})=>{
 await ready(page);await page.getByRole('switch',{name:'编辑模式',exact:true}).click();await page.locator('.class-features [data-feature-id="feature-0"] .feature-caption').click();await expect(workspace(page,'测试圣职')).toBeVisible();await expect(page.getByRole('tab',{name:'主要',exact:true})).toHaveAttribute('aria-selected','true');await expect(page.getByRole('switch',{name:'编辑模式',exact:true})).toHaveAttribute('aria-checked','true');await expect(workspace(page,'测试圣职').getByRole('button',{name:'保护者',exact:true})).toBeVisible();
});
test('ignore retains real ratios, removes dashes, auto-hides resolved options and can be restored after reload',async({page},info)=>{
 await ready(page);await page.locator('.class-features').getByRole('button',{name:'起始熟练项 0/2',exact:true}).click();await workspace(page,'起始熟练项').getByRole('button',{name:'忽略此项',exact:true}).click();await expect(page.locator('.choice-workspace')).toHaveCount(0);await expect(page.locator('.class-features').getByRole('button',{name:'起始熟练项 0/2',exact:true})).not.toHaveClass(/is-pending/);
 await page.locator('.class-features').getByRole('button',{name:'起始装备 0/1',exact:true}).click();await workspace(page,'起始装备').getByRole('button',{name:'忽略此项',exact:true}).click();await page.locator('.class-features [data-feature-id="feature-0"] .feature-caption').click();await workspace(page,'测试圣职').getByRole('button',{name:'忽略此项',exact:true}).click();await expect(page.locator('.class-features .sheet-choice-chip')).toHaveCount(0);await expect(page.locator('.class-features .choice-pending')).toHaveCount(0);await expect(page.locator('.class-features [data-feature-id="feature-0"]')).toContainText('0/1');
 await expect.poll(async()=>(await saved(page)).featureLayout.ignoredChoices.length).toBe(3);const before=await saved(page);expect(before.answers).toEqual({});await page.reload();await expect(page.locator('.class-features .choice-pending')).toHaveCount(0);await page.locator('.class-features .feature-group h4').getByRole('button',{name:'职业 测试职业 Lv.1',exact:true}).click({button:'right'});await page.getByRole('menuitem',{name:'显示自带选项',exact:true}).click();
 await page.locator('.class-features').getByRole('button',{name:'起始熟练项 0/2',exact:true}).click();await expect(workspace(page,'起始熟练项').getByRole('status').first()).toContainText('已忽略');await workspace(page,'起始熟练项').getByRole('button',{name:'恢复填写',exact:true}).click();await workspace(page,'起始熟练项').getByRole('button',{name:'收起选择',exact:true}).click();await expect(page.locator('.class-features').getByRole('button',{name:'起始熟练项 0/2',exact:true})).toHaveClass(/is-pending/);await page.screenshot({path:info.outputPath('ignored-and-restored.png')});
});
test('narrow inline choices keep A4 and the current page while the choice content scrolls',async({page},info)=>{
 await page.setViewportSize({width:390,height:844});await ready(page);await page.getByRole('switch',{name:'编辑模式',exact:true}).click();const preference=await page.evaluate(()=>localStorage.getItem('dnd-card-sheet-display'));await page.locator('.class-features').getByRole('button',{name:'起始熟练项 0/2',exact:true}).click();await expect(page.getByRole('tab',{name:'主要',exact:true})).toHaveAttribute('aria-selected','true');
 const inline=workspace(page,'起始熟练项');await expect(inline).toBeVisible();await inline.getByRole('button',{name:'忽略此项',exact:true}).click();await expect(page.locator('.choice-workspace')).toHaveCount(0);expect(await page.evaluate(()=>localStorage.getItem('dnd-card-sheet-display'))).toBe(preference);await expect(page.locator('.ability-con')).toBeVisible();await page.screenshot({path:info.outputPath('narrow-inline-choice.png')});
});
