import {test,expect} from '@playwright/test';
import {mockSource} from './fixtures';
import {newCharacter,type Entry} from '../../src/core/model';
test('local inventory preserves grid positions, quantities, marquee selection and export layout',async({page})=>{
 await mockSource(page);const c=newCharacter();c.name='背包测试';
 c.inventory={view:'grid',order:[],attunementLimit:3,coins:{cp:0,sp:0,ep:0,gp:10,pp:0}};
 for(let i=0;i<2;i++){const entry:Entry={id:'pack:'+i,name:'测试物品'+i,english:'Test'+i,source:'XPHB',kind:'item',edition:'2024',packId:'test',revision:'1',entries:['自制说明'],raw:{weight:2}};c.selections.push({id:entry.id,entry,quantity:2,level:1,equipped:false});}
 await page.goto('/');await page.getByRole('button',{name:'导入 / 导出',exact:true}).click();await page.getByTestId('character-file').setInputFiles({name:'inventory.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(c))});await page.getByRole('button',{name:'关闭弹窗'}).click();await page.getByRole('tab',{name:'背包',exact:true}).click();
 const stock=page.locator('.stock-board');await expect(stock.getByLabel('金币数量',{exact:true})).toHaveText('x10');await expect(stock).toContainText('负重 8.2 / 150 磅');
 await stock.getByLabel('测试物品0数量').click();await stock.getByLabel('测试物品0数量').fill('3');await stock.getByLabel('测试物品0数量').press('Tab');await expect(stock).toContainText('负重 10.2 / 150 磅');
 const source=stock.locator('[data-stock-id="pack:0"] .stock-name'),target=stock.locator('[data-stock-slot="12"]');const a=(await source.boundingBox())!,b=(await target.boundingBox())!;await page.mouse.move(a.x+8,a.y+6);await page.mouse.down();await page.mouse.move(b.x+b.width/2,b.y+b.height/2,{steps:12});await page.mouse.up();const landing=page.locator('.pointer-ghost[data-landing=true]');await expect(landing).toBeVisible();expect(await landing.evaluate(el=>el.getAnimations().flatMap(a=>(a.effect as KeyframeEffect).getKeyframes()).every(frame=>frame.opacity===undefined))).toBe(true);await expect(landing).toHaveCount(0);await expect(stock.locator('[data-stock-id="pack:0"]')).toHaveAttribute('data-stock-slot','12');
 const empty=(await stock.locator('[data-stock-slot="8"]').boundingBox())!,item=(await stock.locator('[data-stock-id="pack:1"]').boundingBox())!;await page.mouse.move(empty.x+3,empty.y+empty.height-3);await page.mouse.down();await page.mouse.move(item.x+item.width-3,item.y+3,{steps:8});await expect(page.locator('.stock-marquee')).toBeVisible();await page.mouse.up();await expect(stock.locator('[data-stock-id="pack:1"]')).toHaveClass(/selected/);
 await page.reload();await page.getByRole('tab',{name:'背包',exact:true}).click();await expect(stock.locator('[data-stock-id="pack:0"]')).toHaveAttribute('data-stock-slot','12');await expect(stock.getByLabel('测试物品0数量')).toHaveText('x3');
 await page.locator('.paper').evaluate(el=>el.classList.add('sheet-export'));await expect(stock.locator('.stock-empty').first()).toBeHidden();await expect(stock.locator('.stock-collection')).toHaveCSS('display','flex');await page.locator('.paper').evaluate(el=>el.classList.remove('sheet-export'));
});
test('narrow Wiki drag switches to the character and restores Wiki on release',async({page})=>{
 await mockSource(page);await page.setViewportSize({width:800,height:1000});await page.goto('/');await page.getByRole('tab',{name:'背包',exact:true}).click();await page.getByRole('navigation',{name:'工作区'}).getByRole('button',{name:'Wiki',exact:true}).click();await page.getByRole('navigation',{name:'资料分类'}).getByRole('button',{name:'装备',exact:true}).click();await page.locator('.catalog-row').first().click();
 const source=page.locator('.detail-title'),a=(await source.boundingBox())!;await page.mouse.move(a.x+9,a.y+8);await page.mouse.down();await page.mouse.move(a.x-15,a.y-15,{steps:4});await expect(page.locator('.sheet-pane')).toHaveClass(/mobile-active/);const box=(await page.locator('.stock-collection').boundingBox())!;await page.mouse.move(box.x+20,box.y+20,{steps:8});await page.mouse.up();await expect(page.locator('.wiki-pane')).toHaveClass(/mobile-active/);await page.getByRole('navigation',{name:'工作区'}).getByRole('button',{name:'功能页',exact:true}).click();await expect(page.locator('.stock-item.stock-item')).toHaveCount(6);
});

test('inventory frames share state art and gravity, retain hit boxes and restore in edit mode',async({page})=>{
 await mockSource(page);const c=newCharacter();c.name='背包状态测试';
 for(const [id,name] of [['poisoned','中毒'],['petrified','石化'],['invisible','隐形'],['frightened','恐慌'],['exhaustion','力竭']])c.selections.push({id,entry:{id,kind:'condition',name,english:id,source:'XPHB',edition:'2024',packId:'test',revision:'1',entries:[],raw:{}},quantity:1,level:id==='exhaustion'?4:1,equipped:false});
 await page.goto('/');await page.getByRole('button',{name:'导入 / 导出',exact:true}).click();await page.getByTestId('character-file').setInputFiles({name:'stock-states.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(c))});await page.getByRole('button',{name:'关闭弹窗'}).click();await page.getByRole('tab',{name:'背包',exact:true}).click();
 const board=page.locator('.paper .stock-board'),cells=board.locator('[data-physical-frame=stock]');await expect(board).toHaveAttribute('data-fallen','true');await expect(cells).toHaveCount(24);await page.waitForTimeout(3200);
 expect(await cells.evaluateAll(nodes=>nodes.every(n=>n.getAttribute('data-fallen')==='true'))).toBe(true);
 expect(await cells.evaluateAll(nodes=>nodes.some(n=>parseFloat((n as HTMLElement).style.translate.split(' ')[1])>1))).toBe(true);
 expect(await cells.evaluateAll(nodes=>{const boxes=nodes.map(n=>n.getBoundingClientRect());return boxes.every((a,i)=>boxes.slice(i+1).every(b=>Math.min(a.right,b.right)-Math.max(a.left,b.left)<1||Math.min(a.bottom,b.bottom)-Math.max(a.top,b.top)<1));})).toBe(true);
 const coin=board.locator('[data-stock-id="coin:gp"]');await expect(coin.locator('.cell-cracks')).toHaveCSS('opacity','0.7');await expect(coin.locator('.poison-edge')).toHaveCSS('opacity','0.65');await expect(coin.locator('.invisible-cell-edge')).toHaveCSS('opacity','1');await expect(coin.locator('.exhaustion-segment.segment-on')).toHaveCount(4);
 const field=board.getByLabel('金币数量',{exact:true});await field.scrollIntoViewIfNeeded();expect(await field.evaluate(node=>{const r=node.getBoundingClientRect();return document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)===node;})).toBe(true);await field.click();await field.fill('12');await field.press('Enter');await expect(field).toHaveText('x12');
 await page.screenshot({path:'test-results/inventory-status-effects.png'});
 await page.getByRole('switch',{name:'编辑模式'}).click();await page.waitForTimeout(1000);expect(await cells.evaluateAll(nodes=>nodes.every(n=>!n.hasAttribute('data-fallen')&&['0px','0px 0px','none'].includes(getComputedStyle(n).translate)))).toBe(true);await expect(coin.locator('.cell-cracks')).toHaveCSS('opacity','0');await expect(coin).toHaveCSS('border-radius','0px');
 await page.screenshot({path:'test-results/inventory-edit-restored.png'});
});
