import {test,expect} from '@playwright/test';
import {mockSource,suppressAnnouncement} from './fixtures';
import {newCharacter} from '../../src/core/model';
test('legacy empty save expertise loads, invalid active data gets a clear error instead of the previous paper',async({page})=>{
 await mockSource(page);await suppressAnnouncement(page);await page.goto('/#suite=legacy-read&bridge='+encodeURIComponent(String(test.info().project.use.baseURL)));await expect(page.locator('.app-shell')).toBeVisible();
 const send=async(type:string,data:any={})=>page.evaluate(({type,data})=>window.dispatchEvent(new MessageEvent('message',{origin:location.origin,source:window,data:{protocol:'full-suite-workbench/v1',session:'legacy-read',hostStarted:100,type,...data}})),{type,data});
 const c=newCharacter();c.name='兼容读取测试';c.expertise={perception:true,'save:cha':false,'save:con':false};c.proficiencies={'save:cha':false};const target={key:'r:card:old',itemId:'card:old',cardId:'old',name:c.name,kind:'character',role:'GM',write:true,documentRevision:1,stats:{},resources:[]};await send('ready');await send('catalog',{sequence:1,role:'GM',cards:[{...target,id:'old',classSummary:[]}],monsters:[],enabled:{},visibility:{wiki:true,monsters:true},shared:{key:'room:fixture',scope:'room',revision:1,rules:{edition:'2024',profile:c.profile,packs:[],customEntries:[]}}});await send('selection',{sequence:2,state:target,document:{dnd_card_web:c,_suiteRevision:1}});await page.evaluate(()=>window.dispatchEvent(new Event('workbench-show-sheet')));await expect(page.locator('.paper')).toContainText('兼容读取测试');await page.getByRole('switch',{name:'编辑模式',exact:true}).click();const save=page.getByRole('checkbox',{name:'魅力豁免熟练状态：无熟练',exact:true});await expect(save).toBeDisabled();await expect(save).not.toBeChecked();
 const adjustment=page.getByRole('spinbutton',{name:'察觉额外调整值',exact:true});await expect(adjustment).toBeEnabled();await adjustment.fill('3');await adjustment.press('Tab');await expect(page.locator('.ability-skill').filter({has:adjustment}).locator('b')).toHaveText('+7');await expect(save).not.toBeChecked();
 await expect.poll(()=>page.evaluate(async()=>{const databases=await indexedDB.databases(),name=databases.some(x=>x.name==='dnd-card-standalone')?'dnd-card-standalone':'dnd-card-workspace';const db=await new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open(name);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});try{return await new Promise<any>((resolve,reject)=>{const r=db.transaction('documents').objectStore('documents').get('workspace');r.onsuccess=()=>{const c=r.result.characters.find((c:any)=>c.id===r.result.activeId);resolve({proficiencies:c.proficiencies,expertise:c.expertise,skillBonuses:c.skillBonuses});};r.onerror=()=>reject(r.error);});}finally{db.close();}})).toEqual({proficiencies:{'save:cha':false},expertise:{perception:true},skillBonuses:{perception:3}});
 const bad={...c,id:'bad',name:'坏记录测试',expertise:{'save:cha':true}};await send('selection',{sequence:3,state:{...target,key:'r:card:bad',itemId:'card:bad',cardId:'bad',name:bad.name},document:{dnd_card_web:bad,_suiteRevision:1}});await expect(page.locator('.workbench-monster [role=alert]')).toContainText('专精记录无效');await expect(page.locator('.paper')).toHaveCount(0);await page.screenshot({path:test.info().outputPath('invalid-card-load.png')});
 await send('selection',{sequence:4,state:target,document:{dnd_card_web:c,_suiteRevision:2}});await expect(page.getByRole('textbox',{name:'角色姓名',exact:true})).toHaveValue('兼容读取测试');
});
