import {test,expect} from '@playwright/test';
import {mockSource,suppressAnnouncement} from './fixtures';
import {newCharacter} from '../../src/core/model';
test('legacy empty save expertise loads, invalid active data gets a clear error instead of the previous paper',async({page})=>{
 await mockSource(page);await suppressAnnouncement(page);await page.goto('/#suite=legacy-read&bridge='+encodeURIComponent(String(test.info().project.use.baseURL)));await expect(page.locator('.app-shell')).toBeVisible();
 const send=async(type:string,data:any={})=>page.evaluate(({type,data})=>window.dispatchEvent(new MessageEvent('message',{origin:location.origin,source:window,data:{protocol:'full-suite-workbench/v1',session:'legacy-read',hostStarted:100,type,...data}})),{type,data});
 const c=newCharacter();c.name='兼容读取测试';c.expertise={perception:true,'save:cha':false,'save:con':false};const target={key:'r:card:old',itemId:'card:old',cardId:'old',name:c.name,kind:'character',role:'GM',write:true,documentRevision:1,stats:{},resources:[]};await send('ready');await send('catalog',{sequence:1,role:'GM',cards:[{...target,id:'old',classSummary:[]}],monsters:[],enabled:{},visibility:{wiki:true,monsters:true},shared:{key:'room:fixture',scope:'room',revision:1,rules:{edition:'2024',profile:c.profile,packs:[],customEntries:[]}}});await send('selection',{sequence:2,state:target,document:{dnd_card_web:c,_suiteRevision:1}});await page.evaluate(()=>window.dispatchEvent(new Event('workbench-show-sheet')));await expect(page.locator('.paper')).toContainText('兼容读取测试');await page.getByRole('switch',{name:'编辑模式',exact:true}).click();await page.getByLabel('魅力豁免熟练',{exact:true}).check();await page.getByLabel('魅力豁免熟练',{exact:true}).uncheck();
 const bad={...c,id:'bad',name:'坏记录测试',expertise:{'save:cha':true}};await send('selection',{sequence:3,state:{...target,key:'r:card:bad',itemId:'card:bad',cardId:'bad',name:bad.name},document:{dnd_card_web:bad,_suiteRevision:1}});await expect(page.locator('.workbench-monster [role=alert]')).toContainText('专精记录无效');await expect(page.locator('.paper')).toHaveCount(0);await page.screenshot({path:test.info().outputPath('invalid-card-load.png')});
 await send('selection',{sequence:4,state:target,document:{dnd_card_web:c,_suiteRevision:2}});await expect(page.getByRole('textbox',{name:'角色姓名',exact:true})).toHaveValue('兼容读取测试');
});
