import {test,expect,type Page} from '@playwright/test';
import {mockSource,suppressAnnouncement} from './fixtures';
import {newCharacter,type Character,type Entry} from '../../src/core/model';
import {spellState} from '../../src/core/characterDetails';
import {exportCharacter} from '../../src/core/export';
test.afterEach(async({page},info)=>{if(info.status!==info.expectedStatus&&await page.locator('.startup-panel pre').count())console.error(await page.locator('.startup-panel pre').allTextContents());});
async function workspace(page:Page){return page.evaluate(async()=>{const db=await new Promise<IDBDatabase>((resolve,reject)=>{const req=indexedDB.open('dnd-card-standalone');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});try{return await new Promise<any>((resolve,reject)=>{const req=db.transaction('documents').objectStore('documents').get('workspace');req.onsuccess=()=>resolve(req.result);req.onerror=()=>reject(req.error);});}finally{db.close();}});}
async function load(page:Page,c?:Character){await mockSource(page);await suppressAnnouncement(page);await page.goto('/');await expect(page.getByRole('button',{name:'更新资料',exact:true})).toBeEnabled();if(c){await page.getByRole('button',{name:'导入 / 导出',exact:true}).click();await page.getByTestId('character-file').setInputFiles({name:'feedback.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(exportCharacter(c)))});await expect(page.getByRole('tab',{name:c.name+'（导入）'})).toHaveAttribute('aria-selected','true');await expect(page.locator('.save-status')).toContainText('已保存到本机');const imported=page.getByRole('dialog',{name:'导入与导出',exact:true});await imported.getByRole('button',{name:'关闭弹窗',exact:true}).click();await expect(imported).toHaveCount(0);}}
const spell=(id:string,level:number):Entry=>({id,name:id,english:id,kind:'spell',raw:{level},source:'XPHB',edition:'2024',packId:'fixture',revision:'1',entries:['原创法术格验收资料。']});

test('first-use setup selects character rules, display and sources once, with an always-available rules entry',async({page})=>{
 await mockSource(page,{firstSetup:true});await suppressAnnouncement(page);await page.goto('/');const setup=page.getByRole('dialog',{name:'开始使用角色卡'});await expect(setup).toBeVisible();await expect(setup.locator('.setup-intro')).toContainText('你随时可以在右上角');
 await setup.getByRole('radio',{name:'2014',exact:true}).click();await setup.getByRole('radio',{name:'简写',exact:true}).click();await setup.locator('.source-group').filter({has:page.getByRole('checkbox',{name:'启用三宝书',exact:true})}).locator(':scope > summary').click();await expect(setup.locator('.source-book').filter({has:page.getByRole('button',{name:'设置来源 XPHB',exact:true})})).toBeVisible();await setup.locator('.source-book').filter({has:page.getByRole('button',{name:'设置来源 XPHB',exact:true})}).getByRole('checkbox').uncheck();
 await setup.getByRole('button',{name:'完成设置',exact:true}).click();await expect(setup).toHaveCount(0);await expect(page.locator('.save-status')).toContainText('已保存到本机');await page.reload();await expect(page.locator('.paper')).toBeVisible();await expect(setup).toHaveCount(0);
 await page.getByRole('button',{name:'规则与扩展',exact:true}).click();const rules=page.getByRole('dialog',{name:'规则与扩展',exact:true});await expect(rules.getByRole('radio',{name:'2014',exact:true})).toHaveAttribute('aria-checked','true');await expect(rules.getByRole('radio',{name:'简写',exact:true})).toHaveAttribute('aria-checked','true');await rules.locator('.source-group').filter({has:page.getByRole('checkbox',{name:'启用三宝书',exact:true})}).locator(':scope > summary').click();await expect(rules.locator('.source-book').filter({has:page.getByRole('button',{name:'设置来源 XPHB',exact:true})}).getByRole('checkbox')).not.toBeChecked();await page.screenshot({path:test.info().outputPath('rules-setup.png')});
});

test('empty preparation stays hidden, manual allowance creates exactly that many slots and the frame shrinks',async({page})=>{
 await load(page);await page.getByRole('tab',{name:'法术',exact:true}).click();await expect(page.locator('.prepared-cell')).toHaveCount(0);await page.getByRole('switch',{name:'编辑模式',exact:true}).click();await expect(page.locator('.prepared-cell')).toHaveCount(0);
 const allowance=page.getByLabel('预备上限调整',{exact:true});await allowance.fill('16');await allowance.press('Enter');await expect(page.locator('.ordinary-prepared-group .spell-grid-slot')).toHaveCount(16);const tall=(await page.locator('.prepared-cell').boundingBox())!.height;
 await allowance.fill('1');await allowance.press('Enter');await expect(page.locator('.ordinary-prepared-group .spell-grid-slot')).toHaveCount(1);await expect.poll(async()=>(await page.locator('.prepared-cell').boundingBox())!.height).toBeLessThan(tall-40);await expect(page.locator('[data-cantrip-group],.source-spell-group')).toHaveCount(0);
 await page.screenshot({path:test.info().outputPath('small-prepared-frame.png')});await allowance.fill('0');await allowance.press('Enter');await expect(page.locator('.prepared-cell')).toHaveCount(0);
 await expect.poll(async()=>{const w=await workspace(page);return w.characters.find((x:Character)=>x.id===w.activeId).spellSettings?.capacityAdjustment;}).toBe(0);
 await expect(page.locator('.save-status')).toContainText('已保存到本机');await page.reload();await page.getByRole('tab',{name:'法术',exact:true}).click();await expect(page.locator('.prepared-cell')).toHaveCount(0);
});

test('known spell levels fold independently and signed preparation reductions preserve overflow through reload',async({page})=>{
 const c=newCharacter();c.name='法术分组验收';c.selections=[spell('测试戏法',0),spell('测试一环',1),spell('测试二环',2)].map(entry=>({id:entry.id,entry,quantity:1,level:1,equipped:false}));c.spellSettings={...spellState(c),capacityAdjustment:3,prepared:c.selections.map(s=>s.id)};
 await load(page,c);await page.getByRole('switch',{name:'编辑模式',exact:true}).click();await page.getByRole('tab',{name:'法术',exact:true}).click();const tier=page.locator('.spell-library-level[data-spell-level="0"]');await tier.locator('summary').click();await expect(tier.locator('.spell-stock-tile')).toBeHidden();await expect(page.locator('.spell-library-level[data-spell-level="1"] .spell-stock-tile')).toBeVisible();
 await page.getByLabel('预备上限调整',{exact:true}).fill('1');await page.getByLabel('预备上限调整',{exact:true}).press('Enter');await expect(page.locator('.ordinary-prepared-group .spell-grid-slot')).toHaveCount(1);await expect(page.locator('.spell-overflow summary')).toContainText('2 项');await expect(tier.locator('.spell-stock-tile')).toBeHidden();await page.locator('.spell-overflow summary').click();await expect(page.locator('.spell-overflow')).toContainText('测试一环');await expect(page.locator('.save-status')).toContainText('已保存到本机');
 await expect.poll(async()=>{const w=await workspace(page);return w.characters.find((x:Character)=>x.id===w.activeId).spellSettings?.capacityAdjustment;}).toBe(1);
 await page.reload();await page.getByRole('tab',{name:'法术',exact:true}).click();await expect(page.locator('.ordinary-prepared-group .spell-grid-slot')).toHaveCount(1);await expect(page.locator('.spell-overflow summary')).toContainText('2 项');const w=await workspace(page);expect(w.characters.find((x:Character)=>x.id===w.activeId).spellSettings.prepared).toHaveLength(3);await page.locator('.ordinary-prepared-group .spell-stock-tile').click();await page.locator('.spell-library-level[data-spell-level="1"] .spell-stock-tile').click();await expect(page.locator('.ordinary-prepared-group .spell-stock-tile')).toContainText('测试一环');
 await page.setViewportSize({width:390,height:844});expect(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth)).toBe(false);await page.screenshot({path:test.info().outputPath('spell-groups-narrow.png'),fullPage:true});
});

test('legacy class review saves a synchronized copy and preserves the complete original through refresh',async({page})=>{
 const c=newCharacter();c.name='旧职业验收';c.notes='保留测试笔记';c.runtime.hp=7;c.runtime.resources.manual={name:'已消耗测试资源',current:1,max:3};const old:Entry={id:'legacy-mage',kind:'class',name:'旧职业法师',english:'旧职业法师',packId:'imported',source:'IMPORTED',edition:'both',revision:'0.3',entries:[],raw:{hd:{faces:6}}};c.selections=[{id:'legacy-class',entry:old,level:1,quantity:1,equipped:false}];
 await load(page,c);await expect(page.getByRole('button',{name:'核对并同步旧卡',exact:true})).toBeVisible();
 // Import initializes automatic hit dice asynchronously. Capture the complete saved
 // card after that existing initialization, before opening the migration preview.
 await expect.poll(async()=>{const w=await workspace(page);return w.characters.find((x:Character)=>x.id===w.activeId).runtime.resources['hit-die:6'];}).toBeDefined();
 await expect(page.locator('.save-status')).toContainText('已保存到本机');const before=await workspace(page),original=before.characters.find((x:Character)=>x.id===before.activeId);
 await page.getByRole('button',{name:'核对并同步旧卡',exact:true}).click();const review=page.getByRole('dialog',{name:'旧卡资料同步',exact:true});const choices=review.getByRole('radiogroup',{name:'旧职业法师同步目标',exact:true});await expect(choices.getByRole('radio',{name:'旧职业法师同步目标：自定义',exact:true})).toBeChecked();await choices.getByRole('radio',{name:'旧职业法师同步目标：自定义',exact:true}).click();await review.getByLabel('旧职业法师查找资料').fill('测试法师');await review.getByRole('radio',{name:'旧职业法师同步目标：测试法师（XPHB）',exact:true}).click();await expect(review.locator('.migration-manual-selected')).toContainText('测试法师');await review.getByRole('button',{name:'确认并继续',exact:true}).click();await expect(review.locator('.migration-preview')).toContainText('初始特性');
 const unchanged=await workspace(page);expect(unchanged.characters).toEqual(before.characters);await page.screenshot({path:test.info().outputPath('class-sync-preview.png')});await review.getByRole('button',{name:'创建同步副本',exact:true}).click();await expect(review).toHaveCount(0);await expect(page.locator('.suite-toast')).toContainText('同步副本已保存');await expect(page.locator('.save-status')).toContainText('已保存到本机');
 const after=await workspace(page),copy=after.characters.find((x:Character)=>x.id===after.activeId);expect(after.characters).toHaveLength(before.characters.length+1);expect(after.characters.find((x:Character)=>x.id===original.id)).toEqual(original);expect(copy.selections.find((x:any)=>x.id==='legacy-class').entry.source).toBe('XPHB');expect(copy.runtime.hp).toBe(7);expect(copy.runtime.resources.manual.current).toBe(1);expect(copy.notes).toBe(original.notes);expect(copy.runtime.resources['spell-slot:1'].current).toBe(0);
 await page.reload();await expect(page.locator('.paper')).toBeVisible();await expect(page.getByRole('button',{name:'核对并同步旧卡',exact:true})).toHaveCount(0);const persisted=await workspace(page);expect(persisted.characters.find((x:Character)=>x.id===copy.id).runtime.resources['spell-slot:1'].current).toBe(0);expect(persisted.characters.find((x:Character)=>x.id===original.id)).toEqual(original);
});

test('a failed migration save leaves the original active and allows a reviewed retry without duplicates',async({page})=>{
 const c=newCharacter();c.name='保存失败验收';c.selections=[{id:'old',entry:{id:'old',name:'旧法师',english:'Test Mage',kind:'class',source:'IMPORTED',packId:'imported',revision:'0.3',edition:'both',entries:[],raw:{}},level:1,quantity:1,equipped:false}];await load(page,c);
 // This fixture also has pre-existing import hydration: its explicit English
 // identity supplies casting slots. Wait for that save before injecting failure.
 await expect.poll(async()=>{const w=await workspace(page);return w.characters.find((x:Character)=>x.id===w.activeId).runtime.resources['spell-slot:1'];}).toBeDefined();
 await expect(page.locator('.save-status')).toContainText('已保存到本机');const before=await workspace(page);await page.getByRole('button',{name:'核对并同步旧卡',exact:true}).click();const review=page.getByRole('dialog',{name:'旧卡资料同步',exact:true});await review.getByRole('button',{name:'确认并继续',exact:true}).click();
 await page.evaluate(()=>{const original=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(value:any,key?:IDBValidKey){if(key==='workspace'&&value.characters?.some((c:any)=>c.name.endsWith('（资料同步副本）'))){IDBObjectStore.prototype.put=original;this.transaction.abort();throw new DOMException('验收模拟：本机空间不足','QuotaExceededError');}return original.call(this,value,key);};});
 await review.getByRole('button',{name:'创建同步副本',exact:true}).click();await expect(review.getByRole('alert')).toContainText('同步副本保存失败');expect(await workspace(page)).toEqual(before);await expect(page.locator('.startup-panel[role="alert"]')).toHaveCount(0);
 await review.getByRole('button',{name:'创建同步副本',exact:true}).click();await expect(review).toHaveCount(0);await expect(page.locator('.save-status')).toContainText('已保存到本机');const after=await workspace(page);expect(after.characters).toHaveLength(before.characters.length+1);expect(after.characters.find((x:Character)=>x.id===before.activeId)).toEqual(before.characters.find((x:Character)=>x.id===before.activeId));
});
