import {test,expect,type Page} from '@playwright/test';
const visit=(page:Page,mode:string)=>page.goto('/tests/fixtures/manager-recovery/index.html?mode='+mode);
const removeAll=async(page:Page)=>{await page.getByRole('checkbox',{name:'选择当前搜索结果'}).check();await page.getByRole('button',{name:'删除所选',exact:true}).click();await page.getByRole('button',{name:'确认批量删除',exact:true}).click();};
test('partial batch delete closes confirmation and preserves only failed/unattempted selections',async({page})=>{await visit(page,'partial');await removeAll(page);await expect(page.getByRole('button',{name:'确认批量删除',exact:true})).toHaveCount(0);await expect(page.getByRole('checkbox',{name:'选择测试 a',exact:true})).toHaveCount(0);await expect(page.getByRole('checkbox',{name:'选择测试 b',exact:true})).toBeChecked();await expect(page.getByRole('checkbox',{name:'选择测试 c',exact:true})).toBeChecked();await expect(page.getByRole('alert')).toContainText('1');expect(await page.evaluate(()=>(window as any).removeCalls)).toEqual([['a','b','c']]);});
test('uncertain result blocks only affected card, survives reopen and refresh, and needs explicit terminal receipt',async({page})=>{await visit(page,'uncertain');await removeAll(page);const remove=page.getByRole('button',{name:'删除所选',exact:true});await expect(remove).toBeDisabled();await page.getByRole('button',{name:'重新读取目录',exact:true}).click();await expect(remove).toBeDisabled();expect(await page.evaluate(()=>(window as any).refreshCalls)).toBe(1);await page.getByRole('checkbox',{name:'选择测试 b',exact:true}).uncheck();await expect(remove).toBeEnabled();await page.getByRole('button',{name:'切换角色簿',exact:true}).click();await page.getByRole('button',{name:'切换角色簿',exact:true}).click();await page.getByRole('checkbox',{name:'选择测试 b',exact:true}).check();await expect(remove).toBeDisabled();await page.getByRole('button',{name:'明确终态已返回',exact:true}).click();await expect(remove).toBeEnabled();expect(await page.evaluate(()=>(window as any).removeCalls)).toHaveLength(1);});
test('read errors offer a genuinely copyable redacted diagnostic with manual clipboard fallback',async({page},info)=>{await visit(page,'read-error');await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async()=>{throw Error('denied')}}}));await page.getByRole('button',{name:'审卡',exact:true}).first().click();await page.getByRole('button',{name:'复制诊断信息',exact:true}).click();const text=page.getByRole('textbox',{name:'诊断信息',exact:true});await expect(text).toBeVisible();const diagnostic=JSON.parse(await text.inputValue());expect(diagnostic.requestId).toBe('fixture-request');expect(diagnostic.diagnostic.status).toBe(404);expect(await text.inputValue()).not.toMatch(/PRIVATE|private\.invalid|cookie|token|document/);await info.attach('redacted-read-error',{body:await page.screenshot(),contentType:'image/png'});});
test('clipboard success copies the same sanitized text',async({page})=>{await visit(page,'read-error');await page.evaluate(()=>Object.defineProperty(navigator,'clipboard',{configurable:true,value:{writeText:async(text:string)=>{(window as any).copied=text;}}}));await page.getByRole('button',{name:'审卡',exact:true}).first().click();await page.getByRole('button',{name:'复制诊断信息',exact:true}).click();await expect(page.getByRole('button',{name:'已复制',exact:true})).toBeVisible();const text=await page.evaluate(()=>(window as any).copied);expect(JSON.parse(text).diagnostic.status).toBe(404);expect(text).not.toContain('PRIVATE');});
test('read-only rows remain non-deletable and cancelling sends no delete request',async({page})=>{await visit(page,'readonly');await page.getByRole('checkbox',{name:'选择当前搜索结果'}).check();await expect(page.getByRole('button',{name:'删除所选',exact:true})).toBeDisabled();await visit(page,'normal');await page.getByRole('checkbox',{name:'选择当前搜索结果'}).check();await page.getByRole('button',{name:'删除所选',exact:true}).click();await page.getByRole('button',{name:'取消',exact:true}).click();expect(await page.evaluate(()=>(window as any).removeCalls)).toEqual([]);});

test('a pending parent-owned delete stays blocked after dialog reopen until its ACK',async({page})=>{
 await visit(page,'deferred');await removeAll(page);
 await expect(page.getByRole('button',{name:/^测试 a/})).toBeDisabled();
 await expect(page.getByText('有 3 张角色的批量删除正在处理，正在等待宿主确认；请勿重复提交。',{exact:true})).toBeVisible();
 await expect(page.getByText('删除结果尚未确认',{exact:false})).toHaveCount(0);
 await page.getByRole('button',{name:'切换角色簿',exact:true}).click();await page.getByRole('button',{name:'切换角色簿',exact:true}).click();
 await page.getByRole('checkbox',{name:'选择当前搜索结果'}).check();
 await expect(page.getByRole('button',{name:'删除所选',exact:true})).toBeDisabled();
 await expect(page.getByText('可编辑 · 删除处理中',{exact:true})).toHaveCount(3);
 expect(await page.evaluate(()=>(window as any).removeCalls)).toEqual([['a','b','c']]);
 await page.getByRole('button',{name:'完成在途删除',exact:true}).click();
 await expect(page.getByRole('checkbox',{name:'选择测试 a',exact:true})).toHaveCount(0);
 await expect(page.getByText('有 3 张角色的批量删除正在处理，正在等待宿主确认；请勿重复提交。',{exact:true})).toHaveCount(0);
 expect(await page.evaluate(()=>(window as any).removeCalls)).toHaveLength(1);
});
