import {test,expect} from '@playwright/test';
import {mockSource,suppressAnnouncement} from './fixtures';
import {newCharacter} from '../../src/core/model';

// Must run against the integrated build: standalone intentionally removes Suite transport.
test('Suite permission loss hides manual controls and preserves the supplied card',async({page,baseURL})=>{
 await mockSource(page);await suppressAnnouncement(page);await page.goto('/#suite=manual-skills&bridge='+encodeURIComponent(new URL(baseURL!).origin));await expect(page.locator('.app-shell')).toBeVisible();
 const send=async(type:string,data:any={})=>page.evaluate(({type,data})=>window.dispatchEvent(new MessageEvent('message',{origin:location.origin,source:window,data:{protocol:'full-suite-workbench/v1',session:'manual-skills',hostStarted:100,type,...data}})),{type,data});
 await page.evaluate(()=>{(window as any).skillSaves=[];window.addEventListener('message',event=>{if(event.data?.type==='save')(window as any).skillSaves.push(event.data);});});
 const c=newCharacter();c.name='原创技能权限验收';c.proficiencies={arcana:true};c.expertise={stealth:true};c.abilities.dex=18;
 const target={key:'r:card:skills',itemId:'card:skills',cardId:'skills',name:c.name,kind:'character',role:'PLAYER',write:true,documentRevision:1,stats:{},resources:[]};await send('ready');await send('catalog',{sequence:1,role:'PLAYER',cards:[{...target,id:'skills',classSummary:[]}],monsters:[],enabled:{},visibility:{wiki:true,monsters:true},shared:{key:'room:fixture',scope:'room',revision:1,rules:{edition:'2024',profile:c.profile,packs:[],customEntries:[]}}});await send('selection',{sequence:2,state:target,document:{dnd_card_web:c,_suiteRevision:1}});await page.evaluate(()=>window.dispatchEvent(new Event('workbench-show-sheet')));await expect(page.locator('.paper .assign-token-name')).toHaveText(c.name);await expect(page.locator('[aria-label="隐匿专精"]')).toBeVisible();await expect(page.locator('.ability-dex .ability-skill').filter({hasText:'隐匿'}).locator('b')).toHaveText('+8');await page.getByRole('switch',{name:'编辑模式',exact:true}).click();await expect(page.getByRole('textbox',{name:'角色姓名',exact:true})).toHaveValue(c.name);await expect(page.getByRole('checkbox',{name:'隐匿专精',exact:true})).toBeEnabled();await expect(page.getByRole('checkbox',{name:'隐匿专精',exact:true})).toBeChecked();
 await send('catalog',{sequence:3,role:'PLAYER',cards:[{...target,id:'skills',write:false,classSummary:[]}],monsters:[],enabled:{},visibility:{wiki:true,monsters:true}});await send('selection',{sequence:4,state:{...target,write:false},document:{dnd_card_web:c,_suiteRevision:1}});await expect(page.getByRole('switch',{name:'编辑模式',exact:true})).toBeDisabled();await expect(page.locator('.ability-skill input[type=checkbox]')).toHaveCount(0);await expect(page.locator('[aria-label="隐匿专精"]')).toBeVisible();await expect(page.locator('[aria-label="奥秘熟练"]')).toBeVisible();await expect(page.locator('.paper .assign-token-name')).toHaveText(c.name);expect(await page.evaluate(()=>(window as any).skillSaves)).toEqual([]);
});

