import {test,expect,type Page} from '@playwright/test';
test.beforeEach(async({page})=>{page.on('dialog',dialog=>void dialog.accept());});
async function open(page:Page,baseURL:string|undefined){await page.goto('/tests/fixtures/overview-dashboard235/#suite=overview-dashboard235&bridge='+encodeURIComponent(new URL(baseURL!).origin));await expect(page.locator('[data-resource-target="hero"]')).toBeVisible();}
const manage=(page:Page)=>page.getByRole('button',{name:'管理原创资源布局测试资源',exact:true});
const dialog=(page:Page)=>page.getByRole('dialog',{name:'仪表盘',exact:true});
// <output> for content scale also has implicit status role. Target the explicit save receipt.
const saveStatus=(page:Page)=>dialog(page).locator('.dashboard-savebar > [role="status"]');
for(const width of [1100,390])test(`235 ${width}: overview + edits the real dashboard, saves after ACK and preserves concurrent spending`,async({page,baseURL})=>{
 await page.setViewportSize({width,height:950});await open(page,baseURL);const card=page.locator('[data-resource-target="hero"]');await expect(card).not.toContainText('项资源');
 const separators=card.locator('[data-resource-id="spell-slot:1"] .rm-pools-poolpips .rm-pool');await expect(separators).toHaveCount(2);for(const row of await separators.all()){await expect(row).not.toHaveCSS('box-shadow','none');await expect(row).toHaveCSS('border-bottom-width','0px');}
 const focus=card.locator('[data-resource-id="focus"]');await expect(focus.locator('.resource-module-art')).toHaveCSS('--rm-content-scale','1.2');await expect(focus.locator('xpath=../..')).toHaveAttribute('data-grid-x','8');
 await manage(page).click();await expect(dialog(page).getByRole('region',{name:'仪表盘编辑器'})).toBeVisible();await expect(dialog(page).locator('.resource-fixed-attacks')).toHaveCount(0);
 const widget=dialog(page).locator('[data-resource-id="focus"]');await expect(widget).toHaveAttribute('data-grid-x','8');await widget.locator('.resource-widget-face').click();await dialog(page).getByRole('button',{name:'色调 #a36d61',exact:true}).click();await expect(dialog(page).locator('[data-dirty=true]')).toBeVisible();
 await page.evaluate(()=>(window as any).dashboard235.remote());await dialog(page).getByRole('button',{name:'保存布局',exact:true}).click();await expect(saveStatus(page)).toHaveText('已保存布局');
 const saved=await page.evaluate(()=>(window as any).dashboard235.authority());expect(saved.runtime.resources.focus.current).toBe(1);expect(saved.notes).toBe('远端编辑保留');expect(saved.quickbarLayout.widgets.focus.color).toBe('#a36d61');expect(saved.quickbarLayout.widgets.focus.x).toBe(8);
 await dialog(page).getByRole('button',{name:'关闭弹窗',exact:true}).click();await expect(focus.locator('.resource-module-art')).toHaveCSS('--rm-icon-tone','#a36d61');await expect(focus).toHaveAttribute('data-resource-current','1');await page.reload();await expect(focus.locator('.resource-module-art')).toHaveCSS('--rm-icon-tone','#a36d61');
 await manage(page).click();await expect(dialog(page).locator('.resource-dashboard')).toBeVisible();expect(await dialog(page).evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);await page.screenshot({path:test.info().outputPath(`235-overview-dashboard-${width}.png`)});
});
test('235 cancel, failed save and revoked permission keep the authoritative layout intact',async({page,baseURL})=>{
 await open(page,baseURL);const original=await page.evaluate(()=>(window as any).dashboard235.authority());await manage(page).click();await dialog(page).locator('[data-resource-id="focus"] .resource-widget-face').click();await dialog(page).getByRole('button',{name:'色调 #a36d61',exact:true}).click();await page.keyboard.press('Escape');await expect(dialog(page)).toHaveCount(0);expect(await page.evaluate(()=>(window as any).dashboard235.authority())).toEqual(original);
 await manage(page).click();await dialog(page).locator('[data-resource-id="focus"] .resource-widget-face').click();await dialog(page).getByRole('button',{name:'色调 #a36d61',exact:true}).click();await page.evaluate(()=>(window as any).dashboard235.fail());await dialog(page).getByRole('button',{name:'保存布局',exact:true}).click();await expect(saveStatus(page)).toContainText('测试保存失败');await expect(dialog(page).locator('[data-dirty=true]')).toBeVisible();expect(await page.evaluate(()=>(window as any).dashboard235.authority())).toEqual(original);
 await page.evaluate(()=>(window as any).dashboard235.readonly());await expect(dialog(page).getByRole('button',{name:'保存布局',exact:true})).toBeDisabled();await dialog(page).getByRole('button',{name:'关闭弹窗',exact:true}).click();await expect(manage(page)).toBeDisabled();expect((await page.evaluate(()=>(window as any).dashboard235.requests)).filter((r:any)=>r.type==='save')).toHaveLength(1);
});
