import {test,expect} from '@playwright/test';
import {readFileSync} from 'node:fs';
import {mockSource,suppressAnnouncement} from './fixtures';
test('round swatches highlight only on hover; hold previews without writes and releases once',async({page})=>{
 await mockSource(page);await suppressAnnouncement(page);await page.goto('/card/?intro=0');await expect(page.locator('.paper')).toBeVisible();await page.getByRole('button',{name:'调色盘',exact:true}).click();const drawer=page.getByRole('dialog',{name:'调色盘',exact:true});await drawer.getByRole('button',{name:'角色卡组件',exact:true}).click();await drawer.getByRole('navigation',{name:'角色卡配色组件'}).getByRole('button',{name:'六项属性',exact:true}).click();await expect(drawer.locator('select')).toHaveCount(0);
 const swatch=drawer.getByRole('button',{name:'内容底色选色',exact:true}),surface=page.locator('[data-palette-component=abilities] .cell-content').first();await swatch.hover();await expect(page.locator('.palette-highlight-layer>div').first()).toBeVisible();
 const css=await swatch.evaluate(el=>{const s=getComputedStyle(el),r=el.getBoundingClientRect();return {color:s.backgroundColor,radius:s.borderRadius,clip:s.clipPath,width:r.width,height:r.height};});expect(css.radius).toBe('50%');expect(css.clip).toBe('none');expect(css.width).toBe(css.height);expect(css.color).toBe('rgb(232, 232, 232)');
 await drawer.getByText('内容底色',{exact:true}).hover();await expect(page.locator('.palette-highlight-layer')).toHaveCount(0);
 await page.waitForTimeout(700);await page.evaluate(()=>{(window as any).paletteWrites=0;const put=IDBObjectStore.prototype.put;IDBObjectStore.prototype.put=function(value:any,key?:IDBValidKey){if(this.name==='documents'&&key==='workspace')(window as any).paletteWrites++;return put.call(this,value,key);};});
 await swatch.hover();await page.mouse.down();await page.waitForTimeout(360);const picker=page.getByRole('group',{name:'内容底色选色面板'});await expect(picker).toBeVisible();await expect(page.locator('.palette-highlight-layer')).toHaveCount(0);const plane=await picker.locator('.palette-picker-plane').boundingBox();
 await page.mouse.move(plane!.x+plane!.width*.25,plane!.y+plane!.height*.25,{steps:20});await expect(surface).not.toHaveCSS('background-color','rgb(232, 232, 232)');expect(await page.evaluate(()=>(window as any).paletteWrites)).toBe(0);const selected=await surface.evaluate(el=>getComputedStyle(el).backgroundColor);
 await page.mouse.up();await expect(picker).toHaveCount(0);await expect.poll(()=>page.evaluate(()=>(window as any).paletteWrites)).toBe(1);await expect(surface).toHaveCSS('background-color',selected);await page.waitForTimeout(250);expect(await page.evaluate(()=>(window as any).paletteWrites)).toBe(1);
 await swatch.click();await expect(picker).toBeVisible();const box=await picker.locator('.palette-picker-plane').boundingBox();await page.mouse.move(box!.x+20,box!.y+20);await page.mouse.down();await page.mouse.move(box!.x+100,box!.y+100,{steps:10});await page.keyboard.press('Escape');await page.mouse.up();await expect(picker).toHaveCount(0);await expect(surface).toHaveCSS('background-color',selected);expect(await page.evaluate(()=>(window as any).paletteWrites)).toBe(1);
 await page.screenshot({path:test.info().outputPath('palette-round-components.png')});await page.reload();await expect(surface).toHaveCSS('background-color',selected);
});
test('exports and validates imported settings, preserves mechanics, and restores after reload',async({page})=>{
 await mockSource(page);await suppressAnnouncement(page);await page.goto('/card/?intro=0');await expect(page.locator('.paper')).toBeVisible();await page.getByRole('button',{name:'调色盘',exact:true}).click();const drawer=page.getByRole('dialog',{name:'调色盘',exact:true});
 const field=drawer.getByRole('textbox',{name:'页面背景颜色代码'});await field.fill('#CBDBCA');await field.blur();const downloading=page.waitForEvent('download');await drawer.getByRole('button',{name:'保存配色文件'}).click();const download=await downloading;const settings=JSON.parse(readFileSync((await download.path())!,'utf8'));expect(settings.format).toBe('dnd-card-palette');expect(settings.appearance.ui.background).toBe('#CBDBCA');expect(settings.card).toBeDefined();expect(JSON.stringify(settings)).not.toContain('selections');
 const importFile=async(value:any)=>{const choosing=page.waitForEvent('filechooser');await drawer.getByRole('button',{name:'导入配色',exact:true}).click();await (await choosing).setFiles({name:'palette.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(value))});};
 const mechanics=()=>page.evaluate(async()=>{const database=await new Promise<IDBDatabase>((resolve,reject)=>{const request=indexedDB.open('dnd-card-standalone');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});const workspace:any=await new Promise((resolve,reject)=>{const request=database.transaction('documents').objectStore('documents').get('workspace');request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);});database.close();const card={...workspace.characters.find((c:any)=>c.id===workspace.activeId)};for(const key of ['palette','componentPalette','revision','updatedAt'])delete card[key];return card;});await page.waitForTimeout(500);const before=await mechanics();
 await importFile({...settings,appearance:{...settings.appearance,ui:{background:'red'}}});await expect(drawer.getByRole('alert')).toContainText('无效');await expect(page.locator('.app-shell')).toHaveCSS('background-color','rgb(203, 219, 202)');
 await importFile({...settings,appearance:{ui:{background:'#223344'},wiki:{entry:'#BBCDAA'}},card:{palette:{paper:'#CCDDEE'},components:{abilities:{surface:'#BBCCDD'}}}});await expect(page.locator('.app-shell')).toHaveCSS('background-color','rgb(34, 51, 68)');await expect(page.locator('[data-palette-component=abilities] .cell-content').first()).toHaveCSS('background-color','rgb(187, 204, 221)');await page.reload();await expect(page.locator('.app-shell')).toHaveCSS('background-color','rgb(34, 51, 68)');await expect(page.locator('[data-palette-component=abilities] .cell-content').first()).toHaveCSS('background-color','rgb(187, 204, 221)');expect(await mechanics()).toEqual(before);
});
