import {test,expect,type Page} from '@playwright/test';
import {mockSource} from './fixtures';
import {newCharacter} from '../../src/core/model';
async function importCard(page:Page){const c=newCharacter();c.runtime.resources={charge:{name:'能量',type:'count',current:3,max:4}};await page.goto('/');await expect(page.getByRole('button',{name:'更新资料',exact:true})).toBeEnabled();await page.getByRole('button',{name:'导入 / 导出',exact:true}).click();await page.getByTestId('character-file').setInputFiles({name:'portrait-card.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(c))});await page.getByRole('button',{name:'关闭弹窗'}).click();}
test('avatar framing stays bounded on every page; illustration is independent and UI tone leaves paper gray',async({page})=>{
 await mockSource(page);await importCard(page);await page.getByRole('switch',{name:'编辑模式'}).click();
 const data=await page.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=240;canvas.height=320;const ctx=canvas.getContext('2d')!;ctx.fillStyle='#a83d32';ctx.fillRect(0,0,240,320);ctx.fillStyle='#31a88b';ctx.fillRect(60,80,120,160);return canvas.toDataURL().split(',')[1];});
 const upload=async(label:string)=>{const chooser=page.waitForEvent('filechooser');await page.getByRole('button',{name:label,exact:true}).click();await (await chooser).setFiles({name:'picture.png',mimeType:'image/png',buffer:Buffer.from(data,'base64')});};
 await page.locator('.portrait-view').hover();await upload('设置头像');await expect(page.getByAltText('角色头像')).toBeVisible();
 const avatar=await page.getByAltText('角色头像').getAttribute('src');await page.getByRole('button',{name:'移动头像，滚轮缩放'}).hover();await page.mouse.wheel(0,-180);const move=await page.getByRole('button',{name:'移动头像，滚轮缩放'}).boundingBox();await page.mouse.move(move!.x+20,move!.y+20);await page.mouse.down();await page.mouse.move(move!.x+27,move!.y+27,{steps:4});await page.mouse.up();
 let offset:number|undefined;for(const tab of ['主要','特性','法术','背包']){await page.getByRole('tab',{name:tab,exact:true}).click();const image=page.getByAltText('角色头像');await expect(image).toBeVisible();await expect(image).toHaveAttribute('src',avatar!);const info=await image.evaluate(el=>{const image=el as HTMLImageElement,view=image.parentElement!,m=new DOMMatrix(getComputedStyle(image).transform);return {width:view.clientWidth,height:view.clientHeight,imageWidth:image.offsetWidth,imageHeight:image.offsetHeight,left:getComputedStyle(image).left,top:getComputedStyle(image).top,relative:m.e/view.clientWidth};});expect(info.width).toBeGreaterThan(35);expect(info.height).toBeGreaterThan(35);expect(info.imageWidth).toBe(info.width);expect(info.imageHeight).toBe(info.height);expect(info.left).toBe('0px');expect(info.top).toBe('0px');if(offset!==undefined)expect(info.relative).toBeCloseTo(offset,3);offset=info.relative;}
 await page.getByRole('tab',{name:'背景',exact:true}).click();await expect(page.getByAltText('角色头像')).toHaveCount(0);await expect(page.getByAltText('角色立绘')).toHaveCount(0);await page.locator('.illustration-cell').hover();await upload('设置立绘');await expect(page.getByAltText('角色立绘')).toBeVisible();await page.reload();await page.getByRole('tab',{name:'背景',exact:true}).click();await expect(page.getByAltText('角色立绘')).toBeVisible();await page.getByRole('tab',{name:'主要',exact:true}).click();await expect(page.getByAltText('角色头像')).toHaveAttribute('src',avatar!);
 await page.evaluate(()=>document.documentElement.style.setProperty('--suite-tone','#0088ff'));await expect(page.locator('.paper')).toHaveCSS('--paper-heading','#7c7c7c');await expect(page.locator('.paper')).toHaveCSS('--paper-frame','#595959');await expect(page.locator('.paper')).toHaveCSS('--suite-tone','#595959');
 await expect(page.locator('.quickbar-resources .console-resource')).toHaveCSS('border-radius','0px');await expect(page.locator('.quickbar-resources .resource-pip').first()).toHaveCSS('width','14px');await page.screenshot({path:'test-results/presentation-175.png',fullPage:true});
});
