import {test,expect,type Page} from '@playwright/test';
import {mockSource,suppressAnnouncement} from './fixtures';
import {newCharacter,type Entry} from '../../src/core/model';
async function load(page:Page,profile?:{resources:number;selections:number;catalog:number}){const c=newCharacter();c.name='仪表盘测试角色';c.quickbarActions=[{id:'test-sword',name:'测试长剑',attack:'+5',damage:'1d8+3'}];c.runtime.resources={action:{name:'动作如潮',current:2,max:4,type:'count'},hope:{name:'希望',current:3,max:5,type:'count'},'spell-slot:1':{name:'1环法术位',current:3,max:4,type:'count'},'spell-slot:2':{name:'2环法术位',current:2,max:3,type:'count'},'pact-slot:2':{name:'契约法术位',current:1,max:2,type:'count'}};c.spellSettings={ability:'int',attackBonus:0,dcBonus:0,mode:'prepared',capacity:0,prepared:[],slots:{'1':{max:4,used:1},'2':{max:3,used:1}}};if(profile){for(let i=5;i<profile.resources;i++)c.runtime.resources[`authored-${i}`]={name:`原创性能资源 ${i}`,current:2,max:5};c.selections=Array.from({length:profile.selections},(_,i)=>({id:`diagnostic-selection-${i}`,quantity:1,level:1,equipped:false,entry:{id:`diagnostic-entry-${i}`,kind:'feature',name:`原创诊断特性 ${i}`,english:`Authored diagnostic feature ${i}`,source:'XPHB',edition:'2024',packId:'fixture',revision:'1',entries:Array.from({length:20},(_,n)=>`原创性能条目 ${i} 内容 ${n}，用于衡量大角色卡克隆和渲染，不带自动化。`),raw:{}} as Entry}));}
 const characterBytes=Buffer.byteLength(JSON.stringify(c));let catalogResponses=0;
 await mockSource(page);if(profile)await page.route('**/data/spells/spells-test.json',async route=>{catalogResponses++;await route.fulfill({json:{spell:Array.from({length:profile.catalog},(_,i)=>({name:`原创仪表盘资料 ${i}`,ENG_name:`Authored dashboard catalog ${i}`,source:'XPHB',level:i%10,entries:['原创性能数据，不包含出版物或私人角色资料。']}))},headers:{'access-control-allow-origin':'*'}});});await suppressAnnouncement(page);await page.goto('/');await expect(page.getByRole('button',{name:'更新资料',exact:true})).toBeEnabled();await page.getByRole('button',{name:'导入 / 导出',exact:true}).click();await page.getByTestId('character-file').setInputFiles({name:'仪表盘测试角色.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(c))});await page.getByRole('button',{name:'关闭弹窗'}).click();if(profile)await expect.poll(()=>catalogResponses).toBeGreaterThan(0);return {characterBytes,selections:c.selections.length,resources:Object.keys(c.runtime.resources).length,catalogEntriesServed:profile?.catalog??null,catalogResponses};}
test('real App opens the full editor from its heading and retains manual styling and resources across reload',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await load(page);
 const open=page.getByRole('button',{name:'打开快捷栏编辑器',exact:true});await open.click();const dialog=page.getByRole('dialog',{name:'仪表盘',exact:true});await expect(dialog).toBeVisible();
 await expect(dialog.locator('[data-template-id=pool]')).toHaveCount(0);await expect(dialog.locator('[data-template-id=matrix]')).toBeEnabled();await expect(dialog.locator('.resource-page-nav')).toHaveCount(0);
 await dialog.locator('[data-template-id=matrix]').click();const selected=dialog.locator('.resource-widget[data-selected=true]');await expect(selected).toHaveCount(1);await expect(selected.locator('.resource-widget-handle')).toHaveCount(8);const id=await selected.getAttribute('data-resource-id');
 await dialog.getByRole('button',{name:'色调 #a36d61',exact:true}).click();await dialog.getByRole('button',{name:'图标 火焰',exact:true}).click();await expect(dialog.locator('.resource-editor-form')).toHaveCount(1);await dialog.getByRole('textbox',{name:'资源名称',exact:true}).fill('火焰充能');await dialog.getByRole('button',{name:'保存',exact:true}).click();
 await dialog.getByRole('button',{name:'新模块',exact:true}).click();await dialog.getByLabel('新模块名称',{exact:true}).fill('测试大额资源');await dialog.getByLabel('新模块上限',{exact:true}).fill('1000');await dialog.getByLabel('新模块当前值',{exact:true}).fill('750');await expect(dialog.locator('[data-template-id=matrix]')).toHaveCount(0);await dialog.locator('[data-template-id=ring]').click();
 await expect(dialog.locator('[data-resource-name="测试大额资源"] [data-module-style=ring]')).toHaveCount(1);await dialog.getByRole('button',{name:'保存布局',exact:true}).click();await dialog.getByRole('button',{name:'关闭弹窗'}).click();await page.reload();await open.click();await expect(dialog).toBeVisible();
 const restored=dialog.locator(`[data-resource-id="${id}"] .resource-module-art`);await restored.scrollIntoViewIfNeeded();await expect(restored).toContainText('火焰充能');expect(await restored.evaluate(el=>getComputedStyle(el).getPropertyValue('--rm-icon-tone').trim())).toBe('#a36d61');
 await expect(dialog.locator('[data-resource-name="测试大额资源"]')).toHaveAttribute('data-resource-current','750');await page.screenshot({path:test.info().outputPath('dashboard-real-app.png')});expect(errors).toEqual([]);
});
test('single resource settings, independent pools and mobile editor stay reachable without pagination',async({page})=>{
 await load(page);const main=page.locator('.paper .resource-workspace');await main.locator('[data-resource-id="action"] .resource-widget-face').click();const operation=page.getByRole('dialog',{name:'动作如潮资源操作',exact:true});await expect(operation).toBeVisible();await operation.getByRole('button',{name:'设置动作如潮',exact:true}).click();const config=page.getByRole('dialog',{name:'资源配置',exact:true});await expect(config.getByRole('textbox',{name:'资源名称'})).toHaveValue('动作如潮');await expect(config.locator('.resource-editor-form')).toHaveCount(1);await config.getByRole('button',{name:'关闭弹窗'}).click();
 await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'打开快捷栏编辑器',exact:true}).click();const dialog=page.getByRole('dialog',{name:'仪表盘',exact:true});await expect(dialog.locator('[data-template-id=matrix]')).toHaveCount(1);await expect(dialog.locator('[data-template-id=pool]')).toHaveCount(0);await expect(dialog.locator('.resource-page-nav')).toHaveCount(0);
 for(const id of ['action','hope','spell-slot:1','pact-slot:2']){const module=dialog.locator(`[data-resource-id="${id}"]`);await module.scrollIntoViewIfNeeded();await expect(module).toBeVisible();}
 expect(await dialog.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);expect(await dialog.locator('.resource-widget-scroll').evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);await page.screenshot({path:test.info().outputPath('dashboard-real-app-narrow.png')});
});

for(const profile of [{name:'small',resources:5,selections:20,catalog:100},{name:'large',resources:100,selections:200,catalog:10000}])test(`production dashboard diagnostic: ${profile.name} cold and warm browser work`,async({page},info)=>{
 test.skip(info.project.name!=='dashboard-production','Use feedback217 dashboard-production project so diagnostics measure a built App, not the dev server.');
 const errors:string[]=[];page.on('pageerror',error=>errors.push(error.message));const fixture=await load(page,profile);await expect(page.locator('.save-status')).toContainText('已保存到本机');
 expect(await page.evaluate(()=>[...document.scripts].some(script=>script.src.includes('/@vite/client')))).toBe(false);
 const before=await page.evaluate(async()=>{const request=indexedDB.open('dnd-card-standalone');await new Promise<void>(resolve=>request.onsuccess=()=>resolve());const db=request.result;try{return await new Promise<string>(resolve=>{const read=db.transaction('documents').objectStore('documents').get('workspace');read.onsuccess=()=>{const workspace=read.result,character=workspace.characters.find((c:any)=>c.id===workspace.activeId);resolve(JSON.stringify({resources:character.runtime.resources,quickbarLayout:character.quickbarLayout}));};});}finally{db.close();}});
 const measurements:any[]=[];const dialog=page.getByRole('dialog',{name:'仪表盘',exact:true});
 for(let index=0;index<3;index++){
  await page.evaluate(()=>{
   const state:any=(window as any).__dashboardOpening={armedAt:performance.now(),pointerdown:null,click:null,domReady:null,paintOpportunity:null,longtasks:[],supportedLongtasks:PerformanceObserver.supportedEntryTypes.includes('longtask')};
   const isHeading=(event:Event)=>(event.target as Element)?.closest('[aria-label="打开快捷栏编辑器"]');
   const pointer=(event:Event)=>{if(isHeading(event)&&state.pointerdown===null)state.pointerdown=performance.now();};
   const click=(event:Event)=>{if(isHeading(event)&&state.click===null)state.click=performance.now();};
   document.addEventListener('pointerdown',pointer,true);document.addEventListener('click',click,true);
   const longtask=state.supportedLongtasks?new PerformanceObserver(list=>state.longtasks.push(...list.getEntries().map(entry=>({start:entry.startTime,duration:entry.duration})))):null;longtask?.observe({type:'longtask',buffered:false});
   const mutations=new MutationObserver(()=>{
    const gallery=document.querySelector('.resource-dashboard .resource-template-option');
    if(state.pointerdown===null||state.domReady!==null||!gallery?.getClientRects().length)return;
    state.domReady=performance.now();requestAnimationFrame(()=>requestAnimationFrame(()=>{state.paintOpportunity=performance.now();mutations.disconnect();document.removeEventListener('pointerdown',pointer,true);document.removeEventListener('click',click,true);}));
   });mutations.observe(document.body,{childList:true,subtree:true,attributes:true,attributeFilter:['open','hidden']});
   state.cleanup=()=>{mutations.disconnect();document.removeEventListener('pointerdown',pointer,true);document.removeEventListener('click',click,true);if(longtask){state.longtasks.push(...longtask.takeRecords().map(entry=>({start:entry.startTime,duration:entry.duration})));longtask.disconnect();}};
  });
  await page.getByRole('button',{name:'打开快捷栏编辑器',exact:true}).click();
  await expect.poll(()=>page.evaluate(()=>(window as any).__dashboardOpening.paintOpportunity)).not.toBeNull();
  const measured=await page.evaluate(()=>{
   const state=(window as any).__dashboardOpening;state.cleanup();const start=state.pointerdown,end=state.paintOpportunity;
   const scripts=(performance.getEntriesByType('resource') as PerformanceResourceTiming[]).filter(entry=>entry.startTime>=start&&entry.startTime<=end&&(/\.m?js(?:\?|$)/.test(entry.name)||entry.initiatorType==='script')).map(entry=>({url:new URL(entry.name).pathname,start:entry.startTime-start,responseEnd:entry.responseEnd-start,duration:entry.duration,transferSize:entry.transferSize,encodedBodySize:entry.encodedBodySize,decodedBodySize:entry.decodedBodySize}));
   const longtasks=state.longtasks.filter((entry:any)=>entry.start+entry.duration>start&&entry.start<end).map((entry:any)=>({start:entry.start-start,duration:entry.duration,overlap:Math.max(0,Math.min(end,entry.start+entry.duration)-Math.max(start,entry.start))}));
   const lastScriptEnd=scripts.length?Math.max(...scripts.map(entry=>entry.responseEnd)):null;
   return {automationBeforePointerdown:state.pointerdown-state.armedAt,pointerdownToClick:state.click-state.pointerdown,clickToGalleryDOM:state.domReady-state.click,pointerdownToGalleryDOM:state.domReady-start,pointerdownToPaintOpportunity:end-start,DOMToPaintOpportunity:end-state.domReady,scriptResources:scripts,postLastScriptResponseToDOM:lastScriptEnd===null?null:Math.max(0,state.domReady-start-lastScriptEnd),longtasksSupported:state.supportedLongtasks,longtasks,longtaskOverlap:longtasks.reduce((sum:number,entry:any)=>sum+entry.overlap,0),renderedModules:document.querySelectorAll('.resource-dashboard .resource-widget').length,galleryCandidates:document.querySelectorAll('.resource-dashboard .resource-template-option').length};
  });
  expect(measured.pointerdownToGalleryDOM).toBeGreaterThanOrEqual(0);expect(measured.pointerdownToPaintOpportunity).toBeGreaterThanOrEqual(measured.pointerdownToGalleryDOM);expect(measured.renderedModules).toBeGreaterThan(0);expect(measured.galleryCandidates).toBeGreaterThan(0);measurements.push({phase:index===0?'cold':'warm',...measured});
  await dialog.getByRole('button',{name:'关闭弹窗',exact:true}).click();await expect(dialog).toBeHidden();
 }
 const after=await page.evaluate(async()=>{const request=indexedDB.open('dnd-card-standalone');await new Promise<void>(resolve=>request.onsuccess=()=>resolve());const db=request.result;try{return await new Promise<string>(resolve=>{const read=db.transaction('documents').objectStore('documents').get('workspace');read.onsuccess=()=>{const workspace=read.result,character=workspace.characters.find((c:any)=>c.id===workspace.activeId);resolve(JSON.stringify({resources:character.runtime.resources,quickbarLayout:character.quickbarLayout}));};});}finally{db.close();}});
 expect(after).toBe(before);expect(errors).toEqual([]);
 const report={unit:'ms',build:'production standalone',profile:profile.name,fixture,cpuThrottle:1,network:'local preview server, new browser context; warm reopens retain cache',semantics:{start:'captured browser pointerdown, excluding preceding Playwright auto-wait',DOM:'MutationObserver first visible gallery',paint:'second requestAnimationFrame opportunity, not proof of compositor presentation',parse:'not separately observable; postLastScriptResponseToDOM includes remaining import/evaluation/render work and is not a parse duration',longtasks:'observed tasks over 50ms, overlap bounded to pointerdown-to-paint window'},measurements};
 await info.attach('dashboard-production-opening',{body:JSON.stringify(report,null,2),contentType:'application/json'});console.log('DASHBOARD_PRODUCTION_OPENING',JSON.stringify(report));
});

test('237 real App keeps a failed local dashboard save dirty and retries the same draft',async({page})=>{
 await load(page);await page.getByRole('button',{name:'打开快捷栏编辑器',exact:true}).click();const dialog=page.getByRole('dialog',{name:'仪表盘',exact:true});await expect(dialog.locator('.resource-dashboard')).toBeVisible();await dialog.locator('[data-resource-id="action"] .resource-widget-face').click();await dialog.getByLabel('模块描边粗细',{exact:true}).fill('2');
 await page.evaluate(()=>{const original=IDBObjectStore.prototype.put;(window as any).rejectDashboardSave=true;IDBObjectStore.prototype.put=function(value,key){if((window as any).rejectDashboardSave&&this.name==='documents'&&key==='workspace'){this.transaction.abort();throw new DOMException('authored dashboard quota failure','QuotaExceededError');}return original.call(this,value,key);};});
 await dialog.getByRole('button',{name:'保存布局',exact:true}).click();await expect(dialog.locator('.dashboard-savebar > [role=status]')).toContainText('authored dashboard quota failure');await expect(dialog.locator('.resource-dashboard')).toHaveAttribute('data-dirty','true');page.once('dialog',confirmation=>void confirmation.dismiss());await page.keyboard.press('Escape');await expect(dialog).toBeVisible();await expect(dialog.getByLabel('模块描边粗细',{exact:true})).toHaveValue('2');
 await page.evaluate(()=>(window as any).rejectDashboardSave=false);await dialog.getByRole('button',{name:'保存布局',exact:true}).click();await expect(dialog.locator('.dashboard-savebar > [role=status]')).toHaveText('已保存布局');await dialog.getByRole('button',{name:'关闭弹窗',exact:true}).click();await page.reload();await page.getByRole('button',{name:'打开快捷栏编辑器',exact:true}).click();await expect(dialog.locator('[data-resource-id="action"] .resource-module-art')).toHaveCSS('border-top-width','2px');
});
