import {test,expect} from '@playwright/test';
import {mockSource} from './fixtures';import {newCharacter} from '../../src/core/model';
import {resourceWidgetLayout} from '../../src/core/resourceWidgets';
test('actual A4 resource styles, resize, spend, refresh keep presentation separate',async({page})=>{
 await mockSource(page);await page.goto('/');await expect(page.getByRole('button',{name:'更新资料',exact:true})).toBeEnabled();
 const c=newCharacter();c.name='模块验收·原创角色';c.quickbarActions=['长剑','短弓','冰霜射线','灵刃'].map((name,i)=>({id:String(i),name,attack:'+5',damage:'1d8+3'}));
 c.runtime.resources=Object.fromEntries(Array.from({length:12},(_,i)=>['r'+i,{name:i===0?'晨星印记':i===1?'长名资源·银色黎明的祝福':'原创资源'+i,current:3,max:5,type:'number'}]));c.quickbarLayout={order:[],hidden:[],widgets:resourceWidgetLayout(Object.keys(c.runtime.resources))};
 await page.getByRole('button',{name:'导入 / 导出',exact:true}).click();await page.getByTestId('character-file').setInputFiles({name:'original-widget.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(c))});await page.getByRole('button',{name:'关闭弹窗'}).click();
 await expect(page.locator('.resource-widget')).toHaveCount(9);await page.screenshot({path:test.info().outputPath('actual-a4-default.png'),fullPage:true});await page.locator('.resource-diy-quickbar').screenshot({path:test.info().outputPath('actual-quickbar-default.png')});await page.getByRole('switch',{name:'编辑模式',exact:true}).click();await page.getByRole('button',{name:'管理资源',exact:true}).click();await page.locator('.resource-management-item').filter({hasText:'晨星印记'}).locator('summary').click();const editor=page.locator('.resource-management-item').filter({hasText:'晨星印记'});await editor.getByRole('button',{name:'圆环'}).click();await editor.getByRole('button',{name:'保存',exact:true}).click();await page.getByRole('button',{name:'关闭弹窗'}).click();
 await expect(page.locator('[data-resource-id="r0"]')).toHaveClass(/widget-ring/);const mover=page.locator('[data-resource-id="r0"] .resource-widget-move');await mover.focus();await mover.press('ArrowRight');await mover.press('Shift+ArrowDown');await expect(page.locator('[data-resource-id="r0"]')).toHaveCSS('left',/./);const bounds=()=>page.locator('[data-resource-id="r0"]').evaluate(el=>{const s=(el as HTMLElement).style;return {x:s.left,y:s.top,w:s.width,h:s.height};});const persistedBounds=await bounds();
 await page.screenshot({path:test.info().outputPath('actual-a4-editing.png'),fullPage:true});await page.getByRole('switch',{name:'编辑模式',exact:true}).click();await page.locator('[data-resource-id="r0"] .resource-widget-face').click();await page.getByRole('button',{name:'消耗晨星印记',exact:true}).click();await expect(page.locator('[data-resource-id="r0"]')).toHaveAttribute('data-resource-current','2');await page.getByRole('button',{name:'关闭资源操作',exact:true}).click();await page.reload();await expect(page.locator('[data-resource-id="r0"]')).toHaveClass(/widget-ring/);expect(await bounds()).toEqual(persistedBounds);await expect(page.locator('[data-resource-id="r0"]')).toHaveAttribute('data-resource-current','2');
 await page.screenshot({path:test.info().outputPath('actual-a4.png'),fullPage:true});await page.locator('.resource-diy-quickbar').screenshot({path:test.info().outputPath('actual-quickbar.png')});
 const geometry=await page.locator('.resource-workspace').evaluate(el=>({h:el.clientHeight,sh:el.scrollHeight,w:el.clientWidth,sw:el.scrollWidth}));expect(geometry.sh).toBeLessThanOrEqual(geometry.h+1);expect(geometry.sw).toBeLessThanOrEqual(geometry.w+1);
});

test('all eight handles, cancellation, pagination and touch use the real fixed-size widget component',async({page,browser})=>{
 await page.goto('/tests/fixtures/resource-widgets/index.html');await expect(page.locator('.resource-widget')).toHaveCount(9);
 const read=async()=>JSON.parse((await page.locator('#fixture-data').textContent())!);
 for(const handle of ['nw','n','ne','e','se','s','sw','w']){
  await page.evaluate(()=>{const c=JSON.parse(localStorage.getItem('widget-fixture')||document.querySelector('#fixture-data')!.textContent!);c.runtime.resources={probe:{name:'缩放样本',current:2,max:5,type:'number'}};c.quickbarLayout={order:[],hidden:[],widgets:{probe:{x:4,y:2,w:4,h:2,page:0,style:'bar'}}};localStorage.setItem('widget-fixture',JSON.stringify(c));});
  await page.reload();await page.getByRole('button',{name:'编辑布局',exact:true}).click();await page.locator('.resource-widget-move').focus();
  const box=(await page.locator('.resource-widget-canvas').boundingBox())!,grip=(await page.locator('.handle-'+handle).boundingBox())!;
  await page.mouse.move(grip.x+grip.width/2,grip.y+grip.height/2);await page.mouse.down();await page.mouse.move(grip.x+grip.width/2+(handle.includes('w')?-box.width/12:handle.includes('e')?box.width/12:0),grip.y+grip.height/2+(handle.includes('n')?-box.height/6:handle.includes('s')?box.height/6:0),{steps:4});await page.mouse.up();
  const w=(await read()).quickbarLayout.widgets.probe;expect(w).not.toEqual({x:4,y:2,w:4,h:2,page:0,style:'bar'});expect(w.x+w.w).toBeLessThanOrEqual(12);expect(w.y+w.h).toBeLessThanOrEqual(6);expect((await read()).runtime.resources.probe.current).toBe(2);
 }
 const before=(await read()).quickbarLayout;const move=(await page.locator('.resource-widget-move').boundingBox())!;await page.mouse.move(move.x+move.width/2,move.y+move.height/2);await page.mouse.down();await page.mouse.move(move.x+50,move.y+20);await page.keyboard.press('Escape');await page.mouse.up();expect((await read()).quickbarLayout).toEqual(before);
 const context=await browser.newContext({viewport:{width:375,height:550},hasTouch:true,isMobile:true});const touch=await context.newPage();await touch.goto('/tests/fixtures/resource-widgets/index.html');await touch.locator('[data-resource-id="r3"] .resource-widget-face').tap();await touch.getByRole('button',{name:'恢复专注',exact:true}).tap();await touch.getByRole('button',{name:'关闭资源操作',exact:true}).tap();await expect(touch.locator('[data-resource-id="r3"]')).toHaveAttribute('data-resource-current','4');await touch.getByRole('button',{name:'下一页资源'}).tap();await expect(touch.locator('.resource-widget')).toHaveCount(3);const geometry=await touch.locator('.resource-workspace').evaluate(el=>({h:el.clientHeight,sh:el.scrollHeight,w:el.clientWidth,sw:el.scrollWidth}));expect(geometry.sh).toBeLessThanOrEqual(geometry.h+1);expect(geometry.sw).toBeLessThanOrEqual(geometry.w+1);await context.close();
});
