import {test,expect,type Page} from '@playwright/test';
import {mockSource,suppressAnnouncement} from './fixtures';
import {newCharacter} from '../../src/core/model';
async function load(page:Page){const c=newCharacter();c.name='仪表盘测试角色';c.quickbarActions=[{id:'test-sword',name:'测试长剑',attack:'+5',damage:'1d8+3'}];c.runtime.resources={action:{name:'动作如潮',current:2,max:4,type:'count'},hope:{name:'希望',current:3,max:5,type:'count'},'spell-slot:1':{name:'1环法术位',current:3,max:4,type:'count'},'spell-slot:2':{name:'2环法术位',current:2,max:3,type:'count'},'pact-slot:2':{name:'契约法术位',current:1,max:2,type:'count'}};c.spellSettings={ability:'int',attackBonus:0,dcBonus:0,mode:'prepared',capacity:0,prepared:[],slots:{'1':{max:4,used:1},'2':{max:3,used:1}}};await mockSource(page);await suppressAnnouncement(page);await page.goto('/');await expect(page.getByRole('button',{name:'更新资料',exact:true})).toBeEnabled();await page.getByRole('button',{name:'导入 / 导出',exact:true}).click();await page.getByTestId('character-file').setInputFiles({name:'仪表盘测试角色.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(c))});await page.getByRole('button',{name:'关闭弹窗'}).click();}
test('real App opens the full editor from its heading and retains manual styling and resources across reload',async({page})=>{
 const errors:string[]=[];page.on('pageerror',e=>errors.push(e.message));await load(page);
 const open=page.getByRole('button',{name:'打开快捷栏编辑器',exact:true});await open.click();const dialog=page.getByRole('dialog',{name:'仪表盘',exact:true});await expect(dialog).toBeVisible();
 await expect(dialog.locator('[data-template-id=pool]')).toHaveCount(0);await expect(dialog.locator('[data-template-id=matrix]')).toBeEnabled();await expect(dialog.locator('.resource-page-nav')).toHaveCount(0);
 await dialog.locator('[data-template-id=matrix]').click();const selected=dialog.locator('.resource-widget[data-selected=true]');await expect(selected).toHaveCount(1);await expect(selected.locator('.resource-widget-handle')).toHaveCount(8);const id=await selected.getAttribute('data-resource-id');
 await dialog.getByRole('button',{name:'色调 #a36d61',exact:true}).click();await dialog.getByRole('button',{name:'图标 火焰',exact:true}).click();await expect(dialog.locator('.resource-editor-form')).toHaveCount(1);await dialog.getByRole('textbox',{name:'资源名称',exact:true}).fill('火焰充能');await dialog.getByRole('button',{name:'保存',exact:true}).click();
 await dialog.getByRole('button',{name:'新模块',exact:true}).click();await dialog.getByLabel('新模块名称',{exact:true}).fill('测试大额资源');await dialog.getByLabel('新模块上限',{exact:true}).fill('1000');await dialog.getByLabel('新模块当前值',{exact:true}).fill('750');await expect(dialog.locator('[data-template-id=matrix]')).toHaveCount(0);await dialog.locator('[data-template-id=ring]').click();
 await expect(dialog.locator('[data-resource-name="测试大额资源"] [data-module-style=ring]')).toHaveCount(1);await dialog.getByRole('button',{name:'保存布局',exact:true}).click();await dialog.getByRole('button',{name:'关闭弹窗'}).click();await page.reload();await open.click();await expect(dialog).toBeVisible();
 const restored=dialog.locator(`[data-resource-id="${id}"] .resource-module-art`);await restored.scrollIntoViewIfNeeded();await expect(restored).toContainText('火焰充能');expect(await restored.evaluate(el=>getComputedStyle(el).getPropertyValue('--rm-icon-tone').trim())).toBe('#a36d61');
 await expect(dialog.locator('[data-resource-name="测试大额资源"]')).toHaveAttribute('data-resource-current','750');await page.screenshot({path:test.info().outputPath('dashboard-real-app.png')});expect(errors).toEqual([]);
});
test('single resource settings, independent pools and mobile editor stay reachable without pagination',async({page})=>{
 await load(page);const main=page.locator('.paper .resource-workspace');await main.locator('[data-resource-id="action"] .resource-widget-face').click();const operation=page.getByRole('dialog',{name:'动作如潮资源操作',exact:true});await expect(operation).toBeVisible();await operation.getByRole('button',{name:'设置动作如潮',exact:true}).click();const config=page.getByRole('dialog',{name:'资源配置',exact:true});await expect(config.getByRole('textbox',{name:'资源名称'})).toHaveValue('动作如潮');await expect(config.locator('.resource-editor-form')).toHaveCount(1);await config.getByRole('button',{name:'关闭弹窗'}).click();
 await page.setViewportSize({width:390,height:844});await page.getByRole('button',{name:'打开快捷栏编辑器',exact:true}).click();const dialog=page.getByRole('dialog',{name:'仪表盘',exact:true});await expect(dialog.locator('[data-template-id=matrix]')).toHaveCount(1);await expect(dialog.locator('[data-template-id=pool]')).toHaveCount(0);await expect(dialog.locator('.resource-page-nav')).toHaveCount(0);
 for(const id of ['action','hope','spell-slot:1','pact-slot:2']){const module=dialog.locator(`[data-resource-id="${id}"]`);await module.scrollIntoViewIfNeeded();await expect(module).toBeVisible();}
 expect(await dialog.evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);expect(await dialog.locator('.resource-widget-scroll').evaluate(el=>el.scrollWidth<=el.clientWidth+1)).toBe(true);await page.screenshot({path:test.info().outputPath('dashboard-real-app-narrow.png')});
});

test('records cold and warm editor opening times without claiming an unmeasured performance target',async({page},info)=>{
 await load(page);const timings:number[]=[];const dialog=page.getByRole('dialog',{name:'仪表盘',exact:true});
 for(let i=0;i<3;i++){const start=await page.evaluate(()=>performance.now());await page.getByRole('button',{name:'打开快捷栏编辑器',exact:true}).click();await expect(dialog.locator('.resource-template-option').first()).toBeVisible();const end=await page.evaluate(async()=>{await new Promise(requestAnimationFrame);await new Promise(requestAnimationFrame);return performance.now();});timings.push(end-start);await dialog.getByRole('button',{name:'关闭弹窗',exact:true}).click();await expect(dialog).toBeHidden();}
 const report={unit:'ms',scope:'Imported fixture character, click through gallery and two animation frames',cold:timings[0],warm:timings.slice(1)};await info.attach('dashboard-opening-timing',{body:JSON.stringify(report,null,2),contentType:'application/json'});console.log('DASHBOARD_OPENING_TIMING',JSON.stringify(report));
});
