 import React from 'react';import {createRoot} from 'react-dom/client';import {DMConsole} from '../../src/ui/WorkbenchConsole.tsx';import {ResourceRow} from '../../src/ui/ResourceRow.tsx';import {EntryDragProvider,EntryDraggable} from '../../src/ui/DragEntry.tsx';import {newCharacter} from '../../src/core/model.ts';
 const condition={id:'poisoned',name:'中毒',english:'Poisoned',kind:'condition',source:'XPHB',edition:'both',packId:'core',revision:'1',entries:['受毒素影响'],raw:{}};
 createRoot(document.getElementById('test-root')).render(React.createElement(EntryDragProvider,{character:newCharacter(),receive:()=>{}},React.createElement(EntryDraggable,{entry:condition,id:'wiki-condition'},'中毒条目'),React.createElement(DMConsole,{navigate:()=>{}}),React.createElement('div',{className:'paper',style:{width:'320px',minWidth:0,height:'auto',marginTop:'20px'}},React.createElement('div',{className:'quickbar-resources'},...[{name:'生命骰',type:'count',current:2,max:3},{name:'法术位',type:'count',current:2,max:2},{name:'魔法点',type:'number',current:6,max:12}].map(resource=>React.createElement('div',{className:'quick-resource',key:resource.name},React.createElement(ResourceRow,{resource,enabled:true,gm:true,change:async()=>{}})))))));
 window.requests=[];window.emit=(type,rest={})=>window.dispatchEvent(new MessageEvent('message',{source:window,origin:location.origin,data:{protocol:'full-suite-workbench/v1',session:'resources179',type,...rest}}));
 let sequence=1;const history=new Map();
 window.reply=request=>{
  if(request.type!=='condition'){window.emit('ack',{requestId:request.requestId,ok:true,result:{}});return;}
  const before=structuredClone(window.cards),find=id=>window.cards.find(card=>`card:${card.id}`===id),card=find(request.itemId),condition=request.condition;
  if(request.action==='history'){const saved=history.get(request.reference);if(saved)window.cards=structuredClone(saved);}
  else if(card){if(request.action==='add'){if(!card.conditions.some(row=>row.id===condition.id))card.conditions.push(condition);}else card.conditions=card.conditions.filter(row=>row.id!==condition.id);if(request.action==='transfer'){const target=find(request.to);if(target&&!target.conditions.some(row=>row.id===condition.id))target.conditions.push(condition);}}
  const reference=crypto.randomUUID();history.set(reference,before);const result={historyId:reference,undo:{itemId:request.itemId,action:'history',reference},snapshots:window.cards.map(card=>({sequence:++sequence,state:{...card,key:`room:card:${card.id}`,cardId:card.id,role:'GM',pinned:false,slug:''}}))};
  window.emit('ack',{requestId:request.requestId,ok:true,result});
 };
 window.addEventListener('message',event=>{if(event.source!==window||!event.data.requestId||event.data.type==='ack')return;window.requests.push(event.data);if(event.data.type==='condition'&&window.holdCondition){window.held=event.data;return;}window.reply(event.data);});
 window.cards=['艾拉','布莱恩','凯瑟琳'].map((name,index)=>({id:'hero'+index,itemId:'token'+index,kind:'character',name,player:'玩家 '+(index+1),locked:false,write:true,inScene:true,conditions:index===0?[{id:'prone',name:'倒地'},{id:'charmed',name:'魅惑'}]:index===1?[{id:'petrified',name:'石化'},{id:'frightened',name:'恐慌'}]:[],resources:[{id:'a',name:'生命骰',type:'count',current:2,max:3},{id:'b',name:'二环法术位',type:'count',current:2,max:2},{id:'c',name:'魔法能量',type:'number',current:6,max:12},{id:'d',name:'旅途补给',type:'bar',current:3,max:10}],stats:{health:16,'max health':24,'temporary health':3,'armor class':16},passive:14,coins:{gp:12}}));
 window.refresh=(role='GM')=>window.emit('catalog',{sequence:++sequence,role,enabled:{inventory:false},cards:window.cards,monsters:[]});
 window.emit('ready');window.refresh();
