import {test,expect,type Page} from '@playwright/test';
const output='F:/CodexWork/2026-09-20/w-xu/tests180-resources';
async function harness(page:Page){
 page.on('pageerror',error=>console.log('HARNESS',error.message));
 await page.route('**/resources179-harness',route=>route.fulfill({contentType:'text/html',body:`<!doctype html><html><head><meta charset="utf-8">${['style','workspace','workbench','overview','library','cardAtmosphere','libraryRefine','characterPages','suiteTheme','responsive176','responsive177'].map(name=>`<link rel="stylesheet" href="/src/ui/${name}.css">`).join('')}<style>body{height:auto;overflow:auto}#test-root{width:100%;padding:16px;box-sizing:border-box}.dm-console{overflow:visible}</style></head><body><div id="test-root"></div><script type="module">import RefreshRuntime from '/@react-refresh';RefreshRuntime.injectIntoGlobalHook(window);window.$RefreshReg$=()=>{};window.$RefreshSig$=()=>type=>type;window.__vite_plugin_react_preamble_installed__=true;</script><script type="module" src="/tests/e2e/resources179.harness.jsx"> </script></body></html>`}));
 await page.goto('/resources179-harness#suite=resources179&bridge='+encodeURIComponent('http://127.0.0.1:5179'));
 await expect(page.locator('.resource179-card')).toHaveCount(3);
}
test('resources wrap at their own widths and overview frame matches its clipped fill',async({page})=>{
 await harness(page);const cards=page.locator('.resource179-card');await expect(cards.first().locator('.resource179-name')).toHaveCSS('font-size','14px');await expect(cards.first().locator('.resource-title strong').first()).toHaveCSS('font-size','12px');
 const bounds=await cards.first().evaluate(card=>{const b=(el:Element)=>{const r=el.getBoundingClientRect();return {x:r.x,y:r.y,w:r.width,h:r.height};};return {outer:b(card),fill:b(card.querySelector('.resource179-face')!),line:b(card.querySelector(':scope>.adaptive-frame-art')!),resources:[...card.querySelectorAll('.console-resource')].map(b)};});
 expect(bounds.fill).toEqual(bounds.outer);expect(bounds.line).toEqual(bounds.outer);expect(bounds.resources[0].w).toBeLessThan(bounds.outer.w*.65);expect(bounds.resources[1].y).toBe(bounds.resources[0].y);
 const quick=await page.locator('.paper .quick-resource').evaluateAll(nodes=>nodes.map(node=>{const r=node.getBoundingClientRect();return {x:r.x,y:r.y,w:r.width};}));expect(quick[0].w).toBeLessThan(200);expect(quick[1].y).toBe(quick[0].y);expect(quick[1].x).toBeGreaterThan(quick[0].x);
 await page.screenshot({path:output+'/overview-resources179.png',fullPage:true});
});
test('condition effects keep the roster frame fixed and move only its internal frames',async({page})=>{
 await harness(page);const petrified=page.locator('[data-resource-target="hero1"]');await expect(petrified).toHaveClass(/adaptive-condition-incapacitated/);await expect(petrified).not.toHaveAttribute('data-adaptive-physical');await expect.poll(()=>petrified.locator('[data-adaptive-physical][data-adaptive-fallen="true"]').count()).toBeGreaterThan(3);await expect(page.locator('[data-resource-target="hero0"] .resource179-name')).toHaveCSS('rotate','180deg');
 const initial=await petrified.boundingBox();await page.waitForTimeout(1000);const after=await petrified.boundingBox();expect(after?.x).toBe(initial?.x);expect(after?.y).toBe(initial?.y);expect(await petrified.evaluate(el=>getComputedStyle(el).translate)).toBe('none');
 await page.setViewportSize({width:420,height:900});await expect(page.locator('.console-roster')).toHaveCSS('grid-template-columns',/^[0-9.]+px$/);expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(420);await page.screenshot({path:output+'/overview-narrow179.png',fullPage:true});
});
test('condition bubbles transfer and remove using the custom pointer gesture, and Wiki adds directly',async({page})=>{
 await harness(page);const source=page.locator('[data-resource-target="hero0"] [data-overview-condition="prone"]');const target=page.locator('[data-resource-target="hero2"] .resource179-name');let a=await source.boundingBox(),b=await target.boundingBox();await page.mouse.move(a!.x+8,a!.y+6);await page.mouse.down();await page.mouse.move(b!.x+15,b!.y+8,{steps:10});await expect(page.locator('.pointer-ghost')).toHaveCount(1);await page.mouse.up();
 await expect.poll(()=>page.evaluate(()=>(window as any).requests.filter((r:any)=>r.type==='condition').at(-1))).toMatchObject({type:'condition',action:'transfer',itemId:'card:hero0',to:'card:hero2',condition:{id:'prone'}});
  const transferred=page.locator('[data-resource-target="hero2"] [data-overview-condition="prone"]');await expect(transferred).toBeVisible();await expect(source).toHaveCount(0);await expect(page.locator('.pointer-ghost')).toHaveCount(0);a=await transferred.boundingBox();await page.mouse.move(a!.x+8,a!.y+6);await page.mouse.down();await page.mouse.move(8,400,{steps:10});await page.mouse.up();await expect.poll(()=>page.evaluate(()=>(window as any).requests.filter((r:any)=>r.type==='condition').at(-1)?.action)).toBe('remove');
 await expect(page.locator('.pointer-ghost')).toHaveCount(0);a=await page.locator('#wiki-condition').boundingBox();b=await target.boundingBox();await page.mouse.move(a!.x+8,a!.y+6);await page.mouse.down();await page.mouse.move(b!.x+15,b!.y+8,{steps:10});await expect(page.locator('.drop-over')).toHaveCount(1);await page.mouse.up();await expect.poll(()=>page.evaluate(()=>(window as any).requests.filter((r:any)=>r.type==='condition').at(-1))).toMatchObject({type:'condition',action:'add',itemId:'card:hero2',condition:{id:'poisoned'}});
});
test('a player can grant one condition to another unlocked card without editing that card',async({page})=>{
 await harness(page);await page.evaluate(()=>{(window as any).cards[2].write=false;(window as any).refresh('PLAYER');});const recipient=page.locator('[data-resource-target="hero2"]');await expect(recipient).toHaveAttribute('data-condition-write','false');await expect(recipient).toHaveAttribute('data-condition-receive','true');await expect(recipient.getByRole('button',{name:'管理凯瑟琳资源'})).toBeDisabled();const source=page.locator('[data-resource-target="hero0"] [data-overview-condition="prone"]'),a=await source.boundingBox(),b=await recipient.locator('.resource179-name').boundingBox();await page.mouse.move(a!.x+7,a!.y+7);await page.mouse.down();await page.mouse.move(b!.x+10,b!.y+10,{steps:10});await page.mouse.up();await expect(recipient.locator('[data-overview-condition="prone"]')).toBeVisible();await expect(recipient.locator('[data-overview-condition="prone"]')).toHaveAttribute('data-can-drag','false');
});
test('unknown condition result stays optimistic, then a late receipt reconciles once with undo and redo',async({page})=>{
 await harness(page);await page.evaluate(()=>(window as any).holdCondition=true);const source=page.locator('#wiki-condition'),recipient=page.locator('[data-resource-target="hero2"]'),a=await source.boundingBox(),b=await recipient.locator('.resource179-name').boundingBox();await page.mouse.move(a!.x+8,a!.y+7);await page.mouse.down();await page.mouse.move(b!.x+10,b!.y+10,{steps:10});await page.mouse.up();const chip=recipient.locator('[data-overview-condition="poisoned"]');await expect(chip).toBeVisible();await chip.evaluate(node=>(window as any).poisonChip=node);
 await page.evaluate(()=>{const w=window as any;w.emit('ack',{requestId:w.held.requestId,ok:false,uncertain:true,message:'await receipt'});w.refresh();});await expect(chip).toBeVisible();
 await page.evaluate(()=>{const w=window as any;w.holdCondition=false;w.reply(w.held);});await expect(chip).toBeVisible();expect(await chip.evaluate(node=>node===(window as any).poisonChip)).toBe(true);
 await page.getByRole('button',{name:'撤销',exact:true}).click();await expect(chip).toHaveCount(0);await page.getByRole('button',{name:'重做',exact:true}).click();await expect(chip).toBeVisible();
});

test('public resource hover exposes real clickable lock and settings controls',async({page})=>{
 await harness(page);await page.evaluate(()=>{const w=window as any;w.publicInventory={revision:1,publicId:'public:room',silent:false,containers:{'public:room':{id:'public:room',name:'公共仓库',kind:'public',revision:1,columns:4,capacity:20,write:true,items:[{id:'supply',kind:'resource',name:'团队补给',quantity:6,max:6,type:'count',slot:9000,revision:1,locked:false}]}}};
  const originalReply=w.reply;w.reply=(request:any)=>{if(request.type!=='inventory')return originalReply(request);const op=request.operation,inventory=structuredClone(w.publicInventory),container=inventory.containers[op.container];Object.assign(container.items.find((r:any)=>r.id===op.id),op.patch);container.revision++;inventory.revision++;w.publicInventory=inventory;w.emit('ack',{requestId:request.requestId,ok:true,result:{inventory}});};w.emit('catalog',{sequence:1000,role:'GM',enabled:{inventory:true},cards:w.cards,monsters:[],inventory:w.publicInventory});
 });
 const row=page.locator('.public-resource-grid>.console-resource').filter({has:page.getByText('团队补给',{exact:true})}),actions=row.locator('.resource-actions');await row.scrollIntoViewIfNeeded();await page.mouse.move(1,1);await expect(actions).toHaveCSS('opacity','0');await expect(actions).toHaveCSS('pointer-events','none');
 await row.hover();await expect(actions).toHaveCSS('opacity','1');await expect(actions).toHaveCSS('pointer-events','auto');const lock=row.getByRole('button',{name:'锁定团队补给',exact:true});expect(await lock.evaluate(el=>{const r=el.getBoundingClientRect();return document.elementFromPoint(r.x+r.width/2,r.y+r.height/2)?.closest('button')===el;})).toBe(true);
 await lock.click();await expect(row.getByRole('button',{name:'解锁团队补给',exact:true})).toBeVisible();await row.hover();await row.getByRole('button',{name:'设置团队补给',exact:true}).click();await expect(page.getByLabel('资源名称',{exact:true})).toHaveValue('团队补给');
});

test('overview atmosphere keeps symbols proportional through resize and retires removed effects',async({page})=>{
 await harness(page);await page.evaluate(()=>{const w=window as any,labels:Record<string,string>={restrained:'束缚',deafened:'耳聋',blinded:'目盲',charmed:'魅惑',grappled:'受擒',poisoned:'中毒',bloodied:'浴血',concentration:'专注',stunned:'震慑',surprised:'突袭',exhaustion:'力竭'};w.cards[0].conditions=Object.entries(labels).map(([id,name])=>({id,name,level:id==='exhaustion'?3:1}));w.refresh();});
 const card=page.locator('[data-resource-target="hero0"]');
 const shape=async()=>{await expect(card.locator('[data-adaptive-symbol]')).toHaveCount(2);const result=await card.locator('[data-adaptive-symbol]').evaluateAll(nodes=>nodes.map(node=>{const m=(node as SVGGraphicsElement).getScreenCTM()!;return {x:Math.hypot(m.a,m.b),y:Math.hypot(m.c,m.d)};}));for(const scale of result)expect(Math.abs(scale.x/scale.y-1)).toBeLessThan(.01);await expect(card.locator('.card-art-layer')).toHaveCount(0);};
 await shape();await page.waitForTimeout(1200);await page.screenshot({path:output+'/adaptive-overview-wide.png',fullPage:true});await page.setViewportSize({width:420,height:900});await shape();await page.waitForTimeout(900);await page.screenshot({path:output+'/adaptive-overview-narrow.png',fullPage:true});
 await page.evaluate(()=>{const w=window as any;w.cards[0].conditions=[];w.refresh();});await expect(card.locator('[data-adaptive-effect="restrained"][data-phase="leaving"]')).toHaveCount(1);await expect(card.locator('[data-adaptive-effect="restrained"]')).toHaveCount(0);
});

test('adaptive overview uses genuinely different card aspect ratios at 840, 620 and 300 pixels',async({page})=>{
 await harness(page);await page.evaluate(()=>{const w=window as any;w.cards[0].conditions=[{id:'blinded',name:'目盲'},{id:'deafened',name:'耳聋'}];w.refresh();});const sizes:number[]=[];
 for(const width of [840,620,300]){await page.setViewportSize({width,height:950});await page.waitForTimeout(2800);const card=page.locator('[data-resource-target="hero0"]');sizes.push((await card.boundingBox())!.width);for(const item of await card.locator('[data-adaptive-symbol]').evaluateAll(nodes=>nodes.map(n=>{const m=(n as SVGGraphicsElement).getScreenCTM()!;return {x:Math.hypot(m.a,m.b),y:Math.hypot(m.c,m.d)};})))expect(Math.abs(item.x/item.y-1)).toBeLessThan(.01);
  const result=await page.locator('[data-resource-target="hero1"] .resource179-body').evaluate(root=>{const r=root.getBoundingClientRect();return {bounds:{left:r.left,right:r.right,top:r.top,bottom:r.bottom},bodies:[...root.querySelectorAll<HTMLElement>('[data-adaptive-fallen]')].map(n=>{const b=n.getBoundingClientRect(),m=new DOMMatrix(getComputedStyle(n).transform);return {left:b.left,right:b.right,top:b.top,bottom:b.bottom,scaleX:Math.hypot(m.a,m.b),scaleY:Math.hypot(m.c,m.d)};})};});expect(result.bodies.length).toBeGreaterThan(3);for(const b of result.bodies){expect(b.left).toBeGreaterThanOrEqual(result.bounds.left-.6);expect(b.right).toBeLessThanOrEqual(result.bounds.right+.6);expect(b.top).toBeGreaterThanOrEqual(result.bounds.top-.6);expect(b.bottom).toBeLessThanOrEqual(result.bounds.bottom+.6);expect(b.scaleX).toBeCloseTo(1,3);expect(b.scaleY).toBeCloseTo(1,3);}
 }
 expect(Math.max(...sizes)-Math.min(...sizes)).toBeGreaterThan(25);
});

test('overview falling frames remain unscaled and inside their actual local container',async({page})=>{
 await harness(page);const card=page.locator('[data-resource-target="hero1"]'),body=card.locator('.resource179-body');await expect.poll(()=>card.locator('[data-adaptive-fallen="true"]').count()).toBeGreaterThan(3);await page.waitForTimeout(2800);
 for(const width of [1200,420]){await page.setViewportSize({width,height:900});await page.waitForTimeout(2800);const result=await body.evaluate(root=>{const r=root.getBoundingClientRect();return {rect:{x:r.x,y:r.y,right:r.right,bottom:r.bottom},boxes:[...root.querySelectorAll<HTMLElement>('[data-adaptive-fallen]')].map(n=>{const b=n.getBoundingClientRect(),m=new DOMMatrix(getComputedStyle(n).transform);return {x:b.x,y:b.y,right:b.right,bottom:b.bottom,width:n.offsetWidth,height:n.offsetHeight,scaleX:Math.hypot(m.a,m.b),scaleY:Math.hypot(m.c,m.d)};})};});for(const box of result.boxes){expect(box.x).toBeGreaterThanOrEqual(result.rect.x-.6);expect(box.right).toBeLessThanOrEqual(result.rect.right+.6);expect(box.y).toBeGreaterThanOrEqual(result.rect.y-.6);expect(box.bottom).toBeLessThanOrEqual(result.rect.bottom+.6);expect(box.scaleX).toBeCloseTo(1,3);expect(box.scaleY).toBeCloseTo(1,3);}}
});
