import {test,expect} from '@playwright/test';
import {mockSource,suppressAnnouncement} from './fixtures';
import {newCharacter} from '../../src/core/model';
import {resourceWidgetLayout} from '../../src/core/resourceWidgets';
async function load(page:any,c:any){await mockSource(page);await suppressAnnouncement(page);await page.goto('/');await expect(page.getByRole('button',{name:'更新资料',exact:true})).toBeEnabled();await page.getByRole('button',{name:'导入 / 导出',exact:true}).click();await page.getByTestId('character-file').setInputFiles({name:'原创资源模块.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(c))});await page.getByRole('button',{name:'关闭弹窗'}).click();}
test('template insertion uses the actual editing canvas, never spends on selection, and persists the new page and group',async({page})=>{
 const c=newCharacter();c.name='原创资源画布';c.runtime.resources=Object.fromEntries(Array.from({length:9},(_,i)=>['r'+i,{name:'已有资源'+i,current:2,max:4,type:'count'}]));c.quickbarLayout={order:[],hidden:[],widgets:resourceWidgetLayout(Object.keys(c.runtime.resources))};await load(page,c);await page.getByRole('switch',{name:'编辑模式'}).click();
 const workspace=page.getByRole('region',{name:'资源模块快捷栏'});await expect(workspace.locator('.resource-layout-tools')).toHaveCount(0);await workspace.getByRole('button',{name:'管理资源',exact:true}).click();const library=page.getByRole('dialog',{name:'选择资源模块',exact:true});await expect(library.locator('.resource-template-option')).toHaveCount(6);await expect(library).toContainText('2');await page.screenshot({path:test.info().outputPath('templates.png')});await library.getByRole('button',{name:'添加多项资源资源模块',exact:true}).click();await expect(library).toHaveCount(0);await expect(workspace.locator('.resource-page-nav output')).toHaveText('3/3');const group=workspace.locator('.widget-group');await expect(group).toHaveCount(1);await expect(group).toContainText('子资源 1');expect(await group.locator('.resource-widget-face').evaluate(face=>{const box=face.getBoundingClientRect(),title=face.querySelector('.resource-group-title')!.getBoundingClientRect();return title.height>=4&&[...face.querySelectorAll('.resource-subvalue')].every(el=>el.getBoundingClientRect().bottom<=box.bottom+1);})).toBe(true);await group.locator('.resource-widget-face').click();await expect(page.getByRole('dialog',{name:'组合资源资源操作',exact:true})).toHaveCount(0);await expect(group.locator('.resource-widget-handle')).toHaveCount(8);await page.screenshot({path:test.info().outputPath('canvas-group.png')});
 await group.locator('.resource-widget-face').dblclick();const edit=page.getByRole('dialog',{name:'资源配置',exact:true});await expect(edit.locator('.resource-module-tabs button')).toHaveCount(3);await expect(edit.getByText('资源模块样式',{exact:true})).toHaveCount(0);await edit.getByRole('button',{name:'子资源 2',exact:true}).click();await edit.getByRole('textbox',{name:'资源名称',exact:true}).fill('余烬');await edit.getByRole('spinbutton',{name:'资源剩余',exact:true}).fill('1');await edit.getByRole('button',{name:'保存',exact:true}).click();await expect(edit).toHaveCount(0);await expect(group).toContainText('余烬');await page.reload();await workspace.getByRole('button',{name:'下一页资源'}).click();await workspace.getByRole('button',{name:'下一页资源'}).click();await expect(group).toContainText('余烬');await page.setViewportSize({width:390,height:982});expect(await group.locator('.resource-widget-face').evaluate(face=>{const box=face.getBoundingClientRect();return face.scrollHeight<=face.clientHeight+1&&[...face.querySelectorAll('.resource-group-title,.resource-subvalue')].every(el=>{const r=el.getBoundingClientRect();return r.top>=box.top-1&&r.bottom<=box.bottom+1;});})).toBe(true);await group.screenshot({path:test.info().outputPath('group-narrow.png')});await page.setViewportSize({width:1512,height:982});await expect(group.locator('.resource-subvalue').nth(1)).toContainText('1');await page.getByRole('switch',{name:'编辑模式'}).click();await group.locator('.resource-widget-face').click();await page.getByRole('button',{name:'设置余烬',exact:true}).click();const childConfig=page.getByRole('dialog',{name:'资源配置',exact:true});await expect(childConfig.getByRole('textbox',{name:'资源名称',exact:true})).toHaveValue('余烬');await expect(childConfig.getByText('资源模块样式',{exact:true})).toHaveCount(0);await page.getByRole('button',{name:'关闭弹窗'}).click();await workspace.getByRole('button',{name:'上一页资源'}).click();await workspace.getByRole('button',{name:'上一页资源'}).click();for(let i=0;i<6;i++)await expect(workspace.locator(`[data-resource-id="r${i}"]`)).toHaveAttribute('data-resource-current','2');await workspace.getByRole('button',{name:'下一页资源'}).click();for(let i=6;i<9;i++)await expect(workspace.locator(`[data-resource-id="r${i}"]`)).toHaveAttribute('data-resource-current','2');
});
test('each actual spell pool has its own fixed face while normal and pact values remain separately actionable',async({page})=>{
 const c=newCharacter();c.name='原创混合法术位';c.runtime.resources={'spell-slot:1':{name:'1环法术位',current:4,max:4,type:'count'},'spell-slot:2':{name:'2环法术位',current:2,max:3,type:'count'},'pact-slot:2':{name:'2环契约位',current:1,max:2,type:'count'}};c.spellSettings={ability:'int',attackBonus:0,dcBonus:0,mode:'prepared',capacity:0,prepared:[],slots:{'1':{max:4,used:0},'2':{max:3,used:1}}};await load(page,c);const workspace=page.getByRole('region',{name:'资源模块快捷栏'});await expect(workspace.locator('.resource-widget')).toHaveCount(2);await expect(workspace.locator('.resource-slot-values b')).toHaveText(['I','II','II']);await expect(workspace).toContainText('契约');await workspace.locator('[data-resource-id="spell-slot:1"] .resource-widget-face').click();const panel=page.getByRole('dialog',{name:'法术位（共用）资源操作',exact:true});await panel.getByRole('button',{name:'2环法术位 2',exact:true}).click();await expect(workspace.locator('.resource-subvalue strong')).toHaveText(['4','1','1']);await panel.getByRole('button',{name:'关闭资源操作',exact:true}).click();await page.getByRole('switch',{name:'编辑模式'}).click();await workspace.locator('[data-resource-id="spell-slot:1"] .resource-widget-face').click();await expect(panel).toHaveCount(0);await workspace.getByRole('button',{name:'设置法术位（共用）',exact:true}).click();const config=page.getByRole('dialog',{name:'资源配置',exact:true});await expect(config.locator('.resource-module-tabs button')).toHaveCount(2);await expect(config.getByText('资源模块样式',{exact:true})).toHaveCount(0);await page.getByRole('button',{name:'关闭弹窗'}).click();await page.reload();await expect(workspace.locator('.resource-widget')).toHaveCount(2);await expect(workspace.locator('.resource-subvalue strong')).toHaveText(['4','1','1']);await page.screenshot({path:test.info().outputPath('single-spell-module.png')});
});

test('dense standard I to IX and independent pact V fit the A4 canvas at wide and narrow widths',async({page})=>{
 const c=newCharacter();c.name='原创满环法术位';c.runtime.resources=Object.fromEntries(Array.from({length:9},(_,i)=>[`spell-slot:${i+1}`,{name:`${i+1}环法术位`,current:2,max:4,type:'count'}]));c.runtime.resources['pact-slot:5']={name:'5环契约位',current:1,max:3,type:'count'};c.spellSettings={ability:'int',attackBonus:0,dcBonus:0,mode:'prepared',capacity:0,prepared:[],slots:Object.fromEntries(Array.from({length:9},(_,i)=>[String(i+1),{max:4,used:2}]))};await load(page,c);
 for(const width of [1512,390]){await page.setViewportSize({width,height:982});const workspace=page.getByRole('region',{name:'资源模块快捷栏'});await expect(workspace.locator('.resource-widget')).toHaveCount(2);await expect(workspace.locator('.resource-subvalue')).toHaveCount(10);await expect(workspace.locator('.resource-slot-values b')).toHaveText(['I','II','III','IV','V','VI','VII','VIII','IX','V']);expect(await workspace.locator('.resource-widget-face').evaluateAll(faces=>faces.every(face=>{const box=face.getBoundingClientRect();return [...face.querySelectorAll('.resource-subvalue')].every(el=>{const r=el.getBoundingClientRect();return r.top>=box.top-1&&r.left>=box.left-1&&r.right<=box.right+1&&r.bottom<=box.bottom+1;})&&face.scrollHeight<=face.clientHeight+1;}))).toBe(true);await page.screenshot({path:test.info().outputPath(`dense-a4-${width}.png`),fullPage:true});await page.locator('.resource-diy-quickbar').screenshot({path:test.info().outputPath(`dense-quickbar-${width}.png`)});}
 await page.getByRole('switch',{name:'编辑模式'}).click();await page.getByRole('button',{name:'管理资源',exact:true}).click();await expect(page.getByRole('dialog',{name:'选择资源模块',exact:true})).toBeVisible();await page.screenshot({path:test.info().outputPath('templates-narrow.png')});
});

for(const levels of [2,4,6])test(`ordinary ${levels} levels stay within the narrow resource canvas`,async({page})=>{const c=newCharacter();c.runtime.resources=Object.fromEntries(Array.from({length:levels},(_,i)=>[`spell-slot:${i+1}`,{name:`${i+1}环法术位`,current:2,max:4,type:'count'}]));c.spellSettings={ability:'int',attackBonus:0,dcBonus:0,mode:'prepared',capacity:0,prepared:[],slots:Object.fromEntries(Array.from({length:levels},(_,i)=>[String(i+1),{max:4,used:2}]))};await load(page,c);await page.setViewportSize({width:390,height:982});const face=page.locator('.resource-widget-face');await expect(face.locator('.resource-subvalue')).toHaveCount(levels);expect(await face.evaluate(el=>{const b=el.getBoundingClientRect();return el.scrollHeight<=el.clientHeight+1&&[...el.querySelectorAll('.resource-group-title,.resource-subvalue')].every(child=>{const r=child.getBoundingClientRect();return r.top>=b.top-1&&r.bottom<=b.bottom+1&&r.right<=b.right+1;});})).toBe(true);await page.locator('.resource-diy-quickbar').screenshot({path:test.info().outputPath(`narrow-${levels}-levels.png`)});});

test('all four single styles preserve visible labels and numbers on the narrow canvas',async({page})=>{const c=newCharacter();c.runtime.resources=Object.fromEntries(['bar','ring','square','icon'].map(style=>[style,{name:'资源名称',current:2,max:5,type:'number'}]));c.quickbarLayout={order:[],hidden:[],widgets:Object.fromEntries(['bar','ring','square','icon'].map((style,i)=>[style,{x:(i%3)*4,y:i<3?0:3,w:4,h:3,page:0,style}])) as any};await load(page,c);await page.setViewportSize({width:390,height:982});await expect(page.locator('.resource-widget')).toHaveCount(4);for(const style of ['bar','ring','square','icon']){const face=page.locator(`[data-resource-id="${style}"] .resource-widget-face`);expect(await face.evaluate(el=>{const b=el.getBoundingClientRect();return el.scrollHeight<=el.clientHeight+1&&[...el.querySelectorAll('.resource-widget-name,.resource-widget-value')].every(child=>{const r=child.getBoundingClientRect();return r.height>=9&&r.top>=b.top-1&&r.bottom<=b.bottom+1;});})).toBe(true);}await page.locator('.resource-diy-quickbar').screenshot({path:test.info().outputPath('narrow-four-styles.png')});});
