import {test,expect,type Page} from '@playwright/test';
import {writeFileSync} from 'node:fs';
import {mockSource} from './fixtures';
import {newCharacter,type Entry} from '../../src/core/model';
import {customEntryExample} from '../../src/core/customEntrySchema';
const spell:Entry={id:'fixture:spell',kind:'spell',name:'星海光束',english:'Starlight',source:'XPHB',edition:'2024',revision:'1',packId:'fixture',entries:['验收自制法术。'],raw:{level:1,school:'V'}};
async function start(page:Page){await mockSource(page);await page.goto('/');await expect(page.getByRole('button',{name:'更新资料',exact:true})).toBeEnabled();}
test('ordinary spell clicks read only; editing prepares, fixed spells and limited resources persist',async({page})=>{
 await start(page);const c=newCharacter();c.name='预备与天生法术';c.selections=[{id:'s',entry:spell,level:1,quantity:1,equipped:false}];c.spellSettings={mode:'prepared',modeOverride:true,ability:'int',capacity:2,capacityAdjustment:2,attackBonus:0,dcBonus:0,prepared:[],slots:{}};
 await page.getByRole('button',{name:'导入 / 导出',exact:true}).click();await page.getByTestId('character-file').setInputFiles({name:'spell.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(c))});await page.getByRole('button',{name:'关闭弹窗'}).click();
 await page.getByRole('tab',{name:'法术',exact:true}).click();const tile=page.locator('.spell-library .spell-stock-tile');await tile.click();await expect(page.locator('.prepared-cell .spell-stock-tile')).toHaveCount(0);await expect(page.locator('.detail-title')).toContainText('星海光束');await tile.click({button:'right'});await expect(page.getByRole('menuitem',{name:'预备法术',exact:true})).toHaveCount(0);await page.keyboard.press('Escape');
 await page.getByRole('switch',{name:'编辑模式'}).click();await tile.click();await expect(page.locator('.prepared-cell .spell-stock-tile')).toHaveCount(1);await page.getByRole('tab',{name:'主要',exact:true}).click();await expect(page.locator('.overview-spells')).toContainText('星海光束');await page.getByRole('tab',{name:'法术',exact:true}).click();await page.locator('.prepared-cell .spell-stock-tile').click({button:'right'});await page.getByRole('menuitem',{name:'设为次数法术'}).click();await expect(page.locator('.special-spells-cell')).toContainText('星海光束');await expect(page.locator('.prepared-cell .spell-stock-tile')).toHaveCount(0);
 await page.getByRole('switch',{name:'编辑模式'}).click();await page.locator('.special-spells-cell').getByRole('button',{name:'使用',exact:true}).click();await expect(page.getByLabel('星海光束剩余次数')).toHaveValue('0');await page.reload();await page.getByRole('tab',{name:'法术',exact:true}).click();await expect(page.getByLabel('星海光束剩余次数')).toHaveValue('0');await page.screenshot({path:test.info().outputPath('fixed-and-limited-spells.png')});
});
test('pinyin searches navigate into a distant catalog row and class details retain structured starting data',async({page})=>{
 await mockSource(page);await page.route('**/data/spells/spells-test.json',route=>route.fulfill({json:{spell:Array.from({length:150},(_,i)=>({name:i===149?'火球术':`资料法术${String(i).padStart(3,'0')}`,source:'XPHB',level:1,entries:['验收正文。']}))}}));await page.route('**/data/class/class-test.json',route=>route.fulfill({json:{class:[{name:'资料职业',source:'XPHB',hd:{faces:8},proficiency:['str','con'],startingProficiencies:{weapons:['simple'],skills:[{choose:{from:['arcana','history'],count:1}}]},startingEquipment:{entries:['选择 {@item 测试皮甲|XPHB} 或 10 GP。']}}]}}));
 await page.goto('/');await expect(page.getByRole('button',{name:'更新资料',exact:true})).toBeEnabled();await page.getByLabel('搜索规则资料').fill('hqs');await page.locator('.global-result').filter({hasText:'火球术'}).click();await expect(page.locator('.detail-title')).toContainText('火球术');await expect(page.locator('.catalog-row.active')).toContainText('火球术');await page.getByLabel('法术分类搜索').fill('huoqiu');await expect(page.locator('.catalog-list')).toHaveAttribute('data-total-rows','1');
 await page.getByRole('navigation',{name:'资料分类'}).getByRole('button',{name:'职业',exact:true}).click();await page.locator('.catalog-row').filter({hasText:'资料职业'}).click();await expect(page.locator('.entry-detail')).toContainText('起始熟练项');await expect(page.locator('.entry-detail')).toContainText('简易武器');await expect(page.locator('.entry-detail')).toContainText('奥秘、历史');await expect(page.locator('.entry-detail')).toContainText('10 GP');await page.screenshot({path:test.info().outputPath('wiki-starting-data.png')});
});
test('custom JSON preserves nested linked content, offers required fields, and remains editable after save',async({page})=>{
 await start(page);await page.getByRole('navigation',{name:'资料分类'}).getByRole('button',{name:'自定义',exact:true}).click();await page.locator('.custom-json-import summary').click();const example=customEntryExample('class');example.name='星图守望者';example.entries=['参阅 {@spell 微光术|XPHB}。',{type:'entries',name:'星图记录',entries:['保留完整子内容。']}];await page.getByLabel('完整自定义条目 JSON').fill(JSON.stringify(example));await page.getByRole('button',{name:'载入 JSON',exact:true}).click();await expect(page.getByLabel('职业力量豁免熟练')).toBeChecked();await page.getByRole('button',{name:'保存条目',exact:true}).click();await expect(page.locator('.custom-entry-editor .rules-prose')).toContainText('星图记录');await expect(page.locator('.custom-entry-editor .rules-prose')).toContainText('保留完整子内容');await page.reload();await expect(page.getByLabel('自定义条目名称')).toHaveValue('星图守望者');await expect(page.getByLabel('职业力量豁免熟练')).toBeChecked();await page.screenshot({path:test.info().outputPath('custom-structured-entry.png')});
});
test('first large catalog normalization runs in a disposable worker while the editor remains usable',async({page})=>{
 let workers=0,closed=0;page.on('worker',worker=>{if(worker.url().includes('catalog.worker')){workers++;worker.on('close',()=>closed++);}});
 await mockSource(page);await page.route('**/data/spells/spells-test.json',route=>route.fulfill({json:{spell:Array.from({length:6000},(_,i)=>({name:`性能验收法术${i}`,source:'XPHB',level:i%10,entries:[{type:'entries',name:'子内容',entries:['只用于本地性能验收的自制正文。'.repeat(10)]}]}))}}));
 await page.addInitScript(()=>{const gaps:number[]=[],tasks:number[]=[];(window as any).__wikiLongTasks=tasks;new PerformanceObserver(list=>{tasks.push(...list.getEntries().map(entry=>entry.duration));}).observe({type:'longtask',buffered:true});let previous=performance.now();const tick=(now:number)=>{gaps.push(now-previous);previous=now;(window as any).__wikiFrameGaps=gaps;requestAnimationFrame(tick);};requestAnimationFrame(tick);});
 await page.goto('/');await page.getByRole('switch',{name:'编辑模式'}).click();await expect(page.getByRole('switch',{name:'编辑模式'})).toHaveAttribute('aria-checked','true');await expect(page.getByRole('button',{name:'更新资料',exact:true})).toBeEnabled();expect(workers).toBeGreaterThan(0);await expect.poll(()=>closed).toBe(workers);
 await page.getByRole('navigation',{name:'资料分类'}).getByRole('button',{name:'法术',exact:true}).click();await expect(page.locator('.catalog-list')).toHaveAttribute('data-total-rows','6000');expect(await page.locator('.catalog-row').count()).toBeLessThan(80);
 const measure=()=>page.evaluate(()=>({longestFrameMs:Math.round(Math.max(...((window as any).__wikiFrameGaps||[0]))),longTasks:((window as any).__wikiLongTasks||[]).map(Math.round),elapsedMs:Math.round(performance.now())}));const cold=await measure();
 await page.reload();await expect(page.getByRole('button',{name:'更新资料',exact:true})).toBeEnabled();await expect(page.locator('.catalog-list')).toHaveAttribute('data-total-rows','6000');await expect.poll(()=>closed).toBe(workers);const warm=await measure();
 const metrics={production:process.env.FEEDBACK_WIKI_PRODUCTION==='1',entries:6000,workerCount:workers,closedWorkers:closed,cold,warm},path=test.info().outputPath('first-load-local-metrics.json');writeFileSync(path,JSON.stringify(metrics,null,2));await test.info().attach('first-load-local-metrics',{path,contentType:'application/json'});
});
