import {test,expect,type Page} from '@playwright/test';
import {mockSource,suppressAnnouncement} from './fixtures';
import {newCharacter} from '../../src/core/model';

async function ready(page:Page){await mockSource(page);await suppressAnnouncement(page);await page.goto('/card/?intro=0');await expect(page.locator('.paper')).toBeVisible();await expect(page.locator('.save-status')).toContainText('已保存到本机');}
async function workspace(page:Page,mutate?:boolean){return page.evaluate(async change=>{const db=await new Promise<IDBDatabase>((resolve,reject)=>{const r=indexedDB.open('dnd-card-standalone');r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error);});try{const tx=db.transaction('documents',change?'readwrite':'readonly'),store=tx.objectStore('documents'),value:any=await new Promise(resolve=>{const r=store.get('workspace');r.onsuccess=()=>resolve(r.result);});if(change){const c=value.characters.find((c:any)=>c.id===value.activeId);value.characters=Array.from({length:12},(_,i)=>({...structuredClone(c),id:'strip-'+i,name:'原创长名字测试标签滚动与拖动 '+i}));value.activeId='strip-0';store.put(value,'workspace');await new Promise<void>(resolve=>tx.oncomplete=()=>resolve());}return value;}finally{db.close();}},!!mutate);}
test('palette undo/redo covers commits and imports, preserving rules and stopping previews',async({page})=>{
 await ready(page);await page.getByRole('button',{name:'调色盘',exact:true}).click();const drawer=page.getByRole('dialog',{name:'调色盘',exact:true}),field=drawer.getByRole('textbox',{name:'页面背景颜色代码'});
 await expect(drawer.getByRole('button',{name:'撤回配色'})).toBeDisabled();await field.fill('#223344');await field.blur();await expect(page.locator('.app-shell')).toHaveCSS('background-color','rgb(34, 51, 68)');await drawer.getByRole('button',{name:'撤回配色'}).click();await expect(page.locator('.app-shell')).toHaveCSS('background-color','rgb(209, 209, 209)');await drawer.getByRole('button',{name:'重做配色'}).click();await expect(field).toHaveValue('#223344');
 const before=(await workspace(page)).characters;const choosing=page.waitForEvent('filechooser');await drawer.getByRole('button',{name:'导入配色',exact:true}).click();await (await choosing).setFiles({name:'palette.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify({format:'dnd-card-palette',version:1,appearance:{ui:{background:'#CCDDEE'},wiki:{}},card:{palette:{paper:'#CCDDEE'},components:{abilities:{surface:'#AABBCC'}}}}))});
 const surface=page.locator('[data-palette-component=abilities] .cell-content').first();await expect(surface).toHaveCSS('background-color','rgb(170, 187, 204)');await drawer.getByRole('button',{name:'撤回配色'}).click();await expect(surface).toHaveCSS('background-color','rgb(232, 232, 232)');await drawer.getByRole('button',{name:'重做配色'}).click();await expect(surface).toHaveCSS('background-color','rgb(170, 187, 204)');await page.waitForTimeout(400);
 const after=(await workspace(page)).characters;const mechanics=(rows:any[])=>rows.map(c=>{const copy={...c};for(const key of ['palette','componentPalette','revision','updatedAt'])delete copy[key];return copy;});expect(mechanics(after)).toEqual(mechanics(before));
 await drawer.getByRole('button',{name:'基础界面',exact:true}).click();await field.fill('#998877');await field.blur();await expect(drawer.getByRole('button',{name:'重做配色'})).toBeDisabled();await page.screenshot({path:test.info().outputPath('palette-history259.png')});
});
test('name strip wheel and drag scroll without selecting or moving the sheet',async({page})=>{
 await ready(page);await workspace(page,true);await page.reload();const tabs=page.getByRole('tablist',{name:'当前角色'});await expect(tabs.getByRole('tab')).toHaveCount(12);const before=await tabs.evaluate(el=>el.scrollLeft);await tabs.hover();await page.mouse.wheel(0,280);await expect.poll(()=>tabs.evaluate(el=>el.scrollLeft)).toBeGreaterThan(before+100);await expect(tabs.locator('[aria-selected=true]')).toContainText(' 0');
 const box=(await tabs.boundingBox())!;const left=await tabs.evaluate(el=>el.scrollLeft);await page.mouse.move(box.x+box.width*.8,box.y+box.height/2);await page.mouse.down();await page.mouse.move(box.x+box.width*.3,box.y+box.height/2,{steps:15});await page.mouse.up();await expect.poll(()=>tabs.evaluate(el=>el.scrollLeft)).toBeGreaterThan(left+80);await expect(tabs.locator('[aria-selected=true]')).toContainText(' 0');expect(await page.evaluate(()=>scrollY)).toBe(0);
 await tabs.getByRole('tab').last().focus();await page.keyboard.press('End');await expect(tabs.getByRole('tab').last()).toHaveAttribute('aria-selected','true');
});
test('each page keeps its framing through switches, reload and JSON export',async({page})=>{
 await ready(page);const c=newCharacter();c.name='原创逐页头像';c.portrait={data:await page.evaluate(()=>{const canvas=document.createElement('canvas');canvas.width=40;canvas.height=60;const ctx=canvas.getContext('2d')!;ctx.fillStyle='#cc3355';ctx.fillRect(0,0,40,60);return canvas.toDataURL('image/png');}),x:3,y:4,zoom:1.2};
 await page.getByRole('button',{name:'导入 / 导出',exact:true}).click();await page.getByTestId('character-file').setInputFiles({name:'portrait.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(c))});await expect(page.locator('.character-tabs [aria-selected=true]')).toContainText(c.name);await page.keyboard.press('Escape');await page.getByRole('switch',{name:'编辑模式',exact:true}).click();
 for(const [tab,key] of [['主要','overview'],['特性','features'],['法术','spells'],['背包','inventory']]){await page.getByRole('tab',{name:tab,exact:true}).click();const move=page.getByRole('button',{name:'移动头像，滚轮缩放',exact:true});await move.hover();await page.mouse.wheel(0,-140);await expect.poll(async()=>{const w=await workspace(page);return w.characters.find((v:any)=>v.id===w.activeId).portraitPageFraming?.[key]?.zoom||0;}).toBeGreaterThan(1.2);}
 const w=await workspace(page),saved=w.characters.find((v:any)=>v.id===w.activeId);expect(saved.portrait).toEqual(c.portrait);expect(Object.keys(saved.portraitPageFraming).sort()).toEqual(['features','inventory','overview','spells']);await page.reload();const again=await workspace(page);expect(again.characters.find((v:any)=>v.id===again.activeId).portraitPageFraming).toEqual(saved.portraitPageFraming);
 await page.getByRole('button',{name:'导入 / 导出',exact:true}).click();const downloading=page.waitForEvent('download');await page.getByRole('button',{name:'下载 JSON',exact:true}).click();const download=await downloading;const {readFileSync}=await import('node:fs');expect(readFileSync((await download.path())!,'utf8')).toContain('portraitPageFraming');
});
test('library preserves artwork URLs and the character card keeps its announcement QR popover',async({page,request})=>{
 for(const path of ['dice/d4.png','dice/d6.png','dice/d8.png','dice/d10.png','dice/d12.png','support/wechat.png','support/alipay.jpg']){const response=await request.get('/library/'+path);expect(response.status(),path).toBe(200);expect(response.headers()['content-type'],path).toMatch(/^image\//);}
 await ready(page);await page.getByRole('button',{name:'公告',exact:true}).click();await expect(page.locator('dialog.announcement')).toBeVisible();const images=page.locator('dialog.announcement img');expect(await images.count()).toBeGreaterThanOrEqual(2);for(const image of await images.all())await expect.poll(()=>image.evaluate((el:HTMLImageElement)=>el.complete&&el.naturalWidth>0)).toBe(true);
});
