import {test,expect,type Page} from '@playwright/test';
async function harness(page:Page){
 await page.route('**/workspace179-harness',route=>route.fulfill({contentType:'text/html',body:`<!doctype html><html><head><meta charset="utf-8">${['style','workspace','workbench','suiteTheme'].map(name=>`<link rel="stylesheet" href="/src/ui/${name}.css">`).join('')}<style>body{overflow:auto}#root{padding:12px}.stock-board{width:350px}.dm-notes{height:550px}</style></head><body><div id="root"></div><script type="module">import RefreshRuntime from '/@react-refresh';RefreshRuntime.injectIntoGlobalHook(window);window.$RefreshReg$=()=>{};window.$RefreshSig$=()=>type=>type;window.__vite_plugin_react_preamble_installed__=true;</script><script type="module">
 import React from '/node_modules/.vite/deps/react.js';import ReactDOM from '/node_modules/.vite/deps/react-dom_client.js';import {StockBoard} from '/src/ui/StockBoard.tsx';import {KeywordPreview} from '/src/ui/KeywordPreview.tsx';import {DmNotes} from '/src/ui/DmNotes.tsx';import {WorkbenchBar} from '/src/ui/Workbench.tsx';
 const entry={id:'compass',kind:'item',name:'旅行罗盘',english:'Compass',source:'XPHB',edition:'2024',packId:'test',revision:'1',entries:['罗盘正文'],raw:{value:300,weight:1}};
 const row={id:'compass',entry,name:'旅行罗盘',kind:'item',quantity:3,slot:0,revision:1,unitWeight:1};const container=(id,name,kind='card',items=[])=>({id,name,kind,items,revision:1,columns:4,capacity:0,write:true});
 const stock=container('card:a','来源','card',[row]),targets=[container('card:b','在场角色'),container('card:off','不在场角色'),container('monster:token-m','在场怪物','monster'),container('public','公共仓库','public')];
 window.requests=[];window.note={revision:0,text:''};window.emit=(type,data={})=>window.dispatchEvent(new MessageEvent('message',{source:window,origin:location.origin,data:{protocol:'full-suite-workbench/v1',session:'workspace179',type,...data}}));
 window.addEventListener('message',event=>{const m=event.data;if(event.source!==window||!m.requestId||m.type==='ack')return;window.requests.push(m);let result={};if(m.method==='notes.read')result=window.note;if(m.method==='notes.write'){window.note={revision:window.note.revision+1,text:m.args[0].text};result=window.note;}window.emit('ack',{requestId:m.requestId,ok:true,result});});
 const root=ReactDOM.createRoot(document.getElementById('root'));window.render=()=>root.render(React.createElement(KeywordPreview,{resolve:()=>entry,open:()=>{},wikiVisible:()=>false},React.createElement(StockBoard,{container:stock,targets,gm:true,operation:async op=>{window.operation=op;}}),React.createElement(WorkbenchBar,{online:true,message:'',page:'notes',change:()=>{},save:()=>{}}),React.createElement(DmNotes)));
 window.render();window.catalog=role=>window.emit('catalog',{sequence:Date.now(),role,enabled:{},cards:[{id:'b',itemId:'token-b',name:'在场角色',kind:'character',inScene:true,write:true,stats:{},resources:[]},{id:'off',itemId:'card:off',name:'不在场角色',inScene:false,stats:{},resources:[]}],monsters:[{id:'m',itemId:'token-m',name:'在场怪物',kind:'monster',inScene:true,write:true,stats:{},resources:[]}]});window.emit('ready');window.catalog('GM');
 </script></body></html>`}));
 await page.goto('/workspace179-harness#suite=workspace179&bridge='+encodeURIComponent('http://127.0.0.1:5179'));await expect(page.locator('.stock-item')).toHaveCount(1);
}
test('item right click opens its two-level transfer menu, not a pinned tooltip',async({page})=>{
 await page.setViewportSize({width:620,height:900});await harness(page);const item=page.locator('.stock-item');await item.hover();await expect(page.getByRole('tooltip')).toContainText('罗盘正文');await item.click({button:'right'});await expect(page.getByRole('tooltip')).toHaveCount(0);await expect(page.locator('.tooltip-backdrop')).toHaveCount(0);await expect(page.getByRole('menuitem',{name:'转移至…'})).toBeVisible();await expect(page.getByRole('menuitem',{name:'在场角色',exact:true})).toHaveCount(0);await page.getByRole('menuitem',{name:'转移至…'}).hover();const menu=page.getByRole('menu',{name:'转移至',exact:true});await expect(menu.getByRole('menuitem')).toHaveCount(2);await expect(menu).not.toContainText('不在场角色');await menu.getByRole('menuitem',{name:'在场怪物'}).click();expect(await page.evaluate(()=>(window as any).operation)).toMatchObject({action:'transfer',to:'monster:token-m',rows:[{id:'compass',quantity:3}]});
});
test('DM notes edit BBCode, save without card mutation, and disappear for players',async({page})=>{
 await harness(page);const field=page.getByRole('textbox',{name:'笔记 BBCode'});await expect(field).toBeEnabled();await field.fill('[h2]废弃灯塔[/h2]\n[b]线索[/b]：[i]潮声[/i]\n[url=javascript:alert(1)]不执行[/url]');await expect(page.locator('.notes-preview h2')).toHaveText('废弃灯塔');await expect(page.locator('.notes-preview strong')).toHaveText('线索');await expect(page.locator('.notes-preview a')).toHaveCount(0);await expect.poll(()=>page.evaluate(()=>(window as any).note.text)).toContain('潮声');expect(await page.evaluate(()=>(window as any).requests.some((m:any)=>m.type==='save'))).toBe(false);await page.screenshot({path:'F:/CodexWork/2026-09-20/w-xu/tests179-root/dm-notes.png',fullPage:true});await page.evaluate(()=>(window as any).catalog('PLAYER'));await expect(page.getByRole('button',{name:'笔记',exact:true})).toHaveCount(0);await expect(page.locator('.dm-notes')).toHaveCount(0);
});
