import {test,expect,type Page} from '@playwright/test';
import {newCharacter} from '../../src/core/model';
import {evaluate} from '../../src/core/engine';
import {exportOwlbear} from '../../src/core/export';
import {mockSource} from './fixtures';
const protocol='full-suite-workbench/v1',session='owner-sync';
const access=(epoch=1,write=true,ids=['a','b'])=>({room:'room',scope:'room:scene',epoch,role:'PLAYER',cards:ids.map(id=>({id,itemId:'token-'+id,write,locked:false})),monsters:[],enabled:{characterCards:true}});
function snapshot(id='a',revision=1,name='Owner fixture '+id){const character=newCharacter();character.name=name;character.baseHp=20;character.runtime.hp=11;return {state:{key:'room:card:'+id,cardId:id,itemId:'token-'+id,name,kind:'character',role:'PLAYER',write:true,locked:false,pinned:false,documentRevision:revision,stats:{health:11,'max health':20,'temporary health':0,'armor class':10},resources:[],conditions:[]},document:{...exportOwlbear(character,evaluate(character)),dnd_card_web:character,_suiteRevision:revision}};}
async function send(host:Page,type:string,extra:any={}){await host.evaluate(({protocol,session,type,extra})=>(window as any).viewer.postMessage({protocol,session,type,hostStarted:1,...extra},location.origin),{protocol,session,type,extra});}
async function pair(host:Page){await mockSource(host);await host.route('**/owner-sync-host',route=>route.fulfill({contentType:'text/html',body:'<!doctype html><title>Authored owner-sync host</title>'}));await host.goto('/owner-sync-host');await host.evaluate(({protocol,session})=>{(window as any).requests=[];window.addEventListener('message',event=>{const m=event.data;if(m?.protocol!==protocol||m.session!==session)return;(window as any).requests.push(m);if(m.type==='hello'||m.type==='ping')(event.source as Window).postMessage({protocol,session,hostStarted:1,type:m.type==='hello'?'ready':'pong'},location.origin);});},{protocol,session});const opened=host.context().waitForEvent('page');await host.evaluate(session=>{(window as any).viewer=window.open('/#suite='+session+'&bridge='+encodeURIComponent(location.origin));},session);const page=await opened;await mockSource(page);await expect(page.locator('.app-shell')).toBeVisible();await send(host,'ready');await send(host,'catalog',{sequence:1,access:access(),cards:['a','b'].map(id=>({...snapshot(id).state,id,inScene:true})),monsters:[],role:'PLAYER',enabled:{characterCards:true},visibility:{wiki:true,monsters:false}});return page;}
const requests=(host:Page,type:string)=>host.evaluate(type=>(window as any).requests.filter((m:any)=>m.type===type),type);

test('cold player navigation renders its warm document without a selection reply or DM switch',async({page:host},info)=>{const page=await pair(host);await send(host,'navigate',{itemId:'card:a'});await expect(page.getByText('读取角色资料…',{exact:true})).toBeVisible();await send(host,'cacheSnapshot',{sequence:2,...snapshot(),access:access()});await expect(page.getByLabel('当前生命值',{exact:true})).toHaveValue('11');await expect(page.getByRole('switch',{name:'编辑模式',exact:true})).toBeEnabled();expect(await requests(host,'select')).toEqual([]);expect(await requests(host,'save')).toEqual([]);await info.attach('cold-player-warm-document',{body:await page.screenshot(),contentType:'image/png'});});

test('revocation disables the full paper immediately and a debounce cannot survive regrant or late ACK',async({page:host},info)=>{const page=await pair(host);await send(host,'navigate',{itemId:'card:a'});await send(host,'selection',{sequence:2,...snapshot(),access:access()});await expect(page.getByRole('switch',{name:'编辑模式',exact:true})).toBeEnabled();await page.getByRole('switch',{name:'编辑模式',exact:true}).click();await expect(page.getByLabel('角色姓名',{exact:true})).toBeEditable();// Pause at the browser's existing time, with a guaranteed earlier install epoch.
 // The final time does not cross a heartbeat/disconnection deadline.
 const clockNow=await page.evaluate(()=>Date.now());await page.clock.install({time:clockNow-60_000});await page.clock.pauseAt(clockNow);await page.getByLabel('角色姓名',{exact:true}).fill('Discarded before revocation');await send(host,'access',{access:access(2,false)});await expect(page.getByRole('switch',{name:'编辑模式',exact:true})).toBeDisabled();// Read-only workbench names deliberately render as buttons, not disabled inputs.
 await expect(page.getByLabel('角色姓名',{exact:true})).toHaveCount(0);await expect(page.locator('.identity-name .assign-token-name')).toHaveText('Discarded before revocation');await expect(page.getByLabel('玩家姓名',{exact:true})).not.toBeEditable();await expect(page.getByLabel('力量基础值',{exact:true})).not.toBeEditable();await send(host,'access',{access:access(3,true)});await page.clock.runFor(150);expect(await requests(host,'save')).toEqual([]);await expect(page.getByRole('switch',{name:'编辑模式',exact:true})).toBeEnabled();await expect(page.getByLabel('角色姓名',{exact:true})).toBeEditable();
 await send(host,'access',{access:access(4,false)});await send(host,'ack',{requestId:'late-previous-owner',ok:true,result:{snapshot:{sequence:50,...snapshot('a',2,'Late owner view'),access:access()}}});await page.clock.runFor(100);await expect(page.getByRole('switch',{name:'编辑模式',exact:true})).toBeDisabled();const rejected=await page.evaluate(async()=>{const modulePath='/src/platform/workbench.ts',api=await import(/* @vite-ignore */ modulePath);try{await api.workbenchRequest('save',{native:{name:'Denied direct write'}});return false;}catch{return true;}});expect(rejected).toBe(true);expect(await requests(host,'save')).toEqual([]);await info.attach('revoked-player-read-only',{body:await page.screenshot(),contentType:'image/png'});
});

test('only the latest cold navigation can be fulfilled and revocation removes a waiting target',async({page:host})=>{const page=await pair(host);await send(host,'navigate',{itemId:'card:a'});await page.getByRole('tab',{name:'Owner fixture b',exact:true}).click();await send(host,'cacheSnapshot',{sequence:2,...snapshot(),access:access()});await expect(page.locator('.paper')).toHaveCount(0);await send(host,'cacheSnapshot',{sequence:3,...snapshot('b'),access:access()});await expect(page.locator('.identity-name .assign-token-name')).toHaveText('Owner fixture b');await send(host,'access',{access:access(2,true,['b'])});await send(host,'navigate',{itemId:'card:a'});await send(host,'access',{access:access(3,true,['b'])});await send(host,'cacheSnapshot',{sequence:4,...snapshot(),access:access()});await expect(page.locator('.paper')).toHaveCount(0);await expect(page.getByText('读取角色资料…',{exact:true})).toHaveCount(0);});
