import {expect,it} from 'vitest';
import {createIdentity} from '../src/data/automation/identity';
import type {Mechanics} from '../src/data/automation/protocol';
import {newCharacter,type Character,type Entry} from '../src/core/model';
import {initializeAutomation,automationEnabled,validateAutomation} from '../src/core/automation/state';
import {evaluate} from '../src/core/engine';
import {syncAutoResources,setResource} from '../src/core/resources';
import {planFeatureResources,restResources} from '../src/core/automation/featureResources';
import {automaticWeaponAttacks} from '../src/core/automation/weapons';
import {sheetChoices,chooseSheetOption,claimStartingEquipment} from '../src/core/automation/choices';
import {validatePack,validateCharacter} from '../src/core/validation';
import {copyWithIrAutomation} from '../src/core/automation/upgrade';
import {bindAutomationCharacter} from '../src/core/automation/binding';
const entry=(kind:Entry['kind'],name:string,mechanics:Mechanics):Entry=>({id:`synthetic:${kind}:${name}`,kind,name,english:name,source:'XPHB',packId:'kiwee',edition:'2024',revision:'synthetic',entries:['获得 99 点 AC，施展任何法术，长休恢复所有次数。'],raw:{_category:kind,speed:99,ac:99,hd:{faces:20},ability:[{str:99}]},automation:{identity:createIdentity({kind,source:'XPHB',engName:name}),verdict:'automated',provenance:[{layer:'structured',ref:'synthetic-reviewed'}],mechanics,unsupported:[]},automationVersion:'synthetic'});
const character=(entries:Entry[],levels:number[]=[]):Character=>{const c=newCharacter();initializeAutomation(c);c.selections=entries.map((entry,index)=>({id:`row-${index}`,entry,level:levels[index]||1,quantity:1,equipped:false}));return c;};
it('calculates IR values independently of hostile raw fields and translated prose, without mutation',()=>{
 const c=character([entry('class','Synthetic class',{classModel:{hitDie:10},grants:[{type:'savingThrow',fixed:['con'],scope:'firstClass'}]}),entry('race','Synthetic race',{modifiers:[{target:'str',op:'add',value:2},{target:'speed.walk',op:'set',value:40},{target:'ac',op:'add',value:5}]})],[3]);const before=structuredClone(c),d=evaluate(c);
 expect(d.abilities.str).toBe(12);expect(d.speed).toBe(40);expect(d.ac).toBe(15);expect(d.maxHp).toBe(22);expect(d.saves.con.proficient).toBe(true);expect(c).toEqual(before);
 c.selections.forEach(row=>{row.entry.raw={};row.entry.entries=[];});expect(evaluate(c).abilities).toEqual(d.abilities);expect(evaluate(c).maxHp).toBe(d.maxHp);
});
it('pending and missing rules are visible and never execute; partial records execute only their declared supported portion',()=>{
 const e=entry('feat','Synthetic partial',{modifiers:[{target:'initiative',op:'add',value:3}]}),c=character([e]);e.automation!.verdict='needsAnnotation';e.automation!.autoGenerated=true;
 expect(evaluate(c).initiative).toBe(0);expect(evaluate(c).issues.some(issue=>issue.id.startsWith('automation-data:'))).toBe(true);
 e.automation!.verdict='unsupported';e.automation!.unsupported=[{code:'deferred-action',family:'combat',deferred:true}];expect(evaluate(c).initiative).toBe(3);expect(evaluate(c).issues.some(issue=>issue.id.startsWith('automation-gap:'))).toBe(true);
});
it('first-class scope does not promote a remaining class when its original first class is disabled',()=>{
 const a=entry('class','Synthetic first',{classModel:{hitDie:10},grants:[{type:'savingThrow',fixed:['str'],scope:'firstClass'}]}),b=entry('class','Synthetic second',{classModel:{hitDie:6},grants:[{type:'savingThrow',fixed:['wis'],scope:'firstClass'}]}),c=character([a,b]);c.profile.disabledEntries=[a.id];expect(evaluate(c).saves.wis.proficient).toBe(false);
});
it('finite resource debt survives lowering, raising, removal, restoration and explicit rest',()=>{
 const c=character([entry('class','Synthetic caster',{classModel:{hitDie:8,casterProgression:'full'}})],[5]);syncAutoResources(c);setResource(c,'spell-slot:3',0);c.selections[0].level=1;syncAutoResources(c);expect(c.runtime.resources['spell-slot:3']).toBeUndefined();c.selections[0].level=5;syncAutoResources(c);expect(c.runtime.resources['spell-slot:3'].current).toBe(0);
 setResource(c,'spell-slot:1',0);c.selections[0].level=1;syncAutoResources(c);expect(c.runtime.resources['spell-slot:1'].current).toBe(0);c.selections[0].level=5;syncAutoResources(c);expect(c.runtime.resources['spell-slot:1'].current).toBe(0);
 restResources(c,'long');expect(c.runtime.resources['spell-slot:3'].current).toBe(2);syncAutoResources(c);expect(c.runtime.resources['spell-slot:3'].current).toBe(2);
});
it('resource dice and dawn recovery remain explicit; missing data preserves the saved counter',()=>{
 const e=entry('feat','Synthetic counter',{resources:[{key:'uses',max:{value:3},recovery:[{period:'short',amount:'1d2'},{period:'dawn',amount:'all'}]}]}),c=character([e]);syncAutoResources(c);const key=planFeatureResources(c).grants[0].key;expect(planFeatureResources(c).issues).toHaveLength(2);setResource(c,key,0);restResources(c,'short');expect(c.runtime.resources[key].current).toBe(0);
 delete e.automation;syncAutoResources(c);expect(c.runtime.resources[key].current).toBe(0);restResources(c,'long');expect(c.runtime.resources[key].current).toBe(0);
});
it('IR armor and weapon bonuses respect equipment and attunement, without applying a generic weapon bonus twice',()=>{
 const armor=entry('item','Synthetic armor',{equipmentModel:{category:'lightArmor',ac:11,requiresAttunement:true},modifiers:[{target:'ac',op:'add',value:2}]}),weapon=entry('item','Synthetic blade',{equipmentModel:{category:'weapon',weaponType:'melee',weaponCategory:'simple',damage:'1d6',attackBonus:2,damageBonus:2,properties:['F'],requiresAttunement:true}}),c=character([armor,weapon]);c.abilities.dex=16;c.training={weapons:'simple'};c.selections.forEach(row=>row.equipped=true);
 expect(evaluate(c).ac).toBe(14);expect(automaticWeaponAttacks(c,evaluate(c)).attacks[0].attack_bonus).toBe(5);c.selections.forEach(row=>row.attuned=true);expect(evaluate(c).ac).toBe(16);expect(automaticWeaponAttacks(c,evaluate(c)).attacks[0].damage).toBe('1d6+5');
});
it('declared choices retain legacy skill answer keys and never invent a choice from prose',()=>{
 const e=entry('background','Synthetic choices',{grants:[{type:'skillProficiency',key:'skillProficiencies:0',choose:{count:1,from:['arcana','history']}}]}),c=character([e]);const choice=sheetChoices(c)[0];expect(choice.id).toBe('row-0:skills:0');chooseSheetOption(c,choice.id,'arcana');expect(evaluate(c).skills.arcana.value).toBe(2);delete e.automation;expect(sheetChoices(c)).toHaveLength(0);
});
it('an unresolved equipment part blocks the entire chosen package before coins, items or receipts change',()=>{
 const e=entry('background','Synthetic equipment',{startingEquipment:{scope:'all',blocks:[{key:'0',options:[{key:'a',items:[{copper:500},{unresolved:true}]}]}]}}),c=character([e]),before=structuredClone(c),choice=sheetChoices(c)[0];expect(()=>claimStartingEquipment(c,choice.id,'a',[])).toThrow(/未发放/);expect(c).toEqual(before);
});
it('RulePack 1 converts explicit effects and choices once; raw fields remain display only',()=>{
 const pack=validatePack({schemaVersion:1,id:'synthetic.pack',name:'Synthetic pack',version:'1.0.0',editions:['2024'],requires:[],conflicts:[],entries:[{id:'notes',kind:'feat',name:'自定义笔记',entries:['获得 99 点智力。'],raw:{ability:[{int:99}]},effects:[{op:'add',target:'int',value:1}],choices:[{id:'knowledge',label:'知识',count:1,options:['arcana','history']}]}]},[]),c=character(pack.entries);c.profile.enabledSources.push(pack.id);chooseSheetOption(c,'row-0:custom:knowledge','history');expect(evaluate(c).abilities.int).toBe(11);expect(evaluate(c).skills.history.value).toBe(2);expect(pack.entries[0].automation?.identity.engName).not.toMatch(/笔记/);expect(()=>validateCharacter(c)).not.toThrow();
});
it('protocol 2 remains unchanged at load and sync; explicit upgrade creates a copy and does not replenish unknown counters',()=>{
 const c=character([entry('feat','Synthetic upgrade',{resources:[{key:'new',max:{value:2},recovery:[{period:'long',amount:'all'}]}]})]);c.automation={protocol:2,enabled:true,defaultsVersion:1,rulesVersion:'equipment.1'};c.runtime.resources.saved={max:3,current:1};const before=structuredClone(c);expect(automationEnabled(c)).toBe(false);expect(bindAutomationCharacter(c,undefined,[])).toBe(c);syncAutoResources(c);expect(c).toEqual(before);const copy=copyWithIrAutomation(c,[]);expect(copy.id).not.toBe(c.id);expect(copy.automation?.protocol).toBe(3);expect(Object.values(copy.runtime.resources).find(resource=>resource.featureGrant)?.current).toBe(0);expect(copy.runtime.resources.saved.current).toBe(1);expect(c).toEqual(before);expect(()=>validateAutomation({protocol:2,enabled:'yes',rulesVersion:'equipment.1'})).toThrow();
});
it('validates embedded IR again when copying protocol 2, and never trusts a custom version marker alone',()=>{
 const forged=entry('feat','Forged custom',{modifiers:[{target:'ac',op:'add',value:99}]});forged.source='CUSTOM';forged.packId='custom';forged.automationVersion='custom:synthetic';forged.automation!.identity.key='forged';forged.automation!.provenance=[{layer:'rulePack',ref:'forged'}];const c=character([forged]);c.profile.enabledSources.push('CUSTOM');c.automation={protocol:2,enabled:true,rulesVersion:'equipment.1'};const before=structuredClone(c);expect(validateCharacter(c)).toEqual(c);expect(()=>copyWithIrAutomation(c,[])).toThrow(/IR/);expect(c).toEqual(before);
});
it('keeps pact consumption across spell-level changes, source toggles, imports, and an explicit rest',()=>{
 const c=character([entry('class','Synthetic pact',{classModel:{hitDie:8,casterProgression:'pact'}})],[3]);syncAutoResources(c);setResource(c,'pact-slot:2',0);c.selections[0].level=5;syncAutoResources(c);expect(c.runtime.resources['pact-slot:3']).toMatchObject({max:2,current:0,automaticSpent:2});c.selections[0].level=1;syncAutoResources(c);expect(c.runtime.resources['pact-slot:1'].current).toBe(0);const restored=validateCharacter(JSON.parse(JSON.stringify(c)));restored.selections[0].level=5;syncAutoResources(restored);expect(restored.runtime.resources['pact-slot:3'].current).toBe(0);restored.profile.enabledSources=[];syncAutoResources(restored);restored.profile.enabledSources=['XPHB'];syncAutoResources(restored);expect(restored.runtime.resources['pact-slot:3'].current).toBe(0);restResources(restored,'short');restored.selections[0].level=3;syncAutoResources(restored);expect(restored.runtime.resources['pact-slot:2'].current).toBe(2);
});

it('binds a feature class formula to its actual parent across same-name editions, ordering and resource debt',()=>{
 const current=entry('class','Fighter',{classModel:{hitDie:10}}),legacy=entry('class','Fighter',{classModel:{hitDie:10}});
 legacy.id+=':legacy';legacy.source='PHB';legacy.edition='2014';legacy.automation!.identity=createIdentity({kind:'class',source:'PHB',engName:'Fighter'});
 const feature=entry('feature','Synthetic parent-bound counter',{resources:[{key:'uses',max:{formula:'min(1, floor(@classes.fighter.levels / 2)) + min(1, floor(@classes.fighter.levels / 17))'},recovery:[{period:'short',amount:'all'}]}]});
 feature.automation!.identity=createIdentity({kind:'classFeature',source:'XPHB',engName:feature.english,classEngName:'Fighter',classSource:'XPHB',level:2});
 const c=character([current,legacy,feature],[2,17,2]),own=c.selections[0],other=c.selections[1],child=c.selections[2];child.parentId=own.id;
 expect(planFeatureResources(c).grants.map(grant=>grant.max)).toEqual([1]);
 c.selections=[other,child,own];expect(planFeatureResources(c).grants.map(grant=>grant.max)).toEqual([1]);
 c.selections=[own,child,other];other.level=20;expect(planFeatureResources(c).grants.map(grant=>grant.max)).toEqual([1]);
 syncAutoResources(c);const key=planFeatureResources(c).grants[0].key;setResource(c,key,0);
 own.level=17;syncAutoResources(c);expect(c.runtime.resources[key]).toMatchObject({max:2,current:1});
 own.level=2;syncAutoResources(c);expect(c.runtime.resources[key]).toMatchObject({max:1,current:0});
 c.selections=[child,other];syncAutoResources(c);expect(planFeatureResources(c).grants).toEqual([]);expect(c.runtime.resources[key]).toBeUndefined();
 c.selections=[own,child,other];syncAutoResources(c);expect(c.runtime.resources[key]).toMatchObject({max:1,current:0});
 c.profile.enabledSources=['PHB'];syncAutoResources(c);expect(planFeatureResources(c).grants).toEqual([]);
 c.profile.enabledSources=['PHB','XPHB'];syncAutoResources(c);expect(c.runtime.resources[key]).toMatchObject({max:1,current:0});
});

it('keeps an unowned class alias visibly unbound when ambiguous and preserves debt when a unique binding returns',()=>{
 const current=entry('class','Fighter',{classModel:{hitDie:10}}),legacy=entry('class','Fighter',{classModel:{hitDie:10}});
 legacy.id+=':legacy';legacy.source='PHB';legacy.edition='2014';legacy.automation!.identity=createIdentity({kind:'class',source:'PHB',engName:'Fighter'});
 const item=entry('item','Synthetic unowned class counter',{equipmentModel:{category:'wondrous'},resources:[{key:'uses',max:{formula:'@classes.fighter.levels'},recovery:[{period:'short',amount:'all'}]}]});
 const c=character([current,legacy,item],[3,17]),own=c.selections[0],other=c.selections[1],held=c.selections[2];held.equipped=true;
 const ambiguous=planFeatureResources(c);expect(ambiguous.grants).toEqual([]);expect(ambiguous.issues).toEqual(expect.arrayContaining([expect.objectContaining({id:`resource:${held.id}:0`,severity:'warning',message:expect.stringContaining('未执行资源规则')})]));
 syncAutoResources(c);expect(Object.values(c.runtime.resources).filter(resource=>resource.featureGrant)).toEqual([]);
 c.selections=[own,held];syncAutoResources(c);const key=planFeatureResources(c).grants[0].key;expect(c.runtime.resources[key]).toMatchObject({max:3,current:3});setResource(c,key,0);
 c.selections=[own,other,held];syncAutoResources(c);expect(c.runtime.resources[key]).toBeUndefined();restResources(c,'short');
 c.selections=[own,held];syncAutoResources(c);expect(c.runtime.resources[key]).toMatchObject({max:3,current:0});
});
