import {it,expect} from 'vitest';
import {newCharacter} from '../src/core/model';
import {initializeAutomation,newAutomationState,setAutomationEnabled,validateAutomation} from '../src/core/automation/state';
it('enables a validated old card once while retaining existing choices, money and resource use',()=>{const c=newCharacter();c.answers.original=['selected'];c.inventory={view:'grid',order:[],attunementLimit:3,coins:{gp:7,sp:0,cp:0,pp:0,ep:0}};c.runtime.resources.used={name:'Used',max:4,current:1};const before=structuredClone(c);expect(initializeAutomation(c)).toBe(true);expect(c.automation?.enabled).toBe(true);expect(c.answers).toEqual(before.answers);expect(c.inventory).toEqual(before.inventory);expect(c.runtime).toEqual(before.runtime);expect(c.selections).toEqual(before.selections);expect(initializeAutomation(c)).toBe(false);});
it('initializes an unreceipted IR state then persists later deliberate opt-outs through loading',()=>{const c=newCharacter();c.automation={protocol:3,rulesVersion:'ir.1',enabled:false,spellChoices:{gift:['ref']}};expect(initializeAutomation(c)).toBe(true);expect(c.automation.spellChoices).toEqual({gift:['ref']});setAutomationEnabled(c,false);const restored=JSON.parse(JSON.stringify(c));validateAutomation(restored.automation);expect(initializeAutomation(restored)).toBe(false);expect(restored.automation.enabled).toBe(false);});
it('preserves unknown protocol and rule versions without executing or converting them',()=>{for(const state of [{protocol:999,enabled:false,original:{a:1}},{protocol:2,enabled:false,rulesVersion:'future'}]){const c=newCharacter();c.automation=state;const before=JSON.stringify(c);expect(initializeAutomation(c)).toBe(false);expect(JSON.stringify(c)).toBe(before);}});
it('new state is enabled and already has the default migration receipt',()=>{const c=newCharacter();c.automation=newAutomationState();expect(initializeAutomation(c)).toBe(false);expect(c.automation.enabled).toBe(true);});

it('keeps protocol 2 opt-outs and choices intact and requires a copy for upgrade',()=>{const c=newCharacter();c.automation={protocol:2,enabled:false,rulesVersion:'equipment.1',spellChoices:{gift:['ref']}};const before=structuredClone(c);expect(initializeAutomation(c)).toBe(false);expect(c).toEqual(before);expect(()=>setAutomationEnabled(c,true)).toThrow(/协议/);expect(c).toEqual(before);});
