import {it,expect} from 'vitest';
import {newCharacter,type Entry} from '../src/core/model';
import {evaluate,candidateReason} from '../src/core/engine';
import {syncFeatures,removeSelection} from '../src/core/sheet';
import {validateCharacter,importOwlbear} from '../src/core/validation';
import {exportOwlbear} from '../src/core/export';
import {inventoryState,spellState,spellValues,carriedWeight} from '../src/core/characterDetails';
const entry=(kind:Entry['kind'],name:string,raw:Entry['raw']={}):Entry=>({id:name,name,english:name,kind,source:'XPHB',edition:'2024',packId:'test',revision:'1',entries:[],raw});
it('subclasses require their declared class and edition, including multiclass',()=>{const c=newCharacter(),sub=entry('subclass','子职',{className:'法师',classSource:'XPHB'});expect(candidateReason(c,sub)).toBeTruthy();c.selections.push({id:'wizard',entry:entry('class','法师'),level:2,quantity:1,equipped:false});expect(candidateReason(c,sub)).toBeUndefined();expect(candidateReason(c,{...sub,raw:{className:'战士',classSource:'XPHB'}})).toBeTruthy();expect(candidateReason(c,{...sub,raw:{className:'法师',classSource:'PHB'}})).toBeTruthy();});
it('background grants separate feat and equipment; changes and repeated sync never mint extra coins',()=>{const c=newCharacter(),feat=entry('feat','笔记'),item=entry('item','书',{weight:3}),bg=entry('background','学者',{ability:[{choose:{from:['int','wis'],amount:2}}],skillProficiencies:[{history:true}],feats:[{'笔记|XPHB':true}],startingEquipment:[{A:[{item:'书|XPHB',quantity:2},{value:800}],B:[{value:5000}]}]});c.selections.push({id:'bg',entry:bg,quantity:1,level:1,equipped:false});syncFeatures(c,[feat,item]);expect(c.selections.some(s=>s.entry.kind==='feat')).toBe(true);expect(c.selections.some(s=>s.entry.kind==='item')).toBe(false);c.backgroundChoices={bg:{abilities:{int:2},equipment:{'0':'A'}}};syncFeatures(c,[feat,item]);expect(evaluate(c).abilities.int).toBe(10);expect(evaluate(c).skills.history.proficient).toBe(true);expect(carriedWeight(c).items).toBe(6);expect(inventoryState(c).coins.gp).toBe(8);expect(syncFeatures(c,[feat,item])).toBe(false);c.backgroundChoices.bg.equipment!['0']='B';syncFeatures(c,[feat,item]);expect(c.inventory?.coins.gp).toBe(50);expect(c.selections.some(s=>s.entry.kind==='item')).toBe(false);c.inventory!.coins.gp=30;syncFeatures(c,[feat,item]);expect(c.inventory!.coins.gp).toBe(30);removeSelection(c,'bg');expect(c.selections).toHaveLength(0);});
it('speed uses numeric and conditional walking data, then applies modifiers',()=>{const c=newCharacter();for(const speed of [35,{walk:35,fly:60},{walk:{number:35,condition:'测试'}}]){c.selections=[{id:'race',entry:entry('race','旅人',{speed}),quantity:1,level:1,equipped:false}];c.sheetBonuses={speed:5};expect(evaluate(c).speed).toBe(40);}});
it('extended page settings roundtrip safely and spell values follow manual casting settings',()=>{const c=newCharacter();c.biography={story:'人物故事'};c.palette={frame:'#123456'};c.inventory=inventoryState(c);c.spellSettings=spellState(c);c.spellSettings.ability='wis';c.spellSettings.capacity=4;c.spellSettings.slots={'1':{max:4,used:2}};c.abilities.wis=16;expect(spellValues(c,evaluate(c))).toEqual({attack:5,dc:13});expect(validateCharacter(c)).toEqual(c);expect(()=>validateCharacter({...c,portrait:{data:'javascript:bad',x:0,y:0,zoom:1}})).toThrow();expect(()=>validateCharacter({...c,spellSettings:{...c.spellSettings,capacity:1000000}})).toThrow();});

it('Owlbear export preserves configured spell totals, slots, attunement and currency',()=>{const c=newCharacter();c.spellSettings={...spellState(c),ability:'wis',attackBonus:2,dcBonus:1,slots:{'1':{max:4,used:2}}};c.abilities.wis=16;c.inventory=inventoryState(c);c.inventory.coins.gp=23;c.selections=[{id:'staff',entry:entry('item','法杖',{weight:4}),quantity:2,level:1,equipped:true,attuned:true}];const output=exportOwlbear(c,evaluate(c));expect(output.spellcasting.attack_bonus).toBe(7);expect(output.spellcasting.save_dc).toBe(14);expect(output.spellcasting.spell_slots['1']).toEqual({max:4,current:2});const restored=importOwlbear(output);expect(restored.spellSettings?.slots['1']).toEqual({max:4,used:2});expect(spellValues(restored,evaluate(restored))).toEqual({attack:7,dc:14});expect(restored.inventory?.coins.gp).toBe(23);expect(restored.selections.find(s=>s.entry.kind==='item')?.attuned).toBe(true);});
