import {afterEach,describe,expect,it} from 'vitest';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {CloudStore} from '../server/cloud/store';
import {createCloudServer} from '../server/cloud/server';
import {newCharacter} from '../src/core/model';

const stores:CloudStore[]=[],paths:string[]=[];
afterEach(()=>{stores.splice(0).forEach(store=>store.close());paths.splice(0).forEach(path=>rmSync(path,{recursive:true,force:true}));});
const setup=()=>{const store=new CloudStore(':memory:');stores.push(store);const owner=store.provisionVerifiedAccount('provider:owner','1234567'),editor=store.provisionVerifiedAccount('provider:editor','2345678'),stranger=store.provisionVerifiedAccount('provider:stranger','3456789');return {store,owner,editor,stranger};};
const completeCard=()=>{const card=newCharacter('2014');card.name='完整测试冒险者';card.biography={story:'五页故事，保留未知内容。'};card.notes='背景与手工记录';card.runtime.resources={custom:{current:2,max:9,name:'已消耗资源'}};card.externalSnapshot={unknown:{value:'未映射原文'}};card.automation={protocol:2,rulesVersion:'equipment.1',defaultsVersion:1,enabled:false};return card;};

describe('authoritative cloud storage',()=>{
 it('stores the whole original document without regranting or changing edition',()=>{const {store,owner}=setup(),input=completeCard();const saved=store.create(owner,input);expect(saved.id).not.toBe(input.id);expect(store.read(saved.id).character).toEqual(input);expect(store.read(saved.id).role).toBeUndefined();expect(store.read(saved.id)).not.toHaveProperty('editors');});
 it('server enforces ten owned cards and recovers a slot on owner delete',()=>{const {store,owner}=setup();const cards=Array.from({length:10},()=>store.create(owner,newCharacter()));expect(()=>store.create(owner,newCharacter())).toThrow('槽位');expect(store.slots(owner).used).toBe(10);store.delete(cards[0].id,owner,1);expect(store.create(owner,newCharacter()).id).not.toBe(cards[0].id);});
 it('granted cards use only owner quota and verified QQ identities',()=>{const {store,owner,editor,stranger}=setup(),card=store.create(owner,newCharacter());store.grant(card.id,owner,editor.qq);expect(store.list(editor)).toHaveLength(1);expect(store.slots(editor).used).toBe(0);expect(store.list(stranger)).toEqual([]);const anonymousQQ=store.provisionVerifiedAccount('provider:unverified');expect(store.list(anonymousQQ)).toEqual([]);});
 it('editors cannot grant, revoke or delete; revocation immediately blocks writes',()=>{const {store,owner,editor}=setup(),card=store.create(owner,newCharacter());store.grant(card.id,owner,editor.qq);expect(()=>store.grant(card.id,editor,'4567890')).toThrow('卡主');expect(()=>store.grant(card.id,editor,editor.qq,true)).toThrow('卡主');expect(()=>store.delete(card.id,editor,1)).toThrow('卡主');const saved=store.update(card.id,editor,1,{...card.character,name:'编辑者修改'});store.grant(card.id,owner,editor.qq,true);expect(()=>store.update(card.id,editor,saved.revision,card.character)).toThrow('撤销');expect(store.list(editor)).toEqual([]);});
 it('CAS conflicts preserve the input draft and the winning cloud revision',()=>{const {store,owner,editor}=setup(),card=store.create(owner,newCharacter());store.grant(card.id,owner,editor.qq);store.update(card.id,owner,1,{...card.character,name:'领先修改'});const draft={...card.character,name:'本机冲突草稿',runtime:{...card.character.runtime,hp:17}};const old=structuredClone(draft);expect(()=>store.update(card.id,editor,1,draft)).toThrow('草稿保留');expect(draft).toEqual(old);expect(store.read(card.id).character.name).toBe('领先修改');});
 it('validates complete imports before mutation',()=>{const {store,owner}=setup();expect(()=>store.create(owner,{name:'仅界面单文件'})).toThrow();expect(store.slots(owner).used).toBe(0);const card=store.create(owner,newCharacter());expect(()=>store.update(card.id,owner,1,{...card.character,abilities:{str:0}})).toThrow();expect(store.read(card.id).revision).toBe(1);});
 it('persistent database recovery retains grants, spent resources and CAS',()=>{const path=mkdtempSync(join(tmpdir(),'dnd-cloud-'));paths.push(path);const filename=join(path,'cards.sqlite');let store=new CloudStore(filename);const owner=store.provisionVerifiedAccount('owner','1234567'),editor=store.provisionVerifiedAccount('editor','2345678');let card;try{card=store.create(owner,completeCard());store.grant(card.id,owner,editor.qq);}finally{store.close();}store=new CloudStore(filename);stores.push(store);expect(store.read(card.id,editor).role).toBe('editor');expect(store.read(card.id).character.runtime.resources.custom.current).toBe(2);expect(()=>store.update(card.id,owner,0,card.character)).toThrow('修订号');});
 it('quota remains atomic across two connections',()=>{const path=mkdtempSync(join(tmpdir(),'dnd-cloud-'));paths.push(path);const filename=join(path,'cards.sqlite'),a=new CloudStore(filename),b=new CloudStore(filename);stores.push(a,b);const account=a.provisionVerifiedAccount('owner');for(let i=0;i<9;i++)a.create(account,newCharacter());b.create(account,newCharacter());expect(()=>a.create(account,newCharacter())).toThrow('槽位');expect(a.slots(account).used).toBe(10);});
 it('permanent slots are server-owned, two yuan each, with payment disabled',()=>{const {store,owner}=setup();store.db.prepare('UPDATE accounts SET extra_slots=2 WHERE id=?').run(owner.id);expect(store.slots(owner)).toMatchObject({free:10,permanent:2,total:12,priceYuan:2,paymentAvailable:false});});
});

describe('real HTTP, pending identity and mutation protection',()=>{
 async function run(action:(base:string,store:CloudStore,owner:ReturnType<CloudStore['provisionVerifiedAccount']>,headers:Record<string,string>)=>Promise<void>){
  const {store,owner}=setup(),session=store.issueVerifiedSession(owner.id),origin='https://dnd.center',server=createCloudServer(store,origin);await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const address=server.address() as {port:number};
  try{await action('http://127.0.0.1:'+address.port,store,owner,{'Content-Type':'application/json',Origin:origin,Cookie:'dnd_cloud='+session.token,'X-CSRF-Token':session.csrf});}finally{await new Promise<void>(resolve=>server.close(()=>resolve()));}
 }
 it('guest by-ID access works, global directory is denied and mock QQ routes do not exist',()=>run(async(base,store,owner)=>{const card=store.create(owner,newCharacter());expect((await fetch(base+'/api/cards/'+card.id)).status).toBe(200);expect((await fetch(base+'/api/cards')).status).toBe(401);for(const path of ['/api/auth/mock','/api/auth/qq/mock','/api/auth/qq/callback?qq=1234567','/api/register'])expect((await fetch(base+path)).status).toBe(404);expect((await fetch(base+'/api/auth/qq/login')).status).toBe(503);expect(await (await fetch(base+'/api/session')).json()).toMatchObject({authenticated:false,qqLogin:'pending'});}));
 it('requires explicit confirmation, session identity, same origin and CSRF',()=>run(async(base,store,owner,headers)=>{const body=JSON.stringify({character:newCharacter(),confirmUpload:true});expect((await fetch(base+'/api/cards',{method:'POST',headers:{'Content-Type':'application/json'},body})).status).toBe(401);expect((await fetch(base+'/api/cards',{method:'POST',headers:{...headers,Origin:'https://evil.example'},body})).status).toBe(403);expect((await fetch(base+'/api/cards',{method:'POST',headers:{...headers,'X-CSRF-Token':'wrong'},body})).status).toBe(403);expect((await fetch(base+'/api/cards',{method:'POST',headers,body:JSON.stringify({character:newCharacter()})})).status).toBe(400);expect(store.slots(owner).used).toBe(0);expect((await fetch(base+'/api/cards',{method:'POST',headers,body})).status).toBe(201);}));
 it('does not trust a hand-filled QQ or owner/slots field',()=>run(async(base,store,owner,headers)=>{const response=await fetch(base+'/api/cards',{method:'POST',headers,body:JSON.stringify({character:newCharacter(),qq:'2345678',owner_id:'attacker',extra_slots:999,confirmUpload:true})});const card=await response.json();expect(store.read(card.id,owner).role).toBe('owner');expect(store.slots(owner).total).toBe(10);}));
 it('rejects dangerous JSON and has no CORS or API caching',()=>run(async(base,store,owner,headers)=>{const response=await fetch(base+'/api/cards',{method:'POST',headers,body:'{"__proto__":{"admin":true}}'});expect(response.status).toBe(400);const health=await fetch(base+'/api/health');expect(health.headers.get('cache-control')).toBe('no-store');expect(health.headers.get('access-control-allow-origin')).toBeNull();expect(await health.json()).toMatchObject({publicDirectory:false,paymentAvailable:false});}));
 it('unknown and deleted IDs are unavailable to guests',()=>run(async(base,store,owner)=>{expect((await fetch(base+'/api/cards/not-an-id')).status).toBe(404);const card=store.create(owner,newCharacter());store.delete(card.id,owner,1);expect((await fetch(base+'/api/cards/'+card.id)).status).toBe(404);}));
 it('expired and logged-out sessions cannot mutate',()=>run(async(base,store,owner,headers)=>{const expired=store.issueVerifiedSession(owner.id,-1);expect(store.session(expired.token)).toBeUndefined();expect((await fetch(base+'/api/logout',{method:'POST',headers})).status).toBe(200);expect((await fetch(base+'/api/cards',{method:'POST',headers,body:JSON.stringify({character:newCharacter(),confirmUpload:true})})).status).toBe(401);}));
});

describe('temporary public upload with authoritative IP quota',()=>{
 async function run(action:(base:string,store:CloudStore,client:(ip?:string)=>Promise<Record<string,string>>)=>Promise<void>,freeBytes?:()=>number){
  const store=new CloudStore(':memory:');stores.push(store);const origin='https://dnd.center',server=createCloudServer(store,origin,{temporaryUpload:true,trustedLoopbackProxy:true,freeBytes});await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));const base='http://127.0.0.1:'+(server.address() as {port:number}).port;
  const client=async(ip='198.51.100.8')=>{const response=await fetch(base+'/api/session',{headers:{'X-Real-IP':ip}}),data=await response.json();expect(data.authenticated).toBe(false);expect(data.uploadOwner.id).toMatch(/^temporary:/);return {'Content-Type':'application/json',Origin:origin,'X-Real-IP':ip,Cookie:response.headers.get('set-cookie')!.split(';')[0],'X-CSRF-Token':data.csrf};};
  try{await action(base,store,client);}finally{await new Promise<void>(resolve=>server.close(()=>resolve()));}
 }
 const payload=(character=completeCard())=>JSON.stringify({character,confirmUpload:true,confirmPublicTemporary:true});
 it('creates a complete short-ID card without pretending to log in and exposes the directory to guests',()=>run(async(base,store,client)=>{const headers=await client(),input=completeCard(),response=await fetch(base+'/api/cards',{method:'POST',headers,body:payload(input)});expect(response.status).toBe(201);const card=await response.json();expect(card.id).toMatch(/^[A-Z]{6}$/);expect(card.character).toEqual(input);const directory=await(await fetch(base+'/api/cards',{headers:{'X-Real-IP':'203.0.113.9'}})).json();expect(directory.cards).toHaveLength(1);expect(directory.cards[0]).not.toHaveProperty('role');expect(await(await fetch(base+'/api/cards/'+card.id)).json()).toMatchObject({character:input});expect(store.db.prepare('SELECT COUNT(*) n FROM accounts').get()).toEqual({n:0});expect(await(await fetch(base+'/api/policy')).json()).toMatchObject({publicDirectory:true,temporaryUpload:true,quotaScope:'ip'});}));
 it('ten cards share one IP quota across eleven independent browser identities and spoofed forwarding fields',()=>run(async(base,store,client)=>{for(let i=0;i<10;i++){const headers=await client();expect((await fetch(base+'/api/cards',{method:'POST',headers:{...headers,'X-Forwarded-For':'192.0.2.'+i},body:payload()})).status).toBe(201);}const headers=await client();const denied=await fetch(base+'/api/cards',{method:'POST',headers,body:payload()});expect(denied.status).toBe(409);expect((await denied.json()).error).toBe('ip_quota_full');expect(store.temporarySlots('198.51.100.8').used).toBe(10);const other=await client('203.0.113.9');expect((await fetch(base+'/api/cards',{method:'POST',headers:other,body:payload()})).status).toBe(201);}));
 it('requires both explicit public-warning consent, same origin and CSRF',()=>run(async(base,store,client)=>{const headers=await client();for(const body of [JSON.stringify({character:completeCard(),confirmUpload:true}),JSON.stringify({character:completeCard(),confirmPublicTemporary:true})])expect((await fetch(base+'/api/cards',{method:'POST',headers,body})).status).toBe(400);expect((await fetch(base+'/api/cards',{method:'POST',headers:{...headers,Origin:'https://evil.example'},body:payload()})).status).toBe(403);expect((await fetch(base+'/api/cards',{method:'POST',headers:{...headers,'X-CSRF-Token':'bad'},body:payload()})).status).toBe(403);expect(store.temporarySlots('198.51.100.8').used).toBe(0);}));
 it('only the upload browser may edit or delete, conflicts preserve the draft, and delete frees the original IP slot',()=>run(async(base,store,client)=>{const headers=await client(),stranger=await client();const card=await(await fetch(base+'/api/cards',{method:'POST',headers,body:payload()})).json();const update=JSON.stringify({character:{...card.character,name:'先保存'},revision:1,confirmUpload:true,confirmPublicTemporary:true});expect((await fetch(base+'/api/cards/'+card.id,{method:'PUT',headers:stranger,body:update})).status).toBe(403);expect((await fetch(base+'/api/cards/'+card.id,{method:'DELETE',headers:stranger,body:JSON.stringify({revision:1})})).status).toBe(403);expect((await fetch(base+'/api/cards/'+card.id,{method:'PUT',headers,body:update})).status).toBe(200);const conflict=await fetch(base+'/api/cards/'+card.id,{method:'PUT',headers,body:update});expect(conflict.status).toBe(409);expect((await conflict.json()).message).toContain('草稿保留');expect((await fetch(base+'/api/cards/'+card.id+'/editors',{method:'POST',headers,body:JSON.stringify({qq:'1234567'})})).status).toBe(503);expect((await fetch(base+'/api/cards/'+card.id,{method:'DELETE',headers,body:JSON.stringify({revision:1})})).status).toBe(409);expect((await fetch(base+'/api/cards/'+card.id,{method:'DELETE',headers,body:JSON.stringify({revision:2})})).status).toBe(200);expect(store.temporarySlots('198.51.100.8').used).toBe(0);expect(store.db.prepare('SELECT id FROM cloud_ids WHERE id=?').get(card.id)).toEqual({id:card.id});}));
 it('public directory pagination does not hide additional cards',()=>run(async(base,store,client)=>{for(const ip of ['198.51.100.8','203.0.113.9']){const headers=await client(ip);for(let i=0;i<10;i++)expect((await fetch(base+'/api/cards',{method:'POST',headers,body:payload()})).status).toBe(201);}const get=async(offset:number)=>(await(await fetch(base+'/api/cards?offset='+offset+'&limit=7',{headers:{'X-Real-IP':'198.51.100.8'}})).json());const a=await get(0),b=await get(7),c=await get(14);expect(a.total).toBe(20);expect(c.hasMore).toBe(false);expect(new Set([...a.cards,...b.cards,...c.cards].map(row=>row.id)).size).toBe(20);}));
 it('rejects malformed proxy IPs and prevents uploads at the disk reserve',()=>run(async(base,store,client)=>{expect((await fetch(base+'/api/session',{headers:{'X-Real-IP':'198.51.100.8,203.0.113.9'}})).status).toBe(400);const headers=await client();expect((await fetch(base+'/api/cards',{method:'POST',headers,body:payload()})).status).toBe(507);expect(store.temporarySlots('198.51.100.8').used).toBe(0);},()=>0));
 it('canonical IPv6 addresses and IPv4-mapped addresses cannot split the quota',async()=>{const {canonicalIP}=await import('../server/cloud/server');expect(canonicalIP('2001:0db8:0000:0000:0000:0000:0000:0001')).toBe(canonicalIP('2001:db8::1'));expect(canonicalIP('::ffff:192.0.2.1')).toBe('192.0.2.1');});
 it('persistent recovery retains anonymous ownership, IP quota and original spent resources',()=>{const folder=mkdtempSync(join(tmpdir(),'dnd-temporary-'));paths.push(folder);const path=join(folder,'cards.sqlite');let store=new CloudStore(path);const issued=store.issueTemporarySession(),card=store.createTemporary(issued.owner,'198.51.100.8',completeCard());store.close();store=new CloudStore(path);stores.push(store);expect(store.temporarySession(issued.token)).toEqual(issued.owner);expect(store.temporarySlots('198.51.100.8').used).toBe(1);expect(store.read(card.id,undefined,issued.owner)).toMatchObject({role:'owner',character:{runtime:{resources:{custom:{current:2}}}}});expect(store.db.prepare('PRAGMA integrity_check').get()).toEqual({integrity_check:'ok'});});
 it('independent database connections share an atomic anonymous quota',()=>{const folder=mkdtempSync(join(tmpdir(),'dnd-ip-quota-'));paths.push(folder);const path=join(folder,'cards.sqlite'),a=new CloudStore(path),b=new CloudStore(path);stores.push(a,b);const first=a.issueTemporarySession().owner,second=b.issueTemporarySession().owner;for(let i=0;i<9;i++)a.createTemporary(first,'192.0.2.1',completeCard());b.createTemporary(second,'192.0.2.1',completeCard());expect(()=>a.createTemporary(first,'192.0.2.1',completeCard())).toThrow('IP');expect(a.temporarySlots('192.0.2.1').used).toBe(10);});
});
