import {resourceEditorDraft} from '../src/ui/resourceEditorDraft';
import {applyPatch} from '../src/core/merge';
import {describe,it,expect,vi} from 'vitest';
import {newCharacter} from '../src/core/model';
import {createDashboardDraft,commitDashboardDraft,settleDashboardSave} from '../src/core/dashboardDraft';
import {normalizeWidget,validWidget,resourceModuleMinimum,resourceModuleContentScale,normalizeModuleWidget,freeDashboardLayout,resourceModules} from '../src/core/resourceWidgets';
import {readCharacter,importOwlbear,validateCharacter} from '../src/core/validation';
import {exportCharacter,exportLinkedOwlbear,exportOwlbear} from '../src/core/export';
import {evaluate} from '../src/core/engine';
import {canDiscardResourceDrafts} from '../src/ui/resourceDraftGuard';
const frame={background:'#dce8f2',borderWidth:0,borderRadius:6,padding:0,gap:0,contentScale:.25};
function card(){const c=newCharacter();c.runtime.resources={focus:{name:'专注',current:3,max:3},other:{name:'子资源',current:2,max:4}};c.quickbarLayout={order:[],hidden:['resource:other'],attacks:normalizeWidget({resourceArea:true}),widgets:{focus:normalizeWidget({style:'ring',w:1,h:1,...frame})}};return c;}
describe('237 frame controls and dense footprints',()=>{
 it('preserves one-cell geometry and appearance across native, linked and projection exports',()=>{const c=card(),runtime=structuredClone(c.runtime);for(const result of [readCharacter(exportCharacter(c)).character,importOwlbear(exportLinkedOwlbear(c,evaluate(c))),importOwlbear(exportOwlbear(c,evaluate(c)))]){expect(result.quickbarLayout?.widgets?.focus).toEqual(c.quickbarLayout?.widgets?.focus);expect(result.runtime.resources.focus).toEqual(runtime.resources.focus);}expect(c.runtime).toEqual(runtime);});
 it('reduces actual grid minimum with scale, preserves the saved compact box and keeps defaults stable',()=>{const c=card(),module=resourceModules(Object.entries(c.runtime.resources),{})[0];expect(resourceModuleMinimum(module,'ring')).toEqual({w:3,h:3});expect(resourceModuleMinimum(module,'ring',.25)).toEqual({w:1,h:1});expect(normalizeModuleWidget(module,c.quickbarLayout!.widgets!.focus)).toMatchObject({w:1,h:1});expect(freeDashboardLayout([module],c.quickbarLayout!.widgets,c.quickbarLayout!.attacks).widgets.focus).toMatchObject({w:1,h:1,...frame});});
 it('allows dense grouped resources without losing their children or balances',()=>{const c=card();c.quickbarLayout!.hidden=[];c.quickbarLayout!.widgets!.focus=normalizeWidget({...frame,style:'poolpips',members:['focus','other'],label:'资源组',w:2,h:1});const module=resourceModules(Object.entries(c.runtime.resources),c.quickbarLayout!.widgets)[0];expect(resourceModuleMinimum(module,'poolpips',.25)).toEqual({w:2,h:1});expect(normalizeModuleWidget(module,c.quickbarLayout!.widgets!.focus)).toMatchObject({w:2,h:1,members:['focus','other']});expect(()=>validateCharacter(c)).not.toThrow();});
 it('merges appearance and compact geometry over concurrent resource consumption',()=>{const base=card(),draft=createDashboardDraft(base),remote=structuredClone(base);draft.quickbarLayout!.widgets!.focus.background='#abcdef';draft.quickbarLayout!.widgets!.focus.borderWidth=3;remote.runtime.resources.focus.current=1;remote.notes='来自远端';const result=commitDashboardDraft(remote,base,draft);expect(result.runtime.resources.focus.current).toBe(1);expect(result.notes).toBe('来自远端');expect(result.quickbarLayout!.widgets!.focus).toMatchObject({...frame,background:'#abcdef',borderWidth:3,w:1,h:1});});
 it.each([{background:'red'},{background:'url(https://example.com)'},{borderWidth:-1},{borderWidth:9},{borderWidth:1.5},{borderRadius:33},{padding:17},{gap:NaN},{contentScale:.2},{w:0},{h:0}])('rejects invalid appearance atomically: %j',invalid=>{const c=card();Object.assign(c.quickbarLayout!.widgets!.focus,invalid);expect(validWidget(c.quickbarLayout!.widgets!.focus)).toBe(false);expect(()=>validateCharacter(c)).toThrow();});
 it('normalizes frame bounds while retaining explicit zero values and transparent background',()=>{expect(normalizeWidget({...frame,background:'transparent',borderWidth:-2,borderRadius:100,padding:0,gap:0})).toMatchObject({background:'transparent',borderWidth:0,borderRadius:32,padding:0,gap:0});});
});
describe('237 nested draft discard gate',()=>{
 it('does not prompt unchanged opening/closing or after a successful save',()=>{const confirm=vi.fn(()=>false);expect(canDiscardResourceDrafts([{scope:'dashboard',dirty:false,busy:false},{scope:'resource-form',dirty:false,busy:false}],confirm)).toBe(true);expect(confirm).not.toHaveBeenCalled();});
 it('prompts once for nested drafts, retains them on cancel and permits confirmed discard',()=>{const active=[{scope:'dashboard' as const,dirty:true,busy:false},{scope:'resource-form' as const,dirty:true,busy:false}],snapshot=structuredClone(active),cancel=vi.fn(()=>false);expect(canDiscardResourceDrafts(active,cancel)).toBe(false);expect(cancel).toHaveBeenCalledTimes(1);expect(active).toEqual(snapshot);expect(canDiscardResourceDrafts(active,()=>true)).toBe(true);});
 it('blocks dismissal while saving and keeps a failed save dirty',()=>{const confirm=vi.fn(()=>true);expect(canDiscardResourceDrafts([{scope:'dashboard',dirty:true,busy:true}],confirm)).toBe(false);expect(confirm).not.toHaveBeenCalled();expect(canDiscardResourceDrafts([{scope:'dashboard',dirty:true,busy:false}],()=>false)).toBe(false);});
});

describe('237 resource form and acknowledgement boundaries',()=>{
 it('preserves absent defaults on unchanged legacy resource forms',()=>{const base={name:'旧资源',current:2,max:3};expect(resourceEditorDraft(base,{name:base.name,current:'2',max:'3',unlimited:false,locked:false,type:'count'})).toEqual(base);});
 it('does not turn a remotely updated source maximum into a manual override',()=>{const base={name:'来源资源',current:2,max:3,featureGrant:{source:'authored',manualMax:false}} as any,remote={...base,current:1,max:4};const next=resourceEditorDraft(base,{name:base.name,current:'2',max:'3',unlimited:false,locked:false,type:'count'});expect(applyPatch(remote,base,next)).toEqual(remote);expect(next.featureGrant?.manualMax).toBe(false);});
 it('waits for a delayed remote acknowledgement after local rejection before reporting failure',async()=>{let acknowledge!:()=>void,finished=false;const remote=new Promise<void>(resolve=>acknowledge=resolve),error=Error('quota');const operation=settleDashboardSave([Promise.reject(error),remote]).catch(reason=>{finished=true;expect(reason).toBe(error);});await Promise.resolve();await Promise.resolve();expect(finished).toBe(false);acknowledge();await operation;expect(finished).toBe(true);});
});

describe('compact artwork scale is not a thumbnail enlargement',()=>{
 it('leaves normal 12-pool template previews at 100 percent even below module minimum geometry',()=>{const module={id:'pool',name:'大额资源组',slots:false,rows:Array.from({length:12},(_,i)=>[String(i),{name:`子项 ${i+1}`,current:88888,max:99999}] as [string,{name:string;current:number;max:number}])};for(const style of ['pool','poolchips','poolbars'] as const){expect(resourceModuleMinimum(module,style)).toEqual({w:8,h:6});expect(resourceModuleContentScale(module,style,{w:6,h:3})).toBe(1);}});
 it('compensates genuinely compact reduced artwork while bounding it to its outer box',()=>{const module={id:'a',name:'A',slots:false,rows:[['a',{current:3,max:3}]] as [string,{current:number;max:number}][]};expect(resourceModuleContentScale(module,'ring',{w:1,h:1,contentScale:.25})).toBe(.75);expect(resourceModuleContentScale(module,'ring',{w:1,h:1,contentScale:.5})).toBe(1);expect(resourceModuleContentScale(module,'ring',{w:3,h:3,contentScale:.5})).toBe(.5);});
});
