import {planClassMigration} from '../src/core/classMigration';
import {irCharacter as newCharacter,normalizeFixtureData as normalizeData} from './helpers/irFixture';
import {describe,it,expect} from 'vitest';
import {type Entry,subclassOwner,editionAllows} from '../src/core/model';

import {candidateReason,evaluate} from '../src/core/engine';
import {hydrateImportedCasting} from '../src/core/castingSnapshot';
import {spellState} from '../src/core/characterDetails';
import {prepareSpellEntry,spellLibrary} from '../src/core/spells';
import {spellOnClassList,casterProfiles} from '../src/core/spellcastingRules';
import {createCustomEntry} from '../src/core/customEntries';
import {parseCustomEntryJson} from '../src/core/customEntrySchema';
import {WorkbenchRevisions} from '../src/core/workbenchRevisions';
const cls=(name:string,ability='int')=>normalizeData({class:[{name,ENG_name:name,source:'XPHB',spellcastingAbility:ability,casterProgression:'full',preparedSpellsProgression:Array(20).fill(6),preparedSpellsChange:'restLong'}]},'fixture')[0];
const spell=(i:number)=>normalizeData({spell:[{name:'测试法术'+i,source:'XPHB',level:1,entries:['自制测试内容'],classes:{fromClassList:[{name:'甲',source:'XPHB'}]}}]},'fixture')[0];
describe('205 user transitions',()=>{
 it('two classes before either subclass retain separate ownership and total level after toggling multiclass',()=>{const c=newCharacter();c.selections=[{id:'a',entry:cls('甲'),level:5,quantity:1,equipped:false}];c.profile.optional.multiclass=true;c.selections.push({id:'b',entry:cls('乙','wis'),level:3,quantity:1,equipped:false});for(const [name,parent] of [['甲','a'],['乙','b']]){const entry=normalizeData({subclass:[{name:name+'子职',source:'XPHB',className:name,classSource:'XPHB'}]},'fixture')[0];expect(candidateReason(c,entry)).toBeUndefined();expect(subclassOwner(c,entry)?.id).toBe(parent);c.selections.push({id:'sub'+parent,entry,parentId:parent,level:1,quantity:1,equipped:false});}expect(evaluate(c).level).toBe(8);c.profile.optional.multiclass=false;c.profile.optional.multiclass=true;expect(evaluate(c).level).toBe(8);expect(c.selections.filter(s=>s.entry.kind==='subclass')).toHaveLength(2);});
 it('capacity 26 permits 8 -> 9 -> 26 and survives JSON roundtrip without duplicate selections',()=>{const c=newCharacter();c.selections=[{id:'a',entry:cls('甲'),level:3,quantity:1,equipped:false}];c.spellSettings={...spellState(c),capacityAdjustment:20};for(let i=0;i<8;i++)expect(prepareSpellEntry(c,spell(i))).toBeTruthy();expect(spellState(c).capacity).toBe(26);expect(prepareSpellEntry(c,spell(8))).toBeTruthy();for(let i=9;i<26;i++)expect(prepareSpellEntry(c,spell(i))).toBeTruthy();expect(prepareSpellEntry(c,spell(26))).toBeUndefined();const round=JSON.parse(JSON.stringify(c));expect(spellState(round).prepared.filter(Boolean)).toHaveLength(26);expect(spellLibrary(round).filter(s=>s.entry.kind==='spell')).toHaveLength(26);});
 it('explicit legacy class review resolves only its own source for spell lists and subclasses',()=>{const c=newCharacter();const imported={...cls('甲'),source:'IMPORTED',packId:'imported',raw:{}};c.selections=[{id:'a',entry:imported,level:3,quantity:1,equipped:false}];const before=structuredClone(c),target=cls('甲');expect(hydrateImportedCasting(c,[target])).toBe(false);expect(c).toEqual(before);Object.assign(c,planClassMigration(c,[target],{a:target.id},{id:'reviewed',now:'2026-10-03T00:00:00Z'}).card);expect(spellOnClassList(spell(0),casterProfiles(c)[0])).toBe(true);const subs=normalizeData({subclass:[{name:'子',source:'PHB',className:'甲',classSource:'PHB'},{name:'子',source:'PHB',className:'甲',classSource:'XPHB'}]},'fixture');expect(subclassOwner(c,subs[0])).toBeUndefined();expect(subclassOwner(c,subs[1])?.id).toBe('a');expect(editionAllows(subs[0],'2024')).toBe(false);expect(editionAllows(subs[1],'2024')).toBe(true);});
 it('bilingual custom entry save and full JSON edit keep independent names in every representation',()=>{const first=createCustomEntry({name:'水晶球',english:'Crystal Orb',type:'item',body:'自制',raw:{name:'旧名',ENG_name:'Old Orb',value:5000,weight:1}});expect(first.raw.name).toBe('水晶球');expect(first.raw.ENG_name).toBe('Crystal Orb');const next=parseCustomEntryJson(JSON.stringify({...first,type:'item'}));expect(next.name).toBe('水晶球');expect(next.english).toBe('Crystal Orb');expect(next.raw.ENG_name).toBe('Crystal Orb');});
 it('same document revision reuses the document but applies a newly granted edit permission',()=>{const revisions=new WorkbenchRevisions(),document={_suiteRevision:2,dnd_card_web:{name:'卡'}};const first=revisions.snapshot({state:{key:'room:card:x',cardId:'x',write:false},document});const granted=revisions.snapshot({state:{key:'room:card:x',cardId:'x',write:true},document:structuredClone(document)});expect(granted.document).toBe(first.document);expect(granted.state.write).toBe(true);});
});
