import {describe,it,expect} from 'vitest';
import {GroupRollTimeline,type GroupRollState} from '../src/platform/groupRoll';
const group=(id:string,visible=true)=>({id,phase:'resolve',targets:[],visible,kind:'save',ability:'dex',variant:'normal'} as GroupRollState);
describe('group bridge ordering',()=>{
 it('rejects older ready, visibility and close within the same host',()=>{const t=new GroupRollTimeline();expect(t.accept(100,2,group('b'))).toBe(true);expect(t.accept(100,1,null)).toBe(false);expect(t.accept(100,1,group('a'))).toBe(false);expect(t.group?.id).toBe('b');expect(t.accept(100,3,group('b',false))).toBe(true);expect(t.accept(100,2,group('b',true))).toBe(false);expect(t.group?.visible).toBe(false);expect(t.accept(100,4,null)).toBe(true);expect(t.accept(100,3,group('b'))).toBe(false);expect(t.group).toBe(null);});
 it('accepts a restarted host initial snapshot and rejects old-host late replies',()=>{const t=new GroupRollTimeline();t.accept(100,9,group('old'));expect(t.accept(200,0,null)).toBe(true);expect(t.accept(100,99,group('old'))).toBe(false);expect(t.accept(200,1,group('new'))).toBe(true);expect(t.group?.id).toBe('new');});
 it('disconnect clears presentation and freezes late state until an authoritative same-version snapshot',()=>{const t=new GroupRollTimeline();t.accept(100,8,group('current'));expect(t.reset(100,true)).toBe(true);expect(t.group).toBeNull();expect(t.accept(100,9,group('late'))).toBe(false);expect(t.accept(100,7,group('older'),true)).toBe(false);expect(t.accept(100,8,group('current'),true)).toBe(true);expect(t.group?.id).toBe('current');});
 it('host advance clears an old group even when the new legacy ready has no group payload',()=>{const t=new GroupRollTimeline();t.accept(100,8,group('current'));expect(t.reset(200)).toBe(true);expect(t.group).toBeNull();expect(t.accept(100,999,group('old'))).toBe(false);expect(t.reset(100,true)).toBe(false);expect(t.accept(200,0,null,true)).toBe(true);expect(t.group).toBeNull();});
});
