import {beforeEach,describe,expect,it,vi} from 'vitest';
import {newCharacter,type Character} from '../src/core/model';
import {createDashboardDraft} from '../src/core/dashboardDraft';
import {exportLinkedOwlbear} from '../src/core/export';
import {evaluate} from '../src/core/engine';
const bridge=vi.hoisted(()=>({state:{online:true,role:'PLAYER',cards:[] as any[]},request:vi.fn()}));
vi.mock('../src/platform/workbench',()=>({getWorkbench:()=>bridge.state,workbenchRequest:bridge.request}));
import {readResourceDashboard,saveResourceDashboard} from '../src/platform/resourceDashboard';
const card={id:'dashboard235',name:'测试卡',write:true,locked:false,inScene:true,itemId:'token',resources:[],stats:{},kind:'character' as const};
let live:Character;
beforeEach(()=>{vi.clearAllMocks();bridge.state={online:true,role:'PLAYER',cards:[{...card}]};live=newCharacter();live.id='native-dashboard235';live.runtime.resources.focus={name:'专注',current:3,max:5};live.quickbarLayout={order:[],hidden:[],widgets:{focus:{x:0,y:0,w:4,h:3,page:0,style:'ring',resourceArea:true}}};bridge.request.mockImplementation(async(type:string,payload:any)=>{if(type==='readCard')return {document:exportLinkedOwlbear(live,evaluate(live))};if(type==='save'){live=structuredClone(payload.native);return {snapshot:{document:exportLinkedOwlbear(live,evaluate(live))}};}throw Error(type);});});
describe('overview dashboard read/merge/receipt',()=>{
 it('opens only through a read, without selecting or writing the card',async()=>{expect(await readResourceDashboard(card)).toEqual(live);expect(bridge.request.mock.calls).toEqual([['readCard',{key:undefined,itemId:'card:dashboard235'}]]);});
 it('saves layout against the latest counters and keeps unrelated character fields',async()=>{const base=structuredClone(live),draft=createDashboardDraft(base);draft.quickbarLayout!.widgets!.focus.color='#334455';live.runtime.resources.focus.current=1;live.notes='远端笔记';const result=await saveResourceDashboard(card,base,draft);expect(result.runtime.resources.focus.current).toBe(1);expect(result.notes).toBe('远端笔记');expect(result.quickbarLayout!.widgets!.focus.color).toBe('#334455');const save=bridge.request.mock.calls.find(([type])=>type==='save')![1];expect(save.statPatch).toEqual({});expect(save.itemId).toBe('card:dashboard235');expect(save.previous.runtime.resources.focus.current).toBe(1);});
 it('rejects conflicting updates without sending a mutation',async()=>{const base=structuredClone(live),draft=createDashboardDraft(base);draft.runtime.resources.focus.current=2;live.runtime.resources.focus.current=1;await expect(saveResourceDashboard(card,base,draft)).rejects.toThrow();expect(bridge.request.mock.calls.every(([type])=>type==='readCard')).toBe(true);});
 it('rechecks revoked permissions after the read before any mutation',async()=>{const base=structuredClone(live),draft=createDashboardDraft(base);draft.quickbarLayout!.widgets!.focus.color='#334455';bridge.request.mockImplementationOnce(async()=>{bridge.state.cards[0].write=false;return {document:exportLinkedOwlbear(live,evaluate(live))};});await expect(saveResourceDashboard(card,base,draft)).rejects.toThrow('不可编辑');expect(bridge.request).toHaveBeenCalledTimes(1);});
 it('rejects reading a read-only or disappeared card and never sends',async()=>{bridge.state.cards=[];await expect(readResourceDashboard(card)).rejects.toThrow('不可编辑');expect(bridge.request).not.toHaveBeenCalled();});
 it('passes terminal failure to the editor and allows a later explicit retry',async()=>{const base=structuredClone(live),draft=createDashboardDraft(base);draft.quickbarLayout!.widgets!.focus.color='#334455';bridge.request.mockImplementationOnce(async()=>({document:exportLinkedOwlbear(live,evaluate(live))})).mockRejectedValueOnce(Error('测试拒绝保存'));await expect(saveResourceDashboard(card,base,draft)).rejects.toThrow('测试拒绝保存');expect(live.quickbarLayout!.widgets!.focus.color).toBeUndefined();expect((await saveResourceDashboard(card,base,draft)).quickbarLayout!.widgets!.focus.color).toBe('#334455');});
});
