import {afterEach,describe,expect,it} from 'vitest';
import {CloudStore,createCloudServer} from '../server/cloud/server';
import {qqReturnTo,type QQConfig} from '../server/cloud/qq';
import {newCharacter} from '../src/core/model';

const origin='https://dnd.center',appId='123456789',openid='A'.repeat(32);
const cleanups:Array<()=>Promise<void>>=[];
afterEach(async()=>{for(const cleanup of cleanups.splice(0))await cleanup();});
async function setup(variant:'ok'|'wrong-app'|'no-profile'='ok'){
  const store=new CloudStore(':memory:'),calls:URL[]=[];
  const qq:QQConfig={appId,appKey:'test-only-not-a-real-key',callback:origin+'/api/auth/qq/callback',fetch:(async(input:URL|RequestInfo)=>{const url=new URL(String(input));calls.push(url);return new Response(url.pathname.endsWith('/token')?'access_token=server-only-token&expires_in=3600':url.pathname.endsWith('/me')?'callback( '+JSON.stringify({client_id:variant==='wrong-app'?'999999999':appId,openid})+' );':JSON.stringify(variant==='no-profile'?{ret:100030}:{ret:0,nickname:'测试玩家',figureurl_qq_2:'https://q1.qlogo.cn/test.png'}));}) as typeof fetch};
  const server=createCloudServer(store,origin,{qq,temporaryUpload:true});await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));
  cleanups.push(async()=>{await new Promise<void>(resolve=>server.close(()=>resolve()));store.close();});
  const base='http://127.0.0.1:'+(server.address() as {port:number}).port;
  const begin=async(returnTo='/library/')=>{const response=await fetch(base+'/api/auth/qq/login?returnTo='+encodeURIComponent(returnTo),{redirect:'manual'});expect(response.status).toBe(302);const url=new URL(response.headers.get('location')!);return {state:url.searchParams.get('state')!,cookie:response.headers.get('set-cookie')!.split(';')[0],response,url};};
  const finish=async(state:string,cookie:string,extra='code=verified-code')=>fetch(base+'/api/auth/qq/callback?state='+state+'&'+extra,{headers:{Cookie:cookie},redirect:'manual'});
  return {store,calls,base,begin,finish};
}
describe('QQ OAuth identity boundary',()=>{
  it('uses Tencent authorization with the registered callback, no secret, and a secure browser-bound state',async()=>{const {begin}=await setup(),{response,url}=await begin();expect(url.origin).toBe('https://graph.qq.com');expect(url.pathname).toBe('/oauth2.0/authorize');expect(url.searchParams.get('redirect_uri')).toBe(origin+'/api/auth/qq/callback');expect(url.searchParams.get('client_id')).toBe(appId);expect(url.href).not.toContain('test-only');expect(response.headers.get('set-cookie')).toMatch(/Secure; HttpOnly; SameSite=Lax/);});
  it('rejects forged, missing, cross-browser and replayed states before provider calls',async()=>{const {begin,finish,calls}=await setup(),a=await begin(),b=await begin();for(const [state,cookie] of [['forged',a.cookie],[a.state,''],[a.state,b.cookie]])expect((await finish(state,cookie)).status).toBe(400);expect(calls).toHaveLength(0);expect((await finish(a.state,a.cookie)).status).toBe(302);expect((await finish(a.state,a.cookie)).status).toBe(400);expect(calls).toHaveLength(3);});
  it('persists one verified account, shared session and profile without exposing tokens or inventing a QQ number',async()=>{const {begin,finish,base,store}=await setup(),start=await begin('/card/?intro=0'),done=await finish(start.state,start.cookie);expect(done.status).toBe(302);expect(done.headers.get('location')).toBe('/card/?intro=0');const cookie=done.headers.getSetCookie().find(value=>value.startsWith('dnd_cloud='))!.split(';')[0];const session=await(await fetch(base+'/api/session',{headers:{Cookie:cookie}})).json();expect(session).toMatchObject({authenticated:true,qqLogin:'ready',account:{qq:null,nickname:'测试玩家',avatar:'https://q1.qlogo.cn/test.png'}});expect(JSON.stringify(session)).not.toMatch(/server-only-token|test-only|AAAAAAAA/);const second=await begin(),secondDone=await finish(second.state,second.cookie);expect(secondDone.status).toBe(302);expect(store.db.prepare('SELECT COUNT(*) n FROM accounts').get()).toEqual({n:1});});
  it('rejects a different provider application and does not create an account',async()=>{const {begin,finish,store}=await setup('wrong-app'),start=await begin();expect((await finish(start.state,start.cookie)).status).toBe(502);expect(store.db.prepare('SELECT COUNT(*) n FROM accounts').get()).toEqual({n:0});});
  it('allows verified login while profile permission is unavailable',async()=>{const {begin,finish}=await setup('no-profile'),start=await begin();expect((await finish(start.state,start.cookie)).status).toBe(302);});
  it('handles authorization cancellation without provisioning identity',async()=>{const {begin,finish,calls,store}=await setup(),start=await begin();expect((await finish(start.state,start.cookie,'error=access_denied')).status).toBe(400);expect(calls).toHaveLength(0);expect(store.db.prepare('SELECT COUNT(*) n FROM accounts').get()).toEqual({n:0});});
  it('preserves existing upload ownership after login without transferring cards to the QQ account',async()=>{const {begin,finish,base,store}=await setup();const guestResponse=await fetch(base+'/api/session'),guest=await guestResponse.json(),guestCookie=guestResponse.headers.get('set-cookie')!.split(';')[0];const owner=store.temporarySession(guestCookie.split('=')[1])!,card=store.createTemporary(owner,'127.0.0.1',newCharacter());const start=await begin(),done=await finish(start.state,start.cookie),loginCookie=done.headers.getSetCookie().find(value=>value.startsWith('dnd_cloud='))!.split(';')[0],cookie=guestCookie+'; '+loginCookie,session=await(await fetch(base+'/api/session',{headers:{Cookie:cookie}})).json();const directory=await(await fetch(base+'/api/cards',{headers:{Cookie:cookie}})).json();expect(directory.mine.map((row:{id:string})=>row.id)).toContain(card.id);expect(store.slots(store.session(loginCookie.split('=')[1])!.account).used).toBe(0);expect((await fetch(base+'/api/cards/'+card.id,{method:'DELETE',headers:{Cookie:cookie,Origin:origin,'X-CSRF-Token':session.csrf,'Content-Type':'application/json'},body:JSON.stringify({revision:1})})).status).toBe(200);expect(guest.authenticated).toBe(false);});
  it('only accepts local landing pages',()=>{for(const value of ['https://evil.example/','//evil.example/','/api/logout','/card/../api/health'])expect(qqReturnTo(value,origin)).toBe('/');expect(qqReturnTo('/library/?q=test',origin)).toBe('/library/?q=test');});
});
