import {describe,it,expect} from 'vitest';
import {newCharacter} from '../src/core/model';
import {moveWidget,normalizeWidget,resourceWidgetLayout,setResourceWidgetStyle,validWidget} from '../src/core/resourceWidgets';
import {readCharacter,validateCharacter,importOwlbear} from '../src/core/validation';
import {exportCharacter,exportLinkedOwlbear,exportOwlbear} from '../src/core/export';
import {evaluate} from '../src/core/engine';
const resource=()=>({name:'原创能量',current:2,max:7,type:'number',locked:true});
describe('DIY resource presentation persistence and layout boundaries',()=>{
 it('paginates 20 resources without overlap or exceeding the fixed grid',()=>{const ids=Array.from({length:20},(_,i)=>String(i)),layout=resourceWidgetLayout(ids);expect(new Set(Object.values(layout).map(w=>w.page)).size).toBe(3);for(const [i,a] of Object.values(layout).entries()){expect(validWidget(a)).toBe(true);for(const b of Object.values(layout).slice(i+1))expect(a.page!==b.page||a.x>=b.x+b.w||a.x+a.w<=b.x||a.y>=b.y+b.h||a.y+a.h<=b.y).toBe(true);}});
 it.each(['nw','n','ne','e','se','s','sw','w'])('clamps %s resize while anchoring the opposite edge',handle=>{const w={x:3,y:2,w:6,h:2,page:0,style:'bar' as const};for(const delta of [-999,999]){const next=moveWidget(w,delta,delta,handle);expect(validWidget(next)).toBe(true);if(handle.includes('w'))expect(next.x+next.w).toBe(w.x+w.w);if(handle.includes('n'))expect(next.y+next.h).toBe(w.y+w.h);}});
 it('moves an edited module first and relocates collisions without losing identities',()=>{const ids=['a','b','c'];const initial=resourceWidgetLayout(ids);const moved=resourceWidgetLayout(ids,{...initial,a:{...initial.a,x:4,w:8}},'a');expect(moved.a.x).toBe(4);expect(moved.a.w).toBe(8);expect(Object.keys(moved).sort()).toEqual(ids);expect(moved.b).not.toEqual(initial.b);expect(resourceWidgetLayout(['c','a'],moved).a).toEqual(moved.a);});
 it('roundtrips native and linked export without changing counters, locks or spell ownership',()=>{const c=newCharacter();c.runtime.resources.energy=resource();c.runtime.resources['spell-slot:1']={name:'1环',current:1,max:4,automatic:true};setResourceWidgetStyle(c,'energy','ring');const before=structuredClone(c.runtime);c.quickbarLayout!.widgets!.energy=moveWidget(c.quickbarLayout!.widgets!.energy,2,1);const json=JSON.parse(JSON.stringify(exportCharacter(c)));const imported=readCharacter(json).character;expect(imported.quickbarLayout).toEqual(c.quickbarLayout);expect(imported.runtime).toEqual(before);const linked=importOwlbear(exportLinkedOwlbear(c,evaluate(c)));expect(linked.quickbarLayout).toEqual(c.quickbarLayout);expect(linked.runtime.resources.energy).toEqual(before.resources.energy);});
 it('compacts sparse imported pages and keeps arbitrary resource IDs safe',()=>{const saved=JSON.parse(JSON.stringify({safe:{...normalizeWidget(),page:2999}}));const layout=resourceWidgetLayout(['safe','__proto__','constructor'],saved);expect(Object.keys(layout)).toHaveLength(3);expect(Object.getPrototypeOf(layout)).toBeNull();expect(layout.safe.page).toBeLessThan(3);expect(Object.values(layout).every(validWidget)).toBe(true);});
 it('rejects corrupt imported geometry and keeps old layout compatible',()=>{const c=newCharacter();c.quickbarLayout={order:[],hidden:[]};expect(()=>validateCharacter(c)).not.toThrow();c.quickbarLayout.widgets={a:{...normalizeWidget(),x:12}};expect(()=>validateCharacter(c)).toThrow('资源模块布局无效');c.quickbarLayout.widgets={a:{...normalizeWidget(),style:'unknown' as any}};expect(()=>validateCharacter(c)).toThrow();});
 it('imports legacy presentation once and keeps native layout authoritative',()=>{const c=newCharacter();c.runtime.resources.energy=resource();const doc=exportLinkedOwlbear(c,evaluate(c)) as any;delete doc.dnd_card_web;doc.web_resources=c.runtime.resources;doc.web_resource_widgets={energy:{...normalizeWidget(),style:'icon'},hidden:normalizeWidget()};const restored=importOwlbear(doc);expect(restored.quickbarLayout?.widgets).toEqual({energy:doc.web_resource_widgets.energy});expect(restored.runtime.resources.energy.current).toBe(2);expect(importOwlbear(exportOwlbear(restored,evaluate(restored))).quickbarLayout?.widgets).toEqual(restored.quickbarLayout?.widgets);const linked=exportLinkedOwlbear(restored,evaluate(restored)) as any;linked.web_resource_widgets={energy:{...normalizeWidget(),style:'bar'}};expect(importOwlbear(linked).quickbarLayout?.widgets?.energy.style).toBe('icon');doc.web_resource_widgets.energy.style='invalid';expect(()=>importOwlbear(doc)).toThrow('资源模块布局无效');});

});
