import {describe,it,expect} from 'vitest';
import {newCharacter} from '../src/core/model';
import {RESOURCE_TEMPLATES,addResourceModule,resourceModules,moduleLayout,dashboardLayout,normalizeWidget,validWidgets,moveWidget} from '../src/core/resourceWidgets';
import {exportCharacter,exportOwlbear} from '../src/core/export';
import {evaluate} from '../src/core/engine';
import {readCharacter,importOwlbear} from '../src/core/validation';
import {setResource} from '../src/core/resources';
const value=(name:string,current=2)=>({name,current,max:4,type:'count',automatic:false});
describe('218 resource module presentation',()=>{
 it('renders one module per actual standard or pact pool without combining balances or mutating rows',()=>{const rows:any=[['spell-slot:1',value('1环',4)],['pact-slot:3',value('3环契约',1)],['manual',value('独立资源')],['spell-slot:3',value('3环',2)]];const before=JSON.stringify(rows),modules=resourceModules(rows);expect(modules).toHaveLength(3);expect(modules[0].rows.map(([id])=>id)).toEqual(['spell-slot:1','spell-slot:3']);expect(modules[1].rows.map(([id])=>id)).toEqual(['pact-slot:3']);expect(modules.slice(0,2).map(m=>m.name)).toEqual(['法术位','契约法术位']);expect(JSON.stringify(rows)).toBe(before);});
 it('groups by stable anchor even when input order changes; missing or unauthorized members never appear',()=>{const rows:any=[['b',value('乙')],['a',value('甲')],['c',value('丙')]],saved={a:{...normalizeWidget(),members:['a','b','private'],label:'组合'}};expect(resourceModules(rows,saved).map(m=>m.rows.map(([id])=>id))).toEqual([['b','a'],['c']]);const visible=resourceModules([rows[1],rows[2]],saved);expect(visible.flatMap(m=>m.rows.map(([id])=>id))).toEqual(['a','c']);});
 it('inserts on the current page and creates a next page when full, with no edits to existing resources or layouts',()=>{const c=newCharacter();c.runtime.resources=Object.fromEntries(Array.from({length:9},(_,i)=>['r'+i,value('已有'+i,i%4)]));const initial=dashboardLayout(resourceModules(Object.entries(c.runtime.resources)));c.quickbarLayout={order:[],hidden:[],...initial};const before=structuredClone(c.runtime.resources),layout=structuredClone(c.quickbarLayout.widgets),attacks=structuredClone(c.quickbarLayout.attacks);const added=addResourceModule(c,RESOURCE_TEMPLATES[0],0,()=> 'new');expect(added.page).toBe(1);expect(Object.fromEntries(Object.entries(c.runtime.resources).filter(([id])=>id!=='new'))).toEqual(before);for(const id of Object.keys(layout!))expect(c.quickbarLayout.widgets![id]).toEqual(layout![id]);expect(c.quickbarLayout.attacks).toEqual(attacks);expect(dashboardLayout(resourceModules(Object.entries(c.runtime.resources),c.quickbarLayout.widgets),c.quickbarLayout.widgets,c.quickbarLayout.attacks).widgets.new.page).toBe(1);});
 it('creates three independently configured counters and preserves grouping through both file formats',()=>{const c=newCharacter();let n=0;const added=addResourceModule(c,RESOURCE_TEMPLATES.find(t=>t.id==='pool')!,0,()=> 'group'+n++);setResource(c,'group1',1);const saved=structuredClone(c.runtime.resources);for(const copy of [readCharacter(exportCharacter(c)).character,importOwlbear(exportOwlbear(c,evaluate(c)))]){expect(copy.runtime.resources).toEqual(saved);const modules=resourceModules(Object.entries(copy.runtime.resources),copy.quickbarLayout?.widgets);expect(modules).toHaveLength(1);expect(modules[0].id).toBe(added.id);expect(modules[0].rows).toHaveLength(3);}});
 it('consumes a standard slot without changing a pact pool, and changing presentation does not recover either',()=>{const c=newCharacter();c.runtime.resources={'spell-slot:2':value('标准',3),'pact-slot:2':value('契约',1)};c.spellSettings={attackBonus:0,dcBonus:0,ability:'int',mode:'prepared',capacity:0,prepared:[],slots:{'2':{max:4,used:1}}};setResource(c,'spell-slot:2',2);expect(c.spellSettings!.slots['2'].used).toBe(2);expect(c.runtime.resources['pact-slot:2'].current).toBe(1);const m=resourceModules(Object.entries(c.runtime.resources)),layouts=moduleLayout(m);expect(moveWidget(layouts[m[0].id],2,1,'se').w).toBeGreaterThanOrEqual(6);expect(c.runtime.resources['spell-slot:2'].current).toBe(2);});
 it('preserves intentional sparse pages and inserts on the requested free page without moving visible geometry',()=>{const c=newCharacter();c.runtime.resources={a:value('A'),b:value('B')};c.quickbarLayout={order:[],hidden:[],attacks:normalizeWidget({w:3,h:6,page:0}),widgets:{a:normalizeWidget({w:9,h:6,x:3,page:0}),b:normalizeWidget({w:12,h:6,page:5})}};const added=addResourceModule(c,RESOURCE_TEMPLATES[0],1,()=> 'new');const next=dashboardLayout(resourceModules(Object.entries(c.runtime.resources),c.quickbarLayout.widgets),c.quickbarLayout.widgets,c.quickbarLayout.attacks).widgets;expect(added.page).toBe(1);expect(next.new.page).toBe(added.page);expect(next.a).toMatchObject({page:0,x:0,y:0,w:12,h:6});expect(next.b).toMatchObject({page:5,x:0,y:0,w:12,h:6});});
 it('rejects malformed persisted membership and duplicate creation before touching resource values',()=>{expect(validWidgets({a:{...normalizeWidget(),members:['a','a']}})).toBe(false);expect(validWidgets({a:{...normalizeWidget(),members:['a']}})).toBe(false);const c=newCharacter(),before=structuredClone(c);expect(()=>addResourceModule(c,RESOURCE_TEMPLATES.find(t=>t.id==='pool')!,0,()=> 'same')).toThrow();expect(c).toEqual(before);});
 it('projects style-specific readable heights without rewriting old saved layout or balances',()=>{const c=newCharacter();c.runtime.resources={a:value('甲'),b:value('乙')};const saved={a:normalizeWidget({h:2,style:'ring'}),b:normalizeWidget({h:2,x:4,style:'segments'})},before=JSON.stringify(saved),resources=JSON.stringify(c.runtime.resources);const shown=moduleLayout(resourceModules(Object.entries(c.runtime.resources),saved),saved);expect(shown.a.h).toBe(3);expect(shown.b.h).toBe(2);expect(JSON.stringify(saved)).toBe(before);expect(JSON.stringify(c.runtime.resources)).toBe(resources);});

});
