import {describe,it,expect} from 'vitest';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import {runInNewContext} from 'node:vm';
const html=readFileSync(new URL('../index.html',import.meta.url),'utf8');
const flush=async()=>{for(let i=0;i<20;i++)await Promise.resolve();};
function deferred(){let resolve!:()=>void,reject!:(error:Error)=>void;const finished=new Promise<void>((yes,no)=>{resolve=yes;reject=no;});return {finished,resolve,reject};}
function boot({reduced=false,images=true,motion=true,styles=true}:{reduced?:boolean;images?:boolean;motion?:boolean;styles?:boolean}={}){
 let now=0,nextId=0;const listeners=new Map<string,Function[]>(),timeouts=new Map<number,{fn:Function,delay:number}>(),intervals=new Map<number,Function>();
 const nodes=new Map<string,any>(),trace:string[]=[];
 function node(id:string){const events=new Map<string,Set<Function>>();const el:any={hidden:id==='startup'||id==='startup-help',textContent:'',classes:new Set(),offsetWidth:100,addEventListener:(name:string,fn:Function)=>{if(!events.has(name))events.set(name,new Set());events.get(name)!.add(fn);},removeEventListener:(name:string,fn:Function)=>events.get(name)?.delete(fn),emit:(name:string)=>events.get(name)?.forEach(fn=>fn()),classList:{add:(name:string)=>el.classes.add(name)}};nodes.set(id,el);return el;}
 for(const id of ['startup','startup-title','startup-message','startup-detail','startup-help','startup-retry','startup-intro'])node(id);
 const movements=Array.from({length:4},()=>deferred()),fade=deferred();
 const pieces=movements.map((animation,i)=>Object.assign(node(`piece${i}`),{complete:images,naturalWidth:images?100:0,decode:()=>Promise.resolve(),getAnimations:()=>motion?[animation]:[]}));
 const intro=nodes.get('startup-intro');intro.querySelectorAll=()=>pieces;intro.getAnimations=()=>motion?[fade]:[];
 const stylesheet={media:styles?'all':'print',sheet:styles?{}:undefined},icon={href:'',getAttribute:()=> './exe_icon.png'},document={documentElement:{dataset:{} as Record<string,string>},getElementById:(id:string)=>nodes.get(id),querySelector:()=>icon,querySelectorAll:()=>[stylesheet],createElement:()=>({noModule:false})};
 const emit=(name:string,event:any={})=>listeners.get(name)?.forEach(fn=>fn(event));
 const window={addEventListener:(name:string,fn:Function)=>{listeners.set(name,[...(listeners.get(name)||[]),fn]);},dispatchEvent:(event:any)=>{if(event.type==='dnd-card-startup')trace.push(event.detail);emit(event.type,event);}};
 runInNewContext(html.match(/<script>\s*([\s\S]*?)<\/script>/)![1],{document,window,CustomEvent:class{constructor(public type:string,public options:any){}get detail(){return this.options.detail;}},Date:{now:()=>now},navigator:{userAgent:'test'},location:{reload(){}},matchMedia:()=>({matches:reduced}),setTimeout:(fn:Function,delay:number)=>{const id=++nextId;timeouts.set(id,{fn,delay});return id;},setInterval:(fn:Function)=>{const id=++nextId;intervals.set(id,fn);return id;},clearInterval:(id:number)=>intervals.delete(id)});
 return {nodes,pieces,movements,fade,trace,document,stylesheet,timeouts,emit,phase:()=>document.documentElement.dataset.cardStartup,advance:(ms:number)=>{now+=ms;intervals.forEach(fn=>fn());},hold:async()=>{await flush();const hold=[...timeouts].find(([,row])=>row.delay===(reduced?0:330));expect(hold).toBeDefined();timeouts.delete(hold![0]);hold![1].fn();await flush();},animate:async()=>{movements.forEach(animation=>animation.resolve());await flush();}};
}
describe('approved logo startup lifecycle',()=>{
 it('fast/cached card waits for all four actual animations, final pose and fade-out',async()=>{
  const b=boot();b.emit('dnd-card-ready');await flush();expect(b.phase()).toBe('playing');
  b.movements.slice(0,3).forEach(a=>a.resolve());await flush();expect(b.timeouts.size).toBe(0);
  b.movements[3].resolve();await b.hold();expect(b.phase()).toBe('fading');expect(b.nodes.get('startup-intro').hidden).toBe(false);
  b.fade.resolve();await flush();expect(b.phase()).toBe('complete');expect(b.nodes.get('startup-intro').hidden).toBe(true);
  expect(b.trace).toEqual(['loading','playing','waiting','fading','complete']);
 });
 it('finishing the intro first waits for the slow app and only then fades',async()=>{const b=boot();await flush();await b.animate();await b.hold();expect(b.phase()).toBe('waiting');b.emit('dnd-card-ready');expect(b.phase()).toBe('fading');b.fade.resolve();await flush();expect(b.phase()).toBe('complete');});
 it('a ready card waits for its late stylesheet while the opening can finish independently',async()=>{const b=boot({styles:false});b.emit('dnd-card-ready');await flush();expect(b.phase()).toBe('playing');await b.animate();await b.hold();expect(b.phase()).toBe('waiting');b.stylesheet.media='all';b.stylesheet.sheet={};b.emit('dnd-card-style-ready');expect(b.phase()).toBe('fading');b.fade.resolve();await flush();expect(b.phase()).toBe('complete');});
 it('a stylesheet failure after app readiness still shows recovery instead of waiting forever',async()=>{const b=boot({styles:false});b.emit('dnd-card-ready');await flush();b.emit('error',{target:{tagName:'LINK',href:'card.css'}});expect(b.phase()).toBe('failed');expect(b.nodes.get('startup-title').textContent).toBe('程序文件加载失败');});
 it('starts movement only after all PNGs load and decode, including cached images',async()=>{const b=boot({images:false});b.emit('dnd-card-ready');await flush();expect(b.phase()).toBe('loading');for(const piece of b.pieces.slice(0,3)){piece.naturalWidth=100;piece.emit('load');}await flush();expect(b.phase()).toBe('loading');b.pieces[3].naturalWidth=100;b.pieces[3].emit('load');await flush();expect(b.phase()).toBe('playing');});
 it('a failed logo asset settles without trapping the app or skipping remaining animations',async()=>{const b=boot({images:false});b.pieces.forEach(piece=>piece.emit('error'));b.emit('dnd-card-ready');await flush();expect(b.phase()).toBe('playing');await b.animate();await b.hold();expect(b.phase()).toBe('fading');b.fade.resolve();await flush();expect(b.phase()).toBe('complete');});
 it('offers slow-load diagnostics and resumes without dismissing the intro early',async()=>{const b=boot();await flush();await b.animate();await b.hold();b.advance(21000);expect(b.nodes.get('startup').hidden).toBe(false);expect(b.phase()).toBe('waiting');b.emit('dnd-card-ready');expect(b.phase()).toBe('fading');expect(b.nodes.get('startup').hidden).toBe(true);expect(b.nodes.get('startup-intro').hidden).toBe(false);b.fade.resolve();await flush();expect(b.phase()).toBe('complete');});
 it('script failure reveals recovery and never publishes completion or opens pending notices',async()=>{const b=boot();b.emit('error',{message:'load failed'});await flush();b.emit('dnd-card-ready');await b.animate();expect(b.phase()).toBe('failed');expect(b.nodes.get('startup-intro').hidden).toBe(true);expect(b.nodes.get('startup-title').textContent).toBe('程序启动失败');expect(b.trace).not.toContain('complete');});
 it('a React recovery screen cancels pending fade and does not claim ready',async()=>{const b=boot();b.emit('dnd-card-ready');await flush();await b.animate();await b.hold();b.emit('dnd-card-failed');b.fade.resolve();await flush();expect(b.phase()).toBe('failed');expect(b.nodes.get('startup').hidden).toBe(true);expect(b.trace).not.toContain('complete');});
 it('reduced motion still waits for its real shortened animations and transition',async()=>{const b=boot({reduced:true});b.emit('dnd-card-ready');await flush();await b.animate();await b.hold();expect(b.phase()).toBe('fading');b.fade.resolve();await flush();expect(b.phase()).toBe('complete');});
 it('disabled animations and transition need no invented delay to unlock',async()=>{const b=boot({motion:false,reduced:true});b.emit('dnd-card-ready');await b.hold();expect(b.phase()).toBe('complete');});
 it('animation/transition cancellation settles once, without hanging or duplicate completion',async()=>{const b=boot();b.emit('dnd-card-ready');await flush();b.movements[0].reject(new Error('cancelled'));b.movements.slice(1).forEach(a=>a.resolve());await b.hold();b.fade.reject(new Error('cancelled'));await flush();b.emit('dnd-card-ready');expect(b.trace.filter(p=>p==='complete')).toHaveLength(1);});
 it('navigation cancels pending completion and reentry gets an independent lifecycle',async()=>{const old=boot();old.emit('dnd-card-ready');await flush();await old.animate();await old.hold();old.emit('pagehide',{persisted:false});old.fade.resolve();await flush();expect(old.phase()).toBe('cancelled');expect(old.trace).not.toContain('complete');const fresh=boot();await flush();expect(fresh.phase()).toBe('playing');});
 it('bfcache preservation keeps the current intro and can finish after restoration',async()=>{const b=boot();b.emit('dnd-card-ready');await flush();b.emit('pagehide',{persisted:true});await b.animate();await b.hold();b.fade.resolve();await flush();expect(b.phase()).toBe('complete');});
 it('uncovers the styled card during transparent fade and preserves the four original PNG sources',()=>{const hashes=['40d81d05690b0fae1bb39c3bfe404aeadf35a7bffc28627bb7fe3685a0e67d26','d876c79b17189f092fb0519479e06109542e2fc84b9315b5212def431140134a','d4094577e2154933d41d43278a05ba899ee27186676f3d5e1ac0aa75454dee41','3b11e47126df35825dc2af8a6f4bfd9cd3000555a0c0d8ae87e1df4d0ad42fee'];hashes.forEach((hash,i)=>expect(createHash('sha256').update(readFileSync(new URL(`../public/startup-logo/${i+1}.PNG`,import.meta.url))).digest('hex')).toBe(hash));expect(html).toContain('background:#FFFF56');expect(html).toContain('html[data-card-startup]:not([data-card-startup="complete"]):not([data-card-startup="fading"]):not([data-card-startup="failed"]) #root{visibility:hidden}');expect(html).not.toContain('CHARACTER LOBBY');});
});
