import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
const wire=vi.hoisted(()=>({sent:[] as any[],receive:undefined as undefined|((m:any)=>void)}));
vi.mock('../src/platform/relay',()=>({Relay:class {constructor(_u:string,_s:string,_r:string,_k:string,receive:(m:any)=>void){wire.receive=receive;}send(m:any){wire.sent.push(m);return Promise.resolve();}}}));
vi.mock('../src/platform/workbenchSound',()=>({startWorkbenchSound:vi.fn(),playWorkbenchSound:vi.fn()}));
vi.mock('../src/platform/actionHistory',()=>({recordAction:vi.fn()}));
beforeEach(()=>{vi.resetModules();vi.useFakeTimers();vi.setSystemTime(100000);wire.sent=[];vi.stubGlobal('window',Object.assign(new EventTarget(),{opener:null}));vi.stubGlobal('location',new URL('https://fixture.test/#suite=recovery&bridge=https%3A%2F%2Ffixture.test&relay=secret'));});
afterEach(()=>{vi.clearAllTimers();vi.useRealTimers();vi.unstubAllGlobals();});
const card=(id='a',write=true)=>({id,name:id,itemId:'token-'+id,write,locked:false,inScene:true,resources:[],stats:{},documentRevision:1});
const access=(epoch=1)=>({room:'room',scope:'room:scene',epoch,role:'GM',cards:[card(),card('b')],monsters:[],enabled:{characterCards:true}});
const receive=(type:string,extra:any={})=>wire.receive!({protocol:'full-suite-workbench/v1',session:'recovery',hostStarted:1,type,...extra});
const snap=(id='a',sequence=3)=>({access:access(),sequence,state:{...card(id),key:'room:card:'+id,cardId:id,kind:'character',role:'GM',pinned:false},document:{name:id,_suiteRevision:1}});
async function ready(){const api=await import('../src/platform/workbench');receive('ready');receive('catalog',{sequence:1,access:access(),cards:[card(),card('b')],monsters:[],role:'GM',enabled:{characterCards:true}});return api;}
function failure(extra:any={}){receive('selectionError',{access:access(),sequence:2,targetId:'card:a',clientSelection:1,message:'角色资料读取失败（HTTP 404）',status:404,diagnostic:{code:'CARD_READ_FAILED',operation:'readCard',status:404,version:'1.0.243-dev',requestId:'read-123'},...extra});}
async function heartbeat(ms=30000){for(let i=0;i<ms/500;i++){await vi.advanceTimersByTimeAsync(500);receive('pong');}}

describe('failed character reads settle and can be retried explicitly',()=>{
 it('shows a failed initial default card without requiring an earlier manual selection',async()=>{const api=await ready();failure({clientSelection:0});expect(api.getWorkbench()).toMatchObject({loading:false,readFailure:{targetId:'card:a',status:404}});});
 it('ends a matching failed selection and stops hello retries without changing grants',async()=>{const api=await ready();api.chooseWorkbench('card:a');failure();expect(api.getWorkbench()).toMatchObject({loading:false,readFailure:{targetId:'card:a',status:404}});const helloCount=wire.sent.filter(m=>m.type==='hello').length;await heartbeat();expect(wire.sent.filter(m=>m.type==='hello')).toHaveLength(helloCount);expect(api.getWorkbench().cards[0].write).toBe(true);});
 it('ignores an old failed A read after selecting B, and old host errors',async()=>{const api=await ready();api.chooseWorkbench('card:a');api.chooseWorkbench('card:b');failure();expect(api.getWorkbench().loading).toBe(true);expect(api.getWorkbench().readFailure).toBeUndefined();receive('selection',{...snap('b',4),clientSelection:2});failure({sequence:5,hostStarted:0,clientSelection:1});expect(api.getWorkbench().target?.cardId).toBe('b');expect(api.getWorkbench().readFailure).toBeUndefined();});
 it('does not let a stale error advance the map-follow revision',async()=>{const api=await ready();api.chooseWorkbench('card:a');api.chooseWorkbench('card:b');failure({followRevision:999});receive('navigate',{itemId:'card:b',clientSelection:2,followRevision:1});receive('selection',{...snap('b',4),clientSelection:2,followRevision:1});expect(api.getWorkbench().target?.cardId).toBe('b');});
 it('does not gate an authorized explicit delete on a failed document read',async()=>{const api=await ready();api.chooseWorkbench('card:a');failure();const request=api.workbenchRequest('delete',{key:undefined,itemId:'card:a'});const sent=wire.sent.find(m=>m.type==='delete');expect(sent).toBeDefined();receive('ack',{requestId:sent.requestId,ok:true,result:{deleted:true}});await expect(request).resolves.toMatchObject({deleted:true});});
 it('retries only on request, applies a recovered snapshot, and ignores recovery after navigating away',async()=>{const api=await ready();api.chooseWorkbench('card:a');failure();const retry=api.retryWorkbenchRead();const sent=wire.sent.find(m=>m.type==='refreshCard');expect(sent.itemId).toBe('card:a');expect(api.getWorkbench().loading).toBe(true);receive('ack',{requestId:sent.requestId,ok:true,result:{snapshot:snap('a')}});await retry;expect(api.getWorkbench().target?.cardId).toBe('a');expect(api.getWorkbench().readFailure).toBeUndefined();api.chooseWorkbench('card:a');failure({sequence:4,clientSelection:2});const stale=api.retryWorkbenchRead();const old=wire.sent.filter(m=>m.type==='refreshCard').at(-1);api.chooseWorkbench('card:b');receive('selection',{...snap('b',6),clientSelection:3});receive('ack',{requestId:old.requestId,ok:true,result:{snapshot:snap('a',7)}});await stale;expect(api.getWorkbench().target?.cardId).toBe('b');});
 it('keeps a retry failure visible with safe diagnostics and no automatic retry loop',async()=>{const api=await ready();api.chooseWorkbench('card:a');failure();const retry=api.retryWorkbenchRead();const sent=wire.sent.find(m=>m.type==='refreshCard');receive('ack',{requestId:sent.requestId,ok:false,message:'missing',diagnostic:{status:404,code:'CARD_READ_FAILED',url:'https://private.invalid/?token=secret'}});await retry;expect(api.getWorkbench()).toMatchObject({loading:false,readFailure:{status:404}});expect(JSON.stringify(api.getWorkbench().readFailure?.diagnostic)).not.toContain('secret');await heartbeat();expect(wire.sent.filter(m=>m.type==='refreshCard')).toHaveLength(1);});
 it('ignores a late same-card selection error from an old scene scope',async()=>{const api=await ready();receive('access',{access:{...access(2),scope:'room:other-scene'}});failure({clientSelection:0});expect(api.getWorkbench().readFailure).toBeUndefined();expect(api.getWorkbench().access?.scope).toBe('room:other-scene');});
 it('retires a hanging retry on scope change and displays the new default failure immediately',async()=>{const api=await ready();api.chooseWorkbench('card:a');failure();const retry=api.retryWorkbenchRead();const old=wire.sent.find(m=>m.type==='refreshCard');const current={...access(2),scope:'room:other-scene'};receive('access',{access:current});failure({sequence:4,access:current});expect(api.getWorkbench().readFailure?.targetId).toBe('card:a');receive('ack',{requestId:old.requestId,ok:true,result:{snapshot:snap('a')}});await retry;expect(api.getWorkbench().readFailure?.targetId).toBe('card:a');expect(api.getWorkbench().target).toBeUndefined();});
 it('rejects an error whose only stale identity is the older positive host epoch',async()=>{const api=await ready();receive('ready',{hostStarted:2});receive('catalog',{hostStarted:2,sequence:1,access:access(),cards:[card(),card('b')],monsters:[]});api.chooseWorkbench('card:a');failure({hostStarted:1});expect(api.getWorkbench().readFailure).toBeUndefined();expect(api.getWorkbench().loading).toBe(true);});
 it('rejects a valid but different card returned for the failed card retry',async()=>{const api=await ready();api.chooseWorkbench('card:a');failure();const retry=api.retryWorkbenchRead();const sent=wire.sent.find(m=>m.type==='refreshCard');receive('ack',{requestId:sent.requestId,ok:true,result:{snapshot:snap('b')}});await retry;expect(api.getWorkbench().target).toBeUndefined();expect(api.getWorkbench().readFailure?.targetId).toBe('card:a');});
 it('does not apply a recovery snapshot after an access scope change',async()=>{const api=await ready();api.chooseWorkbench('card:a');failure();const retry=api.retryWorkbenchRead();const sent=wire.sent.find(m=>m.type==='refreshCard');receive('access',{access:{...access(2),scope:'room:other-scene'}});receive('ack',{requestId:sent.requestId,ok:true,result:{snapshot:snap('a')}});await retry;expect(api.getWorkbench().target).toBeUndefined();expect(api.getWorkbench().readFailure).toBeUndefined();});
});
