import {afterEach,beforeEach,describe,expect,it,vi} from 'vitest';
import {newCharacter} from '../src/core/model';
import {evaluate} from '../src/core/engine';
const wire=vi.hoisted(()=>({sent:[] as any[],receive:undefined as undefined|((m:any)=>void),fault:undefined as undefined|((m:any)=>void)}));
vi.mock('../src/platform/relay',()=>({Relay:class{
 constructor(_url:string,_session:string,_role:string,_secret:string,receive:(m:any)=>void,_key:unknown,_alive:unknown,_room:unknown,fault:(m:any)=>void){wire.receive=receive;wire.fault=fault;}
 send(message:any){wire.sent.push(message);return Promise.resolve();}
}}));
vi.mock('../src/platform/workbenchSound',()=>({startWorkbenchSound:vi.fn(),playWorkbenchSound:vi.fn()}));
vi.mock('../src/platform/actionHistory',()=>({recordAction:vi.fn()}));
beforeEach(()=>{vi.resetModules();vi.useFakeTimers();vi.setSystemTime(100000);wire.sent=[];vi.stubGlobal('window',Object.assign(new EventTarget(),{opener:null}));vi.stubGlobal('location',new URL('https://fixture.test/#suite=owners&bridge=https%3A%2F%2Ffixture.test&relay=fixture'));});
afterEach(()=>{vi.clearAllTimers();vi.useRealTimers();vi.unstubAllGlobals();});
const card=(write=true)=>({id:'a',name:'A',itemId:'token-a',write,locked:false,inScene:true,resources:[{id:'uses',name:'Uses',current:3,max:3,type:'count'}],stats:{health:10},documentRevision:1});
const access=(epoch=1,write=true)=>({room:'room',scope:'room:scene',epoch,role:'PLAYER',cards:[card(write)],monsters:[],enabled:{characterCards:true}});
const document=()=>{const c=newCharacter();c.id='suite:room:card:a';c.runtime.hp=10;return {dnd_card_web:c,_suiteRevision:1};};
const snapshot=(sequence=2)=>({sequence,state:{...card(),key:'room:card:a',cardId:'a',kind:'character',role:'PLAYER',pinned:false},document:document()});
const receive=(type:string,extra:any={})=>wire.receive!({protocol:'full-suite-workbench/v1',session:'owners',hostStarted:1,type,...extra});
async function ready(){const api=await import('../src/platform/workbench');receive('ready');receive('catalog',{sequence:1,access:access(),cards:[card()],monsters:[],role:'PLAYER',enabled:{characterCards:true}});receive('selection',snapshot());return api;}
function change(api:Awaited<ReturnType<typeof ready>>){const before=document().dnd_card_web,after=structuredClone(before);after.name='Queued name';return api.patchWorkbenchStats(before,after,evaluate(before),evaluate(after))!;}
const saves=()=>wire.sent.filter(m=>m.type==='save');

describe('native owner revocation at the Web write boundary',()=>{
 it('rejects direct writes immediately and ignores cached ownership/late receipts',async()=>{const api=await ready();receive('access',{access:access(2,false)});await expect(api.workbenchRequest('save',{native:{name:'denied'}})).rejects.toThrow(/权限|不可编辑/);expect(saves()).toHaveLength(0);receive('cacheSnapshot',{...snapshot(99),access:access()});receive('ack',{requestId:'old',ok:true,result:{snapshot:{...snapshot(100),access:access()}}});expect(api.getWorkbench().target?.write).toBe(false);});
 it('discards a debounced intent even if Owner is regranted before its timer fires',async()=>{const api=await ready(),result=change(api).catch(e=>e);receive('access',{access:access(2,false)});receive('access',{access:access(3,true)});await vi.advanceTimersByTimeAsync(100);expect(saves()).toHaveLength(0);expect(await result).toMatchObject({permissionChanged:true});});
 it('contains an in-flight write and never runs its old queued successor after regrant/ACK',async()=>{const api=await ready(),first=change(api).catch(e=>e);await vi.advanceTimersByTimeAsync(100);const request=saves()[0],second=change(api).catch(e=>e);await vi.advanceTimersByTimeAsync(100);receive('access',{access:access(2,false)});receive('access',{access:access(3,true)});receive('ack',{requestId:request.requestId,ok:true,result:{snapshot:{...snapshot(8),access:access()}}});await vi.advanceTimersByTimeAsync(100);expect(saves()).toHaveLength(1);expect(await first).toMatchObject({permissionChanged:true,uncertain:true});expect(await second).toBeInstanceOf(Error);const fresh=change(api);await vi.advanceTimersByTimeAsync(100);expect(saves()).toHaveLength(2);receive('ack',{requestId:saves()[1].requestId,ok:true,result:{}});await fresh;});
 it('suspends editing on transport loss and late receipts cannot confirm stale authority',async()=>{const api=await ready(),pending=change(api).catch(e=>e);wire.fault!({status:503,message:'offline'});expect(api.getWorkbench().target?.write).toBe(false);receive('ack',{requestId:'old',ok:true,result:{snapshot:{...snapshot(10),access:access()}}});expect(api.getWorkbench().target?.write).toBe(false);await vi.advanceTimersByTimeAsync(100);expect(saves()).toHaveLength(0);expect(await pending).toBeInstanceOf(Error);receive('catalog',{sequence:12,cards:[card()],monsters:[],role:'GM',enabled:{characterCards:true}});expect(api.getWorkbench().target?.write).toBe(false);expect(api.getWorkbench().role).toBe('PLAYER');receive('access',{access:access()});expect(api.getWorkbench().target?.write).toBe(true);});
 it('does not let an inconsistent same-epoch directory restore cached write access',async()=>{const api=await ready();receive('access',{access:access(2,false)});receive('cacheSnapshot',{...snapshot(20),access:access(2,true)});api.chooseWorkbench('card:a');expect(api.getWorkbench().target?.write).toBe(false);expect(api.getWorkbench().access?.cards[0].write).toBe(false);});
 it('stamps dispatched writes with the current host authorization scope',async()=>{const api=await ready(),result=api.workbenchRequest('save',{native:{name:'yes'}});expect(saves()[0]).toMatchObject({accessEpoch:1,accessScope:'room:scene',accessRoom:'room'});receive('ack',{requestId:saves()[0].requestId,ok:true,result:{}});await result;});
 it('invalidates serialized resource intents through revoke/regrant without replay',async()=>{await ready();const {patchResource}=await import('../src/platform/resources');const first=patchResource(card(),'uses',{current:2}).catch(e=>e),second=patchResource(card(),'uses',{current:1}).catch(e=>e);await vi.advanceTimersByTimeAsync(1);const request=wire.sent.find(m=>m.type==='resource');receive('access',{access:access(2,false)});receive('access',{access:access(3,true)});receive('ack',{requestId:request.requestId,ok:true,result:{}});await vi.advanceTimersByTimeAsync(100);expect(wire.sent.filter(m=>m.type==='resource')).toHaveLength(1);await first;expect(await second).toBeInstanceOf(Error);});
 it('does not allow a stale inventory container or late receipt to keep card write permission',async()=>{const api=await ready();const inventory={publicId:'stock',access:'old-view',revision:1,silent:false,containers:{'card:a':{id:'card:a',name:'A',kind:'card',revision:1,items:[],columns:5,capacity:20,write:true}}};receive('catalog',{sequence:3,access:access(),cards:[card()],monsters:[],role:'PLAYER',enabled:{characterCards:true},inventory});receive('access',{access:access(2,false)});expect(api.getWorkbench().inventory?.containers['card:a'].write).toBe(false);receive('ack',{requestId:'old-stock',ok:true,result:{inventory:{...inventory,revision:2}}});expect(api.getWorkbench().inventory?.containers['card:a'].write).toBe(false);await expect(api.requestInventory({action:'add',container:'card:a',row:{id:'item',kind:'item',name:'Denied',quantity:1,slot:0}})).rejects.toThrow(/权限/);expect(wire.sent.filter(m=>m.type==='inventory')).toHaveLength(0);});
 it('does not restore a removed readable card through a catalog lacking access',async()=>{const api=await ready();receive('access',{access:{...access(2),cards:[]}});receive('catalog',{sequence:50,cards:[card()],monsters:[],role:'GM',enabled:{characterCards:true}});expect(api.getWorkbench().cards).toEqual([]);expect(api.getWorkbench().target).toBeUndefined();expect(api.getWorkbench().role).toBe('PLAYER');});

 it('discards a queued edit when a coalesced revoke/regrant arrives as writable with a new grant version',async()=>{const api=await ready();receive('access',{access:{...access(2),cards:[{...card(),grantVersion:'0:0'}]}});const pending=change(api).catch(e=>e);receive('access',{access:{...access(4),cards:[{...card(),grantVersion:'0:2'}]}});await vi.advanceTimersByTimeAsync(100);expect(saves()).toHaveLength(0);expect(await pending).toMatchObject({permissionChanged:true});});
 it('keeps A queued edits when only B changes its grant version',async()=>{const api=await ready(),b={...card(),id:'b',itemId:'token-b',grantVersion:'0:0'};receive('access',{access:{...access(2),cards:[{...card(),grantVersion:'0:0'},b]}});const pending=change(api);receive('access',{access:{...access(4),cards:[{...card(),grantVersion:'0:0'},{...b,grantVersion:'0:2'}]}});await vi.advanceTimersByTimeAsync(100);expect(saves()).toHaveLength(1);receive('ack',{requestId:saves()[0].requestId,ok:true,result:{}});await pending;});

 it('cancels a dispatched transfer when its destination loses permission',async()=>{const api=await ready(),b={...card(),id:'b',itemId:'token-b'},auth={...access(2),cards:[card(),b]};const inventory={publicId:'stock',revision:1,silent:false,containers:Object.fromEntries(['a','b'].map(id=>['card:'+id,{id:'card:'+id,name:id,kind:'card',revision:1,items:[{id:'item',kind:'item',name:'Item',quantity:2,slot:0,revision:1}],columns:5,capacity:20,write:true}]))};receive('catalog',{sequence:3,access:auth,cards:[card(),b],monsters:[],role:'PLAYER',enabled:{characterCards:true},inventory});const pending=api.requestInventory({action:'transfer',from:'card:a',to:'card:b',rows:[{id:'item',quantity:1}]}).catch(e=>e);await vi.advanceTimersByTimeAsync(1);const request=wire.sent.find(m=>m.type==='inventory');receive('access',{access:{...auth,epoch:3,cards:[card(),{...b,write:false}]}});expect(await pending).toMatchObject({permissionChanged:true,uncertain:true});expect(wire.sent.some(m=>m.type==='cancel'&&m.requestId===request.requestId)).toBe(true);});
 it('keeps original inventory endpoints on undo so revocation cancels that in-flight history write',async()=>{const api=await ready();const inventory={publicId:'stock',revision:1,silent:false,containers:{'card:a':{id:'card:a',name:'A',kind:'card',revision:1,items:[],columns:5,capacity:20,write:true}}};receive('catalog',{sequence:3,access:access(),cards:[card()],monsters:[],role:'PLAYER',enabled:{characterCards:true},inventory});const initial=api.requestInventory({action:'add',container:'card:a',row:{id:'item',kind:'item',name:'Item',quantity:1,slot:0,revision:1}});await vi.advanceTimersByTimeAsync(1);receive('ack',{requestId:wire.sent.find(m=>m.type==='inventory').requestId,ok:true,result:{historyId:'history'}});await initial;const {recordAction}=await import('../src/platform/actionHistory'),undo=vi.mocked(recordAction).mock.calls.at(-1)![0].undo();const pending=Promise.resolve(undo).catch(e=>e);await vi.advanceTimersByTimeAsync(1);const request=wire.sent.filter(m=>m.type==='inventory').at(-1);expect(request.operation.action).toBe('history');receive('access',{access:access(2,false)});expect(await pending).toMatchObject({permissionChanged:true,uncertain:true});expect(wire.sent.some(m=>m.type==='cancel'&&m.requestId===request.requestId)).toBe(true);});

 it('rejects inventory undo invoked after its original card has already lost write access',async()=>{const api=await ready();const inventory={publicId:'stock',revision:1,silent:false,containers:{'card:a':{id:'card:a',name:'A',kind:'card',revision:1,items:[],columns:5,capacity:20,write:true}}};receive('catalog',{sequence:3,access:access(),cards:[card()],monsters:[],role:'PLAYER',enabled:{characterCards:true},inventory});const initial=api.requestInventory({action:'add',container:'card:a',row:{id:'item',kind:'item',name:'Item',quantity:1,slot:0,revision:1}});await vi.advanceTimersByTimeAsync(1);receive('ack',{requestId:wire.sent.find(m=>m.type==='inventory').requestId,ok:true,result:{historyId:'history'}});await initial;receive('access',{access:access(2,false)});const {recordAction}=await import('../src/platform/actionHistory'),pending=Promise.resolve(vi.mocked(recordAction).mock.calls.at(-1)![0].undo()).catch(e=>e);await vi.advanceTimersByTimeAsync(1);expect(wire.sent.filter(m=>m.type==='inventory')).toHaveLength(1);expect(await pending).toMatchObject({permissionChanged:true});});

 it('does not revive a legacy-host debounced edit after catalog revocation and regrant',async()=>{const api=await import('../src/platform/workbench');receive('ready');receive('catalog',{sequence:1,cards:[card()],monsters:[],role:'PLAYER',enabled:{characterCards:true}});receive('selection',snapshot());const pending=change(api).catch(e=>e);receive('catalog',{sequence:3,cards:[card(false)],monsters:[],role:'PLAYER',enabled:{characterCards:true}});receive('catalog',{sequence:4,cards:[card()],monsters:[],role:'PLAYER',enabled:{characterCards:true}});await vi.advanceTimersByTimeAsync(100);expect(saves()).toHaveLength(0);expect(await pending).toMatchObject({permissionChanged:true});});
 it('uses a newer legacy selection revocation rather than older catalog write flags',async()=>{const api=await import('../src/platform/workbench');receive('ready');receive('catalog',{sequence:1,cards:[card()],monsters:[],role:'PLAYER',enabled:{characterCards:true}});receive('selection',snapshot());receive('selection',{...snapshot(3),state:{...snapshot().state,write:false}});await expect(api.workbenchRequest('save',{native:{name:'Denied'}})).rejects.toThrow(/权限/);expect(saves()).toHaveLength(0);});

 it('does not restore legacy permissions from a catalog embedded in a late batch receipt',async()=>{const api=await import('../src/platform/workbench');receive('ready');receive('catalog',{sequence:1,cards:[card()],monsters:[],role:'PLAYER',enabled:{characterCards:true}});receive('selection',snapshot());receive('catalog',{sequence:3,cards:[card(false)],monsters:[],role:'PLAYER',enabled:{characterCards:true}});receive('ack',{requestId:'old-batch',ok:true,result:{snapshots:[],catalog:{sequence:99,cards:[card()],monsters:[]}}});expect(api.getWorkbench().cards[0].write).toBe(false);await expect(api.workbenchRequest('save',{native:{name:'Denied'}})).rejects.toThrow(/权限/);});

});

describe('first-load navigation receives its own warm document',()=>{
 it('finishes an explicit host navigation from its authorized warm snapshot without a DM switch',async()=>{const api=await import('../src/platform/workbench');receive('ready');receive('catalog',{sequence:1,access:access(),cards:[card()],monsters:[],role:'PLAYER',enabled:{characterCards:true}});receive('navigate',{itemId:'card:a'});expect(api.getWorkbench().loading).toBe(true);receive('cacheSnapshot',{...snapshot(2),access:access()});expect(api.getWorkbench().target?.cardId).toBe('a');expect(api.getWorkbench().loading).toBe(false);expect(wire.sent.some(m=>m.type==='save')).toBe(false);});
 it('does not let a late A snapshot replace a newer explicit B navigation',async()=>{const api=await ready();const b={...card(),id:'b',itemId:'token-b'},auth={...access(2),cards:[card(),b]};receive('access',{access:auth});api.chooseWorkbench('card:b');receive('cacheSnapshot',{...snapshot(3),access:auth});expect(api.getWorkbench().target).toBeUndefined();const incoming={...snapshot(4),state:{...snapshot().state,cardId:'b',itemId:'token-b',key:'room:card:b'}};receive('cacheSnapshot',{...incoming,access:auth});expect(api.getWorkbench().target?.cardId).toBe('b');});
 it('keeps a legitimate empty selection empty when an unrelated cache is warmed',async()=>{const api=await import('../src/platform/workbench');receive('ready');receive('catalog',{sequence:1,access:access(),cards:[card()],monsters:[],role:'PLAYER',enabled:{characterCards:true}});receive('selection',{sequence:2});receive('cacheSnapshot',{...snapshot(3),access:access()});expect(api.getWorkbench().target).toBeUndefined();expect(api.getWorkbench().loading).toBe(false);});
 it('retries only hello while an explicit navigation is loading, then stops when warm data arrives',async()=>{const api=await import('../src/platform/workbench');receive('ready');receive('catalog',{sequence:1,access:access(),cards:[card()],monsters:[],role:'PLAYER',enabled:{characterCards:true}});receive('navigate',{itemId:'card:a'});const initial=wire.sent.length;for(let i=0;i<40;i++){await vi.advanceTimersByTimeAsync(500);receive('pong');}const retries=wire.sent.slice(initial).filter(m=>m.type==='hello');expect(retries.length).toBeGreaterThan(0);expect(retries.length).toBeLessThanOrEqual(6);expect(wire.sent.some(m=>m.type==='select')).toBe(false);receive('cacheSnapshot',{...snapshot(2),access:access()});const completed=wire.sent.filter(m=>m.type==='hello').length;for(let i=0;i<24;i++){await vi.advanceTimersByTimeAsync(500);receive('pong');}expect(wire.sent.filter(m=>m.type==='hello')).toHaveLength(completed);expect(api.getWorkbench().loading).toBe(false);});
 it('stops a revoked pending navigation and never displays its late warm snapshot',async()=>{const api=await import('../src/platform/workbench');receive('ready');receive('catalog',{sequence:1,access:access(),cards:[card()],monsters:[],role:'PLAYER',enabled:{characterCards:true}});receive('navigate',{itemId:'card:a'});receive('access',{access:{...access(2),cards:[]}});expect(api.getWorkbench().loading).toBe(false);receive('cacheSnapshot',{...snapshot(3),access:access()});expect(api.getWorkbench().target).toBeUndefined();});

 it('rejects a delayed selection reply for A after a newer host navigation has warmed B',async()=>{const api=await ready();const b={...card(),id:'b',itemId:'token-b'},auth={...access(2),cards:[card(),b]};receive('access',{access:auth});receive('navigate',{itemId:'card:a'});receive('navigate',{itemId:'card:b'});receive('cacheSnapshot',{...snapshot(5),state:{...snapshot().state,cardId:'b',itemId:'token-b',key:'room:card:b'},access:auth});expect(api.getWorkbench().target?.cardId).toBe('b');receive('selection',{...snapshot(6),access:auth});expect(api.getWorkbench().target?.cardId).toBe('b');});

});
