import {useEffect,useId,useLayoutEffect,useRef,useState,type CSSProperties,type ReactNode} from 'react';
import type {ConditionVisual} from './conditionVisuals';
import './adaptiveCardAtmosphere.css';

export type AdaptiveVisualProps={active:ReadonlySet<ConditionVisual>;exhaustion?:number;editing?:boolean};
export function adaptiveConditionClasses(active:ReadonlySet<ConditionVisual>,editing=false){return `adaptive-card-host${editing?' adaptive-editing':[...active].map(id=>` adaptive-condition-${id}`).join('')}`;}
function useArtSize(){const ref=useRef<HTMLDivElement>(null),[size,setSize]=useState({width:0,height:0});useLayoutEffect(()=>{const node=ref.current;if(!node)return;const measure=()=>{const width=Math.round(node.clientWidth),height=Math.round(node.clientHeight);setSize(old=>old.width===width&&old.height===height?old:{width,height});};measure();const observer=new ResizeObserver(measure);observer.observe(node);return()=>observer.disconnect();},[]);return {ref,...size};}
const clamp=(value:number,min:number,max:number)=>Math.max(min,Math.min(max,value));
function Effect({id,active,children}:{id:ConditionVisual;active:boolean;children:ReactNode}){const [retained,setRetained]=useState(active);useEffect(()=>{if(active){setRetained(true);return;}const timer=setTimeout(()=>setRetained(false),850);return()=>clearTimeout(timer);},[active]);if(!active&&!retained)return null;return <g className={`adaptive-effect adaptive-effect-${id} ${active?'adaptive-present':'adaptive-leaving'}`} data-adaptive-effect={id} data-phase={active?'present':'leaving'}>{children}</g>;}
export function adaptivePerimeter(w:number,h:number,inset=1.5){const corner=Math.min(8.5,Math.min(w,h)/4),right=Math.max(inset,w-inset),bottom=Math.max(inset,h-inset);return `M${corner} ${inset}H${w-corner}L${right} ${corner}V${h-corner}L${w-corner} ${bottom}H${corner}L${inset} ${h-corner}V${corner}Z`;}
function Prohibition({kind}:{kind:'deafened'|'blinded'}){return <g className="adaptive-prohibition"><circle r="86"/>{kind==='deafened'?<><path className="adaptive-symbol-fill" d="M-55-24H-30L3-52V52L-30 24H-55Z"/><path d="M23-32Q54 0 23 32M39-47Q86 0 39 47"/></>:<><path d="M-66 0Q0-72 66 0Q0 72-66 0Z"/><circle r="23"/></>}<path className="adaptive-symbol-slash" d="M-61-61L61 61"/></g>;}
function Hearts({width:w,height:h}:{width:number;height:number}){const countY=Math.max(1,Math.floor((h-18)/57)),countX=Math.max(1,Math.floor((w-36)/75)),positions=[...Array.from({length:countY},(_,i)=>[8,20+(h-40)*(i+.5)/countY,-28]),...Array.from({length:countY},(_,i)=>[w-8,20+(h-40)*(i+.5)/countY,152]),...Array.from({length:countX},(_,i)=>[18+(w-36)*(i+.5)/countX,7,60]),...Array.from({length:countX},(_,i)=>[18+(w-36)*(i+.5)/countX,h-7,-120])];return <>{positions.map(([x,y,angle],i)=><g key={i} transform={`translate(${x} ${y}) rotate(${angle})`}><path className="adaptive-heart" d="M0 6C-4 2-11-2-9-7C-8-12-2-12 0-7C3-13 9-11 10-6C11-1 4 3 0 6Z"/><path className="adaptive-vine-curl" d="M0 6C14 11 19-8 11-6C5-4 11 1 14-3"/></g>)}</>;}
function Chains({width:w,height:h,pattern}:{width:number;height:number;pattern:string}){const lines=[[-12,h*.17,w+12,h*.65],[w+12,h*.15,-12,h*.77],[w*.22,-12,w*.69,h+12],[w*.84,h+12,w*.41,-12]];return <>{lines.map(([x,y,ex,ey],i)=>{const length=Math.hypot(ex-x,ey-y),angle=Math.atan2(ey-y,ex-x)*180/Math.PI;return <g key={i} transform={`translate(${x} ${y}) rotate(${angle})`}><g className="adaptive-chain-run" style={{'--adaptive-chain-distance':`${-length-30}px`} as CSSProperties}><rect x="-8" y="-5" width={length+20} height="10" fill={`url(#${pattern})`}/></g></g>;})}</>;}
function Grapple({width:w,height:h}:{width:number;height:number}){const scale=clamp(Math.min(w,h)/280,.38,1.45);return <>{[false,true].map(right=><g key={String(right)} transform={`translate(${right?w:0} ${h*.53}) scale(${right?-scale:scale} ${scale})`}><g className="adaptive-hand"><path d="M-12-98Q12-99 22-77L54-43Q64-31 54-23Q45-16 35-29L16-49V-18L58 9Q72 19 62 31Q53 42 39 29L17 15V41L55 65Q68 76 57 85Q47 93 35 82L12 67Q23 109-12 113Z"/><path className="adaptive-hand-crease" d="M1-44L8-36M1 3L10 13M0 48L8 59"/></g></g>)}</>;}
function Blood({width:w,height:h}:{width:number;height:number}){const count=clamp(Math.round((w+h)/80),6,20),size=clamp(Math.min(w,h)/430,.28,.7);return <>{Array.from({length:count},(_,i)=>{const side=i%4,t=(.17+(i*.317)%1)*.85,x=side===0?9:side===1?w-9:w*t,y=side===2?9:side===3?h-9:h*t;return <g key={i} className="adaptive-blood" transform={`translate(${x} ${y}) scale(${size}) rotate(${i*37})`}><path d="M-7-17L-10-50-1-27 12-18 36-40 21-12 25 1 66 10 28 12 12 22 15 53 3 26-13 20-43 37-23 7-61-6-24-8-20-31Z"/><circle cx="-39" cy="-28" r="5"/><circle cx="47" cy="25" r="6"/></g>;})}</>;}

/** Every coordinate is measured in the container's CSS pixels. Symbols only use
 * uniform scale; changing the card aspect ratio never stretches an A4 canvas. */
export function AdaptiveCardAtmosphere({active,exhaustion=0,editing=false,watermarkUrl}:{watermarkUrl?:string}&AdaptiveVisualProps){
 const {ref,width:w,height:h}=useArtSize(),uid=useId().replace(/:/g,''),has=(id:ConditionVisual)=>!editing&&active.has(id);const small=Math.min(w,h),seal=clamp(small*.58,50,350),symbol=clamp(small*.24,34,112),starScale=clamp(w/340,.6,1.35),centerX=w*.5,centerY=h*.55;
 const [paused,setPaused]=useState(document.hidden);useEffect(()=>{const update=()=>setPaused(document.hidden);document.addEventListener('visibilitychange',update);return()=>document.removeEventListener('visibilitychange',update);},[]);
 const [watermark,setWatermark]=useState(watermarkUrl),[watermarkLeaving,setWatermarkLeaving]=useState(false);useEffect(()=>{if(watermark===watermarkUrl){setWatermarkLeaving(false);return;}if(!watermark){setWatermark(watermarkUrl);return;}setWatermarkLeaving(true);const timer=setTimeout(()=>{setWatermark(watermarkUrl);setWatermarkLeaving(false);},750);return()=>clearTimeout(timer);},[watermarkUrl,watermark]);
 return <div ref={ref} className={`adaptive-card-atmosphere${paused?' adaptive-paused':''}${editing?' adaptive-suppressed':''}`} data-adaptive-atmosphere aria-hidden="true">{!!w&&!!h&&<svg viewBox={`0 0 ${w} ${h}`} focusable="false" data-art-width={w} data-art-height={h}>
  <defs><pattern id={`${uid}-chain`} width="19" height="10" patternUnits="userSpaceOnUse"><rect x="1" y="2" width="15" height="6" rx="3" fill="none" stroke="currentColor" strokeWidth="1.5"/><path d="M12 5h10" fill="none" stroke="currentColor" strokeWidth="1.6"/></pattern><mask id={`${uid}-seal`} maskUnits="userSpaceOnUse" x="-100" y="-100" width="200" height="200"><rect x="-100" y="-100" width="200" height="200" fill="white"/>{watermark&&<image href={watermark} x="-87" y="-87" width="174" height="174" style={{filter:'brightness(0)'}}/>}</mask></defs>
  <Effect id="concentration" active={has('concentration')}><g transform={`translate(${centerX} ${centerY}) scale(${seal/200})`}><g mask={`url(#${uid}-seal)`}><g className="adaptive-magic-seal"><circle r="95"/><circle r="87"/><circle r="71"/><path d="M0-84L73 42H-73ZM0 84L-73-42H73Z"/>{Array.from({length:16},(_,i)=><path key={i} d="M-2-96V-87L4-91V-83" transform={`rotate(${i*22.5})`}/>)}</g></g></g></Effect>
  {watermark&&<image key={watermark} className={`adaptive-watermark${watermarkLeaving?' adaptive-watermark-leaving':''}`} data-phase={watermarkLeaving?'leaving':'present'} href={watermark} x={centerX-seal*.435} y={centerY-seal*.435} width={seal*.87} height={seal*.87}/>}
  <Effect id="restrained" active={has('restrained')}><Chains width={w} height={h} pattern={`${uid}-chain`}/></Effect>
  <Effect id="charmed" active={has('charmed')}><g className="adaptive-vines"><path className="adaptive-vine-stem" pathLength="1000" d={`M${w*.5} 7C${w*.2} -1 2 15 7 ${h*.22}S16 ${h*.51} 7 ${h*.73}S${w*.16} ${h-1} ${w*.5} ${h-7}S${w-2} ${h-15} ${w-7} ${h*.73}S${w-16} ${h*.51} ${w-7} ${h*.22}S${w*.8} -1 ${w*.5} 7`}/><Hearts width={w} height={h}/></g></Effect>
  <Effect id="grappled" active={has('grappled')}><Grapple width={w} height={h}/></Effect>
  {(['deafened','blinded'] as const).map((id,i)=><Effect key={id} id={id} active={has(id)}><g data-adaptive-symbol={id} transform={`translate(${w-symbol*.6-10} ${h*(i?.73:.27)}) scale(${symbol/190})`}><Prohibition kind={id}/></g></Effect>)}
  <Effect id="bloodied" active={has('bloodied')}><Blood width={w} height={h}/></Effect>
  <Effect id="paralyzed" active={has('paralyzed')}><rect className="adaptive-glitch-flash" width={w} height={h}/><path className="adaptive-glitch-slices" d={`M0 ${h*.17}H${w}v3H0ZM0 ${h*.47}H${w}v6H0ZM0 ${h*.79}H${w}v4H0Z`}/></Effect>
  <Effect id="poisoned" active={has('poisoned')}><path className="adaptive-poison-rim" d={adaptivePerimeter(w,h,3)}/></Effect>
  <Effect id="stunned" active={has('stunned')}><g transform={`translate(${Math.min(w*.36,105)} 20) scale(${starScale})`}><g className="adaptive-star-halo"><ellipse rx="45" ry="13"/>{[0,1,2].map(i=><g key={i} className={`adaptive-orbit-star adaptive-star-${i}`}><path d="M0-5L1.6-1.6 5 0 1.6 1.6 0 5-1.6 1.6-5 0-1.6-1.6Z"/></g>)}</g></g></Effect>
  <Effect id="surprised" active={has('surprised')}><g transform={`translate(${w*.82} 25)`}><g className="adaptive-surprise-rays">{Array.from({length:14},(_,i)=><path key={i} d="M-1.6-15L0-26 1.8-15Z" transform={`rotate(${i*360/14})`}/>)}</g></g></Effect>
  <Effect id="exhaustion" active={has('exhaustion')}><g className="adaptive-exhaustion-rim">{Array.from({length:6},(_,i)=>i<exhaustion&&<path key={i} d={adaptivePerimeter(w,h)} pathLength="600" strokeDasharray="98 502" strokeDashoffset={-i*100}/>)}</g></Effect>
 </svg>}</div>;
}

/** Independent frame decoration for small or wide cards; original paper CellArt
 * stays unchanged. Each crack is a fixed-shape corner motif in local pixels. */
export function AdaptiveFrameArt({active,exhaustion=0,editing=false,outline=true}:AdaptiveVisualProps&{outline?:boolean}){
 const {ref,width:w,height:h}=useArtSize(),has=(id:ConditionVisual)=>!editing&&active.has(id),perimeter=adaptivePerimeter(w,h),scale=clamp(Math.min(w,h)/65,.16,.8);
 return <div ref={ref} className={`adaptive-frame-art${editing?' adaptive-suppressed':''}${has('frightened')?' adaptive-frame-tremor':''}`} aria-hidden="true">{!!w&&!!h&&<svg viewBox={`0 0 ${w} ${h}`} focusable="false"><path className={`adaptive-frame-outline${(outline||has('frightened'))&&!has('invisible')?'':' adaptive-outline-hidden'}`} d={perimeter}/>
  <Effect id="invisible" active={has('invisible')}><path className="adaptive-invisible-rim" d={perimeter}/></Effect>
  <Effect id="exhaustion" active={has('exhaustion')}><g className="adaptive-exhaustion-rim">{Array.from({length:6},(_,i)=>i<exhaustion&&<path key={i} d={perimeter} pathLength="600" strokeDasharray="98 502" strokeDashoffset={-i*100}/>)}</g></Effect>
  <Effect id="poisoned" active={has('poisoned')}><path className="adaptive-poison-frame" d={perimeter}/>{Array.from({length:Math.max(2,Math.floor(w/45))},(_,i)=><path className="adaptive-poison-drip" key={i} d={`M${12+i*43} 0q-2 8 2 ${Math.min(h*.42,10+i%3*4)}q4 1 3-7l2-10Z`}/>)}</Effect>
  <Effect id="petrified" active={has('petrified')}><g className="adaptive-stone-cracks">{[[0,0,0],[w,0,90],[w,h,180],[0,h,270]].map(([x,y,a],i)=><g key={i} transform={`translate(${x} ${y}) rotate(${a}) scale(${scale})`}><path d="M12 0L17 15 12 23 29 39 24 48M12 23L1 28M29 39L39 32 51 38M0 8L10 13"/></g>)}</g></Effect>
 </svg>}</div>;
}
