import {useState} from 'react';
import type {Character,Edition} from '../core/model';
import {evaluate} from '../core/engine';
import {exportCharacter,exportCharacters} from '../core/export';
import {download} from '../platform/storage';
import './characterManager.css';

export type CharacterRow={id:string;name:string;player?:string;edition?:string;classes?:string;hp?:number;maxHp?:number;ac?:number;level?:number;write:boolean;locked?:boolean;inScene?:boolean};
export function localCharacterRow(c:Character):CharacterRow{const d=evaluate(c);return {id:c.id,name:c.name,player:c.player,edition:c.edition,classes:c.selections.filter(s=>s.entry.kind==='class').map(s=>`${s.entry.name} ${s.level}`).join(' / '),hp:c.runtime.hp,maxHp:d.maxHp,ac:d.ac,level:d.level,write:true,locked:c.locked};}

export function CharacterManager({rows,currentId,disabled,open,read,remove,create,review}:{rows:CharacterRow[];currentId:string;disabled:boolean;open:(id:string)=>void;read:(ids:string[])=>Promise<Character[]>;remove:(ids:string[])=>Promise<void>;create:(names:string[],edition:Edition)=>Promise<void>;review:(card:Character)=>void}){
 const [selected,setSelected]=useState<string[]>([]),[query,setQuery]=useState(''),[edition,setEdition]=useState<Edition>('2024'),[names,setNames]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[confirm,setConfirm]=useState(false),[createUncertain,setCreateUncertain]=useState(false);
 const visible=rows.filter(r=>`${r.name} ${r.player||''} ${r.classes||''} ${r.edition||''}`.toLowerCase().includes(query.toLowerCase())),ids=selected.filter(id=>rows.some(r=>r.id===id)),all=visible.length>0&&visible.every(r=>ids.includes(r.id));
 const act=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');try{await fn();}catch(e){setError(String(e));}finally{setBusy(false);}};
 const toggle=(id:string,checked:boolean)=>{setConfirm(false);setSelected(current=>checked?[...new Set([...current,id])]:current.filter(v=>v!==id));};
 return <section className="character-manager"><div className="manager-tools"><input aria-label="搜索角色" placeholder="角色 / 玩家 / 职业 / 版本" value={query} onChange={e=>setQuery(e.target.value)}/><span>{rows.length} 张 · 已选 {ids.length} 张</span><button disabled={!ids.length||busy} onClick={()=>void act(async()=>download('角色集合.json',exportCharacters(await read(ids))))}>导出所选 JSON</button><button disabled={!ids.length||busy||disabled||ids.some(id=>!rows.find(r=>r.id===id)?.write)} onClick={()=>setConfirm(true)}>删除所选</button></div>
 {error&&<p role="alert" className="inline-error">{error}</p>}
 {confirm&&<div className="delete-confirm">将删除所选 {ids.length} 张角色资料，场景棋子保留；请先导出备份。<button disabled={busy} onClick={()=>void act(async()=>{await remove(ids);setSelected([]);setConfirm(false);})}>确认批量删除</button><button onClick={()=>setConfirm(false)}>取消</button></div>}
 <div className="manager-table-wrap"><table className="manager-table"><thead><tr><th><input type="checkbox" aria-label="选择当前搜索结果" checked={all} onChange={e=>{setConfirm(false);setSelected(e.target.checked?[...new Set([...ids,...visible.map(r=>r.id)])]:ids.filter(id=>!visible.some(r=>r.id===id)));}}/></th><th>角色 / 玩家</th><th>版本 / 职业</th><th>生命 / AC</th><th>权限</th><th>操作</th></tr></thead><tbody>{visible.map(row=><tr key={row.id} aria-current={row.id===currentId?'true':undefined}><td><input type="checkbox" aria-label={`选择${row.name}`} checked={ids.includes(row.id)} onChange={e=>toggle(row.id,e.target.checked)}/></td><td><button className="character-title" onClick={()=>open(row.id)}><strong>{row.name}</strong><small>{row.player||'未填玩家'}{row.id===currentId?' · 当前':''}</small></button></td><td>{row.edition||'查看详情'}<small>{row.classes|| (row.level?`${row.level} 级`:'')}</small></td><td>{row.hp??'—'} / {row.maxHp??'—'}<small>AC {row.ac??'—'}</small></td><td>{row.write?'可编辑':'只读'}{row.locked?' · 上锁':''}{row.inScene?' · 场内':''}</td><td><button disabled={busy} onClick={()=>void act(async()=>review((await read([row.id]))[0]))}>审卡</button><button disabled={busy} onClick={()=>void act(async()=>download(`${row.name.replace(/[<>:"/\\|?*]/g,'_')}.json`,exportCharacter((await read([row.id]))[0])))}>JSON</button></td></tr>)}</tbody></table></div>
 <details className="manager-create"><summary>批量创建角色</summary><label>规则版本<select value={edition} onChange={e=>setEdition(e.target.value as Edition)}><option>2024</option><option>2014</option></select></label><label>每行一个角色名<textarea aria-label="批量角色名" value={names} onChange={e=>setNames(e.target.value)} placeholder={'旅行者\n向导\n守卫'}/></label><button disabled={busy||disabled||createUncertain||!names.trim()} onClick={()=>void act(async()=>{const list=names.split(/\r?\n/).map(v=>v.trim()).filter(Boolean);if(list.length>100)throw Error('一次最多创建 100 张角色卡');try{await create(list,edition);setNames('');}catch(error){const result=error as {completed?:number;uncertain?:boolean};if(result.completed)setNames(list.slice(result.completed).join('\n'));if(result.uncertain){setCreateUncertain(true);throw Error('创建结果尚未确认，请先回角色簿核对，避免重复创建。');}throw error;}})}>{busy?'正在处理…':'创建这些角色'}</button></details>
 </section>;
}
