import {useEffect,useLayoutEffect,useRef,type KeyboardEvent,type PointerEvent} from 'react';
import type {Character} from '../core/model';
/** A single-row, roving-tabindex list; navigation never moves the sheet viewport. */
export function CharacterTabs({characters,activeId,warnings,label,select}:{characters:Character[];activeId:string;warnings:Set<string>;label:string;select:(id:string)=>void}){
 const list=useRef<HTMLDivElement>(null);
 const drag=useRef<{id:number;x:number;y:number;left:number;moved:boolean}|undefined>(undefined),suppress=useRef(false);
 const tabIds=JSON.stringify(characters.map(character=>character.id));
 const reveal=(button:HTMLButtonElement)=>{const container=list.current;if(!container)return;const strip=container.getBoundingClientRect(),tab=button.getBoundingClientRect();if(tab.left<strip.left)container.scrollLeft+=tab.left-strip.left;else if(tab.right>strip.right)container.scrollLeft+=tab.right-strip.right;};
 useLayoutEffect(()=>{const button=list.current?.querySelector<HTMLButtonElement>('[aria-selected="true"]');if(button)reveal(button);},[activeId,tabIds]);
 useLayoutEffect(()=>{const container=list.current;if(!container)return;const observer=new ResizeObserver(()=>{const button=container.querySelector<HTMLButtonElement>('[aria-selected="true"]');if(button)reveal(button);});// Tab names can change width without changing the strip width. ResizeObserver
 // runs after layout, avoiding a forced whole-sheet layout on every character edit.
 observer.observe(container);for(const button of container.querySelectorAll<HTMLButtonElement>('[role="tab"]'))observer.observe(button);return()=>observer.disconnect();},[tabIds]);
 useEffect(()=>{const container=list.current;if(!container)return;const wheel=(event:WheelEvent)=>{if(event.ctrlKey||container.scrollWidth<=container.clientWidth)return;const distance=(Math.abs(event.deltaX)>Math.abs(event.deltaY)?event.deltaX:event.deltaY)*(event.deltaMode===1?24:event.deltaMode===2?container.clientWidth:1);event.preventDefault();container.scrollLeft+=distance;};container.addEventListener('wheel',wheel,{passive:false});return()=>container.removeEventListener('wheel',wheel);},[]);
 const start=(event:PointerEvent<HTMLDivElement>)=>{if(!event.isPrimary||event.button!==0)return;suppress.current=false;drag.current={id:event.pointerId,x:event.clientX,y:event.clientY,left:event.currentTarget.scrollLeft,moved:false};};
 const move=(event:PointerEvent<HTMLDivElement>)=>{const origin=drag.current;if(!origin||event.pointerId!==origin.id)return;const distance=event.clientX-origin.x;if(Math.hypot(distance,event.clientY-origin.y)>5){origin.moved=true;event.currentTarget.setPointerCapture(event.pointerId);event.currentTarget.classList.add('is-dragging');}if(origin.moved){event.preventDefault();event.currentTarget.scrollLeft=origin.left-distance;}};
 const finish=(event:PointerEvent<HTMLDivElement>)=>{const origin=drag.current;if(!origin||event.pointerId!==origin.id)return;suppress.current=origin.moved;drag.current=undefined;event.currentTarget.classList.remove('is-dragging');if(event.currentTarget.hasPointerCapture(event.pointerId))event.currentTarget.releasePointerCapture(event.pointerId);};
 const navigate=(event:KeyboardEvent<HTMLButtonElement>,index:number)=>{let next=index;if(event.key==='ArrowRight')next=(index+1)%characters.length;else if(event.key==='ArrowLeft')next=(index-1+characters.length)%characters.length;else if(event.key==='Home')next=0;else if(event.key==='End')next=characters.length-1;else return;event.preventDefault();const button=list.current?.querySelectorAll<HTMLButtonElement>('[role="tab"]')[next];button?.focus({preventScroll:true});if(button)reveal(button);select(characters[next].id);};
 return <div ref={list} className="character-tabs" role="tablist" aria-orientation="horizontal" aria-label={label} onPointerDown={start} onPointerMove={move} onPointerUp={finish} onPointerCancel={finish} onClickCapture={event=>{if(suppress.current){event.preventDefault();event.stopPropagation();suppress.current=false;}}}>{characters.map((character,index)=><button key={character.id} type="button" role="tab" tabIndex={character.id===activeId?0:-1} aria-selected={character.id===activeId} title={character.name} onKeyDown={event=>navigate(event,index)} onClick={()=>select(character.id)}>{character.name}{warnings.has(character.id)&&<span className="class-warning-icon" aria-label="旧卡资料需要核对">⚠</span>}</button>)}</div>;
}
