import {InventoryMarks} from './InventoryMarks';
import {NumberInput} from './NumberInput';
import {useContext} from 'react';
import {ABILITIES,ABILITY_LABELS,type Character,type Derived,type Entry,type Kind,type Selection,signed} from '../core/model';
import {spellValues,spellState} from '../core/characterDetails';
import {SheetCell} from './SheetCell';
import {SheetEditContext} from './SheetEdit';
import {Portrait} from './Portrait';
import {FeaturePanel} from './FeaturePanel';
import {IdentityToken} from './IdentityToken';
export type Edit=(action:(c:Character)=>void,key?:string)=>void;
export type PageProps={c:Character;d:Derived;edit:Edit;browse:(kind:Kind)=>void;inspect:(e:Entry)=>void;onLink:(ref:string,kind?:string)=>void;add:(e:Entry)=>void;entries?:Entry[]};
export const number=(v:string,max=9999)=>Math.max(0,Math.min(max,Math.trunc(Number(v)||0)));
function Identity({kind,label,c,edit,inspect,browse}:{kind:Kind;label:string}&Pick<PageProps,'c'|'edit'|'inspect'|'browse'>){return <SheetCell label={label} className={`identity-field detail-identity identity-${kind}`} dropKinds={kind==='class'?['class','subclass']:[kind]}>{c.selections.filter(s=>s.entry.kind===kind||(kind==='class'&&s.entry.kind==='subclass')).map(s=><IdentityToken key={s.id} row={s} c={c} edit={edit} inspect={inspect}/>)}{!c.selections.some(s=>s.entry.kind===kind)&&<button className="cell-fill" onClick={()=>browse(kind)}>点击并拖拽填写</button>}</SheetCell>;}
export function DetailHeader(props:PageProps&{page:string}){
 const {c,d,edit,page}=props,values=spellValues(c,d),editing=useContext(SheetEditContext),settings=spellState(c);
 const spellStat=(kind:'attack'|'dc')=>{const key=kind==='attack'?'attackBonus':'dcBonus',label=kind==='attack'?'法术攻击':'法术DC',bonus=settings[key];return <div className={`adjusted-value ${editing?'has-adjustment':''}`}><strong className="page-value">{kind==='attack'?signed(values.attack):values.dc}</strong>{editing&&<label className="stat-adjustment"><span>调整</span><NumberInput aria-label={`${label}调整值`} type="number" min="-100" max="100" value={bonus} onChange={e=>{const value=Math.max(-100,Math.min(100,Number(e.target.value)||0));edit(d=>{d.spellSettings||=structuredClone(settings);d.spellSettings[key]=value;});}}/></label>}</div>;};
 return <header className={`detail-page-header header-${page}`}><div className="page-caption"><small>{c.name} · {c.edition}</small><h2>{page}</h2></div><div className="page-header-fields">
 {page==='特性'?<>{(['class','background','race'] as Kind[]).map((kind,i)=><Identity {...props} key={kind} kind={kind} label={['职业','背景','种族'][i]}/>)}</>:page==='法术'?<><SheetCell label="法术攻击加值">{spellStat('attack')}</SheetCell><SheetCell label="法术豁免 DC">{spellStat('dc')}</SheetCell></>:page==='背包'?<InventoryMarks c={c} edit={edit}/>:<Identity {...props} kind="background" label="背景"/>}
 {page!=='背景'&&<Portrait c={c} edit={edit}/>}</div></header>;
}
function BackgroundGrants({c,edit}:Pick<PageProps,'c'|'edit'>){const editing=useContext(SheetEditContext);return <>{c.selections.filter(s=>s.entry.kind==='background').map(s=>{
 const raw=s.entry.raw,choice=c.backgroundChoices?.[s.id]||{};const abilities=[...new Set<string>((raw.ability||[]).flatMap((v:any)=>[...Object.keys(v).filter(k=>ABILITIES.includes(k as any)),...(v.choose?.from||[]),...(v.choose?.weighted?.from||[])]))];
 return <section className="background-grants" key={s.id}>{abilities.length>0&&<div className="background-ability-choices"><strong>背景属性</strong>{abilities.map(a=><label key={a}>{ABILITY_LABELS[a as keyof typeof ABILITY_LABELS]}{editing?<NumberInput aria-label={`背景${ABILITY_LABELS[a as keyof typeof ABILITY_LABELS]}加值`} type="number" min="0" max="10" value={choice.abilities?.[a as keyof typeof ABILITY_LABELS]||0} onChange={e=>edit(c=>{const target=(c.backgroundChoices||={})[s.id]||={};(target.abilities||={})[a as keyof typeof ABILITY_LABELS]=number(e.target.value,10);})}/>:<b>{signed(choice.abilities?.[a as keyof typeof ABILITY_LABELS]||0)}</b>}</label>)}</div>}
 {(Array.isArray(raw.startingEquipment)?raw.startingEquipment:[]).map((block:any,i:number)=>{const keys=Object.keys(block).filter(k=>k!=='_');return keys.length>1?<div className="equipment-choices" key={i}><strong>起始装备</strong>{keys.map(key=><button key={key} title={block[key].map((v:any)=>typeof v==='string'?v.split('|')[0]:v.item?.split('|')[0]||v.special||`${(v.value||0)/100} GP`).join('、')} disabled={!editing} aria-pressed={choice.equipment?.[String(i)]===key} onClick={()=>edit(c=>{const target=(c.backgroundChoices||={})[s.id]||={};(target.equipment||={})[String(i)]=key;})}>方案 {key}</button>)}{choice.equipment?.[String(i)]&&<span>{block[choice.equipment[String(i)]].map((v:any)=>typeof v==='string'?v.split('|')[0]:v.item?.split('|')[0]||v.special||`${(v.value||0)/100} GP`).join('、')}</span>}</div>:null;})}</section>;
 })}</>;}
export function FeaturesPage(props:PageProps){const {c,edit,browse,onLink,add}=props;const owner=(s:Selection)=>{let row=s;const seen=new Set<string>();while(row.parentId&&!seen.has(row.id)){seen.add(row.id);const parent=c.selections.find(p=>p.id===row.parentId);if(!parent)break;row=parent;}return row.entry.kind;};const rows=c.selections.filter(s=>['feature','rule','feat'].includes(s.entry.kind));
 const panel=(label:string,items:Selection[],kinds:Kind[],className:string)=><FeaturePanel detailed c={c} edit={edit} rows={items} label={label} kinds={kinds} className={className} browse={()=>browse(kinds[0])} receive={add} onLink={onLink}/>;
 return <><BackgroundGrants c={c} edit={edit}/><div className="features-page-grid">{panel('职业特性',rows.filter(s=>s.entry.kind!=='feat'&&!['race','background'].includes(owner(s))),['feature','rule'],'detail-class-features')}{panel('种族特性',rows.filter(s=>s.entry.kind!=='feat'&&owner(s)==='race'),['feature','rule'],'detail-race-features')}{panel('专长',rows.filter(s=>s.entry.kind==='feat'),['feat'],'detail-feats')}{panel('背景特性',rows.filter(s=>s.entry.kind!=='feat'&&owner(s)==='background'),['feature','rule'],'detail-background-features')}</div></>;
}
function TextField({label,value,change,multi=false}:{label:string;value:string;change:(v:string)=>void;multi?:boolean}){const editing=useContext(SheetEditContext);return <label className={`biography-field ${multi?'biography-multi':''}`}><span>{label}</span>{editing?multi?<textarea aria-label={label} value={value} onChange={e=>change(e.target.value)}/>:<input aria-label={label} value={value} onChange={e=>change(e.target.value)}/>:<div className="biography-text">{value}</div>}</label>;}
export function BackgroundPage({c,edit}:PageProps){const biography=c.biography||{};const bio=(key:keyof NonNullable<Character['biography']>,label:string,multi=true)=><TextField label={label} multi={multi} value={biography[key]??(key==='story'?c.notes:'')} change={value=>edit(c=>{(c.biography||={})[key]=value;},key)}/>;
 return <div className="biography-grid"><SheetCell label="人物资料" className="bio-identity"><TextField label="角色名" value={c.name} change={v=>edit(c=>{c.name=v;},'name')}/><TextField label="玩家" value={c.player} change={v=>edit(c=>{c.player=v;},'player')}/>{bio('hometown','故乡',false)}{(['age','gender','alignment'] as const).map((key,i)=><TextField key={key} label={['年龄','性别','阵营'][i]} value={c.identity[key]} change={v=>edit(c=>{c.identity[key]=v;},key)}/>)}{bio('height','身高',false)}{bio('weight','体重',false)}</SheetCell><SheetCell label="背景描述" className="bio-description">{bio('backgroundDescription','背景描述')}</SheetCell><SheetCell label="人物形象" className="bio-appearance"><TextField label="人物形象" multi value={c.identity.description} change={v=>edit(c=>{c.identity.description=v;},'description')}/></SheetCell><SheetCell label="个性与信念" className="bio-personality">{bio('traits','个性')}{bio('ideals','理念')}{bio('bonds','羁绊')}{bio('flaws','缺陷')}</SheetCell><SheetCell label="背景故事" className="bio-story">{bio('story','背景故事')}</SheetCell><div className="bio-portrait"><Portrait c={c} edit={edit} field="illustration"/>{bio('portraitNotes','立绘备注')}</div></div>;
}
