import {sourceEquipmentChoices} from '../core/automation/sourceEquipment';
import {useContext,useEffect,useMemo,useRef,useState} from 'react';
import type {Character,Entry} from '../core/model';
import {chooseSheetOption,setSheetChoiceSlot,sheetChoices,choiceSource,claimStartingEquipment,equipmentBlocks,equipmentCandidates,equipmentTypeLabel,equipmentOptionConcept,equipmentPackage,type ChoiceOption} from '../core/automation/choices';
import {Reference} from './Reference';
import {SheetCell} from './SheetCell';
import {DragContext,DropZone} from './DragEntry';
import {choiceCatalog,choiceEntryMatcher} from './choiceCatalog';
import {useChoiceWorkspace} from './ChoiceWorkspaceContext';
import './automationChoices.css';

// Only this small leaf follows pointer hover state. Resolving a whole catalog on
// every drag frame makes the drop targets lag behind the pointer on large wikis.
function DraggableChoice({option}:{option:ChoiceOption}){
 const drag=useContext(DragContext);
 return <Reference className="choice-slot-entry" entry={option.entry} reference={`entry:${option.entry.id}`} commitOnClick={false} onPointerDown={event=>{if(option.unavailable)event.stopPropagation();else drag?.start(event,option.entry);}}>{option.label}</Reference>;
}

export function ChoiceWorkspace({c,id,catalog,edit,close}:{c:Character;id:string;catalog:Entry[];edit:(action:(c:Character)=>void)=>void;close:()=>void}){
 const choices=useMemo(()=>sheetChoices(c,catalog),[c,catalog]),choice=choices.find(r=>r.id===id),workspace=useChoiceWorkspace(),[error,setError]=useState(''),[equipment,setEquipment]=useState(''),[picks,setPicks]=useState<Record<string,string>>(()=>{const owner=c.selections.find(row=>row.id===id.split(':equipment')[0]);return owner?sourceEquipmentChoices(c,owner):{};}),confirmed=useRef(false);
 const scope=useMemo(()=>choice?choiceCatalog(c,choice,catalog):undefined,[c,choice,catalog]);
 const matchEntry=useMemo(()=>choice?choiceEntryMatcher(c,choice):()=>undefined,[c,choice]);
 const exit=()=>{window.dispatchEvent(new Event('sheet-gesture'));close();requestAnimationFrame(()=>document.querySelector<HTMLElement>(`[data-choice-id="${CSS.escape(id)}"]`)?.focus({preventScroll:true}));};
 useEffect(()=>{const key=(e:KeyboardEvent)=>{if(e.key==='Escape'&&!e.defaultPrevented&&!document.body.classList.contains('pointer-dragging')){e.preventDefault();exit();}};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[close,id]);
 if(!choice||!scope)return null;
 const selected=choice.channel==='equipment'?(equipment?[equipment]:choice.selected.length?choice.selected:choice.equipmentIndex!<0&&choice.options[0]?[choice.options[0].value]:[]):choice.selected,owner=c.selections.find(s=>s.id===choice.ownerId)!,packageItems=choice.channel==='equipment'&&selected[0]?equipmentPackage(owner.entry,choice.equipmentIndex!,selected[0],picks):[],grouped=choice.channel==='equipment'&&choice.equipmentIndex!<0&&choice.options.length?equipmentBlocks(owner.entry):[],related=choices.filter(row=>choiceSource(c,row)===choiceSource(c,choice)),availableCount=choice.channel==='tools'?choice.selected.filter(value=>choice.options.some(option=>option.value===value&&!option.unavailable)).length:choice.selected.length,preservedTools=choice.channel==='tools'&&availableCount<choice.selected.length;
 const act=(action:(draft:Character)=>void)=>{try{edit(action);setError('');}catch(e){setError(e instanceof Error?e.message:String(e));}};
 const claim=()=>{if(confirmed.current)return;try{if(!selected[0])throw Error('请先选择起始装备方案。');confirmed.current=true;edit(draft=>claimStartingEquipment(draft,id,selected[0],catalog,picks));close();}catch(e){confirmed.current=false;setError(e instanceof Error?e.message:String(e));}};
 return <SheetCell label={`选择${choice.label}`} className="choice-workspace" trailing={<button className="choice-exit" onClick={exit}>返回特性</button>}><div data-choice-workspace data-local-preview>
  <p className="choice-owner">{owner.entry.name} · {choice.channel==='equipment'?'领取后生效，返回可放弃当前方案':'选择即时生效，返回保留已选内容'}</p>
  {related.length>1&&<nav className="choice-navigation" aria-label="职业选择项">{related.map(row=><button key={row.id} aria-current={row.id===id?'step':undefined} onClick={()=>workspace.open(row.id)}>{row.label}<span>{row.selected.length}/{row.count}</span></button>)}</nav>}
  <p className="choice-progress" role="status">{choice.label} {availableCount}/{choice.count}<span>{preservedTools?'已有选择当前不可用，原记录保留':choice.complete?choice.channel==='equipment'?'已领取，再次确认会追加装备':'已完成，可继续调整':availableCount>choice.count?'旧记录超过当前数量，请手动调整':`还需选择 ${choice.count-availableCount} 项`}</span></p>
  {choice.hint&&<p className="choice-hint">{choice.hint}</p>}
  {scope.wiki?<><p className="choice-hint">从 Wiki 拖拽到选择格。拖到已选格可替换；重复条目会交换位置。Esc 取消拖拽。</p><div className="choice-slots">{Array.from({length:Math.max(choice.count,choice.slots?.length||0)},(_,index)=>{
   const stored=(choice.slots||choice.selected)[index],option=choice.options.find(o=>o.value===stored),unavailable=choice.channel==='tools'&&stored&&(!option||option.unavailable);
   return <DropZone referenceOnly key={index} className={`choice-slot ${stored?'is-filled':''}`} aria-label={`${choice.label}选择格 ${index+1}`} accepts={entry=>{const match=matchEntry(entry);return !choice.restricted&&!!match&&!match.unavailable;}} rejectReason={choice.restricted?'此选择来源尚未启用。':'此条目不属于当前可选内容，请从右侧 Wiki 候选中拖入。'} onReceive={entry=>{const match=matchEntry(entry);if(match&&match.value!==stored)act(draft=>setSheetChoiceSlot(draft,id,index,match.value,catalog));}}>
    <span className="choice-slot-number" aria-hidden="true">{index+1}</span>{stored?<>{option?<DraggableChoice option={option}/>:<span className="choice-empty">已有记录：{stored}</span>}{unavailable&&<small>{option?.unavailable||'此记录的资料尚未加载，原值保留。'}</small>}<button className="choice-remove" aria-label={`移除${option?.label||stored}`} disabled={choice.restricted} onClick={()=>act(draft=>setSheetChoiceSlot(draft,id,index,undefined,catalog))}>×</button></>:<span className="choice-empty">等待拖拽加入</span>}
   </DropZone>;
  })}</div>{!scope.entries.length&&<p className="choice-hint choice-loading" role="status">{choice.spellKind==='prepared'&&owner.entry.raw.spellsKnownProgressionFixed?'请先选择法术书中的法术。':'候选资料尚未加载；可以先返回，已有选择会保留。资料载入后可继续。'}</p>}</>:<div className="choice-options">{choice.options.map(option=>{const blocked=choice.restricted||!!option.unavailable&&!(choice.channel==='tools'&&selected.includes(option.value));return <Reference key={option.value} entry={option.entry} reference={`entry:${option.entry.id}`} commitOnClick={false} onPointerDown={e=>e.stopPropagation()} className={`choice-option ${selected.includes(option.value)?'is-picked':''}`} aria-pressed={selected.includes(option.value)} aria-disabled={blocked} onClick={()=>{if(blocked){setError(option.unavailable||'此选择来源尚未启用。');return;}if(choice.channel==='equipment'){setEquipment(option.value);setError('');}else act(draft=>chooseSheetOption(draft,id,option.value,catalog));}}>{option.label}{option.unavailable&&<small>{option.unavailable}</small>}</Reference>;})}</div>}
  {!scope.wiki&&choice.channel==='tools'&&choice.slots?.map((value,index)=>value&&!choice.options.some(option=>option.value===value)&&<div className="choice-slot is-filled" key={`preserved:${index}`}><span>已有记录：{value}</span><small>此记录的资料尚未加载，原值保留。</small><button className="choice-remove" aria-label={`移除${value}`} disabled={choice.restricted} onClick={()=>act(draft=>setSheetChoiceSlot(draft,id,index,undefined,catalog))}>×</button></div>)}
  {grouped.map((block,index)=>{const keys=Object.keys(block).filter(k=>k!=='_');return keys.length>1&&<div className="choice-options" key={`group:${index}`}><strong>装备选择 {index+1}</strong>{keys.map(value=>{const entry=equipmentOptionConcept(owner.entry,index,value);return <Reference key={value} entry={entry} reference={`entry:${entry.id}`} commitOnClick={false} onPointerDown={e=>e.stopPropagation()} className={`choice-option ${picks[`group:${index}`]===value?'is-picked':''}`} aria-pressed={picks[`group:${index}`]===value} onClick={()=>setPicks({...Object.fromEntries(Object.entries(picks).filter(([key])=>key.startsWith('group:'))),[`group:${index}`]:value})}>方案 {value}</Reference>;})}</div>;})}
  {packageItems.flatMap((item:any,index:number)=>item?.equipmentType?Array.from({length:Number.isSafeInteger(item.quantity??1)&&Number(item.quantity??1)>0?Math.min(3000,item.quantity??1):0},(_,n)=><div className="choice-options" key={`${index}:${n}`}><strong>{equipmentTypeLabel(item.equipmentType)} · {n+1}</strong>{equipmentCandidates(item.equipmentType,owner.entry,catalog).map(entry=><Reference key={entry.id} entry={entry} reference={`entry:${entry.id}`} commitOnClick={false} onPointerDown={e=>e.stopPropagation()} className={`choice-option ${picks[`${index}:${n}`]===entry.id?'is-picked':''}`} aria-pressed={picks[`${index}:${n}`]===entry.id} onClick={()=>setPicks({...picks,[`${index}:${n}`]:entry.id})}>{entry.name}</Reference>)}</div>):[])}
  {error&&<p role="alert">{error}</p>}
  <footer className="choice-footer"><button onClick={exit}>{choice.channel==='equipment'?'取消并返回':'完成并返回'}</button>{choice.channel==='equipment'&&<button disabled={choice.restricted||!choice.options.length} title={choice.complete?'再次确认将追加装备，不会回收已领取或已花费的物品。':undefined} onClick={claim}>领取装备</button>}</footer>
 </div></SheetCell>;
}
