import {useEffect,useRef,useState} from 'react';
import {useWorkbench,workbenchRequest} from '../platform/workbench';
import './cloudRoomControl.css';
export function CloudIcon(){return <svg viewBox="0 0 24 24" width="17" height="17" fill="none" stroke="currentColor" strokeWidth="1.8" aria-label="云端同步卡" role="img"><path d="M7 18h11a4 4 0 000-8 6 6 0 00-11.5-1A4.5 4.5 0 007 18Z"/></svg>;}
type Info={cardId:string;name:string;owner:boolean;editor:boolean;write:boolean;locked:boolean;ownerNickname:string;ownerAccountId:string;editors?:string[]};
export function CloudRoomControl(){
 const wb=useWorkbench(),target=wb.target,[open,setOpen]=useState(false),[info,setInfo]=useState<Info>(),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[account,setAccount]=useState(''),dialog=useRef<HTMLDialogElement>(null);
 useEffect(()=>{setOpen(false);setInfo(undefined);},[target?.key]);
 useEffect(()=>{if(open)dialog.current?.showModal();},[open]);
 async function read(){const value=await workbenchRequest('cloudInfo');setInfo(value);return value as Info;}
 async function act(action:()=>Promise<unknown>){setBusy(true);setMessage('');try{await action();}catch(error){setMessage(error instanceof Error?error.message:String(error));}finally{setBusy(false);}}
 if(!target?.cloudRoom)return null;
 return <><button className="card-lock cloud-card-control" aria-label="云端卡设置" disabled={!wb.online} onClick={()=>{setOpen(true);void act(read);}}><CloudIcon/></button>{open&&<dialog ref={dialog} className="cloud-room-dialog" aria-label="云端卡设置" onCancel={()=>setOpen(false)}><header><h2>云端卡设置</h2><button autoFocus onClick={()=>setOpen(false)}>关闭</button></header>{info?<><strong>{info.name}</strong><p>卡主：{info.ownerNickname}</p><p>云端卡 ID：<code>{info.cardId}</code></p><p role="status">{info.owner?'你是这张卡的拥有者。':info.editor?'卡主已授权你的 QQ 账号编辑这张卡；你可以编辑完整角色内容，权限设置由卡主管理。':info.write?'卡主已允许当前房间成员编辑这张卡。':'你没有编辑权限，可以查看和导出；DM 同样需要卡主授权。'}</p><p>获准的房间修改会自动写回云端原卡。</p>{info.owner&&<><label className="cloud-room-toggle"><input type="checkbox" checked={!info.locked} disabled={busy} onChange={event=>void act(async()=>{await workbenchRequest('lock',{locked:!event.target.checked});await read();})}/>允许当前房间所有成员编辑</label><p>也可以单独授权 QQ 账号；授权在云端及已加载房间生效。请填写对方登录后复制的账号 ID。</p><form onSubmit={event=>{event.preventDefault();void act(async()=>{await workbenchRequest('cloudEditors',{accountId:account,remove:false});setAccount('');await read();});}}><label>编辑者账号 ID<input value={account} onChange={event=>setAccount(event.target.value)} pattern="[a-f0-9-]{36}" required/></label><button disabled={busy}>授予编辑权限</button></form>{info.editors?.map(id=><p key={id}><code>{id}</code> <button disabled={busy} onClick={()=>void act(async()=>{await workbenchRequest('cloudEditors',{accountId:id,remove:true});await read();})}>撤销授权</button></p>)}<button disabled={busy} onClick={()=>{if(confirm('将这张云端卡移出当前房间？云端原卡会保留。'))void act(async()=>{await workbenchRequest('delete');setOpen(false);});}}>移出房间</button></>}</>:<p role="status">正在读取云端卡权限…</p>}{message&&<p role="alert">{message}</p>}</dialog>}</>;
}
export function WorkbenchPermissionNotice(){const wb=useWorkbench();if(!wb.target||wb.online&&wb.target.write)return null;return <aside className="class-compatibility-banner card-permission-banner" role="status"><p>{!wb.online?'房间连接尚未恢复，暂时无法编辑。':wb.target.cloudRoom?'卡主未授予当前 QQ 账号编辑权限，DM 同样需要授权。可查看、导出或打开云端设置核对。':'当前玩家没有这张角色卡的编辑权限，请核对枭熊棋子的所属玩家设置。'}</p></aside>;}
