import {FieldHelp,CustomFormatReference,AUTHORING_GUIDE} from './CustomFieldHelp';
import {CustomEntryCanvas} from './CustomEntryCanvas';
import {customEntryExample,customCreationPrompt,parseCustomEntryJson,validateCustomFields} from '../core/customEntrySchema';
import {parseFile,validateEntryContent} from '../core/validation';
import {useEffect,useState} from 'react';
import {createCustomEntry} from '../core/customEntries';
import type {Entry} from '../core/model';
import {EntryDraggable} from './DragEntry';
import {entryLabel} from '../core/entryLabel';
import './customEntries.css';
type Draft={name:string;english:string;type:string;body:string;raw:string;edition:Entry['edition'];price:string;weight:string;entries:unknown[];bodyBaseline:string};
export function CustomEntryEditor({entry,draft,busy,save,remove,newEntry}:{entry?:Entry;draft?:Entry;busy:boolean;save:(entry:Entry)=>Promise<void>;remove:(entry:Entry)=>Promise<void>;newEntry:()=>void}){
 const [expanded,setExpanded]=useState(false);
 const [name,setName]=useState(''),[type,setType]=useState('item'),[body,setBody]=useState(''),[raw,setRaw]=useState('{}'),[error,setError]=useState('');
 const [jsonText,setJsonText]=useState(''),[message,setMessage]=useState(''),[edition,setEdition]=useState<Entry['edition']>('both'),[english,setEnglish]=useState('');
 const [price,setPrice]=useState(''),[weight,setWeight]=useState(''),[mode,setMode]=useState<'fields'|'json'>('fields'),[undoExample,setUndoExample]=useState<{draft:Draft;json:string;mode:'fields'|'json'}>(),[prompt,setPrompt]=useState('');
 const [originalEntries,setOriginalEntries]=useState<unknown[]>([]),[bodyBaseline,setBodyBaseline]=useState('');
 const [canvasError,setCanvasError]=useState('');
 const fields=(()=>{try{const value=parseFile(raw);return value&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,any>:undefined;}catch{return undefined;}})();
 function applyDraft(d:Draft){setName(d.name);setEnglish(d.english);setType(d.type);setBody(d.body);setRaw(d.raw);setEdition(d.edition);setPrice(d.price);setWeight(d.weight);setOriginalEntries(d.entries);setBodyBaseline(d.bodyBaseline);}
 function fromEntry(e?:Entry):Draft{e=e||parseCustomEntryJson(JSON.stringify(customEntryExample('item')));const body=e?.entries.map(v=>typeof v==='string'?v:JSON.stringify(v)).join('\n\n')||'';return {entries:structuredClone(e?.entries||[]),bodyBaseline:body,name:e?.name||'',english:e?.english||'',type:e?.raw._customType||'item',body,raw:JSON.stringify(Object.fromEntries(Object.entries(e?.raw||{}).filter(([key])=>!key.startsWith('_')||key==='_legendaryGroup')),null,2),edition:e?.edition||'both',price:typeof e?.raw.value==='number'?String(e.raw.value/100):'',weight:typeof e?.raw.weight==='number'?String(e.raw.weight):''};}
 function jsonDraft(){const fields=parseFile(raw) as Record<string,any>;if(!fields||typeof fields!=='object'||Array.isArray(fields))throw Error('结构字段必须是对象');const entries=body===bodyBaseline?originalEntries:body.split(/\n\s*\n/).filter(v=>v.trim()).map(v=>{try{const node=JSON.parse(v);return node&&typeof node==='object'?node:v;}catch{return v;}});return JSON.stringify({name,english,edition,type,entries,raw:fields},null,2);}
 // The raw object is authoritative. Dedicated item inputs update the same keys;
 // an invalid raw draft is never replaced by stale price/weight state.
 function changeRaw(text:string){setRaw(text);try{const value=parseFile(text) as Record<string,any>;if(value&&typeof value==='object'&&!Array.isArray(value)){setPrice(typeof value.value==='number'?String(value.value/100):'');setWeight(typeof value.weight==='number'?String(value.weight):'');setError('');}}catch{}}
 function changeItemNumber(key:'value'|'weight',text:string){if(!fields)return;if(key==='value')setPrice(text);else setWeight(text);const next={...fields};if(text.trim())next[key]=Number(text)*(key==='value'?100:1);else delete next[key];setRaw(JSON.stringify(next,null,2));}
 function readJson(text:string){const value=parseCustomEntryJson(text,type);applyDraft(fromEntry(value));setError('');return value;}
 useEffect(()=>{setExpanded(!!draft);applyDraft(fromEntry(entry||draft));setCanvasError('');setJsonText('');setMessage('');setError('');setMode('fields');setUndoExample(undefined);setPrompt('');},[entry?.id,entry?.revision,draft?.id]);
 useEffect(()=>{if(mode==='fields')try{setJsonText(jsonDraft());}catch{/* Keep invalid field text intact until the user repairs it. */}},[mode,name,english,type,body,raw,edition,price,weight,originalEntries,bodyBaseline]);
 function toggle(next:'fields'|'json'){if(next===mode)return;try{if(next==='json')setJsonText(jsonDraft());else readJson(jsonText);setMode(next);setError('');}catch(e){setError(String(e));}}
 function fillExample(){setUndoExample({draft:{name,english,type,body,raw,edition,price,weight,entries:originalEntries,bodyBaseline},json:jsonText,mode});const text=JSON.stringify(customEntryExample(type),null,2);readJson(text);setJsonText(text);setMessage('示例已填入所有字段，可直接修改；撤回可恢复填写前的内容。');}
 async function submit(){try{let next:Entry;if(mode==='json'){next=readJson(jsonText);next.id=entry?.id||next.id;next.revision=String(Number(entry?.revision||0)+1);}else{const fields=parseFile(raw) as Record<string,any>;if(!fields||typeof fields!=='object'||Array.isArray(fields))throw Error('结构字段必须是对象');next=createCustomEntry({id:entry?.id,name,english,type,body,entries:body===bodyBaseline?originalEntries:undefined,raw:fields,edition,revision:String(Number(entry?.revision||0)+1)});validateCustomFields(type,next.raw,next.entries);validateEntryContent(next.entries);}await save(next);setError('');}catch(e){setError(String(e));}}
 if(entry&&!expanded)return <section className="custom-entry-editor is-collapsed" aria-label="自定义条目操作"><header><h2>自定义条目</h2><button onClick={newEntry}>＋ 新建条目</button><button onClick={()=>setExpanded(true)}>编辑此条目</button><button disabled={busy} onClick={()=>void remove(entry).catch(e=>setError(String(e)))}>删除条目</button></header>{error&&<p role="alert">{error}</p>}</section>;
 return <section className="custom-entry-editor" aria-label="自定义条目编辑器"><header><div className="custom-editor-title"><h2>{entry?'编辑条目':'新建条目'}</h2><FieldHelp label="使用必看！" trigger="使用必看！" examples={AUTHORING_GUIDE}/></div><button onClick={newEntry}>＋ 新建条目</button>{entry&&<EntryDraggable entry={entry} className="custom-drag" aria-label={`拖拽 ${entry.name}`}>拖拽 {entryLabel(entry)}</EntryDraggable>}</header><form onSubmit={e=>{e.preventDefault();void submit();}}>
 <div className="custom-authoring-tools"><button type="button" onClick={()=>{void navigator.clipboard.writeText(customCreationPrompt(type)).then(()=>setMessage('创作提示词已复制')).catch(()=>{setPrompt(customCreationPrompt(type));setMessage('剪贴板不可用，可复制下方提示词。');});}}>复制创作提示词</button><button type="button" onClick={fillExample}>填充格式示例</button><CustomFormatReference type={type}/>{undoExample&&<button type="button" onClick={()=>{applyDraft(undoExample.draft);setJsonText(undoExample.json);setMode(undoExample.mode);setUndoExample(undefined);setError('');setMessage('已撤回示例，恢复原填写内容。');}}>撤回</button>}<div className="custom-input-modes" role="group" aria-label="条目输入方式"><button type="button" aria-pressed={mode==='fields'} onClick={()=>toggle('fields')}>格式输入</button><button type="button" aria-pressed={mode==='json'} onClick={()=>toggle('json')}>JSON 输入</button></div></div>
 {prompt&&<textarea aria-label="创作提示词" readOnly value={prompt} onFocus={e=>e.currentTarget.select()}/>}{message&&<p role="status">{message}</p>}
 {mode==='json'?<div className="custom-json-import"><FieldHelp label="完整 JSON"/><textarea aria-label="完整自定义条目 JSON" spellCheck={false} value={jsonText} onChange={e=>{const text=e.target.value;setJsonText(text);try{readJson(text);setMessage('JSON 已同步至格式输入，保存后生效。');}catch(error){setError(String(error));}}}/><button type="button" onClick={()=>{void navigator.clipboard.writeText(jsonText).then(()=>setMessage('条目 JSON 已复制')).catch(()=>setMessage('剪贴板不可用，可复制文本框内容'));}}>复制当前 JSON</button></div>:<>
 {fields&&<CustomEntryCanvas name={name} english={english} type={type} edition={edition} body={body} entries={body===bodyBaseline?originalEntries:body.split(/\n\s*\n/).filter(v=>v.trim()).map(v=>{try{const node=JSON.parse(v);return node&&typeof node==='object'?node:v;}catch{return v;}})} raw={fields} change={value=>changeRaw(JSON.stringify(value,null,2))} changeBody={setBody} invalid={setCanvasError} identity={(key,value)=>{if(key==='name')setName(value);else if(key==='english')setEnglish(value);else if(key==='edition')setEdition(value as Entry['edition']);else {setType(value);changeRaw(JSON.stringify(customEntryExample(value).raw,null,2));}}}/>}
 <details><summary>结构字段</summary><FieldHelp label="结构字段"/><textarea aria-label="自定义结构字段" spellCheck={false} value={raw} onChange={e=>changeRaw(e.target.value)}/></details>
</>}
 {(error||canvasError)&&<p role="alert">{error||canvasError}</p>}<footer><button type="submit" disabled={busy||!!canvasError||mode==='fields'&&!fields}>保存条目</button>{entry&&<button type="button" disabled={busy} onClick={()=>void remove(entry).catch(e=>setError(String(e)))}>删除条目</button>}</footer></form></section>;
}
