import {CustomStructureFields} from './CustomStructureFields';
import {customEntryExample,customCreationPrompt,parseCustomEntryJson,validateCustomFields} from '../core/customEntrySchema';
import {parseFile,validateEntryContent} from '../core/validation';
import {useEffect,useState} from 'react';
import {createCustomEntry,CUSTOM_TYPES} from '../core/customEntries';
import type {Entry} from '../core/model';
import {EntryDraggable} from './DragEntry';
import {Entries} from './Entries';
import {entryLabel} from '../core/entryLabel';
import './customEntries.css';
export function CustomEntryEditor({entry,busy,save,remove,newEntry}:{entry?:Entry;busy:boolean;save:(entry:Entry)=>Promise<void>;remove:(entry:Entry)=>Promise<void>;newEntry:()=>void}){
 const [name,setName]=useState(''),[type,setType]=useState('item'),[body,setBody]=useState(''),[raw,setRaw]=useState('{}'),[error,setError]=useState('');
 const [jsonText,setJsonText]=useState(''),[message,setMessage]=useState(''),[edition,setEdition]=useState<Entry['edition']>('both'),[english,setEnglish]=useState('');
 const [price,setPrice]=useState(''),[weight,setWeight]=useState('');
 const isItem=CUSTOM_TYPES[type]?.kind==='item';
 const fields=(()=>{try{const value=parseFile(raw);return value&&typeof value==='object'&&!Array.isArray(value)?value as Record<string,any>:undefined;}catch{return undefined;}})();
 useEffect(()=>{setPrice(typeof entry?.raw.value==='number'?String(entry.raw.value/100):'');setWeight(typeof entry?.raw.weight==='number'?String(entry.raw.weight):'');},[entry?.id,entry?.revision]);
 useEffect(()=>{setEdition(entry?.edition||'both');setEnglish(entry?.english||'');setJsonText('');setMessage('');setName(entry?.name||'');setType(entry?.raw._customType||'item');setBody(entry?.entries.map(e=>typeof e==='string'?e:JSON.stringify(e)).join('\n\n')||'');setRaw(JSON.stringify(Object.fromEntries(Object.entries(entry?.raw||{}).filter(([key])=>!key.startsWith('_'))),null,2));setError('');},[entry?.id,entry?.revision]);
 return <section className="custom-entry-editor" aria-label="自定义条目编辑器"><header><h2>{entry?'编辑条目':'新建条目'}</h2><button onClick={newEntry}>＋ 新建条目</button>{entry&&<EntryDraggable entry={entry} className="custom-drag" aria-label={`拖拽 ${entry.name}`}>拖拽 {entryLabel(entry)}</EntryDraggable>}</header><form onSubmit={e=>{e.preventDefault();try{const fields=parseFile(raw) as Record<string,any>;if(isItem){if(!price.trim()||!weight.trim())throw Error('请填写价格与重量');fields.value=Number(price)*100;fields.weight=Number(weight);}const next=createCustomEntry({id:entry?.id,name,type,body,raw:fields,edition,revision:String(Number(entry?.revision||0)+1)});next.english=english.trim()||next.name;validateCustomFields(type,next.raw,next.entries);validateEntryContent(next.entries);void save(next).catch(e=>setError(String(e)));}catch(e){setError(String(e));}}}>
 <div className="custom-authoring-tools"><button type="button" onClick={()=>{void navigator.clipboard.writeText(customCreationPrompt(type)).then(()=>setMessage('创作提示词已复制')).catch(()=>{setJsonText(customCreationPrompt(type));setMessage('剪贴板不可用，提示词已显示在下方文本框');});}}>复制创作提示词</button><button type="button" onClick={()=>{setJsonText(JSON.stringify(customEntryExample(type),null,2));setMessage('格式示例已填入 JSON 区；修改后点击载入 JSON');}}>查看格式示例</button></div>
 <details className="custom-json-import" open={!!jsonText}><summary>完整 JSON 输入 / 复制</summary><textarea aria-label="完整自定义条目 JSON" spellCheck={false} value={jsonText} onChange={e=>setJsonText(e.target.value)}/><button type="button" onClick={()=>{try{const value=parseCustomEntryJson(jsonText,type);setType(value.raw._customType);setName(value.name);setEnglish(value.english);setEdition(value.edition);setBody(value.entries.map(v=>typeof v==='string'?v:JSON.stringify(v)).join('\n\n'));setRaw(JSON.stringify(value.raw,null,2));setPrice(typeof value.raw.value==='number'?String(value.raw.value/100):'');setWeight(typeof value.raw.weight==='number'?String(value.raw.weight):'');setError('');setMessage('JSON 已载入编辑器，保存后可拖拽使用');}catch(error){setError(String(error));}}}>载入 JSON</button><button type="button" onClick={()=>{try{const fields=JSON.parse(raw);if(isItem){fields.weight=Number(weight);fields.value=Number(price)*100;}const value=createCustomEntry({name,type,body,raw:fields,edition});const text=JSON.stringify({name,english,edition,type,entries:value.entries,raw:value.raw},null,2);setJsonText(text);void navigator.clipboard.writeText(text).then(()=>setMessage('条目 JSON 已复制')).catch(()=>setMessage('剪贴板不可用，可复制文本框内容'));}catch(error){setError(String(error));}}}>复制当前 JSON</button></details>
 {message&&<p role="status">{message}</p>}
 <div className="custom-fields"><label>名称<input aria-label="自定义条目名称" required maxLength={160} value={name} onChange={e=>setName(e.target.value)}/></label><label>类型<select aria-label="自定义条目类型" value={type} onChange={e=>setType(e.target.value)}>{Object.entries(CUSTOM_TYPES).map(([key,t])=><option value={key} key={key}>{t.label}</option>)}</select></label></div>
 <div className="custom-fields"><label>英文名<input aria-label="自定义条目英文名" value={english} onChange={e=>setEnglish(e.target.value)}/></label><label>适用版本<select aria-label="自定义条目版本" value={edition} onChange={e=>setEdition(e.target.value as Entry['edition'])}><option value="both">通用</option><option value="2014">2014</option><option value="2024">2024</option></select></label></div>
 <CustomStructureFields type={type} raw={fields} change={value=>setRaw(JSON.stringify(value,null,2))}/>
 {isItem&&<div className="custom-fields custom-item-fields"><label>价格（金币）<input aria-label="物品价格（金币）" type="number" required min="0" step="any" value={price} onChange={e=>setPrice(e.target.value)}/></label><label>重量（磅）<input aria-label="物品重量（磅）" type="number" required min="0" step="any" value={weight} onChange={e=>setWeight(e.target.value)}/></label></div>}
 <label>正文<textarea className="custom-body" aria-label="自定义条目正文" value={body} onChange={e=>setBody(e.target.value)} maxLength={100000}/></label>
 <details><summary>结构字段</summary><textarea aria-label="自定义结构字段" spellCheck={false} value={raw} onChange={e=>setRaw(e.target.value)}/></details>
 {error&&<p role="alert">{error}</p>}<footer><button type="submit" disabled={busy}>保存条目</button>{entry&&<button type="button" disabled={busy} onClick={()=>void remove(entry).catch(e=>setError(String(e)))}>删除条目</button>}</footer></form>
 {entry&&<article className="rules-prose"><h3>{entryLabel(entry)}</h3><Entries value={entry.entries}/></article>}
 </section>;
}
