import { explicitlyExcluded } from './libraryData';
import { matchesEntrySearch } from '../core/search';
import { useDeferredValue, useEffect, useMemo, useRef, useState } from 'react';
import { KIND_LABELS, type Character, type Entry } from '../core/model';
import { Reference } from './Reference';
import { useSources } from './SourceName';
import { VirtualList } from './VirtualList';
export function GlobalSearch({query,change,entries,c,inspect}:{query:string;change:(s:string)=>void;entries:Entry[];c:Character;inspect:(e:Entry)=>void}){
 const {format,registry}=useSources(),deferredQuery=useDeferredValue(query);const [open,setOpen]=useState(false),[fixed,setFixed]=useState(false),[keyboardIndex,setKeyboardIndex]=useState(-1);const root=useRef<HTMLDivElement>(null);
 const results=useMemo(()=>{const q=deferredQuery.trim();return q?entries.filter(e=>matchesEntrySearch(e,q,registry[e.source]?.name)):[];},[deferredQuery,entries,registry]);
 useEffect(()=>{if(!open)return;const outside=(e:PointerEvent)=>{if(root.current?.contains(e.target as Node)||(e.target as Element).closest('[role=tooltip]'))return;if(fixed){e.preventDefault();e.stopImmediatePropagation();}setOpen(false);setFixed(false);};document.addEventListener('pointerdown',outside,true);return()=>document.removeEventListener('pointerdown',outside,true);},[open,fixed]);
 useEffect(()=>{if(keyboardIndex>=0)requestAnimationFrame(()=>root.current?.querySelector<HTMLButtonElement>(`[data-row-index="${keyboardIndex}"] button`)?.focus());},[keyboardIndex]);
 return <div className="global-search" ref={root} onKeyDown={e=>{if(e.key==='Escape'){setOpen(false);setFixed(false);}if(['ArrowDown','ArrowUp'].includes(e.key)&&results.length){e.preventDefault();setOpen(true);setKeyboardIndex(index=>(index+(e.key==='ArrowDown'?1:-1)+results.length)%results.length);}}}>
 {fixed&&<div className="global-search-backdrop" onPointerDown={e=>{e.preventDefault();e.stopPropagation();}} onClick={e=>{e.preventDefault();e.stopPropagation();setFixed(false);setOpen(false);}}/>}<div className="wiki-search"><span aria-hidden="true">⌕</span><input aria-label="搜索规则资料" placeholder="搜索所有资料、中文名、英文名或来源" value={query} onFocus={()=>setOpen(true)} onClick={()=>setOpen(true)} onChange={e=>{change(e.target.value);setKeyboardIndex(-1);setOpen(true);}}/>{query&&<button aria-label="清空搜索" onClick={()=>change('')}>×</button>}<button aria-label="全局搜索结果" aria-expanded={open} onMouseEnter={()=>setOpen(true)} onClick={()=>setOpen(v=>!v)}>⌄</button></div>
 {open&&query.trim()&&<div className={`global-results ${fixed?'is-fixed':''}`} role="region" aria-label="全局搜索结果" onPointerDown={e=>{if(e.button===1||e.button===2){e.preventDefault();setFixed(true);}}} onContextMenu={e=>e.preventDefault()}><header><strong>全局结果</strong><span>{results.length} 项</span>{fixed&&<small>已固定</small>}<button aria-label="关闭搜索结果" onClick={()=>{setOpen(false);setFixed(false);}}>×</button></header><VirtualList items={results} rowHeight={44} resetKey={deferredQuery} scrollToIndex={keyboardIndex} itemKey={e=>e.id} empty={<p>没有匹配结果</p>} renderRow={entry=><Reference commitOnClick={false} className={`global-result ${explicitlyExcluded(c,entry)?'entry-disabled':''}`} reference={`entry:${entry.id}`} kind={entry.kind} entry={entry} onClick={()=>{setOpen(false);setFixed(false);inspect(entry);}}><strong>{entry.name}<small> {entry.english!==entry.name?entry.english:''}</small></strong><span>{KIND_LABELS[entry.kind]} · {format(entry.source)}</span></Reference>}/></div>}
 </div>;
}
