import { explicitlyExcluded } from './libraryData';
import { useEffect, useMemo, useRef, useState } from 'react';
import { KIND_LABELS, selectionAllowed, type Character, type Entry } from '../core/model';
import { Reference } from './Reference';
import { useSources } from './SourceName';
export function GlobalSearch({query,change,entries,c,inspect}:{query:string;change:(s:string)=>void;entries:Entry[];c:Character;inspect:(e:Entry)=>void}){
 const {format,registry}=useSources();const [open,setOpen]=useState(false),[fixed,setFixed]=useState(false),[limit,setLimit]=useState(80);const root=useRef<HTMLDivElement>(null);
 const results=useMemo(()=>{const q=query.trim().toLowerCase();return q?entries.filter(e=>`${e.name} ${e.english} ${e.source} ${registry[e.source]?.name||''}`.toLowerCase().includes(q)):[];},[query,entries,registry]);
 useEffect(()=>{if(!open)return;const outside=(e:PointerEvent)=>{if(root.current?.contains(e.target as Node)||(e.target as Element).closest('[role=tooltip]'))return;if(fixed){e.preventDefault();e.stopImmediatePropagation();}setOpen(false);setFixed(false);};document.addEventListener('pointerdown',outside,true);return()=>document.removeEventListener('pointerdown',outside,true);},[open,fixed]);
 return <div className="global-search" ref={root} onKeyDown={e=>{if(e.key==='Escape'){setOpen(false);setFixed(false);}if(['ArrowDown','ArrowUp'].includes(e.key)){e.preventDefault();setOpen(true);const items=[...(root.current?.querySelectorAll<HTMLButtonElement>('.global-result')||[])],index=items.indexOf(document.activeElement as HTMLButtonElement);items[(index+(e.key==='ArrowDown'?1:-1)+items.length)%items.length]?.focus();}}}>
 <>{fixed&&<div className="global-search-backdrop" onPointerDown={e=>{e.preventDefault();e.stopPropagation();}} onClick={e=>{e.preventDefault();e.stopPropagation();setFixed(false);setOpen(false);}}/>}</><div className="wiki-search"><span aria-hidden="true">⌕</span><input aria-label="搜索规则资料" placeholder="搜索所有资料、中文名、英文名或来源" value={query} onFocus={()=>setOpen(true)} onClick={()=>setOpen(true)} onChange={e=>{change(e.target.value);setLimit(80);setOpen(true);}}/>{query&&<button aria-label="清空搜索" onClick={()=>change('')}>×</button>}<button aria-label="全局搜索结果" aria-expanded={open} onMouseEnter={()=>setOpen(true)} onClick={()=>setOpen(v=>!v)}>⌄</button></div>
 {open&&query.trim()&&<div className={`global-results ${fixed?'is-fixed':''}`} role="region" aria-label="全局搜索结果" onPointerDown={e=>{if(e.button===1||e.button===2){e.preventDefault();setFixed(true);}}} onContextMenu={e=>e.preventDefault()}><header><strong>全局结果</strong><span>{results.length} 项</span>{fixed&&<small>已固定</small>}<button aria-label="关闭搜索结果" onClick={()=>{setOpen(false);setFixed(false);}}>×</button></header><div onScroll={e=>{const el=e.currentTarget;if(el.scrollHeight-el.scrollTop-el.clientHeight<160&&limit<results.length)setLimit(n=>Math.min(n+80,results.length));}}>{results.slice(0,limit).map(entry=><Reference key={entry.id} className={`global-result ${explicitlyExcluded(c,entry)?'entry-disabled':''}`} reference={`entry:${entry.id}`} kind={entry.kind} entry={entry} onClick={()=>{setOpen(false);setFixed(false);inspect(entry);}}><strong>{entry.name}<small> {entry.english!==entry.name?entry.english:''}</small></strong><span>{KIND_LABELS[entry.kind]} · {format(entry.source)}</span></Reference>)}{results.length>limit&&<button onClick={()=>setLimit(n=>n+80)}>显示更多（{results.length} 项）</button>}{!results.length&&<p>没有匹配结果</p>}</div></div>}
 </div>;
}
