import {useState} from 'react';
import {useGroupRoll,type GroupRollState} from '../platform/groupRoll';
import {useWorkbench,workbenchRequest} from '../platform/workbench';
import './GroupRollArea.css';
const abilities=[['str','力量'],['dex','敏捷'],['con','体质'],['int','智力'],['wis','感知'],['cha','魅力']];
export function GroupRollArea(){const group=useGroupRoll(),wb=useWorkbench();return wb.role==='GM'&&group?<GroupRollPanel key={group.id} group={group} online={wb.online}/>:null;}
function GroupRollPanel({group,online}:{group:GroupRollState;online:boolean}){
 const [kind,setKind]=useState(group.kind),[ability,setAbility]=useState(group.ability),[variant,setVariant]=useState(group.variant),[hidden,setHidden]=useState(false);
 const [dc,setDc]=useState(String(group.dc??10)),[value,setValue]=useState(String(group.value??group.adjustment?.value??0)),[mode,setMode]=useState<'damage'|'heal'|'set'>((group.mode??group.adjustment?.mode??'damage') as 'damage'|'heal'|'set'),[field,setField]=useState(group.field??group.adjustment?.field??'health'),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const act=async(action:string,extra:Record<string,unknown>={})=>{setBusy(true);setError('');try{await workbenchRequest('groupRoll',{key:undefined,itemId:undefined,id:group.id,action,...extra});}catch(error){setError(String(error));}finally{setBusy(false);}};
 const locked=group.phase!=='select',hasResults=group.targets.some(t=>t.result!==undefined),disabled=!online||busy||group.phase==='rolling',targetCount=group.selectedCount??group.targets.length,dicePerTarget=variant==='normal'?1:2,rollLimit=100/dicePerTarget,invalidTargets=targetCount>100||group.targets.length<2,oversized=invalidTargets||targetCount>rollLimit,uncertain=group.targets.some(t=>t.uncertain),parametersLocked=hasResults?group.targets.some(t=>t.applied):!!group.adjustment?.pending;
 const status=group.phase==='rolling'?'正在生成群体结果…':group.kind==='initiative'?(group.phase==='settled'?'先攻结果已写入':'先攻结果已生成，写入未完成'):group.phase==='settled'?'已结算；头顶结果保留至关闭':'结果已就绪，可以直接结算';
 return <section className="group-roll-area" aria-label="群体区域"><header><h3>群体区域 <small>{group.selectedCount??group.targets.length} 个单位</small></h3><button disabled={!online||busy} onClick={()=>void act('visibility',{visible:!group.visible})}>{group.visible?'隐藏数字':'显示数字'}</button><button disabled={!online||busy} onClick={()=>void act('close')}>关闭</button></header>
 {!locked?<div className="group-roll-controls"><label>投掷<select value={kind} onChange={e=>setKind(e.target.value as typeof kind)}><option value="save">群体豁免</option><option value="ability">属性检定</option><option value="initiative">群体先攻</option></select></label>{kind!=='initiative'&&<label>属性<select value={ability} onChange={e=>setAbility(e.target.value)}>{abilities.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>}<label>方式<select value={variant} onChange={e=>setVariant(e.target.value as typeof variant)}><option value="normal">普通</option><option value="adv">优势</option><option value="dis">劣势</option></select></label><label><input type="checkbox" checked={hidden} onChange={e=>setHidden(e.target.checked)}/>本次全暗骰</label><button disabled={disabled||oversized||!!group.adjustment?.pending} onClick={()=>void act('roll',{kind,ability,variant,hidden})}>同时投掷</button></div>:<p className="group-roll-status">{status}</p>}
 {!locked&&<p className="group-roll-status" role={targetCount>rollLimit?'alert':undefined}>{variant==='normal'?'普通':variant==='adv'?'优势':'劣势'}投掷最多 {rollLimit} 个单位（每目标 {dicePerTarget} 枚，共不超过 100 枚实体骰）。{targetCount>rollLimit?'当前选择超出数量，请减少目标或切换投掷方式；不会省略目标。':''}</p>}
 <ul className="group-roll-targets">{group.targets.map(target=><li key={target.itemId}><span>{target.name}{target.hidden&&<small>暗骰</small>}</span>{target.result!==undefined&&<><strong>{target.result}</strong>{group.kind!=='initiative'&&dc.trim()!==''&&Number.isFinite(Number(dc))&&<small>{target.result>=Number(dc)?'成功':'失败'}</small>}</>}{target.applied&&<small>已处理</small>}{target.error&&<span role="alert">{target.error}</span>}</li>)}</ul>
 {((!locked&&kind!=='initiative')||(hasResults&&group.kind!=='initiative'))&&<form className="group-roll-controls" aria-label={hasResults?'群体结算':'群体数值调整'} onSubmit={e=>{e.preventDefault();void act(hasResults?'settle':'adjust',{dc:dc.trim()===''?undefined:Number(dc),value:Number(value),mode,field});}}>
 {hasResults&&<label>DC<input aria-label="群体结算 DC" type="number" min="0" max="999" step="1" required={mode==='damage'} value={dc} disabled={busy||parametersLocked} onChange={e=>setDc(e.target.value)}/></label>}
 <label>字段<select aria-label="群体修改字段" value={field} disabled={busy||parametersLocked} onChange={e=>setField(e.target.value)}><option value="health">生命值 HP</option><option value="max health">生命值上限 Max HP</option><option value="armor class">护甲等级 AC</option></select></label>
 <label>效果<select aria-label="群体调整效果" value={mode} disabled={busy||parametersLocked} onChange={e=>setMode(e.target.value as typeof mode)}><option value="damage">{hasResults?'减少（成功减半）':'减少'}</option><option value="heal">增加</option><option value="set">设置</option></select></label>
 <label>数值<input aria-label="群体结算数值" type="number" min="0" max="99999" step="1" required value={value} disabled={busy||parametersLocked} onChange={e=>setValue(e.target.value)}/></label>
 <button type="submit" disabled={disabled||invalidTargets||hasResults&&group.phase==='settled'||uncertain}>{parametersLocked?'重试未完成目标':hasResults?'结算':'应用调整'}</button></form>}
 {!locked&&group.adjustment&&!group.adjustment.pending&&<p className="group-roll-status">已应用数值调整；可以继续调整或投掷。</p>}
 {(error||group.error)&&<p role="alert">{error||group.error}</p>}</section>;
}
