import {useState} from 'react';
import {NumberInput} from './NumberInput';
const labels:Record<string,string>={name:'名称',ENG_name:'英文名称',source:'来源',page:'页码',size:'体型',type:'类型',alignment:'阵营',ac:'护甲',hp:'生命值',average:'平均值',formula:'骰子公式',speed:'速度',walk:'步行',fly:'飞行',swim:'游泳',climb:'攀爬',burrow:'掘穴',canHover:'悬浮',str:'力量',dex:'敏捷',con:'体质',int:'智力',wis:'感知',cha:'魅力',save:'豁免',skill:'技能',senses:'感官',passive:'被动察觉',languages:'语言',cr:'挑战等级',pb:'熟练加值',initiative:'先攻',trait:'特质',action:'动作',bonus:'附赠动作',reaction:'反应',legendary:'传奇动作',mythic:'神话动作',spellcasting:'施法',entries:'正文',entry:'正文',resist:'抗性',immune:'免疫',vulnerable:'易伤',conditionImmune:'状态免疫',environment:'栖息地',treasure:'宝藏',headerEntries:'开头说明',footerEntries:'结尾说明',spells:'法术',daily:'每日',will:'随意',level:'等级',slots:'环位',note:'备注',legendaryActions:'传奇动作次数',otherSources:'其他来源'};
const label=(key:string)=>labels[key]||key;
export function MonsterEditor({value,save,busy}:{value:any;save:(value:any)=>Promise<void>;busy:boolean}){
 const [draft,setDraft]=useState(()=>structuredClone(value||{})),[error,setError]=useState('');
 return <form className="monster-editor" onSubmit={event=>{event.preventDefault();setError('');if(!draft.name?.trim()){setError('名称不能为空');return;}void save(draft).catch(e=>setError(String(e)));}}><fieldset disabled={busy}><ObjectFields value={draft} change={setDraft}/></fieldset>{error&&<p role="alert">{error}</p>}<div className="monster-editor-footer"><button type="submit" disabled={busy}>{busy?'保存中…':'保存资料'}</button><button type="button" disabled={busy} onClick={()=>setDraft(structuredClone(value))}>还原本次修改</button></div></form>;
}
function ValueField({value,change,name,depth=0}:{value:any;change:(value:any)=>void;name:string;depth?:number}){
 if(typeof value==='boolean')return <label><input type="checkbox" checked={value} onChange={e=>change(e.target.checked)}/>{name}</label>;
 if(typeof value==='number')return <NumberInput aria-label={name} value={value} onChange={e=>change(Number(e.target.value))}/>;
 if(value&&typeof value==='object')return <details className="monster-editor-group" open={depth<1}><summary>{name} <small>{Array.isArray(value)?value.length:Object.keys(value).length}</small></summary>{Array.isArray(value)?<div className="monster-editor-array">{value.map((row:any,index:number)=><div className="monster-editor-array-row" key={index}><ValueField value={row} name={`${name} ${index+1}`} depth={depth+1} change={next=>change(value.map((v:any,i:number)=>i===index?next:v))}/><button type="button" aria-label={`移除${name} ${index+1}`} onClick={()=>change(value.filter((_:any,i:number)=>i!==index))}>−</button></div>)}<div className="monster-editor-add"><button type="button" onClick={()=>change([...value,typeof value[0]==='object'?{name:'',entries:['']}:typeof value[0]==='number'?0:''])}>＋ 条目</button><button type="button" onClick={()=>change([...value,{name:'',entries:['']}])}>＋ 带标题正文</button></div></div>:<ObjectFields value={value} change={change} depth={depth+1} prefix={name}/>}</details>;
 return String(value??'').length>70||/正文|说明/.test(name)?<textarea aria-label={name} rows={3} value={String(value??'')} onChange={e=>change(e.target.value)}/>:<input aria-label={name} value={String(value??'')} onChange={e=>change(e.target.value)}/>;
}
function ObjectFields({value,change,depth=0,prefix=''}:{value:Record<string,any>;change:(value:any)=>void;depth?:number;prefix?:string}){
 const [key,setKey]=useState(''),[type,setType]=useState('text');
 return <div className="monster-editor-fields">{Object.entries(value).map(([key,v])=><div key={key} className={`monster-editor-field ${v&&typeof v==='object'?'is-group':''}`}><label>{label(key)}</label><ValueField name={`${prefix} ${label(key)}`.trim()} value={v} depth={depth} change={next=>change({...value,[key]:next})}/><button type="button" className="field-remove" aria-label={`删除字段 ${label(key)}`} onClick={()=>{const next={...value};delete next[key];change(next);}}>×</button></div>)}<details className="monster-editor-add-field"><summary>添加字段</summary><div><input aria-label="字段名" value={key} placeholder="字段名" onChange={e=>setKey(e.target.value)}/><select aria-label="字段类型" value={type} onChange={e=>setType(e.target.value)}><option value="text">文字</option><option value="number">数值</option><option value="bool">开关</option><option value="list">列表</option><option value="group">分组</option></select><button type="button" onClick={()=>{if(!key.trim()||['__proto__','constructor','prototype'].includes(key)||Object.hasOwn(value,key))return;change({...value,[key]:({number:0,bool:false,list:[],group:{}} as Record<string,any>)[type]??''});setKey('');}}>添加</button></div></details></div>;
}
