import {useState} from 'react';
import {NumberInput} from './NumberInput';
import {ABILITIES,ABILITY_LABELS,SIZE_LABELS,type Raw} from '../core/model';
import {monsterNumber,setMonsterNumber,parseMonsterDraft,validateMonsterDraft} from '../core/monsterEditing';
import './monsterEditor.css';
const labels:Record<string,string>={name:'名称',ENG_name:'英文名称',source:'来源',page:'页码',size:'体型',type:'类型',alignment:'阵营',ac:'护甲',hp:'生命值',average:'平均值',formula:'骰子公式',speed:'速度',walk:'步行',fly:'飞行',swim:'游泳',climb:'攀爬',burrow:'掘穴',canHover:'悬浮',str:'力量',dex:'敏捷',con:'体质',int:'智力',wis:'感知',cha:'魅力',save:'豁免',skill:'技能',senses:'感官',passive:'被动察觉',languages:'语言',cr:'挑战等级',pb:'熟练加值',initiative:'先攻',trait:'特质',action:'动作',bonus:'附赠动作',reaction:'反应',legendary:'传奇动作',mythic:'神话动作',spellcasting:'施法',entries:'正文',entry:'正文',resist:'抗性',immune:'免疫',vulnerable:'易伤',conditionImmune:'状态免疫',environment:'栖息地',treasure:'宝藏',headerEntries:'开头说明',footerEntries:'结尾说明',spells:'法术',daily:'每日',will:'随意',level:'等级',slots:'环位',note:'备注',legendaryActions:'传奇动作次数',otherSources:'其他来源'};
const label=(key:string)=>labels[key]||key;
export function MonsterEditor({value,save,busy}:{value:any;save:(value:any)=>Promise<void>;busy:boolean}){
 const [draft,setDraft]=useState<Raw>(()=>structuredClone(value||{})),[error,setError]=useState(''),[page,setPage]=useState('基础资料'),[json,setJson]=useState<string>();
 const put=(key:string,next:unknown)=>setDraft(current=>({...current,[key]:next}));
 const text=(key:string,title:string,read?:string,write?:(next:string)=>void)=><label className="monster-form-field" key={key}><span>{title}</span><input aria-label={`怪物${title}`} value={read??String(draft[key]??'')} onChange={event=>write?write(event.target.value):put(key,event.target.value)}/></label>;
 const number=(key:string,title:string)=><label className="monster-form-field" key={key}><span>{title}</span><NumberInput aria-label={`怪物${title}`} min={0} value={monsterNumber(draft,key)??''} onChange={event=>setDraft(current=>setMonsterNumber(current,key,Number(event.target.value)))}/></label>;
 const list=(key:string,title:string)=><label className="monster-form-field monster-form-wide" key={key}><span>{title}（每行一项）</span>{!draft[key]||typeof draft[key]==='string'||Array.isArray(draft[key])&&draft[key].every((row:any)=>typeof row==='string')?<textarea aria-label={`怪物${title}`} rows={2} value={Array.isArray(draft[key])?draft[key].join('\n'):String(draft[key]||'')} onChange={event=>put(key,event.target.value.split('\n').filter(Boolean))}/>:<ValueField name={title} value={draft[key]} change={next=>put(key,next)}/>}</label>;
 return <form className="monster-editor monster-editor-friendly" onSubmit={event=>{event.preventDefault();setError('');try{const next=json!==undefined?parseMonsterDraft(json):validateMonsterDraft(draft);void save(next).catch(e=>setError(String(e)));}catch(e){setError(String(e instanceof Error?e.message:e));}}}>
 <nav aria-label="怪物编辑分类">{['基础资料','属性与防御','特质与动作','施法','高级 JSON'].map(tab=><button type="button" key={tab} aria-pressed={page===tab} onClick={()=>{if(json!==undefined&&page==='高级 JSON'&&tab!=='高级 JSON'){try{setDraft(parseMonsterDraft(json));setJson(undefined);setError('');}catch(e){setError(String(e instanceof Error?e.message:e));return;}}if(tab==='高级 JSON'&&json===undefined)setJson(JSON.stringify(draft,null,2));setPage(tab);}}>{tab}</button>)}</nav>
 <fieldset disabled={busy}>
 {page==='基础资料'&&<div className="monster-form-grid">
  {text('name','名称')}{text('ENG_name','英文名称')}
  <label className="monster-form-field"><span>体型</span><select aria-label="怪物体型" value={(Array.isArray(draft.size)?draft.size[0]:draft.size)||''} onChange={event=>put('size',[event.target.value,...(Array.isArray(draft.size)?draft.size.slice(1):[])])}><option value="">未填写</option>{Object.entries(SIZE_LABELS).map(([key,name])=><option key={key} value={key}>{name}</option>)}</select></label>
  {text('type','类型',typeof draft.type==='object'?draft.type?.type||'':draft.type||'',next=>put('type',draft.type&&typeof draft.type==='object'?{...draft.type,type:next}:next))}
  {text('cr','挑战等级',String(typeof draft.cr==='object'?draft.cr?.cr||'':draft.cr??''),next=>put('cr',draft.cr&&typeof draft.cr==='object'?{...draft.cr,cr:next}:next))}
  {number('ac','护甲等级')}{number('hp','生命值上限')}{text('hp.formula','生命骰公式',draft.hp?.formula||'',next=>put('hp',{...(typeof draft.hp==='object'?draft.hp:{}),formula:next}))}
  {['walk','fly','swim','climb','burrow'].map(key=>number(`speed.${key}`,`${labels[key]}速度（尺）`))}
  {text('source','来源')}{number('page','页码')}{list('languages','语言')}{list('senses','感官')}
  <details className="monster-form-wide"><summary>阵营与复杂数值</summary><ObjectFields value={Object.fromEntries(['alignment','ac','hp','speed'].filter(key=>key in draft).map(key=>[key,draft[key]]))} change={next=>setDraft(current=>{const result={...current};for(const key of ['alignment','ac','hp','speed'])delete result[key];return {...result,...next};})}/></details>
 </div>}
 {page==='属性与防御'&&<>
  <div className="monster-ability-editor">{ABILITIES.map(a=><div key={a}>{number(a,ABILITY_LABELS[a])}<label>豁免加值<input aria-label={`怪物${ABILITY_LABELS[a]}豁免`} value={draft.save?.[a]??''} onChange={event=>put('save',{...draft.save,[a]:event.target.value})}/></label></div>)}</div>
  <div className="monster-form-grid">{number('passive','被动察觉')}{number('pb','熟练加值')}{list('resist','伤害抗性')}{list('immune','伤害免疫')}{list('vulnerable','伤害易伤')}{list('conditionImmune','状态免疫')}</div>
  <details open><summary>技能与先攻</summary><ObjectFields value={{skill:draft.skill||{},...(draft.initiative===undefined?{}:{initiative:draft.initiative})}} change={next=>setDraft(current=>{const result={...current};delete result.skill;delete result.initiative;return {...result,...next};})}/></details>
 </>}
 {page==='特质与动作'&&<>{['trait','action','bonus','reaction','legendary','mythic'].map(key=><ActionSection key={key} title={labels[key]} rows={draft[key]||[]} change={rows=>put(key,rows)}/>)}{number('legendaryActions','传奇动作次数')}</>}
 {page==='施法'&&<><ActionSection title="施法" rows={draft.spellcasting||[]} change={rows=>put('spellcasting',rows)} spellcasting/><p className="monster-editor-note">法术引用可写为 {'{@spell 法术名|来源}'}；骰子可写为 {'{@dice 1d6+2}'}。</p></>}
 {page==='高级 JSON'&&<><textarea className="monster-json-input" aria-label="怪物完整 JSON" value={json??''} onChange={event=>setJson(event.target.value)} spellCheck={false}/><p className="monster-editor-note">切回表单或保存时校验。未在常用表单展示的字段会完整保留。</p></>}
 </fieldset>{error&&<p role="alert">{error}</p>}<div className="monster-editor-footer"><button type="submit" disabled={busy}>{busy?'保存中…':'保存资料'}</button><button type="button" disabled={busy} onClick={()=>{setDraft(structuredClone(value||{}));setJson(undefined);setPage('基础资料');setError('');}}>还原本次修改</button></div></form>;
}
function ActionSection({title,rows,change,spellcasting=false}:{title:string;rows:any[];change:(rows:any[])=>void;spellcasting?:boolean}){
 return <section className="monster-action-editor"><h4>{title}<span>{rows.length} 项</span></h4>{rows.map((row,index)=>typeof row==='object'&&row!==null?<article key={index}><header><input aria-label={`${title} ${index+1} 名称`} placeholder={`${title}名称`} value={row.name||''} onChange={event=>change(rows.map((value,i)=>i===index?{...value,name:event.target.value}:value))}/><button type="button" disabled={index===0} aria-label={`上移${title} ${index+1}`} onClick={()=>{const next=[...rows];[next[index-1],next[index]]=[next[index],next[index-1]];change(next);}}>↑</button><button type="button" disabled={index===rows.length-1} aria-label={`下移${title} ${index+1}`} onClick={()=>{const next=[...rows];[next[index+1],next[index]]=[next[index],next[index+1]];change(next);}}>↓</button><button type="button" aria-label={`移除${title} ${index+1}`} onClick={()=>change(rows.filter((_,i)=>i!==index))}>×</button></header>
 <ValueField name={`${title} ${index+1} 正文`} value={row[spellcasting?'headerEntries':'entries']||[]} change={next=>change(rows.map((value,i)=>i===index?{...value,[spellcasting?'headerEntries':'entries']:next}:value))}/>
 <details><summary>{spellcasting?'法术频率与法术列表':'其他字段'}</summary><ObjectFields value={Object.fromEntries(Object.entries(row).filter(([key])=>key!=='name'&&key!==(spellcasting?'headerEntries':'entries')))} change={next=>change(rows.map((value,i)=>i===index?{name:value.name,[spellcasting?'headerEntries':'entries']:value[spellcasting?'headerEntries':'entries'],...next}:value))}/>{spellcasting&&<button type="button" onClick={()=>change(rows.map((value,i)=>i===index?{...value,will:value.will||[],daily:value.daily||{'1e':[]},spells:value.spells||{}}:value))}>添加随意 / 每日 / 环阶列表</button>}</details>
 </article>:<div key={index}><ValueField name={`${title} ${index+1}`} value={row} change={next=>change(rows.map((value,i)=>i===index?next:value))}/><button type="button" onClick={()=>change(rows.filter((_,i)=>i!==index))}>移除</button></div>)}<button type="button" onClick={()=>change([...rows,{name:'',[spellcasting?'headerEntries':'entries']:['']}])}>＋ 添加{title}</button></section>;
}
function ValueField({value,change,name,depth=0}:{value:any;change:(value:any)=>void;name:string;depth?:number}){
 if(typeof value==='boolean')return <label><input type="checkbox" checked={value} onChange={e=>change(e.target.checked)}/>{name}</label>;
 if(typeof value==='number')return <NumberInput aria-label={name} value={value} onChange={e=>change(Number(e.target.value))}/>;
 if(value&&typeof value==='object')return <details className="monster-editor-group" open={depth<1}><summary>{name} <small>{Array.isArray(value)?value.length:Object.keys(value).length}</small></summary>{Array.isArray(value)?<div className="monster-editor-array">{value.map((row:any,index:number)=><div className="monster-editor-array-row" key={index}><ValueField value={row} name={`${name} ${index+1}`} depth={depth+1} change={next=>change(value.map((v:any,i:number)=>i===index?next:v))}/><button type="button" aria-label={`移除${name} ${index+1}`} onClick={()=>change(value.filter((_:any,i:number)=>i!==index))}>−</button></div>)}<div className="monster-editor-add"><button type="button" onClick={()=>change([...value,typeof value[0]==='object'?{name:'',entries:['']}:typeof value[0]==='number'?0:''])}>＋ 条目</button><button type="button" onClick={()=>change([...value,{name:'',entries:['']}])}>＋ 带标题正文</button></div></div>:<ObjectFields value={value} change={change} depth={depth+1} prefix={name}/>}</details>;
 return String(value??'').length>70||/正文|说明/.test(name)?<textarea aria-label={name} rows={3} value={String(value??'')} onChange={e=>change(e.target.value)}/>:<input aria-label={name} value={String(value??'')} onChange={e=>change(e.target.value)}/>;
}
function ObjectFields({value,change,depth=0,prefix=''}:{value:Record<string,any>;change:(value:any)=>void;depth?:number;prefix?:string}){
 const [key,setKey]=useState(''),[type,setType]=useState('text');
 return <div className="monster-editor-fields">{Object.entries(value).map(([key,v])=><div key={key} className={`monster-editor-field ${v&&typeof v==='object'?'is-group':''}`}><label>{label(key)}</label><ValueField name={`${prefix} ${label(key)}`.trim()} value={v} depth={depth} change={next=>change({...value,[key]:next})}/><button type="button" className="field-remove" aria-label={`删除字段 ${label(key)}`} onClick={()=>{const next={...value};delete next[key];change(next);}}>×</button></div>)}<details className="monster-editor-add-field"><summary>添加字段</summary><div><input aria-label="字段名" value={key} placeholder="字段名" onChange={e=>setKey(e.target.value)}/><select aria-label="字段类型" value={type} onChange={e=>setType(e.target.value)}><option value="text">文字</option><option value="number">数值</option><option value="bool">开关</option><option value="list">列表</option><option value="group">分组</option></select><button type="button" onClick={()=>{if(!key.trim()||['__proto__','constructor','prototype'].includes(key)||Object.hasOwn(value,key))return;change({...value,[key]:({number:0,bool:false,list:[],group:{}} as Record<string,any>)[type]??''});setKey('');}}>添加</button></div></details></div>;
}
