import type {CardComponent} from '../core/palette';
const ui:Record<string,string>={background:'.app-shell,.cloud-library',surface:'.sheet-pane,.cloud-content,.cloud-sidebar,.dialog',heading:'.app-header,.pane-toolbar,.cloud-header,.workbench-bar',band:'.cloud-gallery-title,.cloud-frame>h2',bandInk:'.cloud-gallery-title h2,.cloud-gallery-title>.cloud-stack-id,.cloud-frame>h2',ink:'.brand,.pane-toolbar,.cloud-sidebar-warning',muted:'.save-status,.cloud-sidebar-status>p',line:'.sheet-pane,.wiki-pane,.cloud-frame',accent:'.app-header a,.cloud-source-footer a,.inline-reference',button:'.app-header button,.pane-toolbar button,.cloud-stack-controls button,.cloud-stack-id button',buttonInk:'.app-header button,.pane-toolbar button,.cloud-stack-controls button,.cloud-stack-id button',selected:'.character-tabs [aria-selected=true],.app-header [aria-pressed=true],.cloud-sidebar [aria-current=page]',selectedInk:'.character-tabs [aria-selected=true],.app-header [aria-pressed=true],.cloud-sidebar [aria-current=page]'};
const wiki:Record<string,string>={background:'.wiki-pane,.entry-detail',ink:'.entry-detail .rules-prose,.entry-facts dd',muted:'.wiki-pane small,.wiki-source,.entry-facts dt',title:'.wiki-pane h1,.wiki-pane h2,.wiki-pane h3,.wiki-pane h4,.document-nav>strong',link:'.wiki-pane a,.wiki-pane .inline-reference,.wiki-pane .text-link',area:'.wiki-header,.wiki-filters,.category-tabs,.catalog-columns,.document-nav,.entry-facts',line:'.catalog-columns,.document-nav,.entry-facts,.catalog-row',entry:'.catalog-row,.catalog-race-group',entryInk:'.catalog-row .entry-name,.catalog-row .catalog-value',selected:'.catalog-row.active,.category-tabs button.active,.document-nav button.active',selectedInk:'.catalog-row.active .entry-name,.category-tabs button.active,.document-nav button.active',feature:'.wiki-pane .entry-inset,.wiki-pane .entry-quote,.wiki-pane .resolved-feature',featureInk:'.wiki-pane .entry-inset,.wiki-pane .entry-quote,.wiki-pane .resolved-feature',tableHeading:'.wiki-pane .rules-prose th',tableHeadingInk:'.wiki-pane .rules-prose th',tableCell:'.wiki-pane .rules-prose td',tableAlternate:'.wiki-pane .rules-prose tbody tr:nth-child(even)>td',tableInk:'.wiki-pane .rules-prose th,.wiki-pane .rules-prose td',tableLine:'.wiki-pane .rules-prose table'};
let layer:HTMLDivElement|undefined;
export function clearPaletteHighlight(){layer?.remove();layer=undefined;}
export function highlightPalette(group:'ui'|'wiki'|'card',key:string,component:CardComponent,characterId?:string){
 clearPaletteHighlight();
 let nodes:Element[]=[];
 if(group==='card'){
  const papers=[...document.querySelectorAll<HTMLElement>('.paper[data-character-id]')].filter(p=>p.dataset.characterId===characterId);
  for(const paper of papers){const page={features:1,background:2,spells:3,inventory:4}[component as 'features'|'background'|'spells'|'inventory'];const regions=component==='all'?[paper]:[...paper.querySelectorAll(`[data-palette-component="${component}"]`),...(page!==undefined&&paper.classList.contains(`page-${page}`)?paper.querySelectorAll('.sheet-cell'):[])];
   for(const region of regions){const selector=key==='heading'||key==='headingInk'?'.cell-heading':key==='surface'?'.cell-content,.cell-surface':key==='badge'?'.class-watermark,.cell-art,svg':undefined;nodes.push(...(selector?[...region.querySelectorAll(selector)]:[region]));}
  }
 }else if((group==='ui'?ui:wiki)[key])nodes=[...document.querySelectorAll((group==='ui'?ui:wiki)[key])];
 layer=document.createElement('div');layer.className='palette-highlight-layer';layer.ariaHidden='true';
 for(const node of [...new Set(nodes)].slice(0,80)){if(node.closest('.palette-drawer,.palette-picker,.cloud-gallery-paper[aria-hidden=true]'))continue;const rect=node.getBoundingClientRect();if(rect.width<1||rect.height<1||rect.bottom<0||rect.top>innerHeight||rect.right<0||rect.left>innerWidth)continue;const mark=document.createElement('div');Object.assign(mark.style,{left:rect.left+'px',top:rect.top+'px',width:rect.width+'px',height:rect.height+'px'});layer.append(mark);}
 (document.querySelector('dialog[open]')||document.body).append(layer);
}
