import {standalone} from '../platform/buildMode';
import {quickbarEntries,removePin} from '../core/quickbar';
import './refinement183.css';
import {Reference} from './Reference';
import {SpellSlotResources,isSpellSlot} from './SpellSlotResources';
import {ResourceRow} from './ResourceRow';
import {useWorkbench} from '../platform/workbench';
import {pointerDrag} from './pointerDrag';
import {useContext,useRef,useState,useEffect,type PointerEvent} from 'react';
import {type Character,type Derived,type Entry,signed} from '../core/model';
import {spellValues} from '../core/characterDetails';
import {isHitDieResource,setResource} from '../core/resources';
import {inWorkbench,composeRoll} from '../platform/workbench';
import {SheetEditContext} from './SheetEdit';
import {entryLabel} from '../core/entryLabel';
export function Quickbar({c,d,edit,inspect,manage,manageQuickbar}:{c:Character;d:Derived;edit:(f:(c:Character)=>void)=>void;inspect:(e:Entry)=>void;manage:()=>void;manageQuickbar:()=>void}){
 const wb=useWorkbench();const editing=useContext(SheetEditContext),spell=spellValues(c,d),old=c.externalSnapshot?.combat?.weapons||[];
 const root=useRef<HTMLDivElement>(null),cancel=useRef<(()=>void)|undefined>(undefined),[over,setOver]=useState('');useEffect(()=>()=>cancel.current?.(),[]);
 const layout=c.quickbarLayout||{order:[],hidden:[]},rank=(id:string)=>layout.order.includes(id)?layout.order.indexOf(id):9999;
 const weapons=[...(c.quickbarActions||[]).map(w=>({...w,attack_bonus:w.attack,key:`custom:${w.id}`})),...old,...c.selections.filter(s=>s.entry.kind==='item'&&s.entry.raw.dmg1&&!old.some((w:any)=>w.name===s.entry.name)).map(s=>({name:s.entry.name,damage:s.entry.raw.dmg1,attack_bonus:s.entry.raw.attackBonus,entry:s.entry}))];
 const visibleWeapons=weapons.map((w:any,i:number)=>({...w,key:w.key||(w.entry?`selection:${w.entry.id}`:`weapon:${i}:${w.name}`)})).filter(w=>!layout.hidden.includes(w.key)).sort((a,b)=>rank(a.key)-rank(b.key));
 const resources=Object.entries(c.runtime.resources).filter(([id])=>!isHitDieResource(id)&&!layout.hidden.includes(`resource:${id}`)).sort((a,b)=>rank(`resource:${a[0]}`)-rank(`resource:${b[0]}`)||(a[1].order||0)-(b[1].order||0));
 function drag(e:PointerEvent,id:string,name:string,side:string){
  if(!editing)return;const ids=side==='resources'?resources.map(([id])=>`resource:${id}`):side==='pins'?quickbarEntries(c).map(row=>`pin:${row.id}`):visibleWeapons.map(w=>w.key);
  const target=(hit:Element|null)=>{const row=hit?.closest<HTMLElement>('[data-quick-id]');return row&&root.current?.contains(row)&&row.dataset.quickSide===side?row.dataset.quickId:undefined;};
  cancel.current=pointerDrag(e,{title:name,cancel:()=>setOver(''),outside:hit=>!hit||!root.current?.contains(hit),move:(_,hit)=>setOver(target(hit)||''),finish:(_,hit)=>{setOver('');if(hit&&root.current?.contains(hit)){const to=target(hit);if(!to||to===id)return {resolve:()=>root.current?.querySelector<HTMLElement>(`[data-quick-id="${CSS.escape(id)}"]`)||null};const order=ids.filter(key=>key!==id);order.splice(ids.indexOf(to),0,id);edit(draft=>{if(side==='pins'){draft.quickbarCopies=order.map(id=>quickbarEntries(draft).find(row=>row.id===id.slice(4))!).filter(Boolean);draft.quickbar=[];}else{const l=draft.quickbarLayout||={order:[],hidden:[]};l.order=[...l.order.filter(key=>!ids.includes(key)),...order];}});return {resolve:()=>root.current?.querySelector<HTMLElement>(`[data-quick-id="${CSS.escape(id)}"]`)||null};}else {edit(draft=>{if(id.startsWith('pin:'))removePin(draft,id.slice(4));else{const l=draft.quickbarLayout||={order:[],hidden:[]};l.hidden=[...new Set([...l.hidden,id])];}});return {removed:true};}}});
 }
 const roll=(expression:string,label:string)=>{if((inWorkbench||standalone)&&!editing)composeRoll(expression,label);};
 const resourceRow=(id:string,r:Character["runtime"]["resources"][string])=><div className={`quick-resource ${over===`resource:${id}`?'quick-drag-over':''}`} key={id} data-quick-id={`resource:${id}`} data-quick-side="resources" onPointerDown={e=>{if((e.target as Element).closest('.resource-title>strong'))drag(e,`resource:${id}`,r.name||id,'resources');}}><ResourceRow resource={r} enabled={!inWorkbench||!!wb.target?.write} gm={!inWorkbench||wb.role==='GM'} change={async n=>edit(c=>setResource(c,id,n))} configure={()=>window.dispatchEvent(new CustomEvent('edit-character-resource',{detail:id}))} lock={()=>edit(c=>{c.runtime.resources[id].locked=!r.locked;})}/></div>;
 return <div className="quickbar-split" ref={root}><div className="quickbar-attacks">{editing&&<button className="quickbar-manage-strip" onClick={manageQuickbar}>管理快捷栏</button>}<div className="quick-weapon"><span>法术攻击</span><button disabled={!inWorkbench&&!standalone} className="rollable-stat" onClick={()=>roll(`1d20${signed(spell.attack)}`,'法术攻击')}>{signed(spell.attack)}</button><strong>DC {spell.dc}</strong></div>{visibleWeapons.map((w:any)=>{const bonus=String(w.attack_bonus??'').match(/[+-]?\s*\d+/)?.[0].replace(/\s/g,'');const damage=[w.damage,w.extra_damage].filter(Boolean).join('+').replace(/\s/g,'');return <div className={`quick-weapon ${over===w.key?'quick-drag-over':''}`} key={w.key} data-quick-id={w.key} data-quick-side="attacks"><span className="quick-drag-handle" data-editing={editing} onPointerDown={e=>drag(e,w.key,w.name,'attacks')}>{w.entry?entryLabel(w.entry):w.name}</span><button className="rollable-stat" disabled={(!inWorkbench&&!standalone)||bonus===undefined} onClick={()=>roll(`1d20${signed(Number(bonus))}`,`${w.name} 命中`)}>{bonus===undefined?'—':signed(Number(bonus))}</button><button className="rollable-stat" disabled={(!inWorkbench&&!standalone)||!damage} onClick={()=>roll(damage,`${w.name} 伤害`)}>{damage||'—'} {w.damage_type||''}</button></div>;})}{quickbarEntries(c).map(s=><Reference className={`quick-pin quick-drag-handle ${over===`pin:${s.id}`?'quick-drag-over':''}`} reference={`entry:${s.entry.id}`} entry={s.entry} data-editing={editing} data-quick-id={`pin:${s.id}`} data-entry-id={s.entry.id} data-quick-side="pins" onPointerDown={e=>drag(e,`pin:${s.id}`,entryLabel(s.entry),'pins')} key={s.id} onClick={()=>inspect(s.entry)}>{entryLabel(s.entry)}</Reference>)}</div><div className="quickbar-resources">{editing&&<button className="quickbar-manage-strip" onClick={manage}>管理资源</button>}<SpellSlotResources rows={resources.map(([id,r])=>({...r,id}))} render={r=>resourceRow(r.id!,r)}/>{resources.filter(([id])=>!isSpellSlot(id)).map(([id,r])=>resourceRow(id,r))}</div></div>;
}
