import {resourceEditorDraft} from './resourceEditorDraft';
import {WIDGET_STYLES,widgetStyleNames,normalizeWidget,chooseDefaultWidgetStyle,supportsWidgetStyle,type WidgetStyle,type ResourceWidgetLayout} from '../core/resourceWidgets';
import {ResourceModuleFace} from './ResourceModuleFace';
import './resourceWidgets.css';
import {useState,useRef} from 'react';
import {sameValue} from '../core/merge';
import {useResourceDraftGuard,confirmResourceDraftDiscard} from './resourceDraftGuard';
import {createPortal} from 'react-dom';
import {savePreset,type ResourceValue} from './resourcePresets';
export function ResourceEditor({value,save,remove,close,disabled=false,gm=true,presetScope='player',inline=false,presentation,previewLayout}:{value?:ResourceValue;save:(value:ResourceValue,style?:WidgetStyle,previous?:ResourceValue)=>Promise<unknown>;presentation?:WidgetStyle;previewLayout?:ResourceWidgetLayout;remove?:()=>Promise<unknown>;close:()=>void;disabled?:boolean;gm?:boolean;presetScope?:string;inline?:boolean}){
 const [style,setStyle]=useState<WidgetStyle>(presentation||'bar');
 const [name,setName]=useState(value?.name||''),[max,setMax]=useState(String(value?.max??1)),[current,setCurrent]=useState(String(value?.current??1)),[type]=useState(value?.type||'count'),[unlimited,setUnlimited]=useState(!!value?.unlimited),[locked,setLocked]=useState(!!value?.locked),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const baseValue=useRef(value);
 const data=()=>resourceEditorDraft(baseValue.current,{name,max,current,unlimited,locked,type});
 const formState={name,max,current,unlimited,locked,style},pristine=useRef(formState),guard=useResourceDraftGuard('resource-form',!sameValue(pristine.current,formState),busy);
 function dismiss(){if(!confirmResourceDraftDiscard('resource-form'))return;const saved=pristine.current;setName(saved.name);setMax(saved.max);setCurrent(saved.current);setUnlimited(saved.unlimited);setLocked(saved.locked);setStyle(saved.style);guard.current.dirty=false;close();}
 function valid(){const r=data();if(!r.name||!Number.isInteger(r.max)||!Number.isInteger(r.current)||r.max<0||r.max>99999||r.current<0||r.current>999999999||!r.unlimited&&r.current>r.max)throw Error('检查名称、当前值与上限');return r;}
 async function submit(){setError('');try{const next=valid();setBusy(true);await save(next,presentation===undefined?undefined:style,baseValue.current);baseValue.current=next;pristine.current=formState;guard.current.dirty=false;guard.current.busy=false;close();}catch(e){setError(String(e));}finally{setBusy(false);}}
 const preview={...data(),name:name.trim()||'新资源',current:Number.isFinite(Number(current))?Math.max(0,Number(current)):0,max:Number.isFinite(Number(max))?Math.max(0,Number(max)):0},layout=normalizeWidget({...previewLayout,style:presentation?style:previewLayout?.style||chooseDefaultWidgetStyle(preview)});
 const content=<div className={inline?"resource-editor-inline":"resource-editor-shade"} onPointerDown={e=>{if(e.target===e.currentTarget){e.preventDefault();dismiss();}}}><form role={inline?undefined:"dialog"} aria-modal={inline?undefined:true} aria-label="资源设置" className="resource-editor-form" onSubmit={e=>{e.preventDefault();void submit();}}>{!inline&&<button className="resource-editor-close" type="button" aria-label="关闭资源设置" onClick={dismiss}>×</button>}<fieldset disabled={disabled||busy||!!value?.locked&&!gm}><label className="resource-name-edit">名称<input required aria-label="资源名称" readOnly={!!value?.featureGrant} value={name} onChange={e=>setName(e.target.value)}/><button type="button" className="resource-lock" disabled={!gm} aria-label={locked?'解锁资源':'锁定资源'} aria-pressed={locked} onClick={()=>setLocked(!locked)}><LockIcon locked={locked}/></button></label>{presentation!==undefined&&<fieldset className="resource-style-picker"><legend>资源模块样式</legend><div>{WIDGET_STYLES.filter(id=>supportsWidgetStyle(id,[['preview',preview]],false)).map(id=><button type="button" key={id} aria-pressed={style===id} onClick={()=>setStyle(id)}><span aria-hidden="true">{({ring:'◉',square:'▣'} as Record<string,string>)[id]||'✦'}</span> {widgetStyleNames[id]}</button>)}</div></fieldset>}<div className="resource-edit-numbers"><label>当前值<input aria-label="资源剩余" type="number" min="0" value={current} onChange={e=>setCurrent(e.target.value)}/></label><label><input type="checkbox" aria-label="资源有上限" checked={!unlimited} disabled={value?.automatic||!!value?.featureGrant} onChange={e=>setUnlimited(!e.target.checked)}/>上限<input aria-label="资源上限" disabled={value?.automatic||unlimited} type="number" min="0" max="99999" value={max} onChange={e=>{const next=e.target.value;if(current===max)setCurrent(next);setMax(next);}}/></label></div><div className="resource-editor-preview" aria-label="资源设置预览"><ResourceModuleFace module={{id:'preview',name:preview.name!,slots:false,rows:[['preview',preview]]}} style={layout.style} layout={layout}/></div><div className="resource-editor-actions"><button type="submit">保存</button><button type="button" onClick={dismiss}>取消</button><button type="button" onClick={()=>{try{savePreset(valid(),presetScope);setError('');}catch(e){setError(String(e));}}}>保存为预设</button>{remove&&!value?.automatic&&!value?.featureGrant&&<button type="button" onClick={()=>{setBusy(true);void remove().then(()=>{guard.current.dirty=false;guard.current.busy=false;close();}).catch(e=>setError(String(e))).finally(()=>setBusy(false));}}>移除</button>}</div></fieldset>{error&&<p role="alert">{error}</p>}</form></div>;return inline?content:createPortal(content,document.querySelector("dialog[open]")||document.body);
}
export function LockIcon({locked}:{locked:boolean}){return <svg data-locked={locked} width="13" height="15" viewBox="0 0 16 18" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true"><rect x="2" y="7" width="12" height="9" rx="1"/><path d={locked?'M5 7V4a3 3 0 016 0V7':'M5 7V4a3 3 0 016 0'}/>{locked&&<path d="M8 10v3"/>}</svg>;}
