import {useState} from 'react';
import {createPortal} from 'react-dom';
import {savePreset,type ResourceValue} from './resourcePresets';
export function ResourceEditor({value,save,remove,close,disabled=false,gm=true,presetScope='player',inline=false}:{value?:ResourceValue;save:(value:ResourceValue)=>Promise<unknown>;remove?:()=>Promise<unknown>;close:()=>void;disabled?:boolean;gm?:boolean;presetScope?:string;inline?:boolean}){
 const [name,setName]=useState(value?.name||''),[max,setMax]=useState(String(value?.max??1)),[current,setCurrent]=useState(String(value?.current??1)),[type,setType]=useState(value?.type||'count'),[unlimited,setUnlimited]=useState(!!value?.unlimited),[locked,setLocked]=useState(!!value?.locked),[busy,setBusy]=useState(false),[error,setError]=useState('');
 const data=():ResourceValue=>({...value,name:name.trim(),max:Number(max),current:Number(current),type,unlimited:type==='number'&&unlimited,locked,icon:value?.icon||'gem'});
 function valid(){const r=data();if(!r.name||!Number.isInteger(r.max)||!Number.isInteger(r.current)||r.max<0||r.max>99999||r.current<0||r.current>999999999||!r.unlimited&&r.current>r.max)throw Error('检查名称、剩余次数与上限');return r;}
 async function submit(){setError('');try{const next=valid();setBusy(true);await save(next);close();}catch(e){setError(String(e));}finally{setBusy(false);}}
 const content=<div className={inline?"resource-editor-inline":"resource-editor-shade"} onPointerDown={e=>{if(e.target===e.currentTarget){e.preventDefault();close();}}}><form role={inline?undefined:"dialog"} aria-modal={inline?undefined:true} aria-label="资源设置" className="resource-editor-form" onSubmit={e=>{e.preventDefault();void submit();}}>{!inline&&<button className="resource-editor-close" type="button" aria-label="关闭资源设置" onClick={close}>×</button>}<fieldset disabled={disabled||busy||!!value?.locked&&!gm}><label className="resource-name-edit">名称<input required aria-label="资源名称" value={name} onChange={e=>setName(e.target.value)}/><button type="button" className="resource-lock" disabled={!gm} aria-label={locked?'解锁资源':'锁定资源'} aria-pressed={locked} onClick={()=>setLocked(!locked)}><LockIcon locked={locked}/></button></label><div className="segmented">{[['count','次数'],['bar','进度条'],['number','数值']].map(([id,label])=><button type="button" key={id} aria-pressed={id===type} onClick={()=>{setType(id);if(id!=='number')setUnlimited(false);}}>{label}</button>)}</div><div className="resource-edit-numbers"><label>剩余<input aria-label="资源剩余" type="number" min="0" value={current} onChange={e=>setCurrent(e.target.value)}/></label><label>{type==='number'&&<input type="checkbox" aria-label="资源有上限" checked={!unlimited} disabled={value?.automatic} onChange={e=>setUnlimited(!e.target.checked)}/>}上限<input aria-label="资源上限" disabled={value?.automatic||type==='number'&&unlimited} type="number" min="0" max="99999" value={max} onChange={e=>{const next=e.target.value;if(current===max)setCurrent(next);setMax(next);}}/></label></div><div className="resource-editor-actions"><button type="submit">保存</button><button type="button" onClick={close}>取消</button><button type="button" onClick={()=>{try{savePreset(valid(),presetScope);setError('');}catch(e){setError(String(e));}}}>保存为预设</button>{remove&&!value?.automatic&&<button type="button" onClick={()=>{setBusy(true);void remove().then(close).catch(e=>setError(String(e))).finally(()=>setBusy(false));}}>移除</button>}</div></fieldset>{error&&<p role="alert">{error}</p>}</form></div>;return inline?content:createPortal(content,document.body);
}
export function LockIcon({locked}:{locked:boolean}){return <svg data-locked={locked} width="13" height="15" viewBox="0 0 16 18" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true"><rect x="2" y="7" width="12" height="9" rx="1"/><path d={locked?'M5 7V4a3 3 0 016 0V7':'M5 7V4a3 3 0 016 0'}/>{locked&&<path d="M8 10v3"/>}</svg>;}
