import {useState,useRef,useEffect} from 'react';
import './resource179.css';
import {StatInput} from './StatInput';
import {LockIcon} from './ResourceEditor';
import {pointerDrag} from './pointerDrag';
import {usePresets,removePreset,type ResourceValue} from './resourcePresets';
export function ResourceRow({resource:r,enabled,gm,change,configure,label='',lock,confirmedCurrent}:{resource:ResourceValue;enabled:boolean;gm:boolean;confirmedCurrent?:number;change:(n:number)=>Promise<unknown>;configure?:(()=>void);label?:string;lock?:()=>void}){
 const [input,setInput]=useState(false),[shown,setShown]=useState(r.current),[waitingRevision,setWaitingRevision]=useState(0),busy=useRef(0),desired=useRef(r.current),authoritative=useRef(r.current),generation=useRef(0);
 const waiting=useRef<{requestId?:string;turn:number;target:number;queueBlocked?:boolean}|undefined>(undefined),resource=useRef(r);resource.current=r;authoritative.current=r.current;
 const intent=useRef<{turn:number;target:number;observed:boolean;lastAuthority:number}|undefined>(undefined);
 useEffect(()=>{const confirmed=confirmedCurrent??r.current;if(busy.current&&intent.current&&confirmed!==intent.current.lastAuthority){intent.current.lastAuthority=confirmed;if(confirmed===intent.current.target)intent.current.observed=true;}const wait=waiting.current;if(wait){if(wait.requestId){if(wait.queueBlocked||confirmedCurrent!==wait.target)return;waiting.current=undefined;desired.current=confirmedCurrent;setShown(confirmedCurrent);window.dispatchEvent(new CustomEvent('workbench-operation-reconciled',{detail:{requestId:wait.requestId}}));return;}if(r.current!==wait.target)return;waiting.current=undefined;}if(!busy.current){desired.current=r.current;setShown(r.current);}},[r.current,confirmedCurrent,waitingRevision]);
 useEffect(()=>{const reconcile=(event:Event)=>{const wait=waiting.current;if(!wait?.requestId||wait.requestId!==(event as CustomEvent).detail?.requestId)return;waiting.current=undefined;desired.current=authoritative.current;setShown(authoritative.current);};window.addEventListener('workbench-operation-reconciled',reconcile);return()=>window.removeEventListener('workbench-operation-reconciled',reconcile);},[]);
 useEffect(()=>{const receipt=(event:Event)=>{const detail=(event as CustomEvent).detail,wait=waiting.current;if(!wait?.requestId||detail.uncertain||detail.requestId!==wait.requestId)return;const turn=wait.turn;queueMicrotask(()=>{if(waiting.current!==wait||generation.current!==turn)return;
   const rows=detail.result?.snapshot?.state?.resources||Object.values(detail.result?.inventory?.containers||{}).flatMap((container:any)=>container.items?.filter((row:any)=>row.kind==='resource').map((row:any)=>({...row,current:row.quantity}))||[]);
   const confirmed=rows.find((row:ResourceValue)=>resource.current.id?row.id===resource.current.id:row.name===resource.current.name)?.current;
   const next=detail.ok?(typeof confirmed==='number'?confirmed:wait.target):authoritative.current;
   waiting.current=detail.ok&&authoritative.current!==next?{turn,target:next}:undefined;desired.current=next;setShown(next);
  });};window.addEventListener('workbench-operation-result',receipt);return()=>window.removeEventListener('workbench-operation-result',receipt);},[]);
 const editable=enabled&&(!r.locked||gm),bound=(n:number)=>Math.max(0,Math.min(r.unlimited?999999999:r.max,n));
 const commit=async(expression:string)=>{const amount=Number(expression),next=bound(/^[+-]/.test(expression)?desired.current+amount:amount);if(!Number.isInteger(next))throw Error('请输入整数');const turn=++generation.current;intent.current={turn,target:next,observed:false,lastAuthority:confirmedCurrent??r.current};desired.current=next;setShown(next);setInput(false);busy.current++;try{await change(next);if(turn===generation.current)waiting.current=undefined;}catch(e){if(turn===generation.current){if((e as any)?.uncertain){const previous=waiting.current;waiting.current=(e as any).queueBlocked&&previous&&previous.requestId===(e as any).requestId?{...previous,turn}:{requestId:(e as any).requestId,turn,target:next,queueBlocked:!!(e as any).queueBlocked};setWaitingRevision(n=>n+1);}else{waiting.current=undefined;desired.current=authoritative.current;setShown(authoritative.current);}}throw e;}finally{
  busy.current--;
  // Props may have advanced again after acknowledging this intent while the
  // promise was still pending. Wake the skipped effect only after that proof;
  // an early receipt must never reapply props from before the user's edit.
  if(!busy.current){if(intent.current?.turn===generation.current&&intent.current.observed&&!waiting.current)setWaitingRevision(n=>n+1);intent.current=undefined;}
 }};

 return <div className="console-resource resource179-row"><div className="resource-title"><strong>{r.name}</strong><span className="resource-actions"><button className="resource-lock" aria-label={`${r.locked?'解锁':'锁定'}${r.name}`} disabled={!gm||!enabled||!lock} onClick={lock}><LockIcon locked={!!r.locked}/></button><button className="resource-configure" aria-label={`设置${r.name}`} disabled={!editable||!configure} onClick={configure}>⚙</button></span></div><div className="console-resource-controls">{r.type!=='count'&&<button disabled={!editable||shown<=0} aria-label={`消耗${label}${r.name}`} onClick={()=>void commit('-1').catch(()=>{})}>−</button>}{input?<span className="resource-manual"><StatInput autoFocus label={`${label}${r.name}剩余`} value={shown} disabled={!editable} commit={commit} authority={false} onFinish={()=>setInput(false)}/>{!r.unlimited&&<small>/ {r.max}</small>}</span>:r.type==='bar'?<button className="resource-bar" disabled={!editable} onClick={()=>setInput(true)}><i style={{width:`${r.max?Math.min(100,shown/r.max*100):0}%`}}/><b>{shown} / {r.max}</b></button>:r.type!=='number'&&r.max<=20?<div className="resource-pips">{Array.from({length:r.max},(_,i)=><button key={i} aria-label={`${label}${r.name} ${i+1}`} aria-pressed={shown>i} disabled={!editable} onClick={()=>void commit(String(i+1>shown?i+1:i)).catch(()=>{})}><span className={shown>i?'resource-pip':'resource-pip spent'}/></button>)}</div>:<button className="resource-numeric" disabled={!editable} onClick={()=>setInput(true)}>{shown}{!r.unlimited&&<small> / {r.max}</small>}</button>}{r.type!=='count'&&<button disabled={!editable||!r.unlimited&&shown>=r.max} aria-label={`恢复${label}${r.name}`} onClick={()=>void commit('+1').catch(()=>{})}>＋</button>}</div></div>;
}
export function ResourcePresets({scope='player',give,disabled=false}:{scope?:string;give:(resource:ResourceValue,target:string)=>void;disabled?:boolean}){
 const presets=usePresets(scope);return <div className="resource-heading-presets">{presets.map((r,i)=><button key={r.name+':'+i} disabled={disabled} title="拖拽预设给予资源；右键移除预设" onContextMenu={e=>{e.preventDefault();removePreset(r.name||'',scope);}} onPointerDown={e=>{let marked:Element|null=null;const clear=()=>{marked?.classList.remove('inventory-drop-over');marked=null;};pointerDrag(e,{appearance:'source',title:r.name||'资源',cancel:clear,move:(_,hit)=>{const target=hit?.closest(`[data-resource-target][data-resource-scope="${scope}"]`)||null;if(marked!==target){clear();marked=target;marked?.classList.add('inventory-drop-over');}},finish:(_,hit)=>{const target=hit?.closest<HTMLElement>(`[data-resource-target][data-resource-scope="${scope}"]`);clear();if(target){give(r,target.dataset.resourceTarget!);return {element:target.querySelector<HTMLElement>('.console-resource:last-of-type')||target};}}});}}>{r.name}</button>)}</div>;
}
