import {BookRituals} from './BookRituals';
import {SourceSpellActions} from './SourceSpellActions';
import {sourceSpellEnabled} from '../core/automation/sourceSpellState';
import {planSourceSpells} from '../core/automation/sourceSpells';
import {setSpecialSpell,specialSpellResource,changeSpecialSpellUses} from '../core/specialSpells';
import {ShareEntryButton} from './EntrySharing';
import {NumberInput} from './NumberInput';
import {useContext,useEffect,useLayoutEffect,useMemo,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {uid,signed,selectionAllowed,ABILITIES,ABILITY_LABELS,type Ability,type Entry,type SpecialSpell,type Selection} from '../core/model';
import {spellState} from '../core/characterDetails';
import {prepareSpellEntry,setPreparedSpell,spellLibrary} from '../core/spells';
import {knownSpellCapacity,capacitySlots,sourceCapacity} from '../core/spellCapacity';
import {casterProfiles,spellUsesPreparation,spellOnClassList,hasKnownLibrary} from '../core/spellcastingRules';
import {cantripGroups,chooseCantrip,clearCantrip,spellIsReady,ordinaryPrepared,learnActiveSpell,knownActiveSpells,chooseKnownSpell} from '../core/spellWorkspace';
import {cantripSources,chooseSourceSpell} from '../core/sourceCantrips';
import {removeSelection} from '../core/sheet';
import {SheetCell} from './SheetCell';
import {DropZone} from './DragEntry';
import {SheetEditContext} from './SheetEdit';
import {Reference,ReferenceContext} from './Reference';
import {pointerDrag} from './pointerDrag';
import {type PageProps} from './CharacterPages';
import './spellsPage.css';

export function SpellFrame(){return <svg className="spell-tile-frame" viewBox="0 0 100 28" preserveAspectRatio="none" aria-hidden="true"><path d="M3 .75H97L99.25 3V25L97 27.25H3L.75 25V3Z"/></svg>;}
function ConcentrationMark(){return <svg className="spell-concentration-mark" viewBox="0 0 24 24" role="img" aria-label="专注"><circle cx="12" cy="12" r="10"/><circle cx="12" cy="12" r="7"/><path d="m12 4 7 12H5Zm0 16L5 8h14Z"/><path d="M12 0v3m0 18v3M0 12h3m18 0h3"/></svg>;}
type Target={kind:'cantrip'|'ordinary'|'source';owner?:string;index?:number};
const error=(detail:string)=>window.dispatchEvent(new CustomEvent('workbench-error',{detail}));

export function SpellsPage({c,d,edit,browse,entries=[],inspect,readOnly=false}:PageProps&{readOnly?:boolean}){
 const editing=useContext(SheetEditContext),preview=useContext(ReferenceContext),settings=spellState(c);
 const spells=useMemo(()=>spellLibrary(c,entries),[c,entries]),groups=cantripGroups(c),profiles=casterProfiles(c);
 const sourceIssues=useMemo(()=>planSourceSpells(c,entries).issues,[c,entries]);
 const [focused,setFocused]=useState<Target>(),[menu,setMenu]=useState<{row:Selection;target?:Target;x:number;y:number}>(),[detail,setDetail]=useState<string>(),[classFilter,setClassFilter]=useState('');
 const [giftOwner,setGiftOwner]=useState('');const [collapsed,setCollapsed]=useState<Record<number,boolean>>({});const [preparedHeight,setPreparedHeight]=useState(0);const giftSources=cantripSources(c);
 const preparedRoot=useRef<HTMLDivElement>(null),libraryRoot=useRef<HTMLDivElement>(null);
 const change=(fn:(s:ReturnType<typeof spellState>)=>void)=>edit(draft=>{draft.spellSettings=structuredClone(settings);fn(draft.spellSettings);});
 const prepared=ordinaryPrepared(c),count=prepared.filter(Boolean).length;
 const special=spells.filter(s=>settings.special?.[s.id]);
 const selectedClass=profiles.find(p=>p.owner.id===classFilter);
 const showLibrary=profiles.some(hasKnownLibrary)||!profiles.length||settings.modeOverride&&settings.mode==='prepared'||profiles.some(p=>p.mode==='prepared'&&p.pool==='learned');
 const library=spells.filter(s=>!settings.special?.[s.id]&&(!selectedClass||spellOnClassList(s.entry,selectedClass)||!s.entry.raw._spellClasses&&!s.entry.raw.classes));
 const knownActive=knownActiveSpells(c);
 const sourceOwner=(s:Selection)=>settings.special?.[s.id]?.sourceGrant?.ownerId||settings.special?.[s.id]?.manualSource?.ownerId||'manual';
 const sourceGroups=[...new Set([...special.map(sourceOwner),...Object.keys({...settings.sourceCantripCapacities,...settings.sourceCapacityAdjustments}).filter(id=>id==='manual'||giftSources.some(s=>s.id===id))])].map(owner=>({owner,name:c.selections.find(s=>s.id===owner)?.entry.name||(owner==='manual'?'手动添加':'已移除的来源'),rows:special.filter(s=>sourceOwner(s)===owner)}));
 const normalCapacity=settings.capacity,knownCapacity=knownSpellCapacity(c);
 const ordinaryVisible=normalCapacity>0||count>0;
 const showPrepared=ordinaryVisible||editing&&(groups.length>0||sourceGroups.length>0)||groups.some(g=>g.capacity>0||g.slots.some(Boolean))||sourceGroups.some(g=>g.rows.length>0||sourceCapacity(c,g.owner).total>0)||knownCapacity>0||knownActive.length>0;
 useEffect(()=>{setCollapsed({});setFocused(undefined);},[c.id]);
 useLayoutEffect(()=>{const node=preparedRoot.current;if(!node)return;const measure=()=>setPreparedHeight(node.scrollHeight);const observer=new ResizeObserver(measure);observer.observe(node);measure();return()=>observer.disconnect();},[showPrepared,c.id]);
 const detailRow=spells.find(s=>s.id===detail),detailConfig=detailRow?settings.special?.[detailRow.id]:undefined;
 useEffect(()=>{if(classFilter&&!profiles.some(p=>p.owner.id===classFilter))setClassFilter('');},[classFilter,profiles]);
 useEffect(()=>{if(giftOwner&&!giftSources.some(s=>s.id===giftOwner))setGiftOwner('');},[giftOwner,giftSources]);
 useEffect(()=>{if(!menu&&!detail)return;const close=(e:KeyboardEvent)=>{if(e.key==='Escape'){setMenu(undefined);setDetail(undefined);}};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[menu,detail]);
 function findTile(root:HTMLDivElement|null,id?:string){return id?root?.querySelector<HTMLElement>(`[data-spell-id="${CSS.escape(id)}"]`)||null:null;}
 function receive(entry:Entry,target?:Target){
  if(!editing){error('请先开启编辑模式，再调整预备或戏法。');return;}
  let failure='',id:string|undefined;
  edit(draft=>{
   if(target?.kind==='source'){const result=chooseSourceSpell(draft,entry,target.owner!);failure=result.error||'';id=result.id;}
   else if(Number(entry.raw.level)===0&&cantripGroups(draft).length){const result=chooseCantrip(draft,entry,target?.kind==='cantrip'?target.owner:undefined,target?.kind==='cantrip'?target.index:undefined);failure=result.error||'';id=result.id;}
   else if(target?.kind==='cantrip')failure='这个位置只能放戏法。';
   else if(spellUsesPreparation(draft,entry)){
    const result=prepareSpellEntry(draft,entry,target?.kind==='ordinary'?target.index:undefined);
    id=result||undefined;
    if(!result)failure='无法预备：请检查来源或版本；格子已满时可拖到已有法术上替换。';
   }else {const result=chooseKnownSpell(draft,entry);failure=result.error||'';id=result.id;}
  });
  if(failure)error(failure);else setFocused(undefined);return id;
 }
 function unprepare(row:Selection,target?:Target){if(!editing)return;edit(draft=>{if(target?.kind==='cantrip'){const group=cantripGroups(draft).find(g=>g.id===target.owner);clearCantrip(draft,target.owner!,target.index??group?.slots.indexOf(row.id)??-1);}else if(Number(row.entry.raw.level)===0&&!spellUsesPreparation(draft,row.entry,row.id)){for(const group of cantripGroups(draft))group.slots.forEach((id,index)=>{if(id===row.id)clearCantrip(draft,group.id,index);});}else if(spellUsesPreparation(draft,row.entry,row.id))setPreparedSpell(draft,row.id,false);else removeSelection(draft,row.id);});}
 function configure(row:Selection,config?:SpecialSpell){edit(draft=>{let stored=draft.selections.find(s=>s.id===row.id)||draft.selections.find(s=>s.entry.id===row.entry.id&&!draft.spellSettings?.special?.[s.id]);if(!stored){stored={...row,id:uid(),entry:structuredClone(row.entry)};draft.selections.push(stored);}setSpecialSpell(draft,stored.id,config);});setMenu(undefined);}
 function targetAt(hit:Element|null):Target|undefined{const node=hit?.closest<HTMLElement>('[data-spell-target]');if(!node||!preparedRoot.current?.contains(node))return;return {kind:node.dataset.spellTarget as Target['kind'],owner:node.dataset.spellOwner,index:node.dataset.spellIndex===undefined?undefined:Number(node.dataset.spellIndex)};}
 function tile(row:Selection,target?:Target){
  const config=settings.special?.[row.id],level=Number(row.entry.raw.level)||0,ready=spellIsReady(c,row),enabled=selectionAllowed(c,row.entry)&&(!config||sourceSpellEnabled(c,row.id));
  return <Reference key={row.id} reference={`entry:${row.entry.id}`} entry={row.entry} commitOnClick={false}
   className={`stock-item spell-stock-tile ${target?'prepared-slot':'spell-choice'} ${!target&&!config&&ready?'is-prepared':''} ${row.entry.raw.meta?.ritual?'spell-ritual':''} ${row.entry.raw.duration?.some((v:any)=>v.concentration)?'spell-concentration':''}`}
   data-spell-id={row.id} data-entry-id={row.entry.id} data-drag-enabled={editing&&!config} data-entry-context-menu data-physical-frame="" data-restricted={!enabled} aria-label={row.entry.name} aria-pressed={!target&&!config?ready:undefined}
   onClick={()=>{if(config||!editing)inspect(row.entry);else if(target)unprepare(row,target);else if(ready)unprepare(row);else receive(row.entry,focused);}}
   onContextMenu={e=>{e.preventDefault();e.stopPropagation();preview?.close();setMenu({row,target,x:Math.max(8,Math.min(innerWidth-220,e.clientX)),y:Math.max(8,Math.min(innerHeight-260,e.clientY))});}}
   onPointerDown={e=>{
    if(e.button!==0||!editing||config)return;
    const source=e.currentTarget,preparedZone=preparedRoot.current?.closest('.prepared-cell'),libraryZone=libraryRoot.current?.closest('.spell-library');
    const clear=()=>{preparedZone?.classList.remove('spell-drop-over');libraryZone?.classList.remove('spell-drop-over');};
    const inPrepared=(hit:Element|null)=>!!hit&&!!preparedZone?.contains(hit),inLibrary=(hit:Element|null)=>!!hit&&!!libraryZone?.contains(hit);
    pointerDrag(e,{appearance:'source',title:row.entry.name,cancel:clear,move:(_,hit)=>{preparedZone?.classList.toggle('spell-drop-over',inPrepared(hit));libraryZone?.classList.toggle('spell-drop-over',!!target&&inLibrary(hit));},outside:hit=>!inPrepared(hit)&&!inLibrary(hit),finish:(_,hit)=>{
     clear();const next=targetAt(hit);
     if(inPrepared(hit)){const id=receive(row.entry,next||focused);return {resolve:()=>findTile(preparedRoot.current,id)||source};}
     if(target){unprepare(row,target);return {resolve:()=>findTile(libraryRoot.current,row.id),removed:!inLibrary(hit)};}
     if(hit&&!inLibrary(hit)&&c.selections.some(s=>s.id===row.id)){edit(draft=>removeSelection(draft,row.id));return {removed:true};}
    }});
   }}><SpellFrame/><span className="stock-name">{row.entry.name}</span><span className="spell-stock-meta">{row.entry.raw.duration?.some((v:any)=>v.concentration)&&<ConcentrationMark/>}<span className="spell-stock-level" aria-label={level===0?'戏法':`${level}环`}>{level}</span></span>{!target&&!config&&ready&&<span className="spell-ready-mark">{level===0?'已选':'已预备'}</span>}</Reference>;
 }
 function slot(id:string|undefined,target:Target){const row=spells.find(s=>s.id===id);return <DropZone key={target.index} kinds={['spell']} allowExisting accepts={e=>target.kind==='cantrip'?Number(e.raw.level)===0:spellUsesPreparation(c,e)} rejectReason={target.kind==='cantrip'?'这个位置只能放戏法。':'这个法术属于其他分类，请放入对应的法术栏。'} onReceive={entry=>receive(entry,target)} className="spell-grid-slot" data-spell-target={target.kind} data-spell-owner={target.owner} data-spell-index={target.index} data-prepared-slot={target.kind==='ordinary'?target.index:undefined}>
  {row?tile(row,target):<button data-physical-frame="" className={`stock-empty prepared-slot spell-stock-empty ${focused?.kind===target.kind&&focused.owner===target.owner&&focused.index===target.index?'slot-focused':''}`} aria-label={`${target.kind==='cantrip'?`${groups.find(g=>g.id===target.owner)?.name||''}戏法`:'预备'}空位${(target.index||0)+1}`} disabled={!editing} onClick={()=>{setFocused(target);if(!showLibrary)browse('spell');}}><SpellFrame/>＋</button>}</DropZone>;}
 function grantTile(row:Selection){
  const config=settings.special![row.id],resource=c.runtime.resources[specialSpellResource(row.id,c)],grant=config.sourceGrant,enabled=sourceSpellEnabled(c,row.id);
  const badge=config.mode==='uses'?`${grant?.resourceKey?'共用':'免费'} ${resource?.current??0}/${resource?.max??config.max} · ${config.recovery==='long'?'长休':config.recovery==='short'?'短休':'手动'}`:grant?.usage==='slot'?'已预备 · 法术位':grant?.usage==='free'?'免费 · 随意':grant?.usage==='ritual'?'仅仪式':config.manualSource?'手动赠送 · 按原文':'施放按原文';
  return <div key={row.id} className="spell-grant-tile source-spell-row" data-source-spell={!!grant} data-restricted={!enabled}>{tile(row)}<button className="spell-use-badge" aria-label={`${row.entry.name}施放详情`} onClick={()=>setDetail(row.id)} title="查看施放方式、剩余次数和来源">{enabled?badge:'来源未启用'} <span>›</span></button></div>;
 }
 function adjustment(label:string,value:number,update:(value:number)=>void){return editing&&<label className="spell-capacity-adjust"><span>上限调整</span><NumberInput aria-label={label} min="-100" max="100" value={value} onChange={e=>update(Math.max(-100,Math.min(100,Math.trunc(Number(e.target.value)||0))))}/></label>;}
 function overflow(ids:string[],target?:Target){return ids.length>0&&<details className="spell-overflow"><summary>超出上限 · {ids.length} 项已保留原记录</summary><ul>{ids.map(id=>{const row=spells.find(s=>s.id===id);return row&&<li key={id}><button onClick={()=>inspect(row.entry)}>{row.entry.name}</button>{editing&&!settings.special?.[row.id]?.sourceGrant&&<button onClick={()=>target?.kind==='source'?edit(draft=>removeSelection(draft,row.id)):unprepare(row,target)}>移出此分类</button>}</li>;})}</ul></details>;}
 return <>{editing&&<div className="spell-settings"><div className="segmented"><button aria-pressed={!settings.modeOverride} onClick={()=>change(s=>{s.modeOverride=false;})}>跟随职业</button>{(['known','prepared'] as const).map(mode=><button key={mode} aria-pressed={!!settings.modeOverride&&settings.mode===mode} onClick={()=>change(s=>{s.mode=mode;s.modeOverride=true;})}>{mode==='known'?'随等级选择':'每日预备'}</button>)}</div>{!ordinaryVisible&&settings.mode==='prepared'&&adjustment('预备上限调整',settings.capacityAdjustment||0,value=>change(s=>{s.capacityAdjustment=value;}))}{knownCapacity===0&&knownActive.length===0&&settings.mode==='known'&&adjustment('职业法术上限调整',settings.knownCapacityAdjustment||0,value=>change(s=>{s.knownCapacityAdjustment=value;}))}</div>}
 {editing&&giftSources.length>0&&<div className="spell-settings source-cantrip-settings"><label>赠送法术来源<select aria-label="赠送法术来源" value={giftOwner} onChange={e=>setGiftOwner(e.target.value)}><option value="">选择已加入的来源</option>{giftSources.map(s=><option key={s.id} value={s.id}>{s.entry.name}</option>)}</select></label>{giftOwner&&adjustment('来源法术上限调整',settings.sourceCapacityAdjustments?.[giftOwner]||0,value=>change(s=>{(s.sourceCapacityAdjustments||={})[giftOwner]=value;}))}</div>}
 {profiles.length>1&&<section className="multiclass-spells" aria-label="各职业施法"><div className="segmented"><button aria-pressed={!classFilter} onClick={()=>setClassFilter('')}>全部法术</button>{profiles.map(p=><button key={p.owner.id} aria-pressed={classFilter===p.owner.id} onClick={()=>setClassFilter(p.owner.id)}>{p.owner.entry.name}</button>)}</div><table><thead><tr><th>职业</th><th>属性</th><th>攻击</th><th>DC</th><th>更换</th></tr></thead><tbody>{profiles.map(p=>{const ability=ABILITIES.includes(p.casting.entry.raw.spellcastingAbility)?p.casting.entry.raw.spellcastingAbility as Ability:settings.ability;const bonus=d.modifiers[ability]+d.proficiency;return <tr key={p.owner.id}><th>{p.owner.entry.name}</th><td>{ABILITY_LABELS[ability]}</td><td>{signed(bonus+settings.attackBonus)}</td><td>{8+bonus+settings.dcBonus}</td><td>{p.mode==='known'?'升级':'预备'}</td></tr>;})}</tbody></table></section>}
 {sourceIssues.length>0&&<details className="spell-source-notices"><summary>{sourceIssues.length} 项来源法术需要核对</summary><ul>{sourceIssues.map((issue,i)=><li key={i}>{issue.message}</li>)}</ul></details>}
 {showPrepared&&<SheetCell label="预备法术" style={{height:preparedHeight+38}} className={`prepared-cell unified-prepared spell-stock-cell ${showLibrary?'':'only-prepared'}`} dropKinds={['spell']} allowExisting onReceive={entry=>receive(entry,focused)}>
  <div ref={preparedRoot} className="prepared-spell-groups">
   {ordinaryVisible&&<section className="prepared-spell-group ordinary-prepared-group"><h4><span>普通预备 <small>{count} / {normalCapacity}</small></span>{adjustment('预备上限调整',settings.capacityAdjustment||0,value=>change(s=>{s.capacityAdjustment=value;}))}</h4><div className="prepared-slots spell-stock-grid" data-spell-target="ordinary">{capacitySlots(prepared,normalCapacity).slots.map((id,i)=>slot(id,{kind:'ordinary',index:i}))}</div>{overflow(capacitySlots(prepared,normalCapacity).overflow)}</section>}
   {groups.filter(group=>editing||group.capacity>0||group.slots.some(Boolean)).map(group=><section key={group.id} className="prepared-spell-group" data-cantrip-group={group.id}><h4><span>{group.name==='戏法'?'戏法':`${group.name} · 戏法`} <small>{group.slots.filter(Boolean).length} / {group.capacity}</small></span>{adjustment(`${group.name}所学戏法数量调整`,settings.cantripCapacityAdjustments?.[group.id]||0,value=>change(s=>{(s.cantripCapacityAdjustments||={})[group.id]=value;}))}</h4><div className="spell-stock-grid">{capacitySlots(group.slots,group.capacity).slots.map((id,i)=>slot(id,{kind:'cantrip',owner:group.id,index:i}))}</div>{overflow(capacitySlots(group.slots,group.capacity).overflow,{kind:'cantrip',owner:group.id})}</section>)}
   {sourceGroups.filter(group=>editing||group.rows.length||sourceCapacity(c,group.owner).total>0).map(group=>{const capacity=sourceCapacity(c,group.owner).total,layout=capacitySlots(group.rows.map(row=>row.id),capacity);return <section key={group.owner} className="prepared-spell-group source-spell-group" data-source-cantrip-group={group.owner}><h4><span>来自{group.name} <small>{group.rows.length} / {capacity}</small></span>{adjustment(`${group.name}来源法术上限调整`,settings.sourceCapacityAdjustments?.[group.owner]||0,value=>change(s=>{(s.sourceCapacityAdjustments||={})[group.owner]=value;}))}</h4><DropZone kinds={['spell']} allowExisting onReceive={entry=>receive(entry,{kind:'source',owner:group.owner})} data-spell-target="source" data-spell-owner={group.owner}><div className="spell-stock-grid spell-grants-grid">{layout.slots.map((id,i)=>id?grantTile(spells.find(s=>s.id===id)!):<button key={`empty-${i}`} className="stock-empty prepared-slot spell-stock-empty" disabled={!editing} aria-label={`${group.name}赠送法术空位${i+1}`} onClick={()=>{setFocused({kind:'source',owner:group.owner});browse('spell');}}><SpellFrame/>＋</button>)}</div></DropZone>{overflow(layout.overflow,{kind:'source',owner:group.owner})}</section>;})}
   {(knownActive.length>0||knownCapacity>0)&&<section className="prepared-spell-group known-active-group"><h4><span>职业法术 <small>{knownActive.length} / {knownCapacity}</small></span>{adjustment('职业法术上限调整',settings.knownCapacityAdjustment||0,value=>change(s=>{s.knownCapacityAdjustment=value;}))}</h4><DropZone kinds={['spell']} allowExisting onReceive={entry=>receive(entry)} className="spell-stock-grid">{knownActive.slice(0,knownCapacity).map(row=>tile(row,{kind:'ordinary'}))}{Array.from({length:Math.max(0,knownCapacity-knownActive.length)},(_,i)=><button key={`known-empty-${i}`} className="stock-empty prepared-slot spell-stock-empty" disabled={!editing} aria-label={`职业法术空位${i+1}`} onClick={()=>browse('spell')}><SpellFrame/>＋</button>)}</DropZone>{overflow(knownActive.slice(knownCapacity).map(row=>row.id))}</section>}
   {!showLibrary&&<button className="feature-browse" onClick={()=>browse('spell')}>＋ 从 Wiki 选择法术</button>}
  </div>
 </SheetCell>}
 <BookRituals c={c} edit={edit} inspect={inspect} readOnly={readOnly}/>
 {showLibrary&&<SheetCell label="已知法术" className="spell-library spell-stock-cell" dropKinds={['spell']} allowExisting onReceive={entry=>{if(!editing)return;edit(draft=>{const result=learnActiveSpell(draft,entry);if(result.error)error(result.error);});}}><div ref={libraryRoot} className="spell-library-groups">{[...new Set(library.map(s=>Number(s.entry.raw.level)||0))].sort((a,b)=>a-b).map(level=><details key={level} data-spell-level={level} className="spell-library-level" open={!collapsed[level]} onToggle={e=>{const closed=!e.currentTarget.open;setCollapsed(old=>old[level]===closed?old:{...old,[level]:closed});}}><summary>{level===0?'戏法':`${level}环`} <small>{library.filter(s=>(Number(s.entry.raw.level)||0)===level).length}</small></summary><div className="spell-stock-grid">{library.filter(s=>(Number(s.entry.raw.level)||0)===level).map(s=>tile(s))}</div></details>)}</div><button className="feature-browse" onClick={()=>browse('spell')}>＋ 查阅法术</button></SheetCell>}
 {menu&&createPortal(<div className="stock-menu-shade spell-menu-shade" onPointerDown={e=>{if(e.target===e.currentTarget){e.preventDefault();setMenu(undefined);}}} onContextMenu={e=>{e.preventDefault();setMenu(undefined);}}><div role="menu" aria-label="法术操作" className="stock-menu spell-context-menu" style={{left:menu.x,top:menu.y}}><strong>{menu.row.entry.name}</strong><ShareEntryButton entry={menu.row.entry} done={()=>setMenu(undefined)}/>{editing&&!settings.special?.[menu.row.id]&&<button role="menuitem" onClick={()=>{if(menu.target||spellIsReady(c,menu.row))unprepare(menu.row,menu.target);else receive(menu.row.entry,focused);setMenu(undefined);}}>{menu.target?'移出此格':spellIsReady(c,menu.row)?'取消选中':'放入预备栏'}</button>}<button role="menuitem" onClick={()=>{inspect(menu.row.entry);setMenu(undefined);}}>在 Wiki 中查看</button>{settings.special?.[menu.row.id]&&<button role="menuitem" onClick={()=>{setDetail(menu.row.id);setMenu(undefined);}}>施放方式与次数</button>}{editing&&!settings.special?.[menu.row.id]?.sourceGrant&&<><button role="menuitem" onClick={()=>configure(menu.row,{mode:'locked'})}>设为来源赠送</button><button role="menuitem" onClick={()=>configure(menu.row,{mode:'uses',max:settings.special?.[menu.row.id]?.max||1,recovery:'long'})}>设置免费施放次数</button>{settings.special?.[menu.row.id]&&<button role="menuitem" onClick={()=>configure(menu.row)}>改为普通法术</button>}{c.selections.some(s=>s.id===menu.row.id)&&<button role="menuitem" onClick={()=>{edit(draft=>removeSelection(draft,menu.row.id));setMenu(undefined);}}>从角色卡移除</button>}</>}</div></div>,document.body)}
 {detailRow&&detailConfig&&createPortal(<div className="spell-detail-shade" onPointerDown={e=>{if(e.target===e.currentTarget)setDetail(undefined);}}><section className="spell-detail-dialog" role="dialog" aria-label={`${detailRow.entry.name}施放详情`}><header><strong>{detailRow.entry.name}</strong><button aria-label="关闭施放详情" onClick={()=>setDetail(undefined)}>×</button></header><p>来源：{c.selections.find(s=>s.id===(detailConfig.sourceGrant?.ownerId||detailConfig.manualSource?.ownerId))?.entry.name||'手动添加'} · 不占普通预备格</p>{detailConfig.sourceGrant?.ability&&<p>{ABILITY_LABELS[detailConfig.sourceGrant.ability]} · 攻击 {signed(d.modifiers[detailConfig.sourceGrant.ability]+d.proficiency+settings.attackBonus)} · DC {8+d.modifiers[detailConfig.sourceGrant.ability]+d.proficiency+settings.dcBonus}</p>}{detailConfig.mode==='uses'&&<label className="special-spell-uses">剩余次数 <NumberInput aria-label={`${detailRow.entry.name}剩余次数`} min="0" max={detailConfig.max} value={c.runtime.resources[specialSpellResource(detailRow.id,c)]?.current??0} disabled={!sourceSpellEnabled(c,detailRow.id)} onChange={e=>edit(draft=>changeSpecialSpellUses(draft,detailRow.id,Number(e.target.value)))}/> / {detailConfig.max} · {detailConfig.recovery==='short'?'短休或长休恢复':detailConfig.recovery==='long'?'长休恢复':'手动恢复'}</label>}{detailConfig.sourceGrant?<SourceSpellActions c={c} id={detailRow.id} edit={edit}/>:detailConfig.mode==='uses'?<div className="manual-spell-actions"><button disabled={!c.runtime.resources[specialSpellResource(detailRow.id,c)]?.current} onClick={()=>edit(draft=>changeSpecialSpellUses(draft,detailRow.id,(draft.runtime.resources[specialSpellResource(detailRow.id,draft)]?.current||0)-1))}>使用免费次数</button><button onClick={()=>edit(draft=>changeSpecialSpellUses(draft,detailRow.id,detailConfig.max||1))}>恢复次数</button></div>:<p>施放条件请按来源原文核对。</p>}{editing&&!detailConfig.sourceGrant&&detailConfig.mode==='uses'&&<div><label>次数上限 <NumberInput value={detailConfig.max||1} onChange={e=>configure(detailRow,{...detailConfig,max:Number(e.target.value)})}/></label><select aria-label="次数恢复方式" value={detailConfig.recovery||'manual'} onChange={e=>configure(detailRow,{...detailConfig,recovery:e.target.value as SpecialSpell['recovery']})}><option value="manual">手动</option><option value="short">短休或长休</option><option value="long">长休</option></select></div>}</section></div>,document.body)}
 </>;
}
