import {useEffect,useRef,useState} from 'react';
export function StatInput({value,label,disabled,commit,autoFocus=false,onFinish,authority=true}:{value:number;label:string;disabled?:boolean;autoFocus?:boolean;authority?:boolean;onFinish?:()=>void;commit:(expression:string)=>Promise<unknown>}){
 const [draft,setDraft]=useState(String(value)),[waitingRevision,setWaitingRevision]=useState(0),focused=useRef(false),cancel=useRef(false),pending=useRef(0),generation=useRef(0),latest=useRef(value),shown=useRef(value),waiting=useRef<{requestId?:string;field?:string;turn:number;target:number;queueBlocked?:boolean}|undefined>(undefined);latest.current=value;
 const intent=useRef<{turn:number;target:number;observed:boolean;lastAuthority:number}|undefined>(undefined);
 useEffect(()=>{if(pending.current&&authority&&intent.current&&value!==intent.current.lastAuthority){intent.current.lastAuthority=value;if(value===intent.current.target)intent.current.observed=true;}const wait=waiting.current;if(wait){if(value!==wait.target||wait.requestId&&(!authority||wait.queueBlocked))return;waiting.current=undefined;if(wait.requestId)window.dispatchEvent(new CustomEvent('workbench-operation-reconciled',{detail:{requestId:wait.requestId}}));}if(!focused.current&&!pending.current){shown.current=value;setDraft(String(value));}},[value,authority,waitingRevision]);
 useEffect(()=>{const reconcile=(event:Event)=>{const wait=waiting.current;if(!wait?.requestId||wait.requestId!==(event as CustomEvent).detail?.requestId)return;waiting.current=undefined;shown.current=latest.current;if(!focused.current)setDraft(String(latest.current));};window.addEventListener('workbench-operation-reconciled',reconcile);return()=>window.removeEventListener('workbench-operation-reconciled',reconcile);},[]);
 useEffect(()=>{const receipt=(event:Event)=>{const detail=(event as CustomEvent).detail,wait=waiting.current;if(!wait?.requestId||detail.uncertain||detail.requestId!==wait.requestId)return;queueMicrotask(()=>{if(waiting.current!==wait||generation.current!==wait.turn)return;const confirmed=wait.field?detail.result?.snapshot?.state?.stats?.[wait.field]:undefined;const next=detail.ok?(typeof confirmed==='number'?confirmed:wait.target):latest.current;waiting.current=detail.ok&&latest.current!==next?{turn:wait.turn,target:next}:undefined;shown.current=next;if(!focused.current)setDraft(String(next));});};window.addEventListener('workbench-operation-result',receipt);return()=>window.removeEventListener('workbench-operation-result',receipt);},[]);
 return <input className="stat-input" type="text" inputMode="text" autoFocus={autoFocus} aria-label={label} value={draft} disabled={disabled} onFocus={e=>{focused.current=true;cancel.current=false;e.currentTarget.select();}} onChange={e=>setDraft(e.target.value)} onBlur={()=>{focused.current=false;onFinish?.();const expression=draft.trim();if(cancel.current||!expression||expression===String(shown.current)){setDraft(String(shown.current));return;}const parsed=/^[+-]\d+$/.test(expression)?shown.current+Number(expression):Number(expression);if(Number.isFinite(parsed)){shown.current=parsed;setDraft(String(parsed));}const turn=++generation.current;intent.current={turn,target:shown.current,observed:false,lastAuthority:latest.current};pending.current++;void commit(expression).then(result=>{if(turn===generation.current)waiting.current=undefined;if(typeof result==='number'&&turn===generation.current&&!focused.current){const next=intent.current?.observed?latest.current:result;shown.current=next;setDraft(String(next));}}).catch(error=>{if(turn!==generation.current)return;if(error?.uncertain){const previous=waiting.current;waiting.current=error.queueBlocked&&previous&&previous.requestId===error.requestId?{...previous,turn}:{requestId:error.requestId,field:error.field||error.statField,turn,target:shown.current,queueBlocked:!!error.queueBlocked};setWaitingRevision(n=>n+1);return;}waiting.current=undefined;shown.current=latest.current;if(!focused.current)setDraft(String(latest.current));}).finally(()=>{
  pending.current--;
  // A fulfilled receipt may follow newer props, but unchanged props can also
  // predate the edit. Resync only when this intent was actually observed.
  if(!pending.current){if(intent.current?.turn===generation.current&&intent.current.observed&&!waiting.current)setWaitingRevision(n=>n+1);intent.current=undefined;}
 });}} onKeyDown={e=>{if(e.key==='Escape'){cancel.current=true;setDraft(String(shown.current));e.currentTarget.blur();}if(e.key==='Enter')e.currentTarget.blur();}}/>;
}
