import {useRef,useState,useEffect,useLayoutEffect,useContext,type PointerEvent} from 'react';
import {createPortal} from 'react-dom';
import {sameStock,type Stock,type StockContainer} from '../core/inventory';
import {type Entry} from '../core/model';
import {useWorkbench,requestInventory} from '../platform/workbench';
import {DropZone} from './DragEntry';
import {landingWithin,pointerDrag} from './pointerDrag';
import {ReferenceContext} from './Reference';
import {entryLabel} from '../core/entryLabel';
import './stockBoard.css';
import {CardIdentityContext,CardVisualContext} from './cardVisualState';
import {useCardGravity} from './useCardGravity';
import {StockFrameArt} from './StockFrameArt';
import {LockIcon} from './ResourceEditor';
import {reportWorkbenchError} from './CopyDiagnostic';
import {ItemTransferMenu} from './ItemTransferMenu';
export const inventoryRequest=requestInventory;
export function stockFromEntry(entry:Entry):Stock{return {id:crypto.randomUUID(),kind:entry.kind==='condition'?'condition':'item',entry,name:entry.name,quantity:1,slot:0,revision:1,unitWeight:Math.max(0,Number(entry.raw.weight)||0)};}
export function WorkbenchInventory({id,capacity}:{id:string;capacity?:React.ReactNode}){const wb=useWorkbench(),container=wb.inventory?.containers[id];if(wb.enabled.inventory===false)return null;if(!container)return <p>正在读取背包…</p>;return <StockBoard key={id} container={container} targets={Object.values(wb.inventory?.containers||{})} gm={wb.role==='GM'} disabled={!wb.online} operation={inventoryRequest} capacity={capacity}/>;}
export function StockBoard({container,targets=[],gm=false,disabled=false,operation,capacity}:{container:StockContainer;targets?:StockContainer[];gm?:boolean;disabled?:boolean;capacity?:React.ReactNode;operation:(op:Record<string,unknown>)=>Promise<unknown>}){
 const wb=useWorkbench();
 const recipientIds=new Set([...wb.cards,...wb.monsters].filter(card=>card.inScene&&(gm||card.write||!card.locked)).map(card=>card.kind==='monster'?`monster:${card.itemId}`:`card:${card.id}`));
 const recipients=targets.filter(target=>target.id!==container.id&&recipientIds.has(target.id));
 const [collapsed,setCollapsed]=useState(()=>{try{return container.kind==='public'&&localStorage.getItem('inventory-collapsed:'+container.id)==='true';}catch{return false;}});
 const toggleCollapsed=()=>setCollapsed(value=>{try{localStorage.setItem('inventory-collapsed:'+container.id,String(!value));}catch{}return !value;});
 const [view,setView]=useState<'grid'|'list'>(()=>{try{return container.kind!=='public'&&localStorage.getItem('inventory-view:'+container.id)==='list'?'list':'grid';}catch{return 'grid';}}),[selected,setSelected]=useState<string[]>([]),[menu,setMenu]=useState<{x:number;y:number;ids:string[]}>(),[quantity,setQuantity]=useState('1'),[editingQuantity,setEditingQuantity]=useState(''),[split,setSplit]=useState<{row:Stock;target?:string;slot?:number}>(),[marquee,setMarquee]=useState<{x:number;y:number;w:number;h:number}>();
 useEffect(()=>{if(!menu)return;const key=(e:KeyboardEvent)=>{if(e.key==='Escape')setMenu(undefined);};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key);},[!!menu]);
 const onPaper=!!useContext(CardIdentityContext),visuals=useContext(CardVisualContext),falling=onPaper&&visuals.active.has('incapacitated'),preview=useContext(ReferenceContext);
 const positions=useRef(new Map<string,{x:number;y:number}>()),grid=useRef<HTMLDivElement>(null),latest=useRef(container);latest.current=container;
 useEffect(()=>{try{localStorage.setItem('inventory-view:'+container.id,view);}catch{}},[container.id,view]);
 const selectionCleanup=useRef<()=>void>(undefined);useEffect(()=>()=>selectionCleanup.current?.(),[]);
 const canEdit=gm||(container.kind==='public'?!container.locked:container.write),allowed=(row:Stock|undefined)=>!!row&&!disabled&&canEdit&&(gm||!row.locked);
 const rows=container.items.filter(row=>row.kind!=='resource'&&(container.kind==='public'||row.kind!=='condition'));
 const columns=container.kind==='public'?4:container.columns,slots=Math.max(container.kind==='public'?20:24,Math.ceil((Math.max(-1,...rows.map(row=>row.slot))+1)/columns)*columns);
 useCardGravity(grid,falling,view,container.id,rows.map(row=>row.id+':'+row.slot).join('|'),4);
 const layoutKey=rows.map(row=>row.id+':'+row.slot).join('|');
 useLayoutEffect(()=>{const next=new Map<string,{x:number;y:number}>();for(const node of grid.current?.querySelectorAll<HTMLElement>('[data-stock-id]')||[]){const id=node.dataset.stockId!,after={x:node.offsetLeft,y:node.offsetTop},before=positions.current.get(id);next.set(id,after);if(before&&!falling&&!matchMedia('(prefers-reduced-motion: reduce)').matches){const x=before.x-after.x,y=before.y-after.y;if(Math.abs(x)>.8||Math.abs(y)>.8)node.animate([{transform:`translate(${x}px,${y}px)`},{transform:'none'}],{duration:220,easing:'cubic-bezier(.2,.8,.25,1)'});}}positions.current=next;},[layoutKey,view,falling]);

 const request=async(op:Record<string,unknown>)=>{try{return await operation({container:container.id,expected:{[container.id]:latest.current.revision},...op});}catch(e){reportWorkbenchError(e);throw e;}};
 const run=(op:Record<string,unknown>)=>void request(op).catch(()=>{});
 const add=(entry:Entry)=>run({action:'add',row:stockFromEntry(entry)});
 const transfer=(ids:string[],target:string,amount?:number,slot?:number)=>run({action:'transfer',from:container.id,to:target,slot,rows:ids.map(id=>({id,newId:crypto.randomUUID(),quantity:amount??(latest.current.items.find(row=>row.id===id)?.quantity||0)}))});
 function beginSplit(row:Stock,target?:string,slot?:number){setQuantity(String(Math.max(1,Math.floor(row.quantity/2))));setSplit({row,target,slot});}
 function drag(event:PointerEvent,row:Stock){if(!allowed(row)||event.target instanceof Element&&event.target.closest('input'))return;const ids=selected.includes(row.id)?selected:[row.id],splitting=event.shiftKey&&ids.length===1&&row.quantity>1;setSelected(ids);let marked:Element|null=null;
  const clear=()=>{marked?.classList.remove('inventory-drop-over');marked=null;document.querySelectorAll('.inventory-transfer-ready').forEach(el=>el.classList.remove('inventory-transfer-ready'));};
  pointerDrag(event,{appearance:'source',title:row.name,start:()=>{document.querySelectorAll('[data-inventory-container],[data-inventory-recipient],[data-stock-mark]').forEach(el=>el.classList.add('inventory-transfer-ready'));},cancel:clear,move:(_,hit)=>{const next=hit?.closest('[data-stock-mark],[data-stock-slot],[data-inventory-container],[data-inventory-recipient]')||null;if(next!==marked){marked?.classList.remove('inventory-drop-over');marked=next;marked?.classList.add('inventory-drop-over');}},finish:(_,hit)=>{clear();const mark=hit?.closest<HTMLElement>('[data-stock-mark]');if(mark){if(mark.dataset.stockOwner===container.id&&canEdit&&row.kind!=='resource')run({action:'update',id:row.id,patch:{[mark.dataset.stockMark!]:true}});return {morph:'chip',region:mark,resolve:()=>mark.querySelector<HTMLElement>(`[data-stock-ref-id="${CSS.escape(row.id)}"]`)};}
   const target=hit?.closest<HTMLElement>('[data-inventory-container],[data-inventory-recipient]'),to=target?.dataset.inventoryContainer||target?.dataset.inventoryRecipient;if(!to)return;
   const slotElement=hit?.closest<HTMLElement>('[data-stock-slot]'),slot=slotElement?Number(slotElement.dataset.stockSlot):undefined;
   if(splitting){beginSplit(row,to,slot);return;}
   if(to!==container.id){transfer(ids,to,undefined,slot);return landingWithin(target!,()=>target?.querySelector<HTMLElement>(`[data-entry-id="${CSS.escape(row.entry?.id||'')}"]`)||(!target?.matches('[data-inventory-recipient]')?target?.querySelector<HTMLElement>('.stock-empty'):null)||null);}
   if(!canEdit||slot===undefined||!Number.isInteger(slot))return;
   const selectedRows=ids.map(id=>latest.current.items.find(v=>v.id===id));if(selectedRows.some(v=>!v)){reportWorkbenchError(Error('物品已被转移，请按当前背包继续操作'));return;}
   const start=selectedRows[0]!.slot,moves=selectedRows.map(item=>({id:item!.id,slot:slot+item!.slot-start}));if(moves.some(p=>p.slot<0))return;const taken=latest.current.items.filter(item=>!ids.includes(item.id)&&moves.some(p=>p.slot===item.slot));if(ids.length===1&&taken.length===1&&sameStock(selectedRows[0]!,taken[0])){run({action:'merge',id:row.id,targetId:taken[0].id});return {resolve:()=>grid.current?.querySelector<HTMLElement>(`[data-stock-id="${CSS.escape(taken[0].id)}"]`)||null};}if(ids.length===1&&taken.length===1)moves.push({id:taken[0].id,slot:start});const changed=moves.filter(p=>latest.current.items.find(item=>item.id===p.id)?.slot!==p.slot);if(changed.length)run({action:'move',positions:changed,observedSlots:Object.fromEntries(changed.map(p=>[p.id,latest.current.items.find(item=>item.id===p.id)!.slot]))});return {resolve:()=>grid.current?.querySelector<HTMLElement>(`[data-stock-id="${CSS.escape(row.id)}"]`)||null};}});
 }
 function boxSelect(event:PointerEvent){if(event.button!==0||event.target instanceof Element&&event.target.closest('[data-stock-id],button,input'))return;selectionCleanup.current?.();const origin={x:event.clientX,y:event.clientY},base=event.ctrlKey?selected:[];event.preventDefault();const move=(e:globalThis.PointerEvent)=>{const bounds={x:Math.min(origin.x,e.clientX),y:Math.min(origin.y,e.clientY),w:Math.abs(e.clientX-origin.x),h:Math.abs(e.clientY-origin.y)};setMarquee(bounds);const ids=[...grid.current?.querySelectorAll<HTMLElement>('[data-stock-id]')||[]].filter(el=>{const r=el.getBoundingClientRect();return r.right>=bounds.x&&r.left<=bounds.x+bounds.w&&r.bottom>=bounds.y&&r.top<=bounds.y+bounds.h;}).map(el=>el.dataset.stockId!);setSelected([...new Set([...base,...ids])]);};const end=()=>{setMarquee(undefined);document.removeEventListener('pointermove',move);document.removeEventListener('pointerup',end);document.removeEventListener('pointercancel',end);window.removeEventListener('blur',end);selectionCleanup.current=undefined;};selectionCleanup.current=end;window.addEventListener('blur',end);document.addEventListener('pointermove',move);document.addEventListener('pointerup',end,{once:true});document.addEventListener('pointercancel',end,{once:true});}
 const weight=rows.reduce((sum,row)=>sum+(row.kind==='currency'?.02:row.unitWeight||0)*row.quantity,0);
 const price=(row:Stock)=>{if(row.kind==='currency')return `${({cp:.01,sp:.1,ep:.5,gp:1,pp:10} as Record<string,number>)[row.coin!]*row.quantity} GP`;const value=row.entry?.raw.value;return typeof value==='number'?`${Number((value*row.quantity/100).toFixed(2))} GP`:typeof value==='string'?value:'—';};
 function tile(row:Stock){return <article key={row.id} data-entry-context-menu data-wiki-preview data-entry-id={row.entry?.id} data-physical-frame={onPaper?'stock':undefined} data-stock-id={row.id} data-stock-slot={row.slot} className={`stock-item ${selected.includes(row.id)?'selected':''} ${row.equipped?'stock-equipped':''} ${row.attuned?'stock-attuned':''} stock-${row.kind}`} onPointerDown={e=>drag(e,row)} onMouseEnter={e=>{if(row.entry)preview?.show(e.currentTarget,`entry:${row.entry.id}`,undefined,{x:e.clientX,y:e.clientY},row.entry);}} onMouseLeave={()=>preview?.leave()} onClick={e=>{if(e.target instanceof Element&&e.target.closest('input,button'))return;if(e.altKey&&allowed(row)&&row.quantity>1){beginSplit(row);return;}if(row.entry&&!e.ctrlKey)preview?.commit?.(e.currentTarget,`entry:${row.entry.id}`,undefined,row.entry);setSelected(e.ctrlKey||e.metaKey?selected.includes(row.id)?selected.filter(id=>id!==row.id):[...selected,row.id]:[row.id]);}} onContextMenu={e=>{e.preventDefault();const ids=selected.includes(row.id)?selected:[row.id];setSelected(ids);setQuantity(String(row.quantity));setMenu({x:Math.max(6,Math.min(innerWidth-245,e.clientX)),y:Math.max(6,Math.min(innerHeight-250,e.clientY)),ids});}}>
  <strong className="stock-name">{row.entry?entryLabel(row.entry):row.name}{row.locked&&<span title="仅 DM 可以修改"> ▣</span>}</strong>
  {editingQuantity===row.id?<input className="stock-quantity-input" aria-label={`${row.name}数量`} autoFocus value={quantity} onFocus={e=>e.currentTarget.select()} onChange={e=>setQuantity(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();if(e.key==='Escape'){setEditingQuantity('');}}} onBlur={()=>{setEditingQuantity('');const n=/^[+-]/.test(quantity)?row.quantity+Number(quantity):Number(quantity);if(quantity.trim()&&Number.isSafeInteger(n)&&n>=0&&n!==row.quantity)run({action:'update',id:row.id,patch:{quantity:n}});}}/>:<button className="stock-quantity" aria-label={`${row.name}数量`} disabled={!allowed(row)} onClick={()=>{setQuantity(String(row.quantity));setEditingQuantity(row.id);}}>x{row.quantity}</button>}
  <small className="stock-value">{price(row)}</small><small className="stock-weight">{Number(((row.kind==='currency'?.02:row.unitWeight||0)*row.quantity).toFixed(2))} 磅</small><StockFrameArt/></article>;}
 return <section className={`stock-board ${container.kind==='public'?'public-stock':''} ${collapsed?'stock-collapsed':''}`} data-physical-frame={onPaper?'inventory':undefined} data-inventory-container={container.id}><header role={container.kind==='public'?'button':undefined} tabIndex={container.kind==='public'?0:undefined} aria-label={container.kind==='public'?`${collapsed?'展开':'折叠'}公共仓库`:undefined} aria-expanded={container.kind==='public'?!collapsed:undefined} onClick={container.kind==='public'?toggleCollapsed:undefined} onKeyDown={event=>{if(event.target===event.currentTarget&&container.kind==='public'&&(event.key==='Enter'||event.key===' ')){event.preventDefault();toggleCollapsed();}}}>{container.kind==='public'&&<span className="warehouse-toggle" aria-hidden="true">{collapsed?'▸':'▾'}</span>}<h3>{container.name}{container.kind==='public'?'':' · 背包'}</h3>{container.kind!=='public'&&<div className="segmented"><button aria-pressed={view==='grid'} onClick={()=>setView('grid')}>网格</button><button aria-pressed={view==='list'} onClick={()=>setView('list')}>列表</button></div>}<small>负重 {weight.toLocaleString(undefined,{maximumFractionDigits:2})}{capacity?<> / {capacity}</>:null} 磅</small>{container.kind==='public'&&<button className="warehouse-lock" aria-label={container.locked?'解锁公共仓库':'上锁公共仓库'} aria-pressed={!!container.locked} disabled={!gm||disabled} onClick={event=>{event.stopPropagation();run({action:'containerLock',locked:!container.locked});}}><LockIcon locked={!!container.locked}/></button>}</header>
 {!collapsed&&<DropZone className="stock-drop-zone" kinds={container.kind==='public'?['item','condition']:['item']} allowExisting accepts={entry=>(canEdit||gm)&&(entry.kind==='item'||container.kind==='public'&&entry.kind==='condition')} onReceive={add}><div ref={grid} className={`stock-collection stock-${container.kind==='public'?'grid':view}`} style={{'--stock-columns':columns} as React.CSSProperties} onPointerDown={boxSelect}>{view==='grid'||container.kind==='public'?Array.from({length:slots},(_,slot)=>{const row=rows.find(row=>row.slot===slot);return row?tile(row):<div key={`empty-${slot}`} className="stock-empty" data-physical-frame={onPaper?'stock':undefined} data-stock-slot={slot}><StockFrameArt/></div>;}):[...rows].sort((a,b)=>a.slot-b.slot).map(tile)}</div></DropZone>}
 {marquee&&createPortal(<div className="stock-marquee" style={{left:marquee.x,top:marquee.y,width:marquee.w,height:marquee.h}}/>,document.body)}
 {split&&createPortal(<div className="stock-menu-shade" onPointerDown={e=>{if(e.target===e.currentTarget)setSplit(undefined);}}><form className="stock-split-dialog" onSubmit={e=>{e.preventDefault();const n=Number(quantity);if(!Number.isInteger(n)||n<1||n>=split.row.quantity)return;if(split.target&&split.target!==container.id)transfer([split.row.id],split.target,n,split.slot);else run({action:'split',id:split.row.id,quantity:n,newId:crypto.randomUUID(),slot:split.slot});setSplit(undefined);}}><strong>拆分 {split.row.name}</strong><label>数量<input aria-label="拆分数量" autoFocus type="number" min="1" max={split.row.quantity-1} value={quantity} onChange={e=>setQuantity(e.target.value)}/></label><div><button type="submit">确认</button><button type="button" onClick={()=>setSplit(undefined)}>取消</button></div></form></div>,document.body)}
 {menu&&createPortal(<div className="stock-menu-shade" onPointerDown={e=>{if(e.target===e.currentTarget){e.preventDefault();setMenu(undefined);}}}><div role="menu" className="stock-menu" style={{left:menu.x,top:menu.y}}><strong>{menu.ids.length} 项已选择</strong>{menu.ids.length===1&&<label>转移数量<input aria-label="转移数量" type="number" min="1" value={quantity} onChange={e=>setQuantity(e.target.value)}/></label>}<ItemTransferMenu targets={recipients} disabled={menu.ids.some(id=>!allowed(container.items.find(row=>row.id===id)))} transfer={target=>{transfer(menu.ids,target,menu.ids.length===1?Number(quantity):undefined);setMenu(undefined);}}/>{targets.filter(t=>t.kind==='public'&&t.id!==container.id).map(target=><button role="menuitem" key={target.id} disabled={menu.ids.some(id=>!allowed(container.items.find(row=>row.id===id)))||!gm&&!!target.locked} onClick={()=>{transfer(menu.ids,target.id,menu.ids.length===1?Number(quantity):undefined);setMenu(undefined);}}>放入公共仓库</button>)}{menu.ids.length===1&&['item','condition'].includes(container.items.find(r=>r.id===menu.ids[0])?.kind||'')&&<button role="menuitem" disabled={!allowed(container.items.find(r=>r.id===menu.ids[0]))||(container.items.find(r=>r.id===menu.ids[0])?.quantity||0)<2} onClick={()=>{beginSplit(container.items.find(r=>r.id===menu.ids[0])!);setMenu(undefined);}}>拆分 · Shift 拖拽 / Alt 点击</button>}{gm&&container.kind==='public'&&menu.ids.length===1&&<button role="menuitem" onClick={()=>{const row=container.items.find(row=>row.id===menu.ids[0])!;run({action:'update',id:row.id,patch:{locked:!row.locked}});setMenu(undefined);}}>{container.items.find(row=>row.id===menu.ids[0])?.locked?'解锁':'上锁'}</button>}{canEdit&&menu.ids.every(id=>allowed(container.items.find(row=>row.id===id))&&container.items.find(row=>row.id===id)?.kind!=='currency')&&<button role="menuitem" onClick={()=>{run({action:'remove',ids:menu.ids});setMenu(undefined);}}>移除</button>}</div></div>,document.body)}<StockFrameArt/></section>;
}
