import {useState} from 'react';
import type {Character} from '../core/model';
import {evaluate} from '../core/engine';
import {exportCharacter,exportCharacters,exportReview} from '../core/export';
import {download,downloadBlob} from '../platform/storage';
import {pngArchive,safeFileName,sheetPdf} from '../platform/exportFiles';
import type {SheetCaptureOptions} from '../platform/sheetImage';
import type {SheetPage} from './PaperFrame';
import type {CharacterRow} from './CharacterManager';

export function TransferPanel({rows,currentId,currentName,currentPage,read,importTexts,capture,disabled,formatSource}:{rows:CharacterRow[];currentId:string;currentName:string;currentPage:SheetPage;read:(ids:string[])=>Promise<Character[]>;importTexts:(texts:string[])=>Promise<void>;capture:(pages:SheetPage[],options:SheetCaptureOptions)=>Promise<{page:SheetPage;blob:Blob}[]>;disabled:boolean;formatSource:(id:string)=>string}){
 const [target,setTarget]=useState(()=>rows.some(row=>row.id===currentId)?currentId:rows[0]?.id||'all'),[text,setText]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[status,setStatus]=useState(''),[pages,setPages]=useState<SheetPage[]>(['主要','特性','背景','法术','背包']),[options,setOptions]=useState<SheetCaptureOptions>({});
 const act=async(fn:()=>Promise<void>)=>{setBusy(true);setError('');setStatus('');try{await fn();}catch(e){setError(String(e));}finally{setBusy(false);}};
 const value=async()=>{const cards=await read(target==='all'?rows.map(r=>r.id):[target]);return cards.length===1?exportCharacter(cards[0]):exportCharacters(cards);};
 return <div className="transfer-panel">{error&&<p className="inline-error" role="alert">{error}</p>}{status&&<p role="status">{status}</p>}
 <section className="settings-section"><h3>角色 JSON · 文件与剪贴板</h3><div className="dialog-actions"><label>导出角色<select aria-label="导出角色" value={target} onChange={e=>setTarget(e.target.value)}>{rows.map(r=><option key={r.id} value={r.id}>{r.name}</option>)}<option value="all">全部可见角色</option></select></label><span>完整 JSON 备份 · 网站与枭熊通用</span><button disabled={busy} onClick={()=>void act(async()=>download(`${safeFileName(rows.find(r=>r.id===target)?.name||'角色集合')}.json`,await value()))}>下载 JSON</button><button disabled={busy} onClick={()=>void act(async()=>{const json=JSON.stringify(await value(),null,2);setText(json);try{await navigator.clipboard.writeText(json);setStatus('已生成并复制 JSON');}catch{setStatus('JSON 已生成，请在文本框中全选复制');}})}>生成并复制 JSON</button></div>
 <textarea aria-label="角色 JSON 文本" value={text} onChange={e=>setText(e.target.value)} spellCheck={false}/><div className="dialog-actions"><button disabled={busy} onClick={()=>void act(async()=>setText(await navigator.clipboard.readText()))}>从剪贴板粘贴</button><button disabled={disabled||busy||!text.trim()} onClick={()=>void act(()=>importTexts([text]))}>校验并导入 JSON 文本</button><label className="button-label">批量导入 JSON 文件<input aria-label="批量导入角色文件" type="file" multiple accept=".json,application/json" disabled={disabled||busy} onChange={e=>{const files=[...(e.target.files||[])];e.target.value='';if(files.length)void act(async()=>{if(files.some(f=>f.size>20_000_000))throw Error('单个文件不能超过 20 MB');await importTexts(await Promise.all(files.map(f=>f.text())));});}}/></label></div><p className="muted">导入为新副本。先校验全部文件，再核对版本和禁用来源；网站和枭熊共用完整备份，保留条目身份与选择；旧枭熊 JSON 也可直接导入。</p></section>
 <section className="settings-section"><h3>当前卡 · {currentName} · PNG / PDF</h3><div className="dialog-actions">{(['主要','特性','背景','法术','背包'] as SheetPage[]).map(page=><label key={page}><input type="checkbox" checked={pages.includes(page)} onChange={e=>setPages(e.target.checked?[...pages,page]:pages.filter(p=>p!==page))}/>{page}</label>)}<button onClick={()=>setPages([currentPage])}>仅当前页</button><button onClick={()=>setPages(['主要','特性','背景','法术','背包'])}>全部五页</button></div><div className="export-display-options">{([['hidePortraits','隐藏头像与立绘'],['hideNotes','隐藏人物背景文字'],['hideConditions','隐藏状态与特效'],['hideResources','隐藏资源栏'],['collapseFeatures','合拢特性正文']] as const).map(([key,label])=><label key={key}><input type="checkbox" checked={!!options[key]} onChange={e=>setOptions({...options,[key]:e.target.checked})}/>{label}</label>)}</div><div className="dialog-actions"><button disabled={busy||!pages.length} onClick={()=>void act(async()=>{const files=await capture(pages,options);if(files.length===1)downloadBlob(`${safeFileName(currentName)}-${files[0].page}.png`,files[0].blob);else downloadBlob(`${safeFileName(currentName)}-PNG.zip`,await pngArchive(files.map(f=>({name:`${f.page}.png`,blob:f.blob}))));setStatus(`已导出 ${files.length} 页 PNG`);})}>{busy?'正在生成…':'导出 PNG'}</button><button disabled={busy||!pages.length} onClick={()=>void act(async()=>{const files=await capture(pages,options);downloadBlob(`${safeFileName(currentName)}.pdf`,await sheetPdf(files.map(f=>f.blob)));setStatus(`已导出 ${files.length} 页 A4 PDF`);})}>下载 PDF</button></div><p className="muted">显示选项仅用于导出；生成后恢复原页。长正文可另用下方完整审卡文档打印，避免 A4 格内截断。</p></section>
 <section className="settings-section"><h3>完整审卡文档</h3><button disabled={busy||target==='all'} onClick={()=>void act(async()=>{const [card]=await read([target]);download(`${safeFileName(card.name)}-审卡.html`,exportReview(card,evaluate(card),formatSource),'text/html');})}>下载审卡 HTML / 打印为 PDF</button></section></div>;
}
