import type {Entry} from '../core/model';
import {entryLabel} from '../core/entryLabel';
export type UiLanguage='zh'|'en';
export const UI_LANGUAGE_KEY='dnd-card:ui-language';
const zh={
 fullscreen:'卡片全屏',exitFullscreen:'退出卡片全屏',
 language:'语言',cardBrand:'DND 角色卡',card:'角色卡',threeDragon:'三龙牌',featuresToggle:'功能开关',settings:'设置',announcements:'公告',characters:'角色簿',rules:'规则与扩展',transfer:'导入 / 导出',workspace:'工作区',functionalPage:'功能页',cardWorkspace:'角色卡工作区',currentCharacter:'当前角色',automationSettings:'自动化设置',automation:'自动化',on:'开启',manual:'手动',syncReview:'同步核对',entriesLevels:'条目 / 等级',adjust:'修正',adjustDetails:'数值依据与人工修正',undo:'撤销',redo:'重做',fitWindow:'A4 · 适应窗口',editMode:'编辑模式',room:'房间',cardTitle:'DND 五版角色卡',cardFooter:'{edition} · {level} 级 · 修订 {revision}',snapshotSaved:'资料快照随角色保存',sheetPages:'角色卡页面',pageMain:'主要',pageFeatures:'特性',pageBackground:'背景',pageSpells:'法术',pageInventory:'背包',resetZoom:'还原角色卡缩放',reset:'还原',
 feedbackTitle:'问题反馈',feedbackHelp:'请提供使用版本、复现步骤和截图。',
 readerMissing:'未提供角色 JSON。请从角色卡列表重新打开。',readerJsonOnly:'此阅读器只接受角色 JSON。请在角色卡网站制卡后导入 JSON。',readerHttp:'角色读取失败（HTTP {status}），请重试。',readerLarge:'角色文件超过 20 MB。',readerLoading:'正在读取角色资料…',retry:'重试',goToSite:'前往角色卡网站',readOnly:'只读角色卡',refreshData:'刷新资料',createOnSite:'前往网站制卡',entryDetails:'角色条目正文',closeEntry:'关闭角色条目',
 welcomeSite:'欢迎使用这款开源禁商用车卡/Wiki网站！',welcomeSuite:'欢迎使用 Full Suite 枭熊工作台！',version:'版本 v{version}',rememberVersion:'下次版本更新之前不再弹出',gotIt:'我知道了',faq:'以下是可能用到的Q&A',chineseOriginal:'中文原文',
 ownerTitle:'关于设置玩家单独权限的重要说明',ownerIntro:'由 DM 完成下面两步，每位玩家就能操作自己的角色。DM 仍可管理所有角色。',ownerStep1:'打开 Players 面板，点击盾牌权限按钮，展开 Map → Character，勾选 Owner Only，再点击 SAVE。',ownerImage1:'Players 面板中的盾牌权限按钮',ownerImage2:'Map 的 Character 权限勾选 Owner Only 后保存',ownerStep2:'在地图上选中角色 Token，点击悬浮工具栏的人形 Set Owner，指定所属玩家。',ownerImage3:'选择角色棋子后通过 Set Owner 指定所属玩家',ownerFinish:'设置后玩家可以掷自己的先攻、修改加值并结束自己的回合。未指定所属玩家时，玩家可能无法修改角色。',assignCard:'分配角色卡：DM 打开角色卡，点击工具栏“分配玩家”。玩家姓名只是卡内文字，不会自动授予权限。',independentSite:'进入独立车卡网站',
 faqEditionQ:'可以车20145e/20245r的卡吗？',faqEditionA:'可以的，在右上角规则与扩展中切换',faqSourcesQ:'所有扩展都有吗？第三方也有吗？',faqSourcesA:'都有啊都有，目前数据来源是来自5etool网站，kiwee老师那边有什么我这边就有什么（他们那边翻译有问题我这边翻译也会同样有问题x）',faqSourceControlQ:'可以单独设置某扩展吗？',faqSourceControlA:'当然可以！你可以在右上角规则与扩展中单独选择开启和禁用某扩展/禁用某扩展的特定内容（比如，打开玩家手册2014，在种族中找到矮人，选择取消勾选）',faqAutomationQ:'我填了xxx，我的数据怎么没反应？',faqAutomationA:'新建、导入和旧角色默认开启自动化，无需手动开启。护甲、盾牌、已装备武器和来源赠送法术等已适配规则会参与计算；未支持的规则仍需手动处理。可在工具栏“自动化”中查看依据或主动关闭。',
 releaseAutomation:'基础自动化',releaseAutomation1:'增加了基础自动化，可以在角色卡工具栏中开启。',releaseAutomation2:'装备护甲和盾牌后，现在可以自动计算 AC。',releaseAutomation3:'装备武器后，现在可以生成对应的快捷攻击。',releaseAutomation4:'支持部分特性和种族的赠送法术、免费次数与法术位消耗。',releaseSpells:'法术列表',releaseSpells1:'优化了预备法术和已知法术列表，戏法与赠送法术分组显示。',releaseSpells2:'点击已知法术可以选中打勾，再次点击取消；预备区显示对应法术。',releaseSpells3:'修复了同名赠送法术阻挡普通预备的问题。',releaseSpells4:'恢复了法术格原有样式、专注和仪式效果。',releasePending:'待验证',releasePending1:'实体手机操作待验证；复杂兼职、动态次数和完整休息规则尚未全部支持。',releaseSuite:'枭熊联动',releaseSuite1:'基础自动化的真实多人同步待验证。',releaseInvestigating:'仍在排查',releaseInvestigating1:'卡上已移除但棋子状态残留、保存结果未确认的问题仍在排查。',
} as const;
export type UiTextKey=keyof typeof zh;
const en:Record<UiTextKey,string>={
 fullscreen:'Fullscreen sheet',exitFullscreen:'Exit fullscreen sheet',
 language:'Language',cardBrand:'DND Character Sheet',card:'Character sheet',threeDragon:'Three-Dragon Ante',featuresToggle:'Feature toggles',settings:'Settings',announcements:'Announcements',characters:'Characters',rules:'Rules & expansions',transfer:'Import / Export',workspace:'Workspace',functionalPage:'Tools',cardWorkspace:'Character workspace',currentCharacter:'Current character',automationSettings:'Automation settings',automation:'Automation',on:'On',manual:'Manual',syncReview:'Review sync',entriesLevels:'Entries / levels',adjust:'Adjust',adjustDetails:'Calculation details & manual adjustments',undo:'Undo',redo:'Redo',fitWindow:'A4 · Fit to window',editMode:'Edit mode',room:'Room',cardTitle:'DND 5e Character Sheet',cardFooter:'{edition} · Level {level} · Revision {revision}',snapshotSaved:'Source snapshots are saved with the character',sheetPages:'Character pages',pageMain:'Main',pageFeatures:'Features',pageBackground:'Background',pageSpells:'Spells',pageInventory:'Inventory',resetZoom:'Reset character zoom',reset:'Reset',
 feedbackTitle:'Report a problem',feedbackHelp:'Please include the version, steps to reproduce, and screenshots.',
 readerMissing:'No character JSON was provided. Please reopen the character from the list.',readerJsonOnly:'This reader accepts character JSON only. Create a character on the website, then import its JSON.',readerHttp:'Could not load the character (HTTP {status}). Please retry.',readerLarge:'The character file exceeds 20 MB.',readerLoading:'Loading character data…',retry:'Retry',goToSite:'Open character website',readOnly:'Read-only character',refreshData:'Refresh data',createOnSite:'Create on website',entryDetails:'Character entry details',closeEntry:'Close character entry',
 welcomeSite:'Welcome to this open-source character sheet and Wiki! Commercial use is prohibited.',welcomeSuite:'Welcome to the Full Suite Owlbear workbench!',version:'Version v{version}',rememberVersion:'Do not show again until the next version update',gotIt:'Got it',faq:'Questions & answers',chineseOriginal:'Chinese original',
 ownerTitle:'Player permissions: two important steps',ownerIntro:'The DM completes these steps so each player can operate their own character. The DM can still manage all characters.',ownerStep1:'Open Players, click the shield permissions button, expand Map → Character, enable Owner Only, then click SAVE.',ownerImage1:'Shield permissions button in Players',ownerImage2:'Enable Owner Only under Map → Character and save',ownerStep2:'Select the character token on the map, click Set Owner on the floating toolbar, and assign its player.',ownerImage3:'Select a character token and assign its player with Set Owner',ownerFinish:'Players can then roll their initiative, edit bonuses, and end their turns. Unassigned tokens may prevent players from editing their characters.',assignCard:'Assign a character: the DM opens the sheet and chooses Assign player. A name written in the player field does not grant permission.',independentSite:'Open the independent character website',
 faqEditionQ:'Can I create 2014 and 2024 characters?',faqEditionA:'Yes. Switch editions in Rules & expansions at the top right.',faqSourcesQ:'Are expansions and third-party sources available?',faqSourcesA:'Available data follows the 5etools material on Kiwee’s mirror, including its translations and any translation errors.',faqSourceControlQ:'Can I enable individual expansions?',faqSourceControlA:'Yes. Rules & expansions lets you enable or disable sources and individual entries within them.',faqAutomationQ:'Why did adding an entry not change my statistics?',faqAutomationA:'Automation starts enabled for new, imported, and existing characters. Supported rules for armor, shields, equipped weapons, and source-granted spells are calculated automatically. Unsupported rules still require manual handling. Use Automation on the toolbar to inspect calculations or turn it off.',
 releaseAutomation:'Basic automation',releaseAutomation1:'Basic automation can be enabled on the character toolbar.',releaseAutomation2:'Equipped armor and shields can now calculate AC.',releaseAutomation3:'Equipped weapons can now generate quick attacks.',releaseAutomation4:'Some feature and ancestry spell grants support free uses and spell-slot spending.',releaseSpells:'Spell lists',releaseSpells1:'Prepared and known spell lists now group cantrips and granted spells.',releaseSpells2:'Click a known spell to select it; click again to deselect. Its copy appears in the prepared area.',releaseSpells3:'Fixed a granted spell with the same name blocking ordinary preparation.',releaseSpells4:'Restored the spell-cell style and concentration and ritual indicators.',releasePending:'Pending verification',releasePending1:'Physical phones remain unverified. Complex multiclassing, dynamic uses, and full rest rules are not fully supported.',releaseSuite:'Owlbear integration',releaseSuite1:'Real multiplayer synchronization of basic automation remains unverified.',releaseInvestigating:'Under investigation',releaseInvestigating1:'Removed conditions remaining on tokens and unconfirmed saves are still under investigation.',
};
export function uiText(language:UiLanguage,key:UiTextKey,values:Record<string,string|number>={}):string{return (language==='en'?en:zh)[key].replace(/\{(\w+)\}/g,(token,name)=>values[name]===undefined?token:String(values[name]));}
export function readUiLanguage(storage?:Pick<Storage,'getItem'>):UiLanguage{try{return (storage??localStorage).getItem(UI_LANGUAGE_KEY)==='en'?'en':'zh';}catch{return 'zh';}}
export function writeUiLanguage(language:UiLanguage,storage?:Pick<Storage,'setItem'>):void{try{(storage??localStorage).setItem(UI_LANGUAGE_KEY,language);}catch{/* The current session still keeps its chosen display language. */}}
export function uiEntryName(entry:Entry,language:UiLanguage):string{return language==='en'&&entry.english?.trim()?entry.english:entry.name;}
export function uiEntryLabel(entry:Entry,language:UiLanguage):string{return entryLabel({...entry,name:uiEntryName(entry,language)});}
