import { ABILITIES, SKILLS, selectionAllowed, type Character, type Derived } from './model';
export const exportCharacter = (c: Character) => ({ format: 'dnd-card-web', version: 1, exportedAt: new Date().toISOString(), character: c });
export function exportOwlbear(c: Character, d: Derived) {
  const active = c.selections.filter(s => selectionAllowed(c, s.entry));
  const entryName = (kind: string) => active.find(s => s.entry.kind === kind)?.entry.name || null;
  const features = (kinds: string[]) => active.filter(s => kinds.includes(s.entry.kind)).map(s => ({ name: s.entry.name, source: s.entry.source, description: plainText(s.entry.entries), level: s.entry.raw.level || null }));
  const spells = active.filter(s => s.entry.kind === 'spell').map(s => ({ name: s.entry.name, level: s.entry.raw.level || 0, source: s.entry.source, description: plainText(s.entry.entries), meta: { source: s.entry.source } }));
  const ability = active.find(s => s.entry.kind === 'class' && s.entry.raw.spellcastingAbility)?.entry.raw.spellcastingAbility;
  const spellMod = d.modifiers[ability as keyof typeof d.modifiers];
  return { schema_version: '0.3', meta: { template_name: 'DND Card Web', template_version: '0.1.0', layout_version: 'web-1', ruleset: c.edition, source_file: `${c.name}.json`, parsed_at: new Date().toISOString() },
    identity: { character_name: c.name, display_name: c.name, player: c.player, race: { name: entryName('race'), subrace: null }, background: entryName('background'), alignment: c.identity.alignment || null, gender: c.identity.gender || null, age: c.identity.age || null, languages: [], tool_proficiencies: [] },
    classes: active.filter(s => s.entry.kind === 'class').map((s, i) => ({ role: i === 0 ? '主职' : `兼职${i}`, name: s.entry.name, subclass: active.find(sc => sc.entry.kind === 'subclass' && sc.entry.raw.className === s.entry.name)?.entry.name || null, level: s.level })), total_level: d.level,
    abilities: Object.fromEntries(ABILITIES.map(a => [a, { total: d.abilities[a], initial: c.abilities[a], background: 0, growth: 0, misc: d.abilities[a] - c.abilities[a], modifier: d.modifiers[a], save: { proficient: d.saves[a].proficient, bonus: d.saves[a].value, misc: 0 } }])),
    core_stats: { ac: d.ac, initiative: d.initiative, speed: d.speed, proficiency_bonus: d.proficiency, passive_perception: d.passive, dc: Number.isFinite(spellMod) ? 8 + spellMod + d.proficiency : null, dc_ability: ability || null, hp: { current: c.runtime.hp, max: d.maxHp, temp: c.runtime.tempHp }, hit_dice: { current: d.level, max: d.level, die_size: active.filter(s => s.entry.kind === 'class').length === 1 ? active.find(s => s.entry.kind === 'class')!.entry.raw.hd?.faces || null : null }, inspiration: c.runtime.inspiration },
    skills: Object.entries(d.skills).map(([key, s]) => ({ name: SKILLS[key].name, ability: SKILLS[key].ability, total: s.value, proficiency: s.proficient ? 'proficient' : 'none', misc_bonus: s.value - d.modifiers[SKILLS[key].ability] - (s.proficient ? d.proficiency : 0) })),
    defenses: { resistances: [], immunities: [], advantages: [], disadvantages: [] },
    combat: { armor: null, shield: null, weapons: [] },
    features: { class_features: features(['feature', 'subclass']), race_features: features(['race']), feats: features(['feat']), fighting_style_feats: [], special_abilities: [] },
    inventory: { items: active.filter(s => s.entry.kind === 'item').map(s => ({ name: s.entry.name, quantity: s.quantity, equipped: s.equipped, weight: s.entry.raw.weight || 0, description: plainText(s.entry.entries) })), wondrous_items: [], consumables: [], containers: [] },
    spellcasting: { spellcasting_ability: ability || null, save_dc: Number.isFinite(spellMod) ? 8 + spellMod + d.proficiency : null, attack_bonus: Number.isFinite(spellMod) ? spellMod + d.proficiency : null, spell_slots: {}, cantrips_known: spells.filter(s => s.level === 0), prepared: spells.filter(s => s.level > 0), always_known: [] },
    background: { background_name: entryName('background'), appearance: c.identity.description, story: c.notes, description: plainText(active.find(s => s.entry.kind === 'background')?.entry.entries) },
    web_resources: c.runtime.resources,
    export_warnings: ['填写要求、选择历史和自定义规则包请保留在原生角色备份中。法术暂放入已准备列表；法术位、武器攻击、抗性和复杂特性需在枭熊中核对。', ...d.requirements.filter(r => !r.complete).map(r => `未完成：${r.label}（${r.origin}）`), ...d.issues.map(i => i.message), ...(c.adjustments || []).map(a => `人工修正 ${a.target}=${a.value}：${a.reason}`)] };
}
export function plainText(value: unknown): string {
  if (typeof value === 'string') return value.replace(/\{@\w+\s+([^{}]+)\}/g, (_, body: string) => body.split('|')[2] || body.split('|')[0]);
  if (Array.isArray(value)) return value.map(plainText).filter(Boolean).join('\n');
  if (value && typeof value === 'object') { const v = value as Record<string, unknown>; return [v.name, v.entries, v.entry, v.items, v.rows].map(plainText).filter(Boolean).join('\n'); }
  return '';
}
const esc = (text: unknown) => String(text ?? '').replace(/[&<>"']/g, ch => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[ch]!));
export function exportReview(c: Character, d: Derived): string {
  const pending = d.requirements.filter(r => !r.complete);
  return `<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(c.name)} · 审卡记录</title><style>body{max-width:900px;margin:35px auto;padding:0 24px;font:16px/1.7 system-ui;color:#292d27}h1{border-bottom:3px solid #555}table{border-collapse:collapse;width:100%}td,th{border:1px solid #aaa;padding:6px;text-align:left}article{break-inside:avoid;border-bottom:1px solid #bbb}pre{white-space:pre-wrap;font:inherit}.muted{color:#60665c}@media print{body{margin:0;max-width:none}}</style><h1>${esc(c.name)}</h1><p>玩家 ${esc(c.player)} · ${c.edition} · 修订 ${c.revision} · ${esc(c.updatedAt)}</p><p>这是一份固定修订的审阅副本。人工裁定与未完成项列在下方。</p><table><tr>${ABILITIES.map(a => `<th>${a.toUpperCase()}</th>`).join('')}</tr><tr>${ABILITIES.map(a => `<td>${d.abilities[a]} (${d.modifiers[a] >= 0 ? '+' : ''}${d.modifiers[a]})</td>`).join('')}</tr></table><p>等级 ${d.level} · AC ${d.ac} · HP ${c.runtime.hp}/${d.maxHp} · 先攻 ${d.initiative} · 速度 ${d.speed}</p><h2>填写与核对</h2><ul>${pending.map(r => `<li>${esc(r.label)} — ${esc(r.origin)}</li>`).join('') || '<li>已完成当前支持的填写检查；特殊规则仍以 DM 裁定为准。</li>'}${d.issues.map(i => `<li>${esc(i.message)}</li>`).join('')}</ul><h2>启用规则</h2><p>${c.profile.enabledSources.map(esc).join('、')}</p><p>专长：${c.profile.optional.feats ? '开' : '关'}；兼职：${c.profile.optional.multiclass ? '开' : '关'}；旧版兼容：${c.profile.optional.legacy ? '开' : '关'}</p><h2>人工裁定</h2><ul>${Object.entries(c.profile.exceptions).map(([id, reason]) => `<li>${esc(c.selections.find(s => s.entry.id === id)?.entry.name || id)}：${esc(reason)}</li>`).join('') || '<li>无</li>'}</ul><h2>角色条目与固定来源</h2>${c.selections.map(s => `<article><h3>${esc(s.entry.name)}</h3><p class="muted">${esc(s.entry.source)} · ${esc(s.entry.edition)} · 资料修订 ${esc(s.entry.revision)}${s.entry.page ? ` · 第 ${s.entry.page} 页` : ''}</p><pre>${esc(plainText(s.entry.entries))}</pre></article>`).join('')}<h2>笔记</h2><pre>${esc(c.notes)}</pre><h2>数值依据</h2>${Object.entries(d.trace).map(([key, values]) => `<p>${esc(key)}：${values.map(esc).join('；')}</p>`).join('')}</html>`;
}
