import {writeFileSync} from 'node:fs';
import {execFileSync} from 'node:child_process';
import {it,expect} from 'vitest';
import {normalizeData} from '../../src/data/catalog';
import {newCharacter,type Entry} from '../../src/core/model';
import {newAutomationState} from '../../src/core/automation/state';
import {sheetChoices,setSheetChoiceSlot,syncChoiceContent} from '../../src/core/automation/choices';
import {syncFeatures} from '../../src/core/sheet';
import {syncAutoResources,setResource} from '../../src/core/resources';
import {evaluate} from '../../src/core/engine';
import {normalizeWidget} from '../../src/core/resourceWidgets';
import {validateCharacter} from '../../src/core/validation';

// Authored source-shaped data executed by the actual clean pre-dedup consumer.
it.skipIf(!process.env.DND_CLASS_CHOICE_FIXTURE_OUTPUT)('generates a real old filter grant, its nested choices and saved references',()=>{
 expect(execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim()).toBe('1a1717f84d9774f34194b9e57a45c247980cfba2');
 const source={class:[{name:'原创二级授予职业',ENG_name:'Authored Level Two Class',source:'XPHB',classFeatures:['原创风格授予|原创二级授予职业|XPHB|2'],featProgression:[{name:'原创风格授予',category:['FS'],progression:{'2':1}}]}],classFeature:[{name:'原创风格授予',source:'XPHB',className:'原创二级授予职业',classSource:'XPHB',level:2,entries:['获得一项{@filter 原创风格|feats|category=FS}。']}],feat:[{name:'原创旧卡风格',source:'XPHB',category:'FS',skillProficiencies:[{choose:{from:['arcana','history'],count:1}}],resources:[{name:'原创已消耗资源',max:3,recovery:'long'}],entries:[{type:'options',count:1,entries:[{optionalfeature:'原创子选择|XPHB'}]}]}],optionalfeature:[{name:'原创子选择',source:'XPHB',featureType:['AUTHORED'],entries:[{type:'options',count:1,entries:[{optionalfeature:'原创孙选择|XPHB'}]}]},{name:'原创孙选择',source:'XPHB',featureType:['AUTHORED'],entries:['原创软件验收子项。']}]};
 const entries=normalizeData(source,'pre-dedup-authored');entries.find(entry=>entry.kind==='feat')!.effects=[{op:'add',target:'ac',value:2}];
 const c=newCharacter();c.id='authored-pre-dedup-card';c.createdAt=c.updatedAt='2026-10-07T00:00:00.000Z';c.name='原创旧结构验收';c.automation=newAutomationState();c.notes='手工记录保留';c.runtime.hp=3;
 c.selections=[{id:'class-owner',entry:entries.find(entry=>entry.kind==='class')!,level:2,quantity:1,equipped:false}];syncFeatures(c,entries);
 const feature=c.selections.find(row=>row.entry.raw._category==='classFeature')!,oldChoice=sheetChoices(c,entries).find(choice=>choice.id===`${feature.id}:filter:0`)!;
 setSheetChoiceSlot(c,oldChoice.id,0,entries.find(entry=>entry.kind==='feat')!.id,entries);syncChoiceContent(c,entries);
 const feat=c.selections.find(row=>row.entry.kind==='feat')!,skill=sheetChoices(c,entries).find(choice=>choice.ownerId===feat.id&&choice.channel==='skills')!,nested=sheetChoices(c,entries).find(choice=>choice.ownerId===feat.id&&choice.channel==='content')!;
 setSheetChoiceSlot(c,skill.id,0,'arcana',entries);setSheetChoiceSlot(c,nested.id,0,nested.options[0].value,entries);syncChoiceContent(c,entries);
 const child=c.selections.find(row=>row.parentId===feat.id)!,grandChoice=sheetChoices(c,entries).find(choice=>choice.ownerId===child.id&&choice.channel==='content')!;
 setSheetChoiceSlot(c,grandChoice.id,0,grandChoice.options[0].value,entries);syncChoiceContent(c,entries);
 const manual:Entry={id:'authored-manual-child-entry',kind:'feature',name:'原创手工挂接子项',english:'Authored Manual Child',source:'CUSTOM',edition:'both',packId:'fixture',revision:'1',entries:['手动填写内容，不能静默删除。'],raw:{_custom:true}};
 c.selections.push({id:'authored-manual-child',entry:manual,parentId:feat.id,level:1,quantity:1,equipped:false});c.quickbar=[feat.id,child.id,'authored-manual-child'];
 c.featureLayout={order:[feat.id,child.id,'authored-manual-child'],expanded:[feat.id,child.id],optionsVisible:{[feat.id]:true}};syncAutoResources(c);
 const resourceId=Object.keys(c.runtime.resources).find(key=>c.runtime.resources[key].featureGrant?.ownerId===feat.id)!;expect(resourceId).toBeDefined();setResource(c,resourceId,1);syncAutoResources(c);
 c.quickbarLayout={order:[resourceId],hidden:[],widgets:{[resourceId]:normalizeWidget({style:'counter'})}};
 validateCharacter(c);
 expect(feat.grantKey).toBe(`choice:${oldChoice.id}:${feat.entry.id}`);expect(feat.parentId).toBe(feature.id);expect(c.selections.filter(row=>row.entry.kind==='feat')).toHaveLength(1);expect(evaluate(c).ac).toBe(12);
 writeFileSync(process.env.DND_CLASS_CHOICE_FIXTURE_OUTPUT!,JSON.stringify({producerCommit:'1a1717f84d9774f34194b9e57a45c247980cfba2',authoredOnly:true,note:'Authored software fixture generated by the actual pre-dedup sync implementation; no player data or publisher prose.',entries,character:c,ids:{feature:feature.id,filterChoice:oldChoice.id,feat:feat.id,skillChoice:skill.id,nestedChoice:nested.id,child:child.id,grandChoice:grandChoice.id,resource:resourceId}},null,2)+'\n');
});
